### ISSUE TITLE
Cannot postprocess with "nnUNet_determine_postprocessing -m 2d -t 1" eventhough complete 5 fold training

### ISSUE THREAD

**Issue by 8s1o3s7t7m** [MIC-DKFZ/nnUNet#1026]
Hi, 

When I try to postprocess in order to find the best configuration I get this AssertionError, but I trained with 0-4 folds (with --npz). Could there be another reason?

Thank you so much for any help!

(NCCTvenv) XXX@XXX:~$ nnUNet_determine_postprocessing -m 2d -t 1
...
Traceback (most recent call last):
  File "/home/XXX/miniconda3/envs/NCCTvenv/bin/nnUNet_determine_postprocessing", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_determine_postprocessing')())
  File "/home/XXX/nnUNet/nnunet/postprocessing/consolidate_postprocessing_simple.py", line 56, in main
    consolidate_folds(folder, val)
  File "/home/XXX/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 68, in consolidate_folds
    raise AssertionError("If does not seem like you trained all the folds! Train all folds first!")
AssertionError: If does not seem like you trained all the folds! Train all folds first!

**Comment by 8s1o3s7t7m** [comment]
Also cannot run "nnUNet_find_best_configuration -m 2d 3d_fullres -t 1"

running missing postprocessing for Task001_NCCT and model 2d
Traceback (most recent call last):
  File "/home/sophie/miniconda3/envs/NCCTvenv/bin/nnUNet_find_best_configuration", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')())
  File "/home/sophie/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 144, in main
    consolidate_folds(output_folder, folds=folds)
  File "/home/sophie/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 68, in consolidate_folds
    raise AssertionError("If does not seem like you trained all the folds! Train all folds first!")
AssertionError: If does not seem like you trained all the folds! Train all folds first!

**Comment by Yikeru** [comment]
Hello,

I have run into the same error, how did you manage to solve it?
