### ISSUE TITLE
Error in final stages of 2d training. AssertionError: Shape mismatch

### ISSUE THREAD

**Issue by ddup92** [MIC-DKFZ/nnUNet#1044]
Hi @FabianIsensee 

I amattempting to train your 2d nnUnet on CT images, however I am running into an error in the final stages of the training (after the last epoch has completed). I have checked the shapes of my training images and labels, they all have matching shapes.

Here is a snippet from the error I am getting:

""""""""""
CERV_9 (2, 512, 512, 104)
debug: mirroring True mirror_axes (0, 1)
force_separate_z: None interpolation order: 1
no resampling necessary
2022-05-06 07:27:15.263477: finished prediction
2022-05-06 07:27:15.266301: evaluation of raw predictions
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 313, in run_evaluation
    current_scores = evaluator.evaluate(**metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 303, in evaluate
    return super(NiftiEvaluator, self).evaluate(test, reference, **metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 223, in evaluate
    **metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 207, in accuracy
    tp, fp, tn, fn = confusion_matrix.get_matrix()
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 84, in get_matrix
    self.compute()
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 68, in compute
    assert_shape(self.test, self.reference)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 22, in assert_shape
    test.shape, reference.shape)
AssertionError: Shape mismatch: (512, 512, 117) and (512, 512, 72)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/nnunet/run/run_training.py", line 191, in main
    overwrite=args.val_disable_overwrite)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 195, in validate
    run_postprocessing_on_folds=run_postprocessing_on_folds)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 646, in validate
    json_task=task, num_threads=default_num_threads)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 360, in aggregate_scores
    all_res = p.map(run_evaluation, zip(test, ref, [evaluator]*len(ref), [metric_kwargs]*len(ref)))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 313, in run_evaluation
    current_scores = evaluator.evaluate(**metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 303, in evaluate
    return super(NiftiEvaluator, self).evaluate(test, reference, **metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/evaluator.py", line 223, in evaluate
    **metric_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 207, in accuracy
    tp, fp, tn, fn = confusion_matrix.get_matrix()
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 84, in get_matrix
    self.compute()
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 68, in compute
    assert_shape(self.test, self.reference)
  File "/usr/local/lib/python3.7/dist-packages/nnunet/evaluation/metrics.py", line 22, in assert_shape
    test.shape, reference.shape)
AssertionError: Shape mismatch: (512, 512, 117) and (512, 512, 72)
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

"""""""""""

I hope you could give me some feedback.

**Comment by FabianIsensee** [comment]
Hey, I will have ot reproduce this in order to solve it. Can you share the dataset you used here?

**Comment by TaWald** [comment]
Hey,

I also ran into the same error as you did. 

This error arises when the sizes of your validation images and ground truths have a shape mismatch.
This should be captured by the preprocessing, however I assume you did not use `--verify-dataset-integrity` to make sure the images and ground truths have the same shapes!

In the old nnunet (I believe) this issue was raised during training, making the training impossible should shapes mismatch.

I assume this happens because the data loader choose the crop location based off the the label map, so as long as the groundtruth maps are smaller (or same size) as the images, this does not become an issue during normal training.

During the validation you want to compare prediction from the entire patient to the ground truth of the entire patient, which will not have the same shape and hence throw your error.

### Temporary fix:
Assure that all your images used for training and validation have the same shape!  Your shapes are clearly mismatched: `(512, 512, 117) and (512, 512, 72)`. So if you cannot fix this mismatch, omit the image and label pairs!

Fabian is going to deliver a proper fix so this error will be more visible at the beginning of training soon.

Cheers,
Tassilo

**Comment by FabianIsensee** [comment]
should be fixed now and it should check the shapes upon running `nnUNetv2_plan_and_preprocess`. Please rerun that to verify (preferably also with the --verify-dataset-integrity flag)
