### ISSUE TITLE
Issue in my custom dataset:

### ISSUE THREAD

**Issue by RespectKnowledge** [MIC-DKFZ/nnUNet#1047]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by RespectKnowledge** [comment]
I have issued in the following dataset.
number of threads:  (8, 8)

Are we using the nonzero mask for normalization? OrderedDict([(0, False)])
Traceback (most recent call last):
  File "C:\Users\Usuario\anaconda3\Scripts\nnUNet_plan_and_preprocess-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "c:\users\usuario\nnunet\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "c:\users\usuario\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "c:\users\usuario\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
  File "<__array_function__ internals>", line 5, in vstack
  File "C:\Users\Usuario\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
Thank you

**Comment by FabianIsensee** [comment]
It seems like your training dataset was not properly created. Have you followed the instructions closely? You might also want to take a look at the existing datasets (MSD for example) to get an idea for how it should look like
