### ISSUE TITLE
Problems with the execution of the inference on Mac OS not M1 Processor

### ISSUE THREAD

**Issue by nkoser** [MIC-DKFZ/nnUNet#1073]
Hello dear nnUNet team, 

I have already read that there were similar bugs on Windows and that nnUNet was also developed for Ubuntu/Linux, but especially if you want to use a trained net and share it, it is quite complicated to extract the trained model as a pure Pytorch model. In addition, the sliding window has to be programmed in an extra script. For this reason I wanted to ask if there is another solution apart from this, so that the whole thing can simply be executed with the Framework on Linux or Mac OS ? 
I already tried Colab, but after a certain point the inference doesn't continue and you always get a malloc character or nothing happens. But I have already tested it locally, so I know for sure that it works. 
Below I have also attached the StackTrace to my actual problem. 

Many thanks and best regards
Niklas 

Traceback (most recent call last):
  File "/Users/us/opt/anaconda3/envs/ttest/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/Users/us/Documents/hackathon/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/Users/us/Documents/hackathon/nnUNet/nnunet/inference/predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/Users/us/Documents/hackathon/nnUNet/nnunet/inference/predict.py", line 206, in predict_cases
    for preprocessed in preprocessing:
  File "/Users/us/Documents/hackathon/nnUNet/nnunet/inference/predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/us/opt/anaconda3/envs/ttest/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fe057d35e50>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed

**Comment by FabianIsensee** [comment]
Hey, it appears that pickling functions is not handled nicely in other OSes. Here, nd_softmax is a lambda function and these seem to not be picklable on your system!? The solution here would be to make this a proper function:
```
def softmax_helper(x):
    return F.softmax(x, 1)
```
Best,
Fabian

**Comment by nkoser** [comment]
Hi @Karol-G 

I got it right then, but unfortunately don't remember the solution, do you currently have the same problem ? 

Many greetings 
Niklas

**Comment by Karol-G** [comment]
Hey,

Good that you managed to solve your problem! 
I luckily don't have this problem and was just asking as I am part of the nnU-Net maintenance team. We are currently revisiting open issues and this one was already quite old so I wasn't sure it is still a current problem.
Since you managed to solve it, I will close this issue now. Feel free to reopen it or open a new issue, if you have any questions.

Best,
Karol
