### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by LisaGsGithub** [MIC-DKFZ/nnUNet#1106]
Hello, 
I have greated my own dataset with the task ID 500. After the training of fold0 was complete I wanted to test the inference. I am using Windows, thus I have had to do some modifications mostly because of the backslashes instead of slashes. However this does not seem to fix my current problem with the inference. See log below.
Thank you for your help :)

(XXX) D:\XXX\repos\nnUNet>nnUNet_predict -i "D:\XXX\data\INPUT_FOLDER" -o "D:\XXX\data\OUTPUT_FOLDER" -t 500 -m 3d_fullres --save_npz
using model stored in  D:/XXX/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task500_XXX/nnUNetTrainerV2__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['XXX_007']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['D:/XXX/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task500_XXX/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0']
using the following model files:  ['D:/XXX/nnunet/nnUNet_trained_models/nnUNet/3d_fullres/Task500_XXX/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last):
  File "C:\toolsMiniconda3\envs\XXX\Scripts\nnUNet_predict-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "d:\XXX\repos\nnunet\nnunet\inference\predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "d:\XXX\repos\nnunet\nnunet\inference\predict.py", line 689, in predict_from_folder
    disable_postprocessing=disable_postprocessing)
  File "d:\XXX\repos\nnunet\nnunet\inference\predict.py", line 230, in predict_cases
    for preprocessed in preprocessing:
  File "d:\XXX\repos\nnunet\nnunet\inference\predict.py", line 122, in preprocess_multithreaded
    pr.start()
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x0000015F7AAE2A68>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\toolsMiniconda3\envs\XXX\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
[W C:\cb\pytorch_1000000000000\work\torch\csrc\CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]

**Comment by FabianIsensee** [comment]
The issue you are looking for is this one: `_pickle.PicklingError: Can't pickle <function at 0x0000015F7AAE2A68>: attribute lookup on nnunet.utilities.nd_softmax failed`
This is a known problem with windows: pickling lambda functions

**Comment by LisaGsGithub** [comment]
Thank you for your answer. Replacing the lambda functions does the trick.

**Comment by BegoneGIT** [comment]
Hi!
I have an exactly similiar problem, but those lambdas happen to be in multiple places, like for example in `nnUNetTrainerV2.initialize_network`
```AttributeError: Can't pickle local object 'nnUNetTrainerV2.initialize_network.<locals>.<lambda>'
Traceback (most recent call last):```
This [https://stackoverflow.com/questions/25348532/can-python-pickle-lambda-functions](SO answer) says one could just `import dill` and piclking should go fine, I however have trouble to find in which file should that import happen.
