### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by zliueric** [MIC-DKFZ/nnUNet#1107]
Hi, I tried to train the dataset,  but it raised errors.  Does anyone have ideas for this?

Thanks in advance!

Here is the messages, it seems like the index causes the errors. 

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'CoTr.training.network_training.nnUNetTrainerV2_ResTrans.nnUNetTrainerV2_ResTrans'>
For that I will be using the following configuration:
num_classes:  13
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 80, 160, 160]), 'median_patient_size_in_voxels': array([138, 240, 240]), 'current_spacing': array([3.21640606, 1.61430703, 1.61430703]), 'original_spacing': array([3.        , 0.75781244, 0.75781244]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 2, 'num_pool_per_axis': [3, 5, 5], 'patch_size': array([ 48, 192, 192]), 'median_patient_size_in_voxels': array([148, 512, 512]), 'current_spacing': array([3.        , 0.75781244, 0.75781244]), 'original_spacing': array([3.        , 0.75781244, 0.75781244]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /root/autodl-tmp/nnUNet_preprocessed/Task017_BCV/nnUNetData_plans_v2.1
###############################################
Patch size is [ 48 192 192]
Batch size is 2
2022-07-11 20:38:03.326712: Using dummy2d data augmentation
loading dataset
loading all case properties
Current train-val split is ...
Training set is ['bcv_1', 'bcv_10', 'bcv_2', 'bcv_21', 'bcv_22', 'bcv_23', 'bcv_24', 'bcv_25', 'bcv_26', 'bcv_27', 'bcv_28', 'bcv_29', 'bcv_3', 'bcv_30', 'bcv_31', 'bcv_4', 'bcv_5', 'bcv_6', 'bcv_7', 'bcv_8', 'bcv_9']
Validation set is ['bcv_32', 'bcv_33', 'bcv_34', 'bcv_35', 'bcv_36', 'bcv_37', 'bcv_38', 'bcv_39', 'bcv_40'] 

unpacking dataset
done
/root/CoTr/CoTr_package/CoTr/network_architecture/CNNBackbone.py:115: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
  m.weight = nn.init.kaiming_normal(m.weight, mode='fan_out')
  + Number of Backbone Params: 20.50(e6)
  + Number of Transformer Params: 9.32(e6)
  + Number of Network Params: 41.87(e6)
2022-07-11 20:38:07.501319: lr: 0.01
Exception in background worker 0:
 index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 48, in producer
    item = transform(**item)
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/transforms/spatial_transforms.py", line 346, in __call__
    ret_val = augment_spatial(data, seg, patch_size=patch_size,
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/augmentations/spatial_transformations.py", line 200, in augment_spatial
    seg_result = np.zeros((seg.shape[0], seg.shape[1], patch_size[0], patch_size[1], patch_size[2]),
IndexError: index 1 is out of bounds for axis 0 with size 1
Exception in background worker 1:
 index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 48, in producer
    item = transform(**item)
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/transforms/spatial_transforms.py", line 346, in __call__
    ret_val = augment_spatial(data, seg, patch_size=patch_size,
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/augmentations/spatial_transformations.py", line 200, in augment_spatial
    seg_result = np.zeros((seg.shape[0], seg.shape[1], patch_size[0], patch_size[1], patch_size[2]),
IndexError: index 1 is out of bounds for axis 0 with size 1
using pin_memory on device 0
Traceback (most recent call last):
  File "run_training.py", line 137, in <module>
    main()
  File "run_training.py", line 119, in main
    trainer.run_training()
  File "/root/CoTr/CoTr_package/CoTr/training/network_training/nnUNetTrainerV2_ResTrans.py", line 386, in run_training
    ret = super().run_training()
  File "/root/CoTr/CoTr_package/CoTr/training/network_training/nnUNetTrainer.py", line 315, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/root/CoTr/CoTr_package/CoTr/training/network_training/network_trainer.py", line 408, in run_training
    _ = self.tr_gen.next()
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 182, in next
    return self.__next__()
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/root/miniconda3/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by epiccc** [comment]
How did you solve your problem? I also encountered the same problem. 
Looking forward to your reply

**Comment by zliueric** [comment]
> How did you solve your problem? I also encountered the same problem. Looking forward to your reply

Hi, I used an old version of nnunet, it seems like there is a slight difference in the configuration file.

**Comment by pooya-mohammadi** [comment]
@zliueric what version did you use?
