### ISSUE TITLE
Cannot run the validation for VerSe data

### ISSUE THREAD

**Issue by kartik7737** [MIC-DKFZ/nnUNet#1134]
Hi Fabian 
A great fan of your work. You made training U-Net very easy. 
I am training nnu-net for vertebrae classification and segmentation using VerSe data. I have successfully trained the 3D full res configuration. 
I want to train the cascade configuration. I Have trained the 3D-lowres configuration but after completing the epochs, the trainer is not creating the masks for all the validation cases.  It just freezes after a specific case verse 255, I let it run for more than six hours on V100 GPU

verse255 (2, 215, 210, 210)
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 215, 210, 210)
patch size: [ 96 128 128]
steps (x, y, and z): [[0, 40, 79, 119], [0, 41, 82], [0, 41, 82]]
number of tiles: 36
using precomputed Gaussian
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
prediction done
force_separate_z: None interpolation order: 1
separate z: True lowres axis [0]
separate z, order in z is 0 order inplane is 1

after keyboard interrupt shows following error:

Process ForkPoolWorker-15:
Process ForkPoolWorker-17:
Process ForkPoolWorker-2:
Process ForkPoolWorker-12:
Process ForkPoolWorker-10:
Process ForkPoolWorker-7:
Process ForkPoolWorker-14:
Traceback (most recent call last):
  File "/physical_sciences/user/venvs/test1/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/physical_sciences/user/venvs/test1/bin/nnUNet/nnunet/run/run_training.py", line 189, in main
    trainer.validate(save_softmax=args.npz, validation_folder_name=val_folder,
  File "/physical_sciences/user/venvs/test1/bin/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 191, in validate
Traceback (most recent call last):
Traceback (most recent call last):
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/config/binaries/python/3.8.1/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
Traceback (most recent call last):

**Comment by FabianIsensee** [comment]
Hi, I think this could be related to an out-of-memory issue where you RAM gets full and then nothing progresses anymore. Do you have computers with more RAM available?
