### ISSUE TITLE
AbdomenMRUS prostate segmentation error

### ISSUE THREAD

**Issue by jakubMitura14** [MIC-DKFZ/nnUNet#1163]
First thank you for publishing your work !!

I am trying to executeAbdomenMRUS-prostate-segmentation  on a private dataset.
I had mha files and preprocessed them to nnU-Net Raw Data Archive

directories setup
![image](https://user-images.githubusercontent.com/53857487/189530681-a27ffb77-f27f-4af3-8eb5-0cbe2b8e4aea.png)
dataset json
https://drive.google.com/file/d/1unWemuCz7GGv0D0Iqs5tOrA7zkpWIo_L/view?usp=sharing
log 
https://drive.google.com/file/d/1fpvi2LouMgwr11xNJSScLe7GYdZ4XB7b/view?usp=sharing

call docker like 
```
docker run --gpus='"device=0"' \
    -v /workspaces/baselineUnet/newOutput/workdir:/workdir/ \
    joeranbosma/picai_nnunet:latest nnunet plan_train \
    Task2202_prostate_segmentation /workdir/ \
    --trainer nnUNetTrainerV2_Loss_FL_and_CE_checkpoints --fold 0
```
preprocessing part in python script 
```
archiveNext = MHA2nnUNetConverter(
    scans_dir="/workspaces/baselineUnet/mhaArchive",
    annotations_dir="/workspaces/baselineUnet/labels",  # defaults to input_path
    output_dir="/workspaces/baselineUnet/newOutput/workdir/nnUNet_raw_data",
    mha2nnunet_settings=outJsonDir,
)
archiveNext.convert()
archiveNext.create_dataset_json()
```
with json specification of mha2nnunet settings 
https://drive.google.com/file/d/1Mr3vMrukoE0eIt3bY_sIxuFfcCfAkNYM/view?usp=sharing

error
```
=============
== PyTorch ==
=============

NVIDIA Release 20.12 (build 17950526)
PyTorch Version 1.8.0a0+1606899

Container image Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2020 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

NVIDIA Deep Learning Profiler (dlprof) Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --ipc=host ...



Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/user/nnunet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 103, in main
    task_name = convert_id_to_task_name(i)
  File "/home/user/nnunet/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 2202. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/user/data
RESULTS_FOLDER=/workdir/results
nnUNet_raw_data_base=/workdir
If something is not right, adapt your environemnt variables.
If you have questions or suggestions, feel free to open an issue at https://github.com/DIAGNijmegen/picai_prep



Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

[#] Creating plans and preprocessing data
Traceback (most recent call last):
  File "/usr/local/bin/nnunet", line 568, in <module>
    action(argv)
  File "/usr/local/bin/nnunet", line 250, in plan_train
    subprocess.check_call(cmd)
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['nnUNet_plan_and_preprocess', '-t', '2202', '-tl', '1', '-tf', '1', '--verify_dataset_integrity', '--planner2d', 'None']' returned non-zero exit status 1.
```

[1] https://github.com/DIAGNijmegen/AbdomenMRUS-prostate-segmentation/issues/2

**Comment by FabianIsensee** [comment]
It seems like you did not set up your environment variables correctly:

> raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
> RuntimeError: Could not find a task with the ID 2202. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
> nnUNet_preprocessed=/home/user/data
> RESULTS_FOLDER=/workdir/results
> nnUNet_raw_data_base=/workdir
> If something is not right, adapt your environemnt variables.

That should be an easy fix. 
Another thing you should address is this:

> NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
>    insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
>    nvidia-docker run --ipc=host ...

Otherwise this will give you an error later ;-)

**Comment by mrokuss** [comment]
Hey @jakubMitura14 

Could you resolve the issue in the meantime using the comment above? Otherwise I would close this issue but you can always feel free to reopen it in case a related question comes up.

Best,
Max

**Comment by jakubMitura14** [comment]
ok thanks ! closing issue
