### ISSUE TITLE
dataset convert error

### ISSUE THREAD

**Issue by Alexander-Shao** [MIC-DKFZ/nnUNet#1180]
I have a problem that I can't solve for the time being. Can you give me a hand?

Traceback (most recent call last):
  File "/home/nkhao/anaconda3/envs/nnunet/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/nkhao/HaoShao/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 104, in main
    task_name = convert_id_to_task_name(i)
  File "/home/nkhao/HaoShao/nnUNet/nnunet/utilities/task_name_id_conversion.py", line 59, in convert_id_to_task_name
    os.environ.get('nnUNet_raw_data_base') if os.environ.get('nnUNet_raw_data_base') is not None else 'None',
RuntimeError: Could not find a task with the ID 9. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/nkhao/nnUNetFrame/DATASET/nnUNet_preprocessed/
RESULTS_FOLDER=/home/nkhao/nnUNetFrame/DATASET/nnUNet_trained_models/
nnUNet_raw_data_base=/home/nkhao/nnUNetFrame/DATASET/nnUNet_raw_data_base/
If something is not right, adapt your environemnt variables.

**Comment by Joeycho** [comment]
Hi, I think nnUNet support 3 digit.(XXX, like 001, 002, 003...etc) so..

RuntimeError: Could not find a task with the ID 9

Maybe you need to put 009 as task number, or just put 509, or something else.. 

https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md

**Comment by dojoh** [comment]
Hello,
sorry for the late response.

Its this question still relevant? Otherwise, I would close the issue.

Cheers
Ole

**Comment by e-FunJs** [comment]
Are you sure you have the task with `ID = 9`? Directly modifying the folder name does not represent its ID. You can find the  `nnunetv2/dataset_conversion/convert_MSD_dataset.py`file, and you can see `overwrite_target_id` in the last line. Modifying here will be helpful.
