### ISSUE TITLE
unexpected label found

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#1183]
I am facing the following error while verify dataset integrity for BraTs 2020 dataset. I use colab creating json file and I think that's may be create the problem.
![json](https://user-images.githubusercontent.com/66414863/193507536-bf581df7-b5b5-4b41-aa2a-442b810bf4a5.png)
I checked the task82_BRATS2020 conversion file in the git, but could not make it executable. that's why try my way to convert it that I followed for another dataset (success) and for creating json file follow the prateek gupta's tutorial. Sorry for knocking several time for several issues. 

Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_12.nii.gz. Found these unexpected values (they should not be there) [4]
Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_14.nii.gz. Found these unexpected values (they should not be there) [4]
Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_7.nii.gz. Found these unexpected values (they should not be there) [4]
Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_6.nii.gz. Found these unexpected values (they should not be there) [4]
Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_8.nii.gz. Found these unexpected values (they should not be there) [4]
Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_9.nii.gz. Found these unexpected values (they should not be there) [4]
Traceback (most recent call last):
  File "/home/ubuntu/environments/nnunet_env/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/home/ubuntu/environments/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/home/ubuntu/environments/nnUNet/nnunet/preprocessing/sanity_checks.py", line 191, in verify_dataset_integrity
    "Found unexpected labels in the training dataset. Please correct that or adjust your dataset.json accordingly")
AssertionError: Found unexpected labels in the training dataset. Please correct that or adjust your dataset.json accordingly

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by Joeycho** [comment]
Hi,

Maybe could you share "dataset.json" file in nnUNet_raw_data/Task500_BRATS/?

we need to check whether /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_9.nii.gz
path exists in dataset.json.

That's what your error message said.

**Comment by GregorKoehler** [comment]
Hi @mehnaz1985,
Were you able to resolve this issue back then? If you still encounter problems, please let us know!
Otherwise, we'll close this issue in roughly 2 weeks.

**Comment by mehnaz1985** [comment]
Yeah, I solved that problem. you can close the issue.

Mehnaz Tabassum

**Comment by GregorKoehler** [comment]
Thanks for the info!

**Comment by GMAvaliani** [comment]
> I am facing the following error while verify dataset integrity for BraTs 2020 dataset. I use colab creating json file and I think that's may be create the problem. ![json](https://user-images.githubusercontent.com/66414863/193507536-bf581df7-b5b5-4b41-aa2a-442b810bf4a5.png) I checked the task82_BRATS2020 conversion file in the git, but could not make it executable. that's why try my way to convert it that I followed for another dataset (success) and for creating json file follow the prateek gupta's tutorial. Sorry for knocking several time for several issues.
> 
> Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_12.nii.gz. Found these unexpected values (they should not be there) [4] Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_14.nii.gz. Found these unexpected values (they should not be there) [4] Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_7.nii.gz. Found these unexpected values (they should not be there) [4] Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_6.nii.gz. Found these unexpected values (they should not be there) [4] Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_8.nii.gz. Found these unexpected values (they should not be there) [4] Unexpected labels found in file /home/ubuntu/environments/nnUNet_raw_data_base/nnUNet_raw_data/Task500_BRATS/labelsTr/BRATS_9.nii.gz. Found these unexpected values (they should not be there) [4] Traceback (most recent call last): File "/home/ubuntu/environments/nnunet_env/bin/nnUNet_plan_and_preprocess", line 33, in sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()) File "/home/ubuntu/environments/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main verify_dataset_integrity(join(nnUNet_raw_data, task_name)) File "/home/ubuntu/environments/nnUNet/nnunet/preprocessing/sanity_checks.py", line 191, in verify_dataset_integrity "Found unexpected labels in the training dataset. Please correct that or adjust your dataset.json accordingly") AssertionError: Found unexpected labels in the training dataset. Please correct that or adjust your dataset.json accordingly
> 
> Please read the following resources before posting issues:
> 
> Common questions: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md
> 
> Common Problems and their solutions: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md
> 
> Expected epoch times and tips on how to identify bottlenecks: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

Hi @mehnaz1985,
![noname](https://github.com/MIC-DKFZ/nnUNet/assets/74610889/75714672-6ced-4c80-ae37-c8e0b3c0e6bf)

Can you help with Unexpected Labels in nnUNet.

I am currently working on setting up nnUNet and have encountered the same issue. When running a script, specifically:

C:\УИИ\Internship- модель nnU-Net\nnUNet-2.0\nnunetv2\new_try\nnUNet_raw>nnUNetv2_plan_and_preprocess -d 888 --verify_dataset_integrity

I am presented with the following error message:

Fingerprint extraction...
Dataset888_Lung
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
Error: Unexpected labels found in file C:/УИИ/Internship/- модель nnU-Net/nnUNet-2.0/- DATASET/nnUNet_raw\Dataset888_Lung\labelsTr\LUNG_001_0033.nii.gz.
Expected: [0, 1]
Found: [-1024. -1023. -1022. ... 1306. 1329. 1353.]

for example (attached) one of the slices has a Number of zeros: 35070748

**Comment by GMAvaliani** [comment]
looks like Housefield units, but it's not clear why they're showing up here

**Comment by hdnminh** [comment]
Hi @mehnaz1985, how can you solve that error, I was meeting that bug too. Thanks in advance!

**Comment by mehnaz1985** [comment]
@hdnminh @GMAvaliani 
I made an error while creating the .json file. Initially, there was only one mask, but I need to generate three additional masks for the remaining modalities. Additionally, I had to remap the labels to the nearest whole numbers.

**Comment by hdnminh** [comment]
Thanks @mehnaz1985. My datasets have 5 labels, and I think set them correctly (image below)
![image](https://github.com/MIC-DKFZ/nnUNet/assets/76483242/ede8a4e1-3e56-4924-b7e6-eb01338909a0)

**But I met bug like this:**
Expected label values are [0, 1, 2, 3, 4]
Found these unexpected values (they should not be there) [5.0, 7.0, 8.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 24.0, 26.0, 28.0, 30.0, 31.0, 41.0, 43.0, 44.0, 46.0, 47.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 58.0, 60.0, 62.0, 63.0, 77.0, 80.0, 85.0, 251.0, 252.0, 253.0, 254.0, 255.0, 1000.0, 1002.0, 1003.0, 1005.0, 1006.0, 1007.0, 1008.0, 1009.0, 1010.0, 1011.0, 1012.0, 1013.0, 1014.0, 1015.0, 1016.0, 1017.0, 1018.0, 1019.0, 1020.0, 1021.0, 1022.0, 1023.0, 1024.0, 1025.0, 1026.0, 1027.0, 1028.0, 1029.0, 1030.0, 1031.0, 1034.0, 1035.0, 2000.0, 2002.0, 2003.0, 2005.0, 2006.0, 2007.0, 2008.0, 2009.0, 2010.0, 2011.0, 2012.0, 2013.0, 2014.0, 2015.0, 2016.0, 2017.0, 2018.0, 2019.0, 2020.0, 2021.0, 2022.0, 2023.0, 2024.0, 2025.0, 2026.0, 2027.0, 2028.0, 2029.0, 2030.0, 2031.0, 2034.0, 2035.0]

**Comment by sabinevater** [comment]
Dear @mehnaz1985 , I am encountering the same issue: 

Found: [ 0.       10.921457]
Error: Unexpected labels found in file /home/Dataset077_Images/labelsTr/Image_007.nii.gz.
Expected: [0, 1]
Found: [ 0.        14.2452545]
Error: Unexpected labels found in file /home/Dataset077_Images/labelsTr/Image_005.nii.gz.
Expected: [0, 1]
Found: [ 0.       17.518957]
Error: Unexpected labels found in file /home/Dataset077_Images/labelsTr/Image_003.nii.gz.
Expected: [0, 1]
Found: [ 0.       21.258326]


How can I change these labels into 1, can anybody help? 


Kind regards

**Comment by Ar15Ham** [comment]
Dear @sabinevater 

I had to manually change the labels (.nii.gz) using nibabel and applying a threshold of 0.5 so that any labels above 0.5 are converted to 1 and anything below 0.5 is converted to 1 (this might not work if you have labels between 0 and 1 not too sure about that though) but the code is as follows:

    label= nib.load(label_path)
    label_data = label.get_fdata()

    thresholded_data = (label_data >= 0.5).astype(int)
    nifti_image = nib.Nifti1Image(thresholded_data.astype(np.uint32), label.affine)

    nifti_image.to_filename(toutput_label_path)

This worked for me not sure if it might for your particular situation.
