### ISSUE TITLE
Training(issues with splits): list index out of range

### ISSUE THREAD

**Issue by Li-En-Good** [MIC-DKFZ/nnUNet#1191]
Hi,

I got the below error when trying to train on my dataset.
Could you help me identify the potential issue? Thanks!
I did the planning and preprocessing and everything looks fine before starting to train.

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'SRS'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [2, 4, 4], 'patch_size': array([ 20, 352, 352]), 'median_patient_size_in_voxels': array([ 32, 470, 470]), 'current_spacing': array([0.5       , 0.49700001, 0.49700001]), 'original_spacing': array([0.5       , 0.49700001, 0.49700001]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [1, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /groups/WeiLab/lllin/nnUnet/nnUNet_preprocessed/Task500_GFAP-MAP2-Other/nnUNetData_plans_v2.1
###############################################
2022-10-15 19:35:36.293607: Using dummy2d data augmentation
loading dataset
loading all case properties
2022-10-15 19:35:36.306240: Using splits from existing split file: /groups/WeiLab/lllin/nnUnet/nnUNet_preprocessed/Task500_GFAP-MAP2-Other/splits_final.pkl
2022-10-15 19:35:36.306474: The split file contains 1 splits.
2022-10-15 19:35:36.306637: Desired fold for training: 0
2022-10-15 19:35:36.306807: This split has 0 training and 0 validation cases.
Traceback (most recent call last):
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/run/run_training.py", line 163, in main
    trainer.initialize(not validation_only)
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 95, in initialize
    self.dl_tr, self.dl_val = self.get_basic_generators()
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 402, in get_basic_generators
    dl_tr = DataLoader3D(self.dataset_tr, self.basic_generator_patch_size, self.patch_size, self.batch_size,
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/dataloading/dataset_loading.py", line 202, in __init__
    self.data_shape, self.seg_shape = self.determine_shapes()
  File "/groups/WeiLab/lllin/anaconda3/envs/nnunet/lib/python3.9/site-packages/nnunet/training/dataloading/dataset_loading.py", line 213, in determine_shapes
    k = list(self._data.keys())[0]
IndexError: list index out of range

**Comment by 7tu** [comment]
Hello, sorry to bother you. I also encountered the same problem. How did you solve it? I hope to get your answer as soon as possible. Thank you very much.

**Comment by Li-En-Good** [comment]
> Hello, sorry to bother you. I also encountered the same problem. How did you solve it? I hope to get your answer as soon as possible. Thank you very much.



> Hello, sorry to bother you. I also encountered the same problem. How did you solve it? I hope to get your answer as soon as possible. Thank you very much.

Hi I think it was the because the json did not include proper directories for the data so it wasn’t inputting anything.

**Comment by 7tu** [comment]
Sorry to bother you again. It is indeed an error caused by the data not being imported. You mentioned that it may be a problem with the json file. My data set is MICCAI_BraTS2020_TrainingData. Follow the methods introduced in the nnunet document to perform dataset_conversion and nnUNet_plan_and_preprocess.py -t 82 --verify_dataset_integrity , I checked the reference document to view the json file, but did not find the problem. Could you please teach me how to find the reason why the data was not imported correctly? Thank you very much.
