### ISSUE TITLE
What is the reason for the following error in data preprocessing

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#120]
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 241, in <module>
    split_4d(task)
  File "experiment_planning/plan_and_preprocess_task.py", line 54, in split_4d
    p.starmap(split_4d_nifti, zip(files, output_dirs))
  File "/home/zlf/anaconda3/envs/nnunet/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/zlf/anaconda3/envs/nnunet/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:107:
sitk::ERROR: Unable to determine ImageIO reader for "/home/zlf/nnUNet/nnunet/nnUNet_base/nnUNet_raw/Task02_Heart/imagesTr/._la_029.nii.gz"

**Comment by FabianIsensee** [comment]
This is because the decathlon organizers used some weird software for packing the data. This file exists in the folder but should not be there. You need to delete it manually

**Comment by zlf123-marker** [comment]
Thank you very much
