### ISSUE TITLE
OSError: 17296470 requested and 1648608 written

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#1203]
everything was good till I start training. Could anyone pls help me in this regard? 
###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.n                                                                                        nUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'T1', 1: 'T1ce', 2: 'T2', 3: 'FLAIR'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3,                                                                                         'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128,                                                                                         128]), 'median_patient_size_in_voxels': array([139, 170, 137]), 'current_spacin                                                                                        g': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_d                                                                                        ata_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2                                                                                        , 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3,                                                                                         3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/ubuntu/environments/nnUNet_preprocessed                                                                                        /Task500_BRATS/nnUNetData_plans_v2.1
###############################################
loading dataset
loading all case properties
2022-10-25 11:16:01.943131: Creating new 5-fold cross-validation split...
2022-10-25 11:16:01.944341: Desired fold for training: 0
2022-10-25 11:16:01.944426: This split has 236 training and 59 validation cases.
unpacking dataset
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/environments/nnUNet/nnunet/training/dataloading/dataset_loa                                                                                        ding.py", line 45, in convert_to_npy
    np.save(npz_file[:-3] + "npy", a)
  File "<__array_function__ internals>", line 6, in save
  File "/home/ubuntu/environments/nnunet_env/lib/python3.6/site-packages/numpy/l                                                                                        ib/npyio.py", line 529, in save
    pickle_kwargs=dict(fix_imports=fix_imports))
  File "/home/ubuntu/environments/nnunet_env/lib/python3.6/site-packages/numpy/l                                                                                        ib/format.py", line 675, in write_array
    array.tofile(fp)
OSError: 17296470 requested and 1648608 written
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/environments/nnunet_env/bin/nnUNet_train", line 33, in <mod                                                                                        ule>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/ubuntu/environments/nnUNet/nnunet/run/run_training.py", line 163,                                                                                         in main
    trainer.initialize(not validation_only)
  File "/home/ubuntu/environments/nnUNet/nnunet/training/network_training/nnUNet                                                                                        TrainerV2.py", line 98, in initialize
    unpack_dataset(self.folder_with_preprocessed_data)
  File "/home/ubuntu/environments/nnUNet/nnunet/training/dataloading/dataset_loa                                                                                        ding.py", line 68, in unpack_dataset
    p.map(convert_to_npy, zip(npz_files, [key] * len(npz_files)))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
OSError: 17296470 requested and 1648608 written

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by Karol-G** [comment]
Hey @mehnaz1985  ,

Is the problem still current or did you manage to solve it?

Best,
Karol
