### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'maxsize'

### ISSUE THREAD

**Issue by Overflowu7** [MIC-DKFZ/nnUNet#1204]
hello fabian:
After i run one fold of 3d_fullers or another ,but this error happened to it. I have looked for a lot of solutions, but nothing seems to help the.
I tried to use different version of batchgenerators but it didn't work,
I am stuck

finished prediction, now evaluating...
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x7faf34d97d30>
Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 269, in __del__
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 239, in _finish
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/multiprocessing/synchronize.py", line 338, in set
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/multiprocessing/synchronize.py", line 297, in notify_all
AttributeError: 'NoneType' object has no attribute 'maxsize'
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x7faf34d97d30>
Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 269, in __del__
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 239, in _finish
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/multiprocessing/synchronize.py", line 338, in set
  File "/home/cui/anaconda3/envs/wyc/lib/python3.9/multiprocessing/synchronize.py", line 297, in notify_all
AttributeError: 'NoneType' object has no attribute 'maxsize'

**Comment by seziegler** [comment]
HI @Overflowu7 , sorry for leaving this issue stale for so long. I've looked into your error and it seems like the MultiThreadedAugmenter is not initialized properly. Do you still get this error when using nnunetv2?
Best,
Sebastian

**Comment by Overflowu7** [comment]
> HI @Overflowu7 , sorry for leaving this issue stale for so long. I've looked into your error and it seems like the MultiThreadedAugmenter is not initialized properly. Do you still get this error when using nnunetv2? Best, Sebastian

i never get this error again in v2.But i have some another question.did you know this warning?My persudo dice is zero,but i don't know how it happend.
/home/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py:1045: RuntimeWarning: Mean of empty slice
  mean_fg_dice = np.nanmean(global_dc_per_class)
2023-08-01 19:07:14.793154: train_loss -0.1514
2023-08-01 19:07:14.892137: val_loss -0.1738
2023-08-01 19:07:14.892280: Pseudo dice []

**Comment by seziegler** [comment]
This warning comes from numpys function [nanmean](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html) and is thrown for all-NaN slices. 
Best,
Sebastian

**Comment by Overflowu7** [comment]
> This warning comes from numpys function [nanmean](https://numpy.org/doc/stable/reference/generated/numpy.nanmean.html) and is thrown for all-NaN slices. Best, Sebastian

I can't find out if I have  all-NaN slices., but thanks for your help!
