### ISSUE TITLE
Hello,, what happened to the following error?

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#122]
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 275, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 351, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 543, in run_iteration
    l.backward()
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 10.73 GiB total capacity; 9.23 GiB already allocated; 7.75 MiB free; 542.02 MiB cached)

**Comment by FabianIsensee** [comment]
Your graphics card is too small. You need 12GB vram.
You can train with --fp16, that should solve it

**Comment by FabianIsensee** [comment]
> nnU-Net configures the U-Net architectures based on that information. All U-Nets are configured to optimally use 12GB Nvidia TitanX GPUs. There is currently no way of adapting to smaller or larger GPUs.

quote from documentation
