### ISSUE TITLE
OSError: [Errno 5] Input/output error after saving checkpoint

### ISSUE THREAD

**Issue by PatrickGonzalez** [MIC-DKFZ/nnUNet#1254]
Dear Fabian,

After having trained a 2 nnUNet on several tasks without any problems, I now get an Input/output error after saving the checkpoint from epoch 1. See below. Do you have any thoughts on this?

Beste,
Patrick González

2022-12-12 11:06:50.304311: saving checkpoint...
Traceback (most recent call last):
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 448, in run_training
    ret = super().run_training()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 484, in run_training
    continue_training = self.on_epoch_end()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 421, in on_epoch_end
    super().on_epoch_end()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 617, in on_epoch_end
    continue_training = self.manage_patience()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 577, in manage_patience
    if self.save_best_checkpoint: self.save_checkpoint(join(self.output_folder, "model_best.model"))
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 727, in save_checkpoint
    super(nnUNetTrainer, self).save_checkpoint(fname, save_optimizer)
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 287, in save_checkpoint
    torch.save(save_this, fname)
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/torch/serialization.py", line 381, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/torch/serialization.py", line 214, in __exit__
    self.file_like.close()
**OSError: [Errno 5] Input/output error
Exception in thread Thread-5:**
Traceback (most recent call last):
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/scistor/guest/pgo204/.conda/envs/nnUnetConda/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

**Comment by JackRio** [comment]
Looks similar to this 
https://github.com/pytorch/pytorch/issues/48580

**Comment by FabianIsensee** [comment]
Yeah that is definitely related to torch. The line where the code fails is this one here:

> torch.save(save_this, fname)

Thanks @JackRio for charing the torch issue

**Comment by mrokuss** [comment]
Hi @PatrickGonzalez 

Could you resolve this issue with a more recent version of torch?
