### ISSUE TITLE
x = torch.cat((x, skips[-(u + 1)]), dim=1) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 1 for tensor number 1 in the list.

### ISSUE THREAD

**Issue by 888yyh** [MIC-DKFZ/nnUNet#1256]
operating environment:win10 + rtx3050+4GB vram
Based on the mentioned environment, the test image[prostate_03_0000.nii, prostate_03_0001.nii] with shape(20, 320, 320) took a lot of time to predict(almost an hour without result, so i stopped running.), so i took two slices from the test image [prostate_03_0000.nii, prostate_03_0001.nii],getting shape (2, 320, 320).Then, i updated the "patch_size" from (20, 320, 256) to (2, 320, 256).

however, ran the command "nnUNet_predict -i E:/nzl/nnunetbrats2020/nnUNet-master/nnUNet_raw_data_base/nnUNet_raw_data/Task005_Prostate/imagesTs/ -o E:/nzl/nnunetbrats2020/nnUNet-master/output/prostate -t 5 -m 3d_fullres --num_threads_nifti_save 2 --num_threads_preprocessing 2 -f 4", the following issue occured:
Traceback (most recent call last):
  File "D:\SoftWare\Anaconda\envs\pacsai3.7\Scripts\nnUNet_predict-script.py", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')()
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\inference\predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\inference\predict.py", line 641, in predict_from_folder
    segmentation_export_kwargs=segmentation_export_kwargs)
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\inference\predict.py", line 225, in predict_cases
    mixed_precision=mixed_precision)[1][None])
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\training\network_training\nnUNetTrainerV2.py", line 219, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\training\network_training\nnUNetTrainer.py", line 524, in predict_preprocessed_data_return_seg_and_softmax
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\network_architecture\neural_network.py", line 385, in _internal_predict_3D_3Dconv_tiled
    gaussian_importance_map)[0]
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\network_architecture\neural_network.py", line 522, in _internal_maybe_mirror_and_pred_3D
    pred = self.inference_apply_nonlin(self(x))
  File "D:\SoftWare\Anaconda\envs\pacsai3.7\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl    return forward_call(*input, **kwargs)
  File "e:\nzl\nnunet-windows-master\nnunet-windows-master\nnunet\network_architecture\generic_UNet.py", line 400, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 2 but got size 1 for tensor number 1 in the list.
how to solve it?

i saw a similar issue, https://github.com/MIC-DKFZ/nnUNet/issues/73,
while i didn't know what to change.
please help me, thanks!

**Comment by seziegler** [comment]
Hi @888yyh , it is normal that the prediction process can take a while. Have you tried just letting it run until it finishes? 
How did you change the patch size?
Best,
Sebastian

**Comment by marieanselmet** [comment]
Hi everyone,
Was this issue finally solved ?

Thanks in advance.
Best,

Marie
