### ISSUE TITLE
Error when running nnUNet_find_best_configuration 

### ISSUE THREAD

**Issue by haidermri** [MIC-DKFZ/nnUNet#1268]
I am just starting with nnunet. It seems I have omitted a step but it is not clear to me what I have left out

I have completed a 5 fold 3d low res training. 

nnUNet_train 3d_lowres nnUNetTrainerV2 Task602_L3VertBodySeg 0 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task602_L3VertBodySeg 1 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task602_L3VertBodySeg 2 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task602_L3VertBodySeg 3 --npz
nnUNet_train 3d_lowres nnUNetTrainerV2 Task602_L3VertBodySeg 4 --npz

I assume the enxt step is to find the best fold. I am not ensembling outside of the low res mode yet (next step)

When I run
nnUNet_find_best_configuration -m 3d_lowres -tr nnUNetTrainerV2 -t 602

I get the following error:
running missing postprocessing for Task602_L3VertBodySeg and model 3d_lowres
Traceback (most recent call last):
  File "/home/mahaider/miniconda3/envs/nnunet/bin/nnUNet_find_best_configuration", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')())
  File "/home/mahaider/Dropbox/MyCode/git/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 144, in main
    consolidate_folds(output_folder, folds=folds)
  File "/home/mahaider/Dropbox/MyCode/git/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 64, in consolidate_folds
    num_niftis_gt = len(subfiles(join(output_folder_base, "gt_niftis"), suffix='.nii.gz'))
  File "/home/mahaider/miniconda3/envs/nnunet/lib/python3.8/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 40, in subfiles
    res = [l(folder, i) for i in os.listdir(folder) if os.path.isfile(os.path.join(folder, i))
FileNotFoundError: [Errno 2] No such file or directory: '/home/mahaider/Documents/nnunet/nnUNet_trained_models/nnUNet/3d_lowres/Task602_L3VertBodySeg/nnUNetTrainerV2__nnUNetPlansv2.1/gt_niftis'

The contents of the folder
/home/mahaider/Documents/nnunet/nnUNet_trained_models/nnUNet/3d_lowres/Task602_L3VertBodySeg/nnUNetTrainerV2__nnUNetPlansv2.1 are:
├── cv_niftis_raw
├── fold_0
│   └── validation_raw
├── fold_1
│   └── validation_raw
├── fold_2
│   └── validation_raw
├── fold_3
│   └── validation_raw
└── fold_4
    └── validation_raw

in each fold_xx are:
 fold_4
│   ├── debug.json
│   ├── model_best.model
│   ├── model_best.model.pkl
│   ├── model_final_checkpoint.model
│   ├── model_final_checkpoint.model.pkl
│   ├── progress.png
│   ├── training_log_2022_12_25_23_59_30.txt
│   └── validation_raw

**Comment by haidermri** [comment]
I should add I cannto find any summary.json files

**Comment by haidermri** [comment]
I found an error in my data preparation. After rerunning all is fine
