### ISSUE TITLE
Hello, what is the reason for the following error

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#127]
Traceback (most recent call last):
  File "run/run_training.py", line 114, in <module>
    trainer.validate(save_softmax=args.npz, validation_folder_name=val_folder)
  File "/home/zlf/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 478, in validate
    use_gaussian=use_gaussian)
  File "/home/zlf/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 415, in predict_preprocessed_data_return_softmax
    pad_kwargs=self.inference_pad_kwargs)[2]
  File "/home/zlf/nnUNet/nnunet/network_architecture/neural_network.py", line 96, in predict_3D
    all_in_gpu=all_in_gpu)
  File "/home/zlf/nnUNet/nnunet/network_architecture/neural_network.py", line 248, in _internal_predict_3D_3Dconv_tiled
    num_repeats, mirror_axes, do_mirroring, add_torch)[0]
  File "/home/zlf/nnUNet/nnunet/network_architecture/neural_network.py", line 363, in _internal_maybe_mirror_and_pred_3D
    x = to_cuda(maybe_to_torch(x), gpu_id=self.get_device())
  File "/home/zlf/nnUNet/nnunet/utilities/to_torch.py", line 30, in to_cuda
    data = data.cuda(gpu_id, non_blocking=True)
RuntimeError: Source tensor must be contiguous.

**Comment by Celestenono** [comment]
Hi,
You have to change the following line:

data = data.cuda(gpu_id, non_blocking=True)

to

data = data.contiguous().cuda(gpu_id, non_blocking=True) 
see the close issue #92 

Best,
Noémie

**Comment by zlf123-marker** [comment]
thank you very much

**Comment by FabianIsensee** [comment]
I am not sure why you guys are getting this error and I am not :-/ Do you have any idea?

**Comment by Celestenono** [comment]
Hi

My GPU card is quite old so I am using Cuda 8.0 and torch 1.0.0.
I don't have this issue with my other GPU card with torch 1.2.0 (Cuda 9.2)

Best,
Noémie

**Comment by wukaiyeah** [comment]
Hi,
if my computer-server doesn't have GPU, Can I run nnUnet successfully?

**Comment by FabianIsensee** [comment]
No, nnU-Net does not support CPU. It would run way too slow on CPU anyways
