### ISSUE TITLE
cannot select an axis to squeeze out which has size not equal to one

### ISSUE THREAD

**Issue by helenShen2023** [MIC-DKFZ/nnUNet#1295]
epoch:  0
0it [00:00, ?it/s]Exception in background worker 0:
 cannot select an axis to squeeze out which has size not equal to one
using pin_memory on device 0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/mist/home/mist/UNet2022/nnunet/run/run_training.py", line 224, in <module>
    main()
  File "/home/mist/home/mist/UNet2022/nnunet/run/run_training.py", line 203, in main
    trainer.run_training()
  File "/home/mist/UNet2022/nnunet/training/network_training/nnUNetTrainerV2_unet2022_hanoar.py", line 411, in run_training
    ret = super().run_training()
  File "/home/mist/UNet2022/nnunet/training/network_training/nnUNetTrainer.py", line 295, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/mist/UNet2022/nnunet/training/network_training/network_trainer.py", line 454, in run_training
    for batch in tbar:
  File "/mistgpu/miniconda/envs/UNet2022/lib/python3.6/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/mistgpu/miniconda/envs/UNet2022/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/mistgpu/miniconda/envs/UNet2022/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by FabianIsensee** [comment]
It seems like you have modified the code a bit so its hard to tell what is going on. Have you tried the standard nnU-Net? Does that work? It will also print a better error message which will be helpful
