### ISSUE TITLE
 index 0 is out of bounds for axis 1 with size 0

### ISSUE THREAD

**Issue by Hydrobomb** [MIC-DKFZ/nnUNet#1299]
Hi all users,
I am trying to train nnUNet using LITS data sets,
I confirmed that there is no problem when performing 'verify_dataset_integrity'.
But I got index error when I trained nnUNET as shown below.
I saw some issues that these kind of massage could come from using old version of nnUNet, but I downloaded nnUNET codes from GITHUB directly (instead of pip install).
Could you give me a tip for this problem?
Thank you.

loading dataset
loading all case properties
2023-02-15 02:44:27.712442: Creating new 5-fold cross-validation split...
2023-02-15 02:44:27.715186: Desired fold for training: 5
2023-02-15 02:44:27.715319: INFO: You requested fold 5 for training but splits contain only 5 folds. I am now creating a random (but seeded) 80:20 split!
2023-02-15 02:44:27.716716: This random 80:20 split has 73 training and 19 validation cases.
unpacking dataset
done
2023-02-15 02:50:18.587592: lr: 0.01
Exception in background worker 1:
 index 0 is out of bounds for axis 1 with size 0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 48, in producer
    item = transform(**item)
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/root/share/keonmin/nnunet_lits/nnUNet-master/nnunet/training/data_augmentation/pyramid_augmentations.py", line 85, in __call__
    target = data_dict.get(self.key_target)
IndexError: index 0 is out of bounds for axis 1 with size 0
using pin_memory on device 0

**Comment by Hydrobomb** [comment]
solved.

**Comment by FabianIsensee** [comment]
What turned out to be the problem?

**Comment by Hydrobomb** [comment]
@FabianIsensee 
I deleted all directories which contain raw, cropped and preprocessed data. 
And re-preprocessed all files.
I guessed there was a crash during unpacking data, and it resulted in above error when I trained again.

**Comment by FabianIsensee** [comment]
Thanks :+1:
