### ISSUE TITLE
Exception in worker

### ISSUE THREAD

**Issue by AJ2019** [MIC-DKFZ/nnUNet#130]
I am trying to train 2D U-Net on 2D images and I commented the code corresponding to 3D experiment planning. So, dataset creation and experiment planning were successful.

But when I try to train the 2d model using "python nnunet/run/run_training.py 2d nnUNetTrainer TASK00_XY all --ndet", following exception happens on all workers,

Exception in worker 0
Traceback (most recent call last):
  File "/pytorch/pytorch/lib/python3.5/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 48, in producer
    item = next(data_loader)
  File "/pytorch/pytorch/lib/python3.5/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "nnUNet/nnunet/training/dataloading/dataset_loading.py", line 442, in generate_train_batch
    case_all_data = np.load(self._data[i]['data_file'][:-4] + ".npy", self.memmap_mode)
  File "/pytorch/pytorch/lib/python3.5/site-packages/numpy/lib/npyio.py", line 437, in load
    return format.open_memmap(file, mode=mmap_mode)
  File "pytorch/pytorch/lib/python3.5/site-packages/numpy/lib/format.py", line 845, in open_memmap
    mode=mode, offset=offset)
  File "pytorch/pytorch/lib/python3.5/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)

I also see,
Exception in pin_memory_loop and
OSError: [Errno 24] Too many open files

I tried removing npy files as suggesting in one of the other issues related to exception from pre-processing folder, but that did not help

Any suggestions on how to fix this?

Thanks,
Aditya

**Comment by FabianIsensee** [comment]
> OSError: [Errno 24] Too many open files

You need to increase the open file limit of your operating system. Depending on what your OS is this works differently. Google will help ;-)

Best,
Fabian
