### ISSUE TITLE
Preprocessing Error

### ISSUE THREAD

**Issue by Xtaltec** [MIC-DKFZ/nnUNet#132]
I have not been able to solve this error while performing the preprocessing .

Are we using the nonzero maks for normalizaion? OrderedDict([(0, False)])
Traceback (most recent call last):
  File "plan_and_preprocess_task.py", line 245, in <module>
    plan_and_preprocess(task, processes_lowres, processes_fullres, no_preprocessing)
  File "plan_and_preprocess_task.py", line 134, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "c:\users\mreib\onedrive\documentos\neural networks\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 235, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "c:\users\mreib\onedrive\documentos\neural networks\nnunet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 63, in get_target_spacing
    target = np.percentile(np.vstack(spacings), TARGET_SPACING_PERCENTILE, 0)
  File "<__array_function__ internals>", line 6, in vstack
  File "C:\Users\mreib\Anaconda3\envs\nunet\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

**Comment by AJ2019** [comment]
Please check if this answer helps you,
https://github.com/MIC-DKFZ/nnUNet/issues/18

**Comment by Xtaltec** [comment]
Hi! I'm using my own dataset so I followed the instruction provided on dataset_conversion. My data is conformed of splitted 3D niftis so I saved them on the corresponding folders 'imageTs', 'imageTr', 'labelsTr', inside my **splitted_4d_output_dir**. So my folder structure is '**splitted_4d_output_dir**/TaskXX_My_Dataset/imageTs'. I think I have done every step correctly to convert my dataset and generate de .json file but I still keep getting this error

**Comment by FabianIsensee** [comment]
Interesting. Do you have the labelsTr folder as well? I did not see you mention it

**Comment by Xtaltec** [comment]
I manage to solve the issue by switching to Linux. So it had to be a problem with the Windows operative system. Thank you for your help anyways!!!
