### ISSUE TITLE
2d numpy images

### ISSUE THREAD

**Issue by eyalhana** [MIC-DKFZ/nnUNet#1348]
Hi,
First of all, thank you for your fantastic work!
Each image in my dataset is of size ```[H,W]``` in numpy format.

How should I save the images in the raw folder?

If I save it as nii.gz, should I add a dimension ```[1,H,W]``` or two dimensions ```[1,1,H,W]``` using np.newaxis, before using ```nib.Nifti1Image(img, np.eye(4))```?

I would appreciate an explanation of how I should convert the images and how to add dimensions before saving the images. The inputs size is ```[H,W]``` and the original format is numpy.

Thank you!

**Comment by FabianIsensee** [comment]
Hey, 
you don't need to mess with dimension. Unless i messed up (let me know in that case) you can just save your image as 2D niftis.
If you prefer png (and your pixel type is compatible with that) then that's fine, too.
Best,
Fabian

**Comment by eyalhana** [comment]
Thanks for the answer! 
After saving the [H,W] numpy files using the following command: 
```nib_img = nib.Nifti1Image(np_img, np.eye(4))```
```nib.save(nib_img,filename_img)```

I have got the following error while trying to run ```nnUNetv2_plan_and_preprocess -d 500 -c 2d --verify_dataset_integrity``` 
```
Failed to open file /home/eyalhan/nnUNetT1/nnUNet_raw/Dataset500_cardiac/imagesTr/cardiac_00000_0000.nii.gz with reader <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'>:
...
AssertionError: only 3d images are supported by NibabelIO
...
RuntimeError: Unable to determine a reader for file ending .nii.gz and file /home/eyalhan/nnUNetT1/nnUNet_raw/Dataset500_cardiac/imagesTr/cardiac_00000_0000.nii.gz (file None means no file provided).
```

After added ``` "overwrite_image_reader_writer": "SimpleITKIO" ``` to the json file I got the following:
```
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 33, in verify_labels
    seg, properties = rw.read_seg(label_file)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 115, in read_seg
    return self.read_images((seg_fname, ))
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 59, in read_images
    spacings_for_nnunet[-1] = list(np.abs(spacings_for_nnunet[-1]))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eyalhan/.local/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 173, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 186, in verify_dataset_integrity
    result = p.starmap(
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

I would appreciate an explanation what I should do :-) 
Thanks!

**Comment by eyalhana** [comment]
I'm not sure which files you mean, so for now I'll share here a short script that creates random data in the same format without forcing you to mess with the original dataset..

```
import numpy as np
import nibabel as nib
import os
import matplotlib.pyplot as plt

# ***************** Loading *****************

out_base = '/home/eyalhan/nnUNetT1'
path = '/home/eyalhan/nnUNetT1/nnUNet_raw/Dataset501_cardiac'
os.makedirs(path,exist_ok=True)
os.makedirs(path+'/imagesTr',exist_ok=True)
os.makedirs(path+'/labelsTr',exist_ok=True)

ind = 0 
for p in range(10):
    np_img = np.random.rand(160,160).astype(np.float64)
    np_seg = np.random.randint(0,2,(160,160)).astype(np_img.dtype)

    nib_img = nib.Nifti1Image(np_img, np.eye(4))
    nib_seg = nib.Nifti1Image(np_seg, np.eye(4))
    
    filename_img  = os.path.join(path,'imagesTr', 'cardiac_'+str(ind).zfill(5)+'_0000.nii.gz')
    nib.save(nib_img,filename_img)  

    filename_seg  = os.path.join(path,'labelsTr', 'cardiac_'+str(ind).zfill(5)+'.nii.gz')
    nib.save(nib_seg,filename_seg)  

    ind = ind+1
```

```
{ 
 "channel_names": {  
   "0": "T1"
 }, 
 "labels": {  
   "background": 0,
   "myocardial": 1
 }, 
 "numTraining": 10, 
 "file_ending": ".nii.gz",
 "overwrite_image_reader_writer": "SimpleITKIO" 
 }
```

**Comment by FabianIsensee** [comment]
Hey, 
I mean this file: `/home/eyalhan/nnUNetT1/nnUNet_raw/Dataset500_cardiac/imagesTr/cardiac_00000_0000.nii.gz`
Best,
Fabian

**Comment by eyalhana** [comment]
[cardiac_00002.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077184/cardiac_00002.nii.gz)
[cardiac_00001.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077185/cardiac_00001.nii.gz)
[cardiac_00000.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077186/cardiac_00000.nii.gz)
[cardiac_00002_0000.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077187/cardiac_00002_0000.nii.gz)
[cardiac_00001_0000.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077188/cardiac_00001_0000.nii.gz)
[cardiac_00000_0000.nii.gz](https://github.com/MIC-DKFZ/nnUNet/files/11077189/cardiac_00000_0000.nii.gz)

BTW the data was taken from ```https://cardiacmr.hms.harvard.edu/downloads-0``` (After performing several operations such as creating the segmentation and cutting the relevant area and converting the file to np, etc.)

**Comment by FabianIsensee** [comment]
Thanks for sharing! It was a bug and is fixed now. Please install latest version from Github :-)

**Comment by eyalhana** [comment]
Thanks you!
 
Unfortunately I think that maybe I miss something.
After perform 
``` pip uninstall nnunetv2```
``` pip install nnunetv2```

I get the following message:
```
(nnUNet) [eyalhan@bm.technion.ac.il@argus02 ~]$ nnUNetv2_plan_and_preprocess -d 500 -c 2d --verify_dataset_integrity
Fingerprint extraction...
Dataset500_cardiac
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 33, in verify_labels
    seg, properties = rw.read_seg(label_file)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 115, in read_seg
    return self.read_images((seg_fname, ))
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 59, in read_images
    spacings_for_nnunet[-1] = list(np.abs(spacings_for_nnunet[-1]))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eyalhan/.local/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 173, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/home/eyalhan/.local/lib/python3.9/site-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 186, in verify_dataset_integrity
    result = p.starmap(
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/tcmldrive/lib/envs/nnUNet/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
```

Do you have idea what I should do?

Thanks!

**Comment by FabianIsensee** [comment]
> Please install latest version from Github :-)

```
git clone https://github.com/MIC-DKFZ/nnUNet.git
cd nnUNet
pip install -e .
```

**Comment by eyalhana** [comment]
Thank you, it works! 

I really appreciate your availability and the effort to answer questions quickly even though I assume you are very busy.

Have a great day,
Eyal

**Comment by FabianIsensee** [comment]
You, too :-)
