### ISSUE TITLE
Hello, what happened to the following error when I reprocessed my data set?

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#135]
Traceback (most recent call last):
  File "run/run_training.py", line 79, in <module>
    trainer_class = get_default_configuration(network, task, network_trainer, plans_identifier)
  File "/home/zlf/nnUNet/nnunet/run/default_configuration.py", line 50, in get_default_configuration
    plans = load_pickle(plans_file)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 48, in load_pickle
    with open(file, mode) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/zlf/nnUNet/nnUNet_preprocessed/Task02_Lumbar/nnUNetPlans_plans_3D.pkl'

**Comment by FabianIsensee** [comment]
Seems like the preprocessing did not finish. What was the output of the preprocessing script?
