### ISSUE TITLE
Unable to determine a reader for file ending .png

### ISSUE THREAD

**Issue by XinZ0419** [MIC-DKFZ/nnUNet#1350]
**Did anyone have the same RuntimeError during preprocessing? :**
**Fingerprint extraction...
Dataset066_CC
Failed to open file /mnt/hdd/xzhang/CC/nnUNet/nnUNet_raw/Dataset066_CC/imagesTr/0010610620190924091717RCASIA2000_0000.png with reader <class 'nnunetv2.imageio.natural_image_reager_writer.NaturalImage2DIO'>:**
Traceback (most recent call last):
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/imageio/reader_writer_registry.py", line 49, in determine_reader_writer_from_file_ending
    _ = tmp.read_images((example_file,))
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/imageio/natural_image_reager_writer.py", line 39, in read_images
    npy_img = io.imread(f)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/skimage/io/_io.py", line 53, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/skimage/io/manage_plugins.py", line 205, in call_plugin
    return func(*args, **kwargs)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/skimage/io/_plugins/imageio_plugin.py", line 15, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/v2.py", line 227, in imread
    result = file.read(index=0, **kwargs)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 147, in read
    reader = self.legacy_get_reader(**kwargs)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 116, in legacy_get_reader
    return self._format.get_reader(self._request)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/core/format.py", line 221, in get_reader
    return self.Reader(self, request)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/core/format.py", line 312, in __init__
    self._open(**self.request.kwargs.copy())
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/imageio/plugins/simpleitk.py", line 120, in _open
    self._img = _read_function(self.request.get_local_filename(), *args)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/SimpleITK/extra.py", line 355, in ReadImage
    return reader.Execute()
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 8438, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
**RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/mnt/hdd/xzhang/CC/nnUNet/nnUNet_raw/Dataset066_CC/imagesTr/0010610620190924091717RCASIA2000_0000.png"**
Traceback (most recent call last):
  File "/home/share/anaconda3/envs/nnUNet/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 173, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 180, in verify_dataset_integrity
    reader_writer_class = determine_reader_writer_from_dataset_json(dataset_json, join(folder, 'imagesTr',
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/imageio/reader_writer_registry.py", line 37, in determine_reader_writer_from_dataset_json
    return determine_reader_writer_from_file_ending(dataset_json_content['file_ending'], example_file,
  File "/home/share/anaconda3/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/imageio/reader_writer_registry.py", line 70, in determine_reader_writer_from_file_ending
    raise RuntimeError("Unable to determine a reader for file ending %s and file %s (file None means no file provided)." % (file_ending, example_file))
**RuntimeError: Unable to determine a reader for file ending .png and file /mnt/hdd/xzhang/CC/nnUNet/nnUNet_raw/Dataset066_CC/imagesTr/0010610620190924091717RCASIA2000_0000.png (file None means no file provided).**

**Comment by FabianIsensee** [comment]
Can you please share the file?

**Comment by XinZ0419** [comment]
> Can you please share the file?

Hi Fabianlsensee, thanks for your reply.
I put it here: [](https://drive.google.com/file/d/1_jPb0-mVZZd_PVQNOInSAzm1SZgAR16l/view?usp=sharing)
The image I used is quite large (2133*1866). Is this the reason I looking for?

**Comment by FabianIsensee** [comment]
The size shouldn't matter

Somehow skimage cannot read your image:
```
import skimage
skimage.io.imread('0010610620190924091717RCASIA2000_0000.png')
```

> RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/home/isensee/Downloads/0010610620190924091717RCASIA2000_0000.png"

It doesn't appear to be a standard png!?

**Comment by XinZ0419** [comment]
Thanks. I resave them with skimage, it works!

**Comment by FabianIsensee** [comment]
Maybe. This could be because png then rounds everything to either 0 or 1. But it could also just be a display issue with your image viewer which assumes that pixels range from [0, 255].

If you read the image again after doing that: are the pixel values still correct or are they only either 0 or 1?
If the values are still correct then you don't need to worry about it.

But why would you do any rescaling of intensities in in the first place? Let nnU-Net handle that. Either leave everything on default or declare 'rgb_to_0_1' for all three input channels in dataset.json (will divide pixel values by 255 to bring them to [0, 1])

Best,
Fabian
