### ISSUE TITLE
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 2305: invald continuation byte

### ISSUE THREAD

**Issue by Overflowu7** [MIC-DKFZ/nnUNet#1361]
Hello, I don't know what happend with this error because i don't change anythings. Why the unicodedecodeError appear in the evaluator?

2023-03-30 10:55:56.292514: finished prediction
2023-03-30 10:55:56.292727: evaluation of raw predictions
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/multiprocessing/pool.py",line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/multiprocessing/pool.py",line 48, in mapstar
    return list(map(*args))
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/evaluation/evaluator.py", line 313, n run_evaluation
    current_scores = evaluator.evaluate(**metric_kwargs)
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/evaluation/evaluator.py", line 303, n evaluate
    return super(NiftiEvaluator, self).evaluate(test, reference, **metric_kwargs
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/evaluation/evaluator.py", line 172, n evaluate
    frames = inspect.getouterframes(inspect.currentframe())
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/inspect.py", line 1531, i getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/inspect.py", line 1505, i getframeinfo
    lines, lnum = findsource(frame)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/inspect.py", line 831, infindsource
    lines = linecache.getlines(file, module.__dict__)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/linecache.py", line 46, i getlines
    return updatecache(filename, module_globals)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/linecache.py", line 137, n updatecache
    lines = fp.readlines()
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/codecs.py", line 322, in ecode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 2305: invald continuation byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wycback/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/run/run_training.py", line 189, in min
    trainer.validate(save_softmax=args.npz, validation_folder_name=val_folder,
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTraierV2.py", line 193, in validate
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/training/network_training/nnUNetTraier.py", line 643, in validate
    _ = aggregate_scores(pred_gt_tuples, labels=list(range(self.num_classes)),
  File "/home/cui/nnUNetFrame/nnUNet/nnunet/evaluation/evaluator.py", line 360, n aggregate_scores
    all_res = p.map(run_evaluation, zip(test, ref, [evaluator]*len(ref), [metrickwargs]*len(ref)))
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/multiprocessing/pool.py",line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/multiprocessing/pool.py",line 771, in get
    raise self._value
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 2305: invald continuation byte
Exception in thread Thread-5:
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/threading.py", line 980, n _bootstrap_inner
Traceback (most recent call last):
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/threading.py", line 980, n _bootstrap_inner
    self.run()
    self.run()
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/threading.py", line 917, n run
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/threading.py", line 917, n run
    self._target(*self._args, **self._kwargs)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/site-packages/batchgeneraors/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    self._target(*self._args, **self._kwargs)
  File "/home/cui/anaconda3/envs/wycback/lib/python3.9/site-packages/batchgeneraors/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end tis madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madnes.
IMPORTANT: This is not the actual error message! Look further up to see what caued the error. Please also check whether your RAM was full    raise RuntimeError(Abort event was set. So someone died and we should end this madness. \nIMPORTANT "

RuntimeError: Abort event was set. So someone died and we should end this madnes.
IMPORTANT: This is not the actual error message! Look further up to see what caued the error. Please also check whether your RAM was full

**Comment by FabianIsensee** [comment]
Uff I don't know. @jenspetersen wrote the evaluator a long time ago. nnU-Net V2 uses a simpler implementation of the metrics. My suggestion would be to use v2 from here on :sweat_smile:

**Comment by Overflowu7** [comment]
But the error was happend when i run  "nnUNet_train 3d_lowres nnUNetTrainerV2". It appeared everytime after  finished prediction and  evaluation of raw predictions.It maybe a system unicode error not code. However  the error still occur ,thought I try some way to solve it T_T.

**Comment by FabianIsensee** [comment]
If you can give me something with which I can reproduce this error then I can try to fix it

**Comment by FabianIsensee** [comment]
ah and btw nnUNetTrainerV2 is not nnU-net v2 ;-)

**Comment by Overflowu7** [comment]
> ah and btw nnUNetTrainerV2 is not nnU-net v2 ;-)

Thank you very very much fabian! The errors disappear in V2 but still exist in V1 ,I will try to check it in the future!
