### ISSUE TITLE
What is the reason for the following error when I am training my data

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#138]
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 275, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 351, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 534, in run_iteration
    l = self.loss(output, target)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/nnUNet/nnunet/training/loss_functions/dice_loss.py", line 122, in forward
    dc_loss = self.dc(net_output, target)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zlf/nnUNet/nnunet/training/loss_functions/dice_loss.py", line 100, in forward
    tp, fp, fn = get_tp_fp_fn(x, y, axes, loss_mask, self.square)
  File "/home/zlf/nnUNet/nnunet/training/loss_functions/dice_loss.py", line 56, in get_tp_fp_fn
    fn = (1 - net_output) * y_onehot
RuntimeError: CUDA error: device-side assert triggered

**Comment by FabianIsensee** [comment]
see https://github.com/MIC-DKFZ/nnUNet/issues/139
Probably the same issue :-)
