### ISSUE TITLE
What does it mean to find the best configuration in the 5-fold cross-validation under the 3d_fullres configuration?

### ISSUE THREAD

**Issue by angolin22** [MIC-DKFZ/nnUNet#1388]
When I use this command `nnUNetv2_find_best_configuration DATASET_NAME_OR_ID -c 3d_fullres,` because I don't know much about his theoretical knowledge, I don't know what he means to decide the best configuration. May I ask what is his theoretical knowledge?

**Comment by FabianIsensee** [comment]
This command uses the 5-fold cross validation to determine which if the configurations among the ones given with -c is the best. It also checks for possible ensembles and will configure the postprocessing. I recommend you take a look at the paper & documentation if you need more information

**Comment by shiblyg** [comment]
Hi While I am running this getting this error:
Traceback (most recent call last):
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/evaluate_predictions.py", line 26, in key_to_label_or_region
    return int(key)
ValueError: invalid literal for int() with base 10: '(3,)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/msadi002/envs/nnUnet2/bin/nnUNetv2_find_best_configuration", line 8, in <module>
    sys.exit(find_best_configuration_entry_point())
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/find_best_configuration.py", line 295, in find_best_configuration_entry_point
    find_best_configuration(dataset_name, model_dict, allow_ensembling=not args.disable_ensembling,
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/find_best_configuration.py", line 103, in find_best_configuration
    'result': load_summary_json(join(merged_output_folder, 'summary.json'))['foreground_mean']['Dice']
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/evaluate_predictions.py", line 54, in load_summary_json
    results['mean'] = {key_to_label_or_region(k): results['mean'][k] for k in results['mean'].keys()}
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/evaluate_predictions.py", line 54, in <dictcomp>
    results['mean'] = {key_to_label_or_region(k): results['mean'][k] for k in results['mean'].keys()}
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/evaluate_predictions.py", line 31, in key_to_label_or_region
    return tuple([int(i) for i in splitted])
  File "/home/msadi002/envs/nnUnet2/lib/python3.10/site-packages/nnunetv2/evaluation/evaluate_predictions.py", line 31, in <listcomp>
    return tuple([int(i) for i in splitted])
ValueError: invalid literal for int() with base 10: ''
.....It takes 28 s to finish the task.....

**Comment by dojoh** [comment]
Hey, 

which command are you running precisely so I can try to reproduce the problem?

Cheers
Ole Johannsen
