### ISSUE TITLE
Hey, why do I have the following problems when I'm training

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#139]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/generic/THCTensorMath.cu line=26 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 275, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 351, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/zlf/nnUNet/nnunet/training/network_training/network_trainer.py", line 543, in run_iteration
    l.backward()
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1565272279342/work/aten/src/THC/generic/THCTensorMath.cu:26

**Comment by FabianIsensee** [comment]
Hi,
it seems like something is off with your data. Maybe there are labels in your segmentations that you did not declare in the dataset.json? If you declare label 0, 1, 2, 3 and then there is for example a 4 in one of your images this is the error you will get.
Best,
Fabian
