### ISSUE TITLE
error about pretrain and fine-tune? 

### ISSUE THREAD

**Issue by xiaolinfan** [MIC-DKFZ/nnUNet#1398]
Hi,
When I fine-tune, the following error occurred. ```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/nnunetdev/nnUNet/nnunetv2/run/run_training.py", line 119, in run_ddp
    maybe_load_checkpoint(nnunet_trainer, c, val, pretrained_weights)
  File "/home/nnunetdev/nnUNet/nnunetv2/run/run_training.py", line 91, in maybe_load_checkpoint
    load_pretrained_weights(nnunet_trainer.network, pretrained_weights_file, verbose=True)
  File "/home/nnunetdev/nnUNet/nnunetv2/run/load_pretrained_weights.py", line 19, in load_pretrained_weights
    model_dict = network.state_dict()
AttributeError: 'NoneType' object has no attribute 'state_dict'
```
May I ask what the reason is?

**Comment by xiaolinfan** [comment]
May I ask if the solution is the following：
`run_training.py—>get_trainer_from_args(), `Add a code `nnunet_trainer.initialize()` to the penultimate line of this function
@Fabian

**Comment by FabianIsensee** [comment]
Hey, it could be that the weights of the network were not yet initialized. This should be fixed on the current master already
