### ISSUE TITLE
RuntimeError: One or more background workers are no longer alive

### ISSUE THREAD

**Issue by xh542428798** [MIC-DKFZ/nnUNet#1406]
when I run preidict 'nnUNetv2_predict -d Dataset012_npcMutiMod -i /imagesTs -o /infer1 -f  0 1 2 3 4 -tr nnUNetTrainer -c 2d -p nnUNetPlans --save_probabilities', nearly predict half of data, it return an error: 
  File "/home/xiehui/anaconda3/envs/nnUnetV2/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

is it the error of my data?

**Comment by alf-wangzhi** [comment]
i got the same question  do you fix it

**Comment by xh542428798** [comment]
> i got the same question  do you fix it
> 

it seems do not influenced the further step, my npz data had been created successesfully, you can try further steps.

**Comment by FabianIsensee** [comment]
For real guys - do you even read error messages? There are like 1000 issues here where people only post this generic error message even though it clearly states to **`check the print statements above for the actual error message`**
Please provide the entire text output!

**Comment by FabianIsensee** [comment]
(if there is none, then this is also valuable information)

**Comment by YunxinZhong** [comment]
threadpoolctl 2.2.0 will cause bugs in batchgenerators 0.25. batchgenerators will report error message "One or more background workers are no longer alive. Exiting. Please check the..."

threadpoolctl 3.3.0 is OK.

**Comment by Guurrrrrr** [comment]
> threadpoolctl 2.2.0 将导致 batchgenerators 0.25 出现错误。batchgenerators 将报告错误消息“一个或多个后台工作人员不再活着。正在退出。请检查...”
> 
> threadpoolctl 3.3.0 没问题。

I tried the threadpoolctl 3.0.0, but this problem didn't resolved.

**Comment by mengxuanli** [comment]
when i run nnUNet_train 3d_fullres nnUNetTrainerV2 1 0 --npz
it return the following error:

Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/run/run_training.py", line 182, in main
    trainer.run_training()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/network_trainer.py", line 419, in run_training
    _ = self.val_gen.next()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lhq323/1Tdev/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

I added os.environ['OMP_NUM_THREADS']="1" in __init__.py, but the problem still has.

**Comment by merezhou** [comment]
nnUNet defaults to 1000 for the original epoch, which is too long for us to open the nnUNet/nnunet/training/network_training/nnUNetTrainerV2 .py

The max_epoch in line 48 to modify epoch
