### ISSUE TITLE
Exception in thread Thread-4 (results_loop):

### ISSUE THREAD

**Issue by alf-wangzhi** [MIC-DKFZ/nnUNet#1411]
2023-04-20 04:33:58.757071: unpacking dataset...
2023-04-20 04:34:04.979595: unpacking done...
2023-04-20 04:34:04.986058: do_dummy_2d_data_aug: False
2023-04-20 04:34:05.006134: Using splits from existing split file: D:\论文代码\nnunet\nnUNet\nnUNetFrame\DATASET\nnUNet_preprocessed/Dataset001_BrainTumour/splits_final.json
2023-04-20 04:34:05.017286: The split file contains 5 splits.
2023-04-20 04:34:05.023050: Desired fold for training: 0
2023-04-20 04:34:05.029380: This split has 387 training and 97 validation cases.
2023-04-20 04:34:09.043840: Unable to plot network architecture:
2023-04-20 04:34:09.048353: module 'torch.onnx' has no attribute '_optimize_trace'
2023-04-20 04:34:09.066314:
2023-04-20 04:34:09.070392: Epoch 0
2023-04-20 04:34:09.074604: Current learning rate: 0.01
using pin_memory on device 0
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/workspace/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/workspace/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/workspace/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1227, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

run nnUNetv2_train  1 2d 0 --npz                i dont know  what's the problem

**Comment by FabianIsensee** [comment]
can you please send me the entire text output? The actual error message is missing:

> RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by FabianIsensee** [comment]
not sure how compatible things are with chinese characters in folder names: `D:\论文代码\nnunet\nnUNet\nnUNetFrame\DATASET\nnUNet_preprocessed/Dataset001_BrainTumour/splits_final.json`

**Comment by hdnissen** [comment]
I am getting the exact same error - without any chinese chaca

2023-05-02 17:05:18.213253: unpacking dataset...
2023-05-02 17:05:28.636516: unpacking done...
2023-05-02 17:05:28.637755: do_dummy_2d_data_aug: False
2023-05-02 17:05:28.638428: Using splits from existing split file: output/nnUNet_preprocessed/Dataset555_AIRCON/splits_final.json
2023-05-02 17:05:28.638997: The split file contains 5 splits.
2023-05-02 17:05:28.639093: Desired fold for training: 1
2023-05-02 17:05:28.639178: This split has 5 training and 2 validation cases.
2023-05-02 17:05:47.219182: Unable to plot network architecture:
2023-05-02 17:05:47.219708: module 'torch.onnx' has no attribute '_optimize_trace'
2023-05-02 17:05:47.280705: 
2023-05-02 17:05:47.280872: Epoch 0
2023-05-02 17:05:47.281216: Current learning rate: 0.01
using pin_memory on device 0
using pin_memory on device 0
2023-05-02 17:09:45.935655: train_loss 0.5165
2023-05-02 17:09:45.936461: val_loss 0.3101
2023-05-02 17:09:45.936769: Pseudo dice [0.0, 0.0, 0.4665, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
2023-05-02 17:09:45.936964: Epoch time: 238.66 s
2023-05-02 17:09:45.937135: Yayy! New best EMA pseudo Dice: 0.0466
2023-05-02 17:09:48.682938: 
2023-05-02 17:09:48.683683: Epoch 1
2023-05-02 17:09:48.683932: Current learning rate: 0.00999
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/workspace/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/workspace/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/workspace/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1227, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message


It is running in a docker container.

**Comment by FabianIsensee** [comment]
That information is important :-) Did you set --ipc=host when launching the docker?

**Comment by hdnissen** [comment]
It is running in a nomad cloud-like setup, so I cannot directly set this.  

Initially we had this error:

2023-04-28 07:03:51.830091: Unable to plot network architecture:
2023-04-28 07:03:51.830244: No module named 'hiddenlayer'
2023-04-28 07:03:51.839402: 
2023-04-28 07:03:51.839560: Epoch 0
2023-04-28 07:03:51.839766: Current learning rate: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 369, in reduce_storage
    fd, size = storage._share_fd_cpu_()
**RuntimeError: unable to write to file </torch_32096_1415667320_0>: No space left on device (28)**
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/opt/conda/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Where we got an out-of-space error message. I increased shared memory to 1GB and that got us to the present point, with a similar failure but no specific error message. I have tried increasing shared memory even more, and it seems to be running without errors now...

**Comment by FabianIsensee** [comment]
--ipc=host would also have fixed the shared memory problem. So that seems to have been it :-) Glad it works now
