### ISSUE TITLE
One or more background workers are no longer alive.

### ISSUE THREAD

**Issue by ekinyagis** [MIC-DKFZ/nnUNet#1437]
Hello,

I have received the following runtime error when I started training the model.

Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/Users/yagis/opt/anaconda3/envs/nn_UNet/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Users/yagis/opt/anaconda3/envs/nn_UNet/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yagis/opt/anaconda3/envs/nn_UNet/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/Users/yagis/opt/anaconda3/envs/nn_UNet/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Why do you think it could be?

**Comment by LouisDo2108** [comment]
It is likely that you have run out of CPU, nnUNet is very computational expensive in terms of CPUs.

**Comment by waleve** [comment]
Maybe you can shut down the Chrome and other programme, to leave CPU for nnUnet use

**Comment by Guurrrrrr** [comment]
> 

I got the same question do you fix it?

**Comment by akeebatra** [comment]
in same situation. anyone got it running?

**Comment by ancestor-mithril** [comment]
Use less threads for data augmentation when OOM.
```
nnUNet_n_proc_DA=4 nnUNetv2_train ...
```

**Comment by akeebatra** [comment]
> Use less threads for data augmentation when OOM.
> 
> ```
> nnUNet_n_proc_DA=4 nnUNetv2_train ...
> ```

What this nnUNet_n_proc_DA=4 does?

**Comment by akeebatra** [comment]
Same error
(base) Akshays-MacBook-Pro:~ akshay$ nnUNet_n_proc_DA=4 nnUNetv2_train 1 2d 0 -device cpu
Using device: cpu

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################


This is the configuration used by this training:
Configuration name: 2d
 {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 13, 'patch_size': [768, 320], 'median_image_size_in_voxels': [3180.0, 1498.5], 'spacing': [1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2, 2], 'num_pool_per_axis': [7, 6], 'pool_op_kernel_sizes': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 1]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'unet_max_num_features': 512, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': True} 

These are the global plan.json settings:
 {'dataset_name': 'Dataset001_InBreast', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [999.0, 1.0, 1.0], 'original_median_shape_after_transp': [1, 3180, 1498], 'image_reader_writer': 'NaturalImage2DIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 255.0, 'mean': 171.5933231709939, 'median': 176.0, 'min': 69.0, 'percentile_00_5': 101.0, 'percentile_99_5': 230.0, 'std': 30.106854637129793}}} 

2023-06-20 19:08:09.706048: unpacking dataset...
2023-06-20 19:08:15.793287: unpacking done...
2023-06-20 19:08:15.796338: do_dummy_2d_data_aug: False
2023-06-20 19:08:15.798208: Using splits from existing split file: /Users/akshay/Documents/Master Project/Breast segmenatation Unet/nnUNet_preprocessed/Dataset001_InBreast/splits_final.json
2023-06-20 19:08:15.798935: The split file contains 5 splits.
2023-06-20 19:08:15.799138: Desired fold for training: 0
2023-06-20 19:08:15.799375: This split has 68 training and 18 validation cases.
2023-06-20 19:08:15.856199: Unable to plot network architecture:
2023-06-20 19:08:15.856580: No module named 'hiddenlayer'
2023-06-20 19:08:15.892347: 
2023-06-20 19:08:15.892934: Epoch 0
2023-06-20 19:08:15.894056: Current learning rate: 0.01
Process Process-4:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 371, in _load_modules
    self._find_modules_with_dyld()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
    self._make_module_from_path(filepath)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Process Process-6:
Process Process-3:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 371, in _load_modules
    self._find_modules_with_dyld()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
    self._make_module_from_path(filepath)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 371, in _load_modules
    self._find_modules_with_dyld()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
    self._make_module_from_path(filepath)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Process Process-5:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 371, in _load_modules
    self._find_modules_with_dyld()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 428, in _find_modules_with_dyld
    self._make_module_from_path(filepath)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/opt/anaconda3/lib/python3.9/site-packages/threadpoolctl.py", line 646, in get_version
    config = get_config().split()
AttributeError: 'NoneType' object has no attribute 'split'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/opt/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/opt/anaconda3/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/opt/anaconda3/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 252, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/opt/anaconda3/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 195, in run_training
    nnunet_trainer.run_training()
  File "/opt/anaconda3/lib/python3.9/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1211, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/opt/anaconda3/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
(base) Akshays-MacBook-Pro:~ akshay$

**Comment by ancestor-mithril** [comment]
> > Use less threads for data augmentation when OOM.
> > ```
> > nnUNet_n_proc_DA=4 nnUNetv2_train ...
> > ```
> 
> What this nnUNet_n_proc_DA=4 does?

It sets the number of processes for data augmentation to 4.

**Comment by ancestor-mithril** [comment]
> Same error (base) Akshays-MacBook-Pro:~ akshay$ nnUNet_n_proc_DA=4 nnUNetv2_train 1 2d 0 -device cpu Using device: cpu
> 

In your case, use single threaded nnUNet: 
```nnUNet_n_proc_DA=0 ...```
For multi-threading, solve the issue with threadpoolctl incompatibility (see [this](https://stackoverflow.com/questions/71352354/sklearn-kmeans-is-not-working-as-i-only-get-nonetype-object-has-no-attribute)).

**Comment by akeebatra** [comment]
I was able to run it on different hardware. Now i am trying to run it on linux, even though i have installed nnunet, it still gives eror
nnUNetv2_: command not found

**Comment by Karol-G** [comment]
Hey all,

nnU-Net recently had some major changes done to its multiprocessing handling. It might be that the errors you are all getting are fixed by now.
Please pull the latest commits and reinstall nnU-Net or install it with `pip install -e .`

Best,
Karol
