### ISSUE TITLE
 list index out of range

### ISSUE THREAD

**Issue by NLPgameplayer** [MIC-DKFZ/nnUNet#1445]
Run'nnUNetv2_predict -i /home/cz/model/nnUNet-master/DATASET/nnUNet_raw/nnUNet_raw_data/Task04_Hippocampus/imagesTs/ -o /home/cz/model/nnUNet-master/DATASET/nnUNet_raw/nnUNet_raw_data/Task04_Hippocampus/inferTs/ -d 4  -c 3d_fullres
'debug assertion failed：
There are 1 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 0 cases that I would like to predict
Exception in background worker 0:
 list index out of range
Traceback (most recent call last):
  File "/home/cz/anaconda3/envs/nnUnet/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 46, in producer
    item = next(data_loader)
  File "/home/cz/anaconda3/envs/nnUnet/lib/python3.9/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/cz/model/nnUNet-master/nnunetv2/inference/data_iterators.py", line 42, in generate_train_batch
    files = self._data[idx][0]
IndexError: list index out of range
using pin_memory on device 0
Traceback (most recent call last):
  File "/home/cz/anaconda3/envs/nnUnet/bin/nnUNetv2_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_predict')())
  File "/home/cz/model/nnUNet-master/nnunetv2/inference/predict_from_raw_data.py", line 600, in predict_entry_point
    r = predict_from_raw_data(args.i,
  File "/home/cz/model/nnUNet-master/nnunetv2/inference/predict_from_raw_data.py", line 221, in predict_from_raw_data
    return predict_from_data_iterator(data_iterator, network, parameters, plans_manager, configuration_manager, dataset_json,
  File "/home/cz/model/nnUNet-master/nnunetv2/inference/predict_from_raw_data.py", line 250, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/cz/anaconda3/envs/nnUnet/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/home/cz/anaconda3/envs/nnUnet/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

what should I do？

**Comment by Lars-Kraemer** [comment]
Hey @NLPgameplayer 

could you resolve the problem or is it still happening with the current nnUNet version?

Best,
Lars
