### ISSUE TITLE
Has validation_raw been changed to validation?

### ISSUE THREAD

**Issue by mangovisual** [MIC-DKFZ/nnUNet#1455]
Hi!
I can't find a **validation_raw** folder in every fold but just a **validation** folder after i trained using --npz, and no summary.json in the validation folder, is it something wrong in my training process? Thanks!

**Comment by mangovisual** [comment]
![L9LU$W%Z)AM`%~0TVTD1R9U](https://github.com/MIC-DKFZ/nnUNet/assets/65489402/4f0f441c-f025-4339-a241-57ed5a63a69d)

**Comment by mangovisual** [comment]
The reason why  no summary.json is because of assertion error:

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/bqs/.conda/envs/bqs/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/bqs/.conda/envs/bqs/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/bqs/nnUNet/nnunetv2/inference/export_prediction.py", line 92, in export_prediction_from_logits
    rw.write_seg(segmentation_final, output_file_truncated + dataset_json_dict_or_file['file_ending'],
  File "/home/bqs/nnUNet/nnunetv2/imageio/nibabel_reader_writer.py", line 188, in write_seg
    assert np.all(np.isclose(properties['nibabel_stuff']['original_affine'], seg_nib_reoriented.affine)), \
AssertionError: restored affine does not match original affine
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bqs/.conda/envs/bqs/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/home/bqs/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/bqs/nnUNet/nnunetv2/run/run_training.py", line 198, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/home/bqs/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1198, in perform_actual_validation
    _ = [r.get() for r in results]
  File "/home/bqs/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1198, in <listcomp>
    _ = [r.get() for r in results]
  File "/home/bqs/.conda/envs/bqs/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AssertionError: restored affine does not match original affine

is it because bad data? how can i fixed it?

**Comment by sten2lu** [comment]
Hi @mangovisual,
it seems as if you already were able to solve this issue by yourself.

Generally when encountering this behavior, we advise to check the data.
Often the problem is then related to the warning during the verification of the dataset integrity:
```
WARNING: Affine is not the same for image and seg! ...
```
In the warning the specific files which lead to this warning are mentioned.

As there was no further activity on this issue, it is marked as stale and will be closed on Monday 11th of September if no further activity occurs.

Best regards,

Carsten
