### ISSUE TITLE
Issue with bringing over focal loss to v2

### ISSUE THREAD

**Issue by thegooby** [MIC-DKFZ/nnUNet#1468]
Instead of trying to fix the issue I previously had in v1, I made an attempt to bring the files over to work with v2. Notably, I used the relevant DC focal loss files from https://github.com/JunMa11/SegLoss . After placing the files in the correct folders and adjusting the paths in the imports, I run

`nnUNetv2_train -tr nnUNetTrainer_Loss_DiceFocal 500 3d_fullres all`

I was able to correct the first few errors that came up by modifying parts of the files that I was adjusting. However, I am stuck on 

`2023-05-25 23:47:25.735886: unpacking dataset...
2023-05-25 23:47:25.889124: unpacking done...
2023-05-25 23:47:25.889558: do_dummy_2d_data_aug: False
2023-05-25 23:47:25.901818: Unable to plot network architecture:
2023-05-25 23:47:25.901860: No module named 'pexpect'
2023-05-25 23:47:25.903691: 
2023-05-25 23:47:25.903715: Epoch 0
2023-05-25 23:47:25.903759: Current learning rate: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/home/luke/miniconda3/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/home/luke/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/luke/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/home/luke/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1228, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/luke/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 872, in train_step
    l = self.loss(output, target)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/nnUNet/nnunetv2/training/loss/DC_focals.py", line 20, in forward
    dc_loss = self.dc(net_output, target)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/nnUNet/nnunetv2/training/loss/dice.py", line 28, in forward
    shp_x = x.shape
AttributeError: 'list' object has no attribute 'shape'
`
I am attaching txt versions of files that I have modified. I don't believe I made any modifications to the nnUNetTrainer file.

[DC_focals.txt](https://github.com/MIC-DKFZ/nnUNet/files/11571410/DC_focals.txt)
[focal_loss.txt](https://github.com/MIC-DKFZ/nnUNet/files/11571411/focal_loss.txt)
[nnUNetTrainer_Loss_DiceFocal.txt](https://github.com/MIC-DKFZ/nnUNet/files/11571425/nnUNetTrainer_Loss_DiceFocal.txt)

**Comment by ancestor-mithril** [comment]
I think you need the following code:
https://github.com/MIC-DKFZ/nnUNet/blob/45a47ec7254b56628ec03765ab24bb0b3422e22b/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L351-L362

Or you could disable deep supervision.

**Comment by thegooby** [comment]
> I think you need the following code:
> 
> https://github.com/MIC-DKFZ/nnUNet/blob/45a47ec7254b56628ec03765ab24bb0b3422e22b/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L351-L362
> 
> I guess you receive a list of losses for deep supervision so you need to use the DeepSupervisionWrapper. Or you could disable deep supervision.

Adding those lines of code absolutely fixed the current issue I was having. However, I am getting this error now:

`
Traceback (most recent call last):
  File "/home/luke/miniconda3/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/home/luke/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/luke/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/home/luke/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1228, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/luke/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 872, in train_step
    l = self.loss(output, target)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/nnUNet/nnunetv2/training/loss/deep_supervision.py", line 30, in forward
    l = weights[0] * self.loss(*[j[0] for j in args])
  File "/home/luke/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/nnUNet/nnunetv2/training/loss/DC_focals.py", line 22, in forward
    dc_loss = self.dc(net_output, target)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/luke/nnUNet/nnunetv2/training/loss/dice.py", line 40, in forward
    tp = AllGatherGrad.apply(tp).sum(0)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/luke/nnUNet/nnunetv2/utilities/ddp_allgather.py", line 35, in forward
    gathered_tensor = [torch.zeros_like(tensor) for _ in range(torch.distributed.get_world_size())]
  File "/home/luke/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1181, in get_world_size
    return _get_group_size(group)
  File "/home/luke/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 566, in _get_group_size
    default_pg = _get_default_group()
  File "/home/luke/.local/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 697, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
`

My best guess is that it is expecting an additional `def __init__` somewhere, but the trainer variant I am using follows the same format as variants that are included in this repo, such as

`
class nnUNetTrainer_Loss_DiceFocal(nnUNetTrainer):
...
    def _build_loss(self):
...
        return loss 
`
so I am unsure what is lacking.

**Comment by dheepak-s** [comment]
@thegooby I'm also facing the same issue as you. Can you share the updated working code?

**Comment by thegooby** [comment]
> @thegooby I'm also facing the same issue as you. Can you share the updated working code?
[DC_focals.txt](https://github.com/MIC-DKFZ/nnUNet/files/14642860/DC_focals.txt)
[focal_loss.txt](https://github.com/MIC-DKFZ/nnUNet/files/14642861/focal_loss.txt)
[nnUNetTrainer_Loss_DiceFocal.txt](https://github.com/MIC-DKFZ/nnUNet/files/14642862/nnUNetTrainer_Loss_DiceFocal.txt)

Sorry for the late reply. I've attached the 3 modified files I used.
