### ISSUE TITLE
Error when trying to run plan_and_process using 2d data

### ISSUE THREAD

**Issue by vcasellesb** [MIC-DKFZ/nnUNet#1486]
Hi,

First of all, thank you very much Fabian and the team for all the effort. I've been trying to find an issue entry that already solves my issue, but I haven't found a satisfactory one.

I'm trying to run plan_and_processing on a 2d dataset, and I get the following error:

```
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/nervis/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 177, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 82, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 68, in plan_experiment_dataset
    ).plan_experiment()
      ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 400, in plan_experiment
    plan_3d_fullres = self.get_plans_for_configuration(fullres_spacing_transposed,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 260, in get_plans_for_configuration
    shape_must_be_divisible_by = get_pool_and_conv_props(spacing, initial_patch_size,
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/nervis/lib/python3.11/site-packages/nnunetv2/experiment_planning/experiment_planners/network_topology.py", line 82, in get_pool_and_conv_props
    if spacings_of_axes[d] / min(current_spacing) < 2:
       ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

The command I've run to get this error is the following one: `nnUNetv2_plan_and_preprocess -d 001 -c 2d -np 8`

I've specified the configuration and set the number of processes to its default (8) as specified in the docs.

Additional info:

The images are in .nii.gz format, and the shape of one of them is as follows (using nibabel): `(370, 1, 170)`

Is it possible that I have to do some preprocessing to the data?

Thank you very much for your time and your efforts.

Best regards,
Vicent Caselles

**Comment by vcasellesb** [comment]
Hey!

So it's me again. I wanted to respond to myself to say that it is solved! Basically what I did was reshaping the images (e.g. from `(370, 1, 170)` to `(370, 170)`. I don't know if I should close the issue, but yeah, that solved it.

Vicent
