### ISSUE TITLE
Bug with function key_to_label_or_region when using nnUNetv2_find_best_configuration

### ISSUE THREAD

**Issue by arkiolok** [MIC-DKFZ/nnUNet#1495]
Hello,
I was using nnUNetV2 on BraTS 2021 dataset and after training phase, when I was trying to use the nnUNetv2_find_best_configuration function, I came accross this error.

```
Configuration 3d_lowres not found in plans nnUNetPlans.
Inferred plans file: /projects/hakanak2/nnUNet_prj/nnUNet_preprocessed/Dataset137_BraTS2021/nnUNetPlans.json.
Configuration 3d_cascade_fullres not found in plans nnUNetPlans.
Inferred plans file: /projects/hakanak2/nnUNet_prj/nnUNet_preprocessed/Dataset137_BraTS2021/nnUNetPlans.json.
Traceback (most recent call last):
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/evaluate_predictions.py", line 26, in key_to_label_or_region
    return int(key)
           ^^^^^^^^
ValueError: invalid literal for int() with base 10: '(3,)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hakanak2/miniconda3/envs/brainseg/bin/nnUNetv2_find_best_configuration", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_find_best_configuration')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/find_best_configuration.py", line 295, in find_best_configuration_entry_point
    find_best_configuration(dataset_name, model_dict, allow_ensembling=not args.disable_ensembling,
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/find_best_configuration.py", line 103, in find_best_configuration
    'result': load_summary_json(join(merged_output_folder, 'summary.json'))['foreground_mean']['Dice']
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/evaluate_predictions.py", line 54, in load_summary_json
    results['mean'] = {key_to_label_or_region(k): results['mean'][k] for k in results['mean'].keys()}
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/evaluate_predictions.py", line 54, in <dictcomp>
    results['mean'] = {key_to_label_or_region(k): results['mean'][k] for k in results['mean'].keys()}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/evaluate_predictions.py", line 31, in key_to_label_or_region
    return tuple([int(i) for i in splitted])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hakanak2/nnUNet/nnunetv2/evaluation/evaluate_predictions.py", line 31, in <listcomp>
    return tuple([int(i) for i in splitted])
                  ^^^^^^
ValueError: invalid literal for int() with base 10: ''

```

The error is occuring because in the 'summary.json' files, the last key in 'mean' or 'metrics' is written as '(3,)'. When using the python string.split function, it also creates and empty '' element inside the list.

I could solve the issue on my side by editing key_to_label_or_region funciton and adding a exception for the cause:
```
def key_to_label_or_region(key: str):
    try:
        return int(key)
    except ValueError:
        key = key.replace('(', '')
        key = key.replace(')', '')
        splitted = key.split(',')
        try:
            return tuple([int(i) for i in splitted])
        except ValueError:
            return tuple([int(splitted[0])])
```

This workaround worked well for my case but I didn't bother to change how the 'summary.json' files are written. Wanted to inform you on that.

Best.

**Comment by GregorKoehler** [comment]
Hi @arkiolok,
thanks for pointing this out! Can you provide a little more context so we can reproduce this? Did you find what caused this '(3,)' entry?

**Comment by GregorKoehler** [comment]
Closing this issue for now, as it has been stale for a while. Feel free to re-open if there is a need for it!
