### ISSUE TITLE
RuntimeError: CUDA error: uncorrectable NVLink error detected during the execution

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#1519]
Any idea what would cause this error during training?

```
/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainer.py:712: RuntimeWarning: invalid value encountered in double_scalars
  global_dc_per_class = [i for i in [2 * i / (2 * i + j + k) for i, j, k in
Traceback (most recent call last):
  File "/home/support/public/pytorch_1.11.0_agate/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 255, in run_iteration
    self.amp_grad_scaler.step(self.optimizer)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 338, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in _maybe_opt_step
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/cuda/amp/grad_scaler.py", line 284, in <genexpr>
    if not sum(v.item() for v in optimizer_state["found_inf_per_device"].values()):
RuntimeError: CUDA error: uncorrectable NVLink error detected during the execution
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: uncorrectable NVLink error detected during the execution
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from record at /opt/conda/conda-bld/pytorch_1646755888698/work/aten/src/ATen/cuda/CUDAEvent.h:119 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x4d (0x7f20cabce1bd in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xaeeb5 (0x7f2108fb2eb5 in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libtorch_cuda_cpp.so)
frame #2: <unknown function> + 0x2ecde8 (0x7f210f642de8 in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #3: c10::TensorImpl::release_resources() + 0x175 (0x7f20cabb4fb5 in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x1db689 (0x7f210f531689 in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x4c679c (0x7f210f81c79c in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: THPVariable_subclass_dealloc(_object*) + 0x292 (0x7f210f81caa2 in /home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x12fb9f (0x560d161e7b9f in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #8: <unknown function> + 0x13cc08 (0x560d161f4c08 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #9: <unknown function> + 0x14dfef (0x560d16205fef in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #10: <unknown function> + 0x14e0d1 (0x560d162060d1 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #11: <unknown function> + 0x14e0d1 (0x560d162060d1 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #12: <unknown function> + 0x14e0d1 (0x560d162060d1 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #13: <unknown function> + 0x14e0d1 (0x560d162060d1 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #14: <unknown function> + 0x14e0d1 (0x560d162060d1 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #15: <unknown function> + 0x1232c9 (0x560d161db2c9 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #16: PyDict_SetItemString + 0x4a (0x560d161deb8a in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #17: <unknown function> + 0x21cfba (0x560d162d4fba in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #18: Py_FinalizeEx + 0x16f (0x560d162d427f in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #19: Py_RunMain + 0x108 (0x560d162c64d8 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #20: Py_BytesMain + 0x39 (0x560d16294f89 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)
frame #21: __libc_start_main + 0xf5 (0x7f21470b6555 in /lib64/libc.so.6)
frame #22: <unknown function> + 0x1dce91 (0x560d16294e91 in /home/support/public/pytorch_1.11.0_agate/bin/python3.1)

/var/spool/slurmd/job73855914/slurm_script: line 34: 28236 Aborted                 nnUNet_train 3d_fullres nnUNetTrainerV2 552 2

```

**Comment by ykirchhoff** [comment]
Hi Paul,

could you post the error message when running the training with `CUDA_LAUNCH_BLOCKING=1`?

Best,
Yannick
