### ISSUE TITLE
OSError: [WinError 6] Descripteur non valide

### ISSUE THREAD

**Issue by MarwaAbderrahim** [MIC-DKFZ/nnUNet#1523]
Hello, 

I am doing the training, but the code hangs displaying this error message: OSError: [WinError 6] Descripteur non valide

Thank you for your help,  

using pin_memory on device 0
Traceback (most recent call last):
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\Scripts\nnUNet_train.exe\__main__.py", line 7, in <module>
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\nnunet\run\run_training.py", line 177, in main
    trainer.run_training()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\nnunet\training\network_training\nnUNetTrainerV2.py", line 442, in run_training
    ret = super().run_training()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\nnunet\training\network_training\nnUNetTrainer.py", line 319, in run_training
    super(nnUNetTrainer, self).run_training()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\nnunet\training\network_training\network_trainer.py", line 417, in run_training
    _ = self.tr_gen.next()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x000001DB3C9888B0>
Traceback (most recent call last):
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 290, in __del__
    self._finish()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 262, in _finish
    self.abort_event.set()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\multiprocessing\synchronize.py", line 338, in set
    self._cond.notify_all()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\multiprocessing\synchronize.py", line 297, in notify_all
    self.notify(n=sys.maxsize)
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\multiprocessing\synchronize.py", line 272, in notify
    assert not self._wait_semaphore.acquire(
OSError: [WinError 6] Descripteur non valide
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x000001DB3C9888B0>
Traceback (most recent call last):
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 290, in __del__
    self._finish()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 262, in _finish
    self.abort_event.set()
  File "C:\Users\MarwaABDERRAHIM\anaconda3\envs\Train_totalseg\lib\multiprocessing\synchronize.py", line 336, in set
    self._flag.acquire(False)
OSError: [WinError 6] Descripteur non valide

**Comment by sten2lu** [comment]
Hi @MarwaAbderrahim,

have you already solved this issue?
If not, please get in contact with me, but please give me additional information.
Most crucially, I need to know more about the data that you are using, your system, and which trainer.

Best regards,

Carsten
