### ISSUE TITLE
RuntimeError("One or more background workers are no longer alive. Exiting. 

### ISSUE THREAD

**Issue by giuliarubiu** [MIC-DKFZ/nnUNet#1533]
hi I also get the following error:
Traceback (most recent call last):
File "/usr/local/bin/nnUNetv2_train", line 33, in
sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
File "/data/users/giulia/scripts/nnUNet/nnunetv2/run/run_training.py", line 253, in run_training_entry
run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
File "/data/users/giulia/scripts/nnUNet/nnunetv2/run/run_training.py", line 196, in run_training
nnunet_trainer.run_training()
File "/data/users/giulia/scripts/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1227, in run_training
train_outputs.append(self.train_step(next(self.dataloader_train)))
File "/data/users/giulia/scripts/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 867, in train_step
output = self.network(data)
File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
return fn(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/dynamic_network_architectures/architectures/unet.py", line 58, in forward
def forward(self, x):
File "/usr/local/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
return fn(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2819, in forward
return compiled_fn(full_args)
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
return f(*args)
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2386, in debug_compiled_function
return compiled_function(*args)
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1898, in runtime_wrapper
all_outs = call_func_with_args(
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
out = normalize_as_list(f(args))
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1222, in g
return f(*args)
File "/usr/local/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
return super().apply(*args, **kwargs) # type: ignore[misc]
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 2151, in forward
fw_outs = call_func_with_args(
File "/usr/local/lib/python3.9/site-packages/torch/_functorch/aot_autograd.py", line 1247, in call_func_with_args
out = normalize_as_list(f(args))
File "/usr/local/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 248, in run
return model(new_inputs)
File "/tmp/torchinductor_root/76/c76z3d2vbytq5iohj6abm6ohfqvzfklu3vdqtdyy3dmloqxapdjk.py", line 2126, in call
triton__0.run(primals_1, buf0, 864, grid=grid(864), stream=stream0)
File "/usr/local/lib/python3.9/site-packages/torch/_inductor/triton_ops/autotune.py", line 190, in run
result = launcher(
File "", line 6, in launcher
File "/usr/local/lib/python3.9/site-packages/triton/compiler.py", line 1679, in getattribute
self._init_handles()
File "/usr/local/lib/python3.9/site-packages/triton/compiler.py", line 1672, in _init_handles
mod, func, n_regs, n_spills = cuda_utils.load_binary(self.metadata["name"], self.asm["cubin"], self.shared, device)
RuntimeError: Triton Error [CUDA]: device kernel image is invalid
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/threading.py", line 917, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
raise e
File "/usr/local/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

I tried setting the following environment variable:
os.environ['OMP_NUM_THREADS']= "1"
os.environ['nnunet_proc_DA']= "6"

None of them seem working. It's strange because I made others trainings before and everything went alright. Anyone has some suggestion?

**Comment by Joker-ZXR** [comment]
Hello， I meet the same problem. Do you deal with this problem?

**Comment by TenziSky** [comment]
Hello, I solved this problem by expanding share memory from the default 64M to 10G. I hope this can help you.

**Comment by mengxuanli** [comment]
> Hello, I solved this problem by expanding share memory from the default 64M to 10G. I hope this can help you.

hello, Where did you modify it?

**Comment by TenziSky** [comment]
> > Hello, I solved this problem by expanding share memory from the default 64M to 10G. I hope this can help you.
> 
> hello, Where did you modify it?
I'm using docker, and I expand the shared memory when I create the image. If you're using another OS, you can probably do this from the command line.

**Comment by TenziSky** [comment]
> > Hello, I solved this problem by expanding share memory from the default 64M to 10G. I hope this can help you.
> 
> hello, Where did you modify it?

I'm using docker, and I expand the shared memory when I create the image. If you're using another OS, you can probably do this from the command line.

**Comment by giuliarubiu** [comment]
> 

hi my problem is that I was using nnUNet_compile = '1' in a GPU in which I can't do it. Eliminating this environment variable it doesn't give the error anymore

**Comment by FabianIsensee** [comment]
The error you are looking for is `RuntimeError: Triton Error [CUDA]: device kernel image is invalid`.
This means that your GPU isn't supported for compilation. You can try to fix this by upgrading your pytorch version

**Comment by FabianIsensee** [comment]
Or you disable compiling by setting nnUNet_compile to 0 or false
