### ISSUE TITLE
Exception in thread Thread-5 (results_loop):

### ISSUE THREAD

**Issue by mengxuanli** [MIC-DKFZ/nnUNet#1540]
When I run "nnUNet_train 3d_fullres nnUNetTrainerV2 1 0 --npz" the following error with appear

2023-07-05 16:46:21.568689:
epoch:  0

2023-07-05 16:56:44.388724: train loss : -0.2746
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/home/limx/miniconda3/envs/nnunet/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/run/run_training.py", line 182, in main
    trainer.run_training()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/network_trainer.py", line 467, in run_training
    l = self.run_iteration(self.val_gen, False, True)
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration
    data_dict = next(data_generator)
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/limx/miniconda3/envs/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Anyone has some suggestion?

**Comment by mrokuss** [comment]
Hey @mengxuanli 

Thank you for your question. Generally this behavior occurs when some kind of error happened in your pipeline and you are using the `MultiThreadedAugmenter` in the Dataloader. Due to the multiprocessing one or many threads die and report this. However, as the error message says _"One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message"_ - the actual error message is typically higher up in the printed output. Therefore it is hard to say what went wrong if you just get this output. You can try:

- Set the environment variable `nnUNet_n_proc_DA=0` to use the `SingleThreadedAugmenter` (supported in V2, not sure about V1 atm)
- Set OMP_NUM_THREADS=1

and then check if you see an error. Hope this helps.

Max

**Comment by mrokuss** [comment]
Hey @mengxuanli 

Could you resolve your issue in the meantime or have any further questions regarding this topic? Otherwise I might close this issue but feel free to reopen it.

Best,

Max
