### ISSUE TITLE
nnUNetPlans.json not found or created

### ISSUE THREAD

**Issue by KateElizabeth112** [MIC-DKFZ/nnUNet#1541]
I am trying to run planning and preprocessing on a dataset prior to training a 3D nnUNet v2 model. I have split up the planning and preprocessing to separate commands in order to trace errors more easily. After generating the dataset.json, I run the following: 

```
nnUNetv2_extract_fingerprint -d 301
nnUNetv2_plan_experiment -d 301 --verbose
nnUNetv2_preprocess -d 301
```
The extract_fingerprint seems to run fine, but when running plan_experiment there is an error to say that the nnUNetPlans.json cannot be found. I thought this file was automatically generated so I am unsure why this is the case (see below)

```
(venv) Kates-MacBook-Pro:Experiment2 katecevora$ ./run_nnUNet.sh 
/Users/katecevora/Documents/PhD/data/TotalSegmentator_nnUNet/nnUNet_raw
/Users/katecevora/Documents/PhD/data/TotalSegmentator_nnUNet/nnUNet_preprocessed
/Users/katecevora/Documents/PhD/data/TotalSegmentator_nnUNet/nnUNet_results
/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Dataset301_Set1
/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Preprocessing dataset Dataset301_Set1
Traceback (most recent call last):
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/bin/nnUNetv2_plan_experiment", line 8, in <module>
    sys.exit(preprocess_entry())
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 97, in preprocess_entry
    preprocess(args.d, args.plans_name, configurations=args.c, num_processes=args.np, verbose=args.verbose)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 127, in preprocess
    preprocess_dataset(d, plans_identifier, configurations, num_processes, verbose)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 105, in preprocess_dataset
    plans_manager = PlansManager(plans_file)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/utilities/plans_handling/plans_handler.py", line 190, in __init__
    self.plans = plans_file_or_dict if isinstance(plans_file_or_dict, dict) else load_json(plans_file_or_dict)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 68, in load_json
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/katecevora/Documents/PhD/data/TotalSegmentator_nnUNet/nnUNet_preprocessed/Dataset301_Set1/nnUNetPlans.json'
/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/urllib3/__init__.py:34: NotOpenSSLWarning: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Preprocessing dataset Dataset301_Set1
Traceback (most recent call last):
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/bin/nnUNetv2_preprocess", line 8, in <module>
    sys.exit(preprocess_entry())
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 97, in preprocess_entry
    preprocess(args.d, args.plans_name, configurations=args.c, num_processes=args.np, verbose=args.verbose)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 127, in preprocess
    preprocess_dataset(d, plans_identifier, configurations, num_processes, verbose)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 105, in preprocess_dataset
    plans_manager = PlansManager(plans_file)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/nnunetv2/utilities/plans_handling/plans_handler.py", line 190, in __init__
    self.plans = plans_file_or_dict if isinstance(plans_file_or_dict, dict) else load_json(plans_file_or_dict)
  File "/Users/katecevora/Documents/PhD/code/Experiment2/venv/lib/python3.8/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 68, in load_json
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/katecevora/Documents/PhD/data/TotalSegmentator_nnUNet/nnUNet_preprocessed/Dataset301_Set1/nnUNetPlans.json'
```

**Comment by Karol-G** [comment]
Hey @KateElizabeth112,

I was unable to reproduce the error you are getting. Everything works fine on my end. I would recommend to pull the latest commits, make sure that the nnU-Net version you are using is not modified, delete the old preprocessed folder and then to rerun the preprocessing.

Best,
Karol
