### ISSUE TITLE
nnUNetv2_plan_and_preprocess spacings_of_axes Index Out of Range Error on 3D .nii.gz Data

### ISSUE THREAD

**Issue by Karl5766** [MIC-DKFZ/nnUNet#1555]
I wish to run image segmentation on a bio 3D-dataset, where both the input images and the segmentation masks are .nii.gz files of size (1200, 1600, 16). However, similar to issue https://github.com/MIC-DKFZ/nnUNet/issues/1402 I encountered the following error when running plan_and_preprocess:

```Fingerprint extraction...
Dataset001_myelin
Experiment planning...
Traceback (most recent call last):
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 177, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 82, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 61, in plan_experiment_dataset
    return experiment_planner_class(dataset_id,
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\experiment_planners\default_experiment_planner.py", line 400, in plan_experiment
    plan_3d_fullres = self.get_plans_for_configuration(fullres_spacing_transposed,
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\experiment_planners\default_experiment_planner.py", line 301, in get_plans_for_configuration
    get_pool_and_conv_props(spacing, tmp,
  File "C:\Users\Karl2\anaconda3\envs\cellsegmentation\lib\site-packages\nnunetv2\experiment_planning\experiment_planners\network_topology.py", line 82, in get_pool_and_conv_props
    if spacings_of_axes[d] / min(current_spacing) < 2:
IndexError: list index out of range
```

The following script should replicate this issue:

```import os
import nibabel as nib
import numpy as np
import subprocess
import shutil
import json


BASE_DIR = './temp'
RAW_DIR = f'{BASE_DIR}/nnUNet_raw_data'
PREPROCESS_DIR = f'{BASE_DIR}/nnUNet_preprocessed'
RESULTS_DIR = f'{BASE_DIR}/nnUNet_results'
DATASET_DIR = f'{RAW_DIR}/Dataset001_SampleDataset'
IM_TR_DIR = f'{DATASET_DIR}/imagesTr'
LB_TR_DIR = f'{DATASET_DIR}/labelsTr'
if not os.path.exists(BASE_DIR):
    os.mkdir(BASE_DIR)
if not os.path.exists(RAW_DIR):
    os.mkdir(RAW_DIR)
if os.path.exists(PREPROCESS_DIR):
    shutil.rmtree(PREPROCESS_DIR)
if os.path.exists(DATASET_DIR):
    shutil.rmtree(DATASET_DIR)
os.mkdir(DATASET_DIR)
os.mkdir(IM_TR_DIR)
os.mkdir(LB_TR_DIR)
data_json = {"description": "", "labels": {
                            "background": 0,
                            "object": 1,
                        }, "channel_names": {
                            "0": "GRAY",
                        }, "file_ending": ".nii.gz", "overwrite_image_reader_writer": "SimpleITKIO", "numTraining": 1}
with open(f'{DATASET_DIR}/dataset.json',
          'w', encoding='utf-8') as f:
    json.dump(data_json, f, ensure_ascii=False, indent=4)

# make an artificial dataset of only one image/label pair to recreate the issue
dims = (1200, 1600, 16)

# label image
np_im = np.zeros(dims, dtype=np.uint8)
np_im[10:30, 10:30, :] = 1  # avoid zero-size array to reduction operation minimum which has no identity error
nii_im = nib.Nifti1Image(np_im, np.diag((1., 1., 14., 1.)))
nib.save(nii_im, f'{LB_TR_DIR}/sample.nii.gz')

# input image
input_np_im = np.zeros(dims, dtype=np.uint8)
# input_np_im[10:30, 10:30, :] = 1  # with this line the index out of range error disappears
input_nii_im2 = nib.Nifti1Image(input_np_im, np.diag((1., 1., 14., 1.)))
nib.save(input_nii_im2, f'{IM_TR_DIR}/sample_0000.nii.gz')


os.environ['nnUNet_raw'] = RAW_DIR
os.environ['nnUNet_preprocessed'] = PREPROCESS_DIR
os.environ['nnUNet_results'] = RESULTS_DIR
ps = subprocess.run(['nnUNetv2_plan_and_preprocess', '-d', '1'], capture_output=True, text=True)
print(ps.stdout)
print(ps.stderr)
```
The error seems to depend on both the dimensions and the content of the input images, and after adding the line "input_np_im[10:30, 10:30, :] = 1" the error disappears. However, it does occur if I replace the empty input image with the 3d images from the real dataset, which are not empty files as I verified by displaying them as slices using cv2.imshow.

Any help is appreciated!

**Comment by Karl5766** [comment]
https://github.com/MIC-DKFZ/nnUNet/pull/1497 This change seems to solve it, now I can start training. Closing this issue now.

**Comment by FabianIsensee** [comment]
Hey, just to let you know that the PR you reference did not use the correct fix to the problem. Take a look at my commit.
Thanks a lot for the detailed problem description and short script for reproducing the problem. That made it a lot easier to find it and fix it :+1: I really appreciate that!
