### ISSUE TITLE
What is the reason for the following error

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#156]
I am using data from this folder:  /home/cybe/Desktop/copy/nnUNet/nnUNet_preprocessed/Task02_Heart/nnUNet
###############################################
2020-02-18 15:03:45.661914: unpacking dataset
2020-02-18 15:03:45.791786: done
2020-02-18 15:03:47.066677: Unable to plot network architecture:
2020-02-18 15:03:47.066742: No module named 'hiddenlayer'
2020-02-18 15:03:47.066966: 
epoch:  0
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/nnunet-0.6-py3.7.egg/nnunet/training/network_training/nnUNetTrainer.py", line 275, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/nnunet-0.6-py3.7.egg/nnunet/training/network_training/network_trainer.py", line 351, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/nnunet-0.6-py3.7.egg/nnunet/training/network_training/network_trainer.py", line 532, in run_iteration
    output = self.network(data)
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/nnunet-0.6-py3.7.egg/nnunet/network_architecture/generic_UNet.py", line 381, in forward
    x = self.tu[u](x)
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cybe/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 921, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: CUDA out of memory. Tried to allocate 450.00 MiB (GPU 0; 5.93 GiB total capacity; 4.82 GiB already allocated; 278.44 MiB free; 57.30 MiB cached)

**Comment by FabianIsensee** [comment]
Please read the documentation, you need a 12GB GPU
