### ISSUE TITLE
RuntimeError on inference using predict_from_files

### ISSUE THREAD

**Issue by skim2257** [MIC-DKFZ/nnUNet#1561]
I'm attempting to run inference via .predict_from_files with the following line:
```python
model.predict_from_files(files, None,
                         save_probabilities=False, 
                         overwrite=False,
                         num_processes_preprocessing=1, 
                         num_processes_segmentation_export=1,
                         folder_with_segs_from_prev_stage=None,
                         num_parts=1, part_id=0)
```

`files` is a list of absolute file paths to files ending with `.nii.gz`

```
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 7 cases that I would like to predict
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fdeprec.c line 156 in itk_H5Fis_hdf5(): unable to determine if file is accessible as HDF5
    major: File accessibility
    minor: Not an HDF5 file
  #001: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3769 in itk_H5VL_file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #002: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3699 in H5VL__file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #003: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLnative_file.c line 384 in itk_H5VL__native_file_specific(): error in HDF5 file check
    major: File accessibility
    minor: Unable to initialize object
  #004: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1086 in itk_H5F__is_hdf5(): error while trying to locate file signature
    major: File accessibility
    minor: Not an HDF5 file
  #005: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 113 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #006: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 189 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #007: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 755 in H5FD__sec2_read(): file read failed: time = Mon Jul 17 14:30:02 2023
, filename = '/', file descriptor = 5, errno = 21, error message = 'Is a directory', buf = 0x7ffc65bfa728, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/cluster/home/sejinkim/miniconda3/envs/nnunet/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/cluster/home/sejinkim/miniconda3/envs/nnunet/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/inference/data_iterators.py", line 57, in preprocess_fromfiles_save_to_queue
    raise e
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properites = preprocessor.run_case(list_of_lists[idx],
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 128, in run_case
    data, data_properites = rw.read_images(image_files)
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/imageio/simpleitk_reader_writer.py", line 37, in read_images
    itk_image = sitk.ReadImage(f)
  File "/cluster/home/sejinkim/miniconda3/envs/nnunet/lib/python3.10/site-packages/SimpleITK/extra.py", line 355, in ReadImage
    return reader.Execute()
  File "/cluster/home/sejinkim/miniconda3/envs/nnunet/lib/python3.10/site-packages/SimpleITK/SimpleITK.py", line 8438, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/"
Traceback (most recent call last):
  File "/cluster/home/sejinkim/pkgs/rENE_inference/code/larynx.py", line 54, in <module>
    main()
  File "/cluster/home/sejinkim/pkgs/rENE_inference/code/larynx.py", line 31, in main
    y_hat = larynx_model.predict_from_files(files,#p.input_directory,
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/inference/predict_from_raw_data.py", line 242, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/inference/predict_from_raw_data.py", line 335, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/cluster/home/sejinkim/pkgs/nnUNetv2/nnunetv2/inference/data_iterators.py", line 109, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!
```

**Comment by skim2257** [comment]
Not sure if this is the only cause for the error, but it seems to be attempting to use the HDF5 reader although the files are NIfTI. 

I don't think there are any other error outputs.

**Comment by ancestor-mithril** [comment]
Try reading each of your files using SimpleITK and see for which file does it fail. 
This could also be helpful: https://github.com/SimpleITK/SimpleITK/issues/434

**Comment by smriti-joshi** [comment]
Something you could check: maybe the predictions are already made once in the output folder and the 'overwriting' is set to false in 'predict_from_files'

**Comment by constantinulrich** [comment]
Hi, is the issue still unsolved? I would need more information to work on it.  

> sitk::ERROR: Unable to determine ImageIO reader for "/"

Looks like there are not only images in your file list.

**Comment by xioaxin** [comment]
I use model.predict_from_files function  after if __name__=="__main__": , and it works

**Comment by sofisappia** [comment]
I am getting the same error on mha files, even for a list with a single file entry. Using predict_single_npy_array and SimpleITKIO reader works, so I do not believe it is a memory issue:

The following code works:
```
        image_np, properties = SimpleITKIO().read_images([input_img_path])
        _, probabilities = self.predictor.predict_single_npy_array(
            image_np, properties, None, None, save_probabilities)
```
            
 The following snippet fails:
```
         self.predictor = nnUNetPredictor(
            tile_step_size=0.5,
            use_gaussian=True,
            use_mirroring=True,
            device=torch.device('cuda', 0),
            verbose=False,
            verbose_preprocessing=False,
            allow_tqdm=True
        )
         self.predictor.predict_from_files(
            list_of_lists_or_source_folder, output_folder, save_probabilities, overwrite,
            num_processes_preprocessing=1, num_processes_segmentation_export=1,
        )
    
```
    
    
   ```
 HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fdeprec.c line 156 in itk_H5Fis_hdf5(): unable to determine if file is accessible as HDF5
    major: File accessibility
    minor: Not an HDF5 file
  #001: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3769 in itk_H5VL_file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #002: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLcallback.c line 3699 in H5VL__file_specific(): file specific failed
    major: Virtual Object Layer
    minor: Can't operate on object
  #003: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5VLnative_file.c line 384 in itk_H5VL__native_file_specific(): error in HDF5 file check
    major: File accessibility
    minor: Unable to initialize object
  #004: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Fint.c line 1086 in itk_H5F__is_hdf5(): error while trying to locate file signature
    major: File accessibility
    minor: Not an HDF5 file
  #005: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 113 in itk_H5FD_locate_signature(): unable to read file signature
    major: Low-level I/O
    minor: Unable to initialize object
  #006: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDint.c line 189 in itk_H5FD_read(): driver read request failed
    major: Virtual File Layer
    minor: Read failed
  #007: /tmp/SimpleITK-build/ITK/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5FDsec2.c line 755 in H5FD__sec2_read(): file read failed: time = Mon Sep 30 16:32:10 2024
, filename = '/', file descriptor = 5, errno = 21, error message = 'Is a directory', buf = 0x7ffc8dbe2df8, total read size = 8, bytes this sub-read = 8, bytes actually read = 18446744073709551615, offset = 0
    major: Low-level I/O
    minor: Read failed
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/nnunet/nnunetv2/inference/data_iterators.py", line 57, in preprocess_fromfiles_save_to_queue
    raise e
  File "/root/nnunet/nnunetv2/inference/data_iterators.py", line 31, in preprocess_fromfiles_save_to_queue
    data, seg, data_properties = preprocessor.run_case(list_of_lists[idx],
  File "/root/nnunet/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 132, in run_case
    data, data_properties = rw.read_images(image_files)
  File "/root/nnunet/nnunetv2/imageio/simpleitk_reader_writer.py", line 37, in read_images
    itk_image = sitk.ReadImage(f)
  File "/usr/local/lib/python3.9/site-packages/SimpleITK/extra.py", line 355, in ReadImage
    return reader.Execute()
  File "/usr/local/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 8438, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:105:
sitk::ERROR: Unable to determine ImageIO reader for "/"
Traceback (most recent call last):
  File "/workdir/code/twmp_baseline/inference_batch.py", line 199, in <module>
    raise SystemExit(run())
  File "/workdir/code/twmp_baseline/inference_batch.py", line 44, in run
    algorithm.predict_from_files(
  File "/workdir/code/twmp_baseline/segmentation_model.py", line 66, in predict_from_files
    self.predictor.predict_from_files(
  File "/root/nnunet/nnunetv2/inference/predict_from_raw_data.py", line 249, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/root/nnunet/nnunetv2/inference/predict_from_raw_data.py", line 342, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/root/nnunet/nnunetv2/inference/data_iterators.py", line 109, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!
```
