### ISSUE TITLE
What is the reason for the following error in preprocessing

### ISSUE THREAD

**Issue by zlf123-marker** [MIC-DKFZ/nnUNet#157]
normalization...
normalization done
saving:  /home/zlf/liuyuan/nnUNet/nnUNet_preprocessed/Task02_yao/nnUNet_stage1/la_008.npz
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 245, in <module>
    plan_and_preprocess(task, processes_lowres, processes_fullres, no_preprocessing)
  File "experiment_planning/plan_and_preprocess_task.py", line 136, in plan_and_preprocess
    exp_planner.run_preprocessing((processes_lowres, processes_fullres))
  File "/home/zlf/nnUNet/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 409, in run_preprocessing
    self.plans['data_identifier'], num_threads)
  File "/home/zlf/nnUNet/nnunet/preprocessing/preprocessing.py", line 348, in run
    p.map(self._run_star, all_args)
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/zlf/anaconda3/envs/nn_unet/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '<multiprocessing.pool.ExceptionWithTraceback object at 0x7f17d58353c8>'. Reason: 'PicklingError("Can't pickle <class 'MemoryError'>: it's not the same object as builtins.MemoryError",)'

**Comment by FabianIsensee** [comment]
This looks like you are running out of RAM. Have you checked that?
