### ISSUE TITLE
Background worker not alive in docker

### ISSUE THREAD

**Issue by rajanish4** [MIC-DKFZ/nnUNet#1578]
Hi,
I am currently running nnUNev2_predict command from a python script, it runs well from pycharm, but when i create docker image with same virtual environment and run it in a docker container with my current GPU, i get following error:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app/venv2/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/opt/app/venv2/bin/nnUNetv2_predict", line 33, in <module>
using pin_memory on device 0
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_predict')())
  File "/opt/app/algorithm/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 525, in predict_entry_point
    predict_from_raw_data(args.i,
  File "/opt/app/algorithm/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 236, in predict_from_raw_data
    for preprocessed in mta:
  File "/opt/app/venv2/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/opt/app/venv2/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Can you tell me what can be the solution to this? I am not sure why it doesn't run in docker. Thanks in advance.

**Comment by ancestor-mithril** [comment]
If no other errors are present in the error message => OOM (see https://github.com/MIC-DKFZ/nnUNet/issues/1572), your docker does not have enough RAM memory available. Check https://github.com/pytorch/pytorch#using-pre-built-images (the `--shm-size`option).

**Comment by rajanish4** [comment]
Hi, 
Thanks for information. After i set --ipc=host, i get following error: 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/app/venv2/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 107, in results_loop
    item[k] = item[k].pin_memory()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Though i use same gpu in pycharm, and that works, do you know the reason for this?

**Comment by ancestor-mithril** [comment]
Ensure that you have the same environment in both places and check if other applications use the GPU.
