### ISSUE TITLE
Error with predict 3d_cascade_fullres

### ISSUE THREAD

**Issue by taborjia** [MIC-DKFZ/nnUNet#1582]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnunet/bin/nnUNetv2_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_predict')())
  File "/home/ubuntu/project/nnUNet_code/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 838, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/home/ubuntu/project/nnUNet_code/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 249, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/home/ubuntu/project/nnUNet_code/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 342, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/home/ubuntu/project/nnUNet_code/nnUNet/nnunetv2/inference/data_iterators.py", line 115, in preprocessing_iterator_fromfiles
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
  File "/home/ubuntu/project/nnUNet_code/nnUNet/nnunetv2/inference/data_iterators.py", line 115, in <listcomp>
    [i.pin_memory() for i in item.values() if isinstance(i, torch.Tensor)]
RuntimeError: CUDA error: OS call failed or operation not supported on this OS
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Can you tell me what can be the solution to this? Thank you!

**Comment by taborjia** [comment]
Maybe update pytorch version can solve this issue, but it's not stable. In some test dataset, this issue occurs again.

**Comment by Lars-Kraemer** [comment]
Hi @taborjia ,

could you post the error message when running nnUNetv2_predict with CUDA_LAUNCH_BLOCKING=1?

Best,
Lars
