### ISSUE TITLE
Error in experiment planner  network topology

### ISSUE THREAD

**Issue by itaijj** [MIC-DKFZ/nnUNet#1583]
it seems that in case not all axis are valid for pool then you get this error
`Traceback (most recent call last):
  File "/dccstor/mm_hcls/guez/anaconda3/envs/fuse3.9/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 186, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 83, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 62, in plan_experiment_dataset
    return experiment_planner_class(dataset_id,
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 400, in plan_experiment
    plan_3d_fullres = self.get_plans_for_configuration(fullres_spacing_transposed,
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 260, in get_plans_for_configuration
    shape_must_be_divisible_by = get_pool_and_conv_props(spacing, initial_patch_size,
  File "/dccstor/mm_hcls/guez/nnUNet/nnunetv2/experiment_planning/experiment_planners/network_topology.py", line 85, in get_pool_and_conv_props
    if spacings_of_axes[d] / min(current_spacing) < 2:
IndexError: list index out of range`
this small fix solved it:
`

        spacings_of_axes = {i : current_spacing[i] for i in range(dim) if i in valid_axes_for_pool}
        # find axis that are within factor of 2 within smallest spacing
        min_spacing_of_valid = min(spacings_of_axes.values())
        valid_axes_for_pool = [i for i in valid_axes_for_pool if current_spacing[i] / min_spacing_of_valid < 2]

        # max_numpool constraint
        valid_axes_for_pool = [i for i in valid_axes_for_pool if num_pool_per_axis[i] < max_numpool]

        if len(valid_axes_for_pool) == 1:
            if current_size[valid_axes_for_pool[0]] >= 3 * min_feature_map_size:
                pass
            else:
                break
        if len(valid_axes_for_pool) < 1:
            break

        # now we need to find kernel sizes
        # kernel sizes are initialized to 1. They are successively set to 3 when their associated axis becomes within
        # factor 2 of min_spacing. Once they are 3 they remain 3
        for d in range(dim):
            if kernel_size[d] == 3 or d not in spacings_of_axes:
                continue
            else:
                if spacings_of_axes[d] / min(current_spacing) < 2:
                    kernel_size[d] = 3
`

**Comment by FabianIsensee** [comment]
Hey, please install the most recent master. This issue is fixed in commit 33b27b1
`pip install --upgrade git+https://github.com/MIC-DKFZ/nnUNet.git`
Best,
Fabian
