### ISSUE TITLE
2D nnUNET: preprocessing crashes at the experiment planning phase (network topology.py)

### ISSUE THREAD

**Issue by MachtaYassine** [MIC-DKFZ/nnUNet#1587]
Hello Fabian and DKFZ team, 

I am having an issue when launching 2D UNet with PNG pictures (or nii.gz) converted manually i noticed that the preprocess step crashes at the experiment planning phase after the fingerprint extraction phase.

Fingerprint extraction...
Dataset010_Test
Experiment planning...
current_size [256.0, 256.0, 1.0]  #These are prints of relevant variables in the get_pool_and_conv_props function that crashes
min_feature_map_size 4
dim 3
spacings_of_axes [1.0, 1.0]
`
Traceback (most recent call last):
  File "ymachta/miniconda3/envs/nnunet/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 186, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 83, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 69, in plan_experiment_dataset
    ).plan_experiment()
  File "nnUNet/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 400, in plan_experiment
    plan_3d_fullres = self.get_plans_for_configuration(fullres_spacing_transposed,
  File "nnUNet/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 260, in get_plans_for_configuration
    shape_must_be_divisible_by = get_pool_and_conv_props(spacing, initial_patch_size,
  File "nnUNet/nnunetv2/experiment_planning/experiment_planners/network_topology.py", line 86, in get_pool_and_conv_props
    if spacings_of_axes[d] / min(current_spacing) < 2:
IndexError: list index out of range`

I'd love to get pointers or hints on how to solve this problem. My input is a 2d dataset (unrelated to medical image like your road segmentation example) the dimensions of the nii.gz when i created them were (1 512 512) and the when i tried with the original png images (1024*1024) it's the same error. It seems Spacings_of_axes is only of length 2 while dim =3
Spacings_of_axes is created after this line

`valid_axes_for_pool = [i for i in range(dim) if current_size[i] >= 2*min_feature_map_size]`

So i'd love a lead on how to start to solve this since i don't understand quite yet the whole preprocessing pipeline.

Thank you !

**Comment by FabianIsensee** [comment]
Hey, please install the most recent master. This issue should have been fixed in commit https://github.com/MIC-DKFZ/nnUNet/commit/33b27b106985d9514854b8053997f800ee8aebed
pip install --upgrade git+https://github.com/MIC-DKFZ/nnUNet.git
Best,
Fabian

**Comment by MachtaYassine** [comment]
Thanks a lot ! my bad i didn't update it.

**Comment by kabbas570** [comment]
@FabianIsensee  thanks, the error is solved but now the nnUNetPlans_2d, and nnUNetPlans_3d_fullres folders are empty.

Cheers
Abbas
