### ISSUE TITLE
IndexError: list index out of range when inference

### ISSUE THREAD

**Issue by zx0412** [MIC-DKFZ/nnUNet#1607]
I run this：“nnUNetv2_predict -d Dataset102_Lung -i F:\nnUNet-master\nnUNet_raw\Dataset102_Lung\imagesTs -o F:\tmp\three\raw_pngPre -f  0 1 2 3 4 -tr nnUNetTrainer -c 2d -p nnUNetPlans”

the err：

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 6 cases in the source folder
Traceback (most recent call last):
  File "D:\soft\Anaconda\envs\nnUnet\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\soft\Anaconda\envs\nnUnet\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\soft\Anaconda\envs\nnUnet\Scripts\nnUNetv2_predict.exe\__main__.py", line 7, in <module>
  File "D:\soft\Anaconda\envs\nnUnet\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 838, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "D:\soft\Anaconda\envs\nnUnet\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 237, in predict_from_files
    self._manage_input_and_output_lists(list_of_lists_or_source_folder,
  File "D:\soft\Anaconda\envs\nnUnet\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 162, in _manage_input_and_output_lists
    caseids = [os.path.basename(i[0])[:-(len(self.dataset_json['file_ending']) + 5)] for i in
  File "D:\soft\Anaconda\envs\nnUnet\lib\site-packages\nnunetv2\inference\predict_from_raw_data.py", line 162, in <listcomp>
    caseids = [os.path.basename(i[0])[:-(len(self.dataset_json['file_ending']) + 5)] for i in
IndexError: list index out of range

**Comment by ancestor-mithril** [comment]
Do your images in the `imagesTs` folder have "_00XX" in their name? nnUNet images must have the modality in their name according to the documentation.

**Comment by zx0412** [comment]
> 文件夹中的图像名称中是否包含“_00XX”？nnUNet 图像的名称中必须包含文档的模态。`imagesTs`

I have，My images have names like "-0004-0072-0212-W1500L-600.png"

**Comment by ancestor-mithril** [comment]
> > Do your images in the imagesTs folder have "_00XX" in their name? nnUNet images must have the modality in their name according to the documentation.
> 
> I have，My images have names like "-0004-0072-0212-W1500L-600.png"

Check https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format_inference.md#data-format-for-inference

**Comment by zx0412** [comment]
> > > Do your images in the imagesTs folder have "_00XX" in their name? nnUNet images must have the modality in their name according to the documentation.
> > 
> > 
> > I have，My images have names like "-0004-0072-0212-W1500L-600.png"
> 
> Check https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format_inference.md#data-format-for-inference

thanks! is useful!

**Comment by hermancollin** [comment]
@zx0412 did you solve your issue? I have the exact same problem.

**Comment by hermancollin** [comment]
To be more precise, I will add that the test image filenames are valid according to the documentation. I only have 1 image. This is the exact command I am using:

```
CUDA_VISIBLE_DEVICES=3 nnUNetv2_predict -d Dataset001_Unmyelinated -i nnUNet_raw/Dataset001_Unmyelinated/imagesTs/ -o testing -f  5 -tr nnUNetTrainer -c 2d -p nnUNetPlans
```

My error is slightly different:
```
#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 1 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1 cases that I would like to predict
Exception in background worker 0:
 list index out of range
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 46, in producer
    item = next(data_loader)
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 55, in generate_train_batch
    data, seg, data_properites = self.preprocessor.run_case(files, seg_prev_stage, self.plans_manager,
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 89, in run_case
    data = self._normalize(data, seg, configuration_manager,
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 166, in _normalize
    scheme = configuration_manager.normalization_schemes[c]
IndexError: list index out of range
Traceback (most recent call last):
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 525, in predict_entry_point
    predict_from_raw_data(args.i,
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 236, in predict_from_raw_data
    for preprocessed in mta:
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/home/GRAMES.POLYMTL.CA/arcol/.local/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
```

**Comment by hermancollin** [comment]
For future reference I solved this. The test image was incorrectly saved in RGB format and converting it to grayscale fixed this.
