### ISSUE TITLE
Error when running plan_and_preprocess_task

### ISSUE THREAD

**Issue by faisal-zaman** [MIC-DKFZ/nnUNet#161]
Hi. I encounter the following error when I run the plan_and_preprocess_task.py file. I have made sure I have changed the path.py variables to adapt to my system. This problem occurs with the Heart dataset as well. I do not get the 3D datasets from the 4D Nifti data.

"""
Traceback (most recent call last):
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\multiprocessing\pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "c:\users\faiza\nnunet\nnunet\experiment_planning\common_utils.py", line 29, in split_4d_nifti
    shutil.copy(filename, join(output_folder, file_base[:-7] + "_0000.nii.gz"))
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/faiza/nnUNet/nnunet\\nnUNet_raw_splitted\\Task04_Hippocampus\\imagesTr\\nnunet\\nnUNet_raw\\Task04_Hippocampus\\imagesTr\\hippocampus_001_0000.nii.gz'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 241, in <module>
    split_4d(task)
  File "experiment_planning/plan_and_preprocess_task.py", line 54, in split_4d
    p.starmap(split_4d_nifti, zip(files, output_dirs))
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\multiprocessing\pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\faiza\AppData\Local\Continuum\anaconda3\envs\nnUNet\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/faiza/nnUNet/nnunet\\nnUNet_raw_splitted\\Task04_Hippocampus\\imagesTr\\nnunet\\nnUNet_raw\\Task04_Hippocampus\\imagesTr\\hippocampus_001_0000.nii.gz'

**Comment by FabianIsensee** [comment]
Your file paths seem to be messed up and my intuition is that this is a windows related thing. nnU-Net only officially supports Linux and I do not have a Windows computer that I could use to find what causes this problem. I recommend you use Linux (Ubuntu) :-)
