### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by Kedaya66** [MIC-DKFZ/nnUNet#1614]
hello ，input nnUNetv2_plan_and_preprocess -d 101，the below problems happened。 
How to fix this problem？

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "E:\Anaconda\envs\dl\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\Anaconda\envs\dl\lib\site-packages\acvl_utils\miscellaneous\ptqdm.py", line 43, in wrapper
    result = function(*enum_iterable[1], **kwargs)
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\experiment_planning\dataset_fingerprint\fingerprint_extractor.py", line 84, in analyze_case
    images, properties_images = rw.read_images(image_files)
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\imageio\simpleitk_reader_writer.py", line 100, in read_images
    stacked_images = np.vstack(images)
  File "<__array_function__ internals>", line 5, in vstack
  File "E:\Anaconda\envs\dl\lib\site-packages\numpy\core\shape_base.py", line 282, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Anaconda\envs\dl\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda\envs\dl\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\dl\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 173, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 32, in extract_fingerprint_dataset
    return fpe.run(overwrite_existing=clean)
  File "E:\Anaconda\envs\dl\lib\site-packages\nnunetv2\experiment_planning\dataset_fingerprint\fingerprint_extractor.py", line 130, in run
    results = ptqdm(DatasetFingerprintExtractor.analyze_case,
  File "E:\Anaconda\envs\dl\lib\site-packages\acvl_utils\miscellaneous\ptqdm.py", line 34, in ptqdm
    for i, result in p.imap_unordered(function_wrapper, enumerate(iterable), chunksize=chunksize):
  File "E:\Anaconda\envs\dl\lib\multiprocessing\pool.py", line 870, in next
    raise value
ValueError: need at least one array to concatenate

**Comment by seziegler** [comment]
Hi @Kedaya66 , it seems like the list of image files that are being read is empty. Can you rerun the command with the `--verify_dataset_integrity` flag? 
Best,
Sebastian

**Comment by Kedaya66** [comment]
for each of my data，some slices does’nt have annotations due to the imbalance distribution of lesions

**Comment by Kedaya66** [comment]
Sincerely thanks for your replies. I have fixed this problem.

**Comment by seziegler** [comment]
You're welcome! I'll close this issue then. Feel free to open a new one if something else comes up.
Best,
Sebastian

**Comment by SakinaMohammed21** [comment]
Hi, 

I am facing the same issue and have verified that all my cases have label files. I have tried several things and can't figure out how to solve this problem. The screenshots of the error were captured after using --verify_dataset_integrity along with the fingerprint extractor. 

<img width="1147" alt="1" src="https://github.com/MIC-DKFZ/nnUNet/assets/53149319/24d79d29-75f2-4552-84cc-f0b2c4609f84">

<img width="1147" alt="2" src="https://github.com/MIC-DKFZ/nnUNet/assets/53149319/19143a22-adcd-441d-847f-4bb57a68f547">

<img width="1147" alt="3" src="https://github.com/MIC-DKFZ/nnUNet/assets/53149319/6d9e9720-0b92-4b5b-896c-2c6150e2ef43">

**Comment by seziegler** [comment]
Hi @SakinaMohammed21 ,
There seems to be a problem with your case `aab020`. Image and labels have different directions meaning that they are not completely aligned. I'm not sure if this also causes the error you see but can you try either fixing `aab020` (so that you won't get the warning anymore) or excluding it from your data and see if the error persists?
Also, can you share your dataset.json so that I can see if there are any errors there?
Best,
Sebastian

**Comment by SakinaMohammed21** [comment]
Thank you for your reply, Sebastian! I checked aab020, the direction was
just a warning. Many cases previously also got it but they still ran
normally. Here is the dataset.json

Best regards

*Sakina Mohammed Mota*
***@***.***
+1 (832) 732-3052

**Comment by seziegler** [comment]
Hey @SakinaMohammed21 ,
There is no dataset.json, I think you need to attach it in github directly and not via email.
Best,
Sebastian

**Comment by SakinaMohammed21** [comment]
Sorry, my bad. Here it is. 

```
{
    "description": "",
    "labels": {
        "background": 0,
        "Prostate": 1
    },
    "licence": "hands off!",
    "name": "Task0001_PROSTATE",
    "numTraining": 6247,
    "reference": "",
    "release": "0.0",
    "channel_names": {
        "0": "T2"
    },
    "file_ending": ".nii.gz"
}
```

**Comment by seziegler** [comment]
Thanks, the json seems fine. The error you've shown comes from code that is only run when using `verify_dataset_integrity`. Do you get a different error when running the preprocessing without this flag?

**Comment by SakinaMohammed21** [comment]
No, same error when I run preprocessing or extract the fingerprint

**Comment by seziegler** [comment]
Where exactly? Can you post the traceback please?

**Comment by SakinaMohammed21** [comment]
Here is the traceback:

[Traceback.txt](https://github.com/MIC-DKFZ/nnUNet/files/12483709/Traceback.txt)

Plan_and_preprocessing had run successfully for this exact dataset using nnUNet v1.

**Comment by seziegler** [comment]
Hey @SakinaMohammed21 ,
I don't know what might cause this problem. If you want you can send me a very minimal sample of the data with which you still get this error and I can try to debug it.
Best,
Sebastian
