### ISSUE TITLE
Value error when running plan_and_preprocess_task.py

### ISSUE THREAD

**Issue by onlie202** [MIC-DKFZ/nnUNet#162]
##########################################################################
Traceback (most recent call last):
  File "plan_and_preprocess_task.py", line 245, in <module>
    plan_and_preprocess(task, processes_lowres, processes_fullres, no_preprocessing)
  File "plan_and_preprocess_task.py", line 134, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "E:\MRI_Automatic_Sketch\nnUnet\nnUNet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 237, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "E:\MRI_Automatic_Sketch\nnUnet\nnUNet\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 56, in get_target_spacing
    target = np.median(np.vstack(spacings), 0)
  File "<__array_function__ internals>", line 6, in vstack
  File "E:\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
##########################################################################
I found that variable "spacings" always to be "[ ]",where's the problem ?

**Comment by FabianIsensee** [comment]
This is probably empty because nnU-Net does not find any image data. Please make sure all the paths are set correctly and that nnU-Net is looking in the correct folder. Please also keep in mind that we don't support Windows and cannot help out with any issues arising from that :-)

**Comment by onlie202** [comment]
Thank you! : )

**Comment by FabianIsensee** [comment]
Could you resolve your issues? If so please let me know so that I can close this :-)

**Comment by onlie202** [comment]
Yes I've resloved.You can close this.
