### ISSUE TITLE
KeyError: 'trainer_name'

### ISSUE THREAD

**Issue by LightNing233** [MIC-DKFZ/nnUNet#1653]
`!nnUNetv2_predict -d Dataset502_spine -i /content/drive/MyDrive/nnUNetdemo1/nnUNet_raw/Dataset502_spine/imagesTs -o /content/drive/MyDrive/nnUNetdemo1/nnUNet_raw/Dataset502_spine/imagesTs  -f 0 -c 3d_fullres -tr nnUNetTrainer`
when i run this ,an error occured like this 
`Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/inference/predict_from_raw_data.py", line 525, in predict_entry_point
    predict_from_raw_data(args.i,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/inference/predict_from_raw_data.py", line 159, in predict_from_raw_data
    load_what_we_need(model_training_output_dir, use_folds, checkpoint_name)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/inference/predict_from_raw_data.py", line 86, in load_what_we_need
    trainer_name = checkpoint['trainer_name']
KeyError: 'trainer_name'`
thanks for telling me what i can do to solve this problem
best wishes for you

**Comment by lisakausch** [comment]
Hi @LightNing233 ,

did you already try loading the checkpoint separately? Maybe the checkpoint file is corrupted?

Best wishes,
Lisa

**Comment by Sere1nz** [comment]
Did you solve it? I got same problem here.
Im using checkpoint that trained by others using nnunet. I loaded it seperately and it only shown the following keys:
`dict_keys(['epoch', 'state_dict', 'optimizer_state_dict', 'lr_scheduler_state_dict', 'plot_stuff', 'best_stuff', 'amp_grad_scaler'])`
It doesn't have keys like `trainer_name,`
How can I inference with this checkpoint?
