### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Num13er-XIII** [MIC-DKFZ/nnUNet#1658]
Hello Fabian, I keep getting the following runtime error, I guess my paths are correct, and I can't find a solution to this problem, Do you have any suggestions?

 My paths are as follows:

nnUNet_raw_data_base = '.../nnUNet_raw_data_base'
nnUNet_raw = '.../nnUNet_raw_data_base/nnUNet_raw_data'
nnUNet_preprocessed = '.../nnUNet/nnUNet_preprocessed'
nnUNet_results = '.../nnUNet/nnUNet_trained_models'

my custom dataset is located under: .../nnUNet_raw_data_base/nnUNet_raw_data/Dataset013

the nnUNetv2_plan_and_preprocess -d 13 --verify_dataset_integrity runs without any errors and creat .../nnUNet/nnUNet_preprocessed/Dataset013

after running nnUNet_train 2d nnUNetTrainerV2 13 4 --npz I receive the following error

Traceback (most recent call last):
  File ".../miniconda3/envs/tf/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File ".../miniconda3/envs/tf/lib/python3.9/site-packages/nnunet/run/run_training.py", line 123, in main
    task = convert_id_to_task_name(task_id)
  File ".../miniconda3/envs/tf/lib/python3.9/site-packages/nnunet/utilities/task_name_id_conversion.py", line 51, in convert_id_to_task_name
    raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: I could not find a task with the ID 13. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=.../nnUNet/nnUNet_preprocessed
RESULTS_FOLDER=.../nnUNet/nnUNet_trained_models
nnUNet_raw_data_base=.../nnUNet_raw_data_base
If something is not right, adapt your environemnt variables.

**Comment by Num13er-XIII** [comment]
I solve it by using nnUNetv2_train directly
