### ISSUE TITLE
Missing case file despite existing

### ISSUE THREAD

**Issue by jonathanquantumalpha** [MIC-DKFZ/nnUNet#1690]
Hi,
I've been running the following code,

!nnUNet_plan_and_preprocess -t 1 --verify_dataset_integrity

But it came with the following error, despite the file existing in the right folder, why is that the case?

```Verifying training set
checking case NKI-TRT-20-12
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/usr/local/lib/python3.10/dist-packages/nnunet/preprocessing/sanity_checks.py", line 129, in verify_dataset_integrity
    assert isfile(expected_label_file), "could not find label file for case %s. Expected file: \n%s" % (
AssertionError: could not find label file for case NKI-TRT-20-12. Expected file: 
/content/drive/MyDrive/EdenSehat/nnUnet/my_nnunet/nnUNet/nnunet/nnUNet_raw_data_base/nnUNet_raw_data/Task001/labelsTr/NKI-TRT-20-12.nii.gz```

![nkitrt](https://github.com/MIC-DKFZ/nnUNet/assets/135941084/5b00fb8a-b61c-486c-83b0-19f5ccd834a8)

**Comment by Lars-Kraemer** [comment]
Hey @jonathanquantumalpha,

could you solve the problem or does this still occur? Regardless of this, I would recommend using nnUNetv2 if possible.

Best,
Lars
