### ISSUE TITLE
zipfile.BadZipFile when running plan_and_preprocess_task.

### ISSUE THREAD

**Issue by FoilHao** [MIC-DKFZ/nnUNet#174]
Hello! Sorry for asking another question.
At the end of running plan_and_preprocess_task, I meet zipfile.BadZipFile error.
But after I deleted all generated files and rerun plan_and_preprocess_task, it doesn't give this error.
The weirdest thing is that it happens periodically. Everytime I have to run prepross twice, meeting error the first time and seemingly fine the second time.
The detailed error report is below.

/home/szh/dataset/verse19/base/nnUNet_preprocessed/Task19_DeepSpine/nnUNet_2D_stage0/verse255.pkl
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/szh/Documents/nnUNet/nnunet/experiment_planning/find_classes_in_slice.py", line 28, in add_classes_in_slice_info
    seg_map = np.load(npz_file)['data'][-1]
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 777, in read_array
    data = _read_bytes(fp, read_size, "array data")
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/format.py", line 906, in _read_bytes
    r = fp.read(size - len(data))
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/zipfile.py", line 872, in read
    data = self._read1(n)
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/zipfile.py", line 962, in _read1
    self._update_crc(data)
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/zipfile.py", line 890, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'data.npy'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 245, in <module>
    plan_and_preprocess(task, processes_lowres, processes_fullres, no_preprocessing)
  File "experiment_planning/plan_and_preprocess_task.py", line 163, in plan_and_preprocess
    p.map(add_classes_in_slice_info, zip(list_of_npz_files, list_of_pkl_files, all_classes))
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/szh/anaconda3/envs/py36/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
zipfile.BadZipFile: Bad CRC-32 for file 'data.npy'

**Comment by FabianIsensee** [comment]
I have never seen this error before. Something seems to be up with your system?
Did you run two preprocessings at the same time? That would explain it.
Have you tried googling the error?
Best,
Fabian

**Comment by FoilHao** [comment]
Thanks for your quick answer.
I googled it but haven't figure it out. But it still works when not meeting this error, so it's not a fatal problem.
