### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by tensorctn** [MIC-DKFZ/nnUNet#1761]
Hi, thank you for the great work! I am trying to train the nnunet with Dataset002_Heart,however, when I executed python run_training.py Dataset002_Heart 3d_fullres 0.
I  get the following error:

2023-10-21 14:13:49.498454: unpacking dataset...
2023-10-21 14:13:54.944668: unpacking done...
2023-10-21 14:13:54.954137: do_dummy_2d_data_aug: False
2023-10-21 14:13:54.960239: Using splits from existing split file: C:\Users\TNC\Coderlife\nnUNet-master\DATASET\nnUNet_preprocessed\Dataset002_Heart\splits_final.json
2023-10-21 14:13:54.967239: The split file contains 5 splits.
2023-10-21 14:13:54.972240: Desired fold for training: 0
2023-10-21 14:13:54.978782: This split has 16 training and 4 validation cases.
2023-10-21 14:13:55.004782: Unable to plot network architecture:
2023-10-21 14:13:55.008782: No module named 'hiddenlayer'
2023-10-21 14:13:55.039386: 
2023-10-21 14:13:55.047668: Epoch 0
2023-10-21 14:13:55.054914: Current learning rate: 0.01
using pin_memory on device 0
using pin_memory on device 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 240, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\run\run_training.py", line 8, in <module>
    import torch.cuda
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\__init__.py", line 1382, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 120, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 129, in _main
    prepare(preparation_data)
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 240, in prepare
    from .functional import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\functional.py", line 7, in <module>
    import torch.nn.functional as F
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\nn\__init__.py", line 1, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\spawn.py", line 291, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\run\run_training.py", line 8, in <module>
    import torch.cuda
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\__init__.py", line 1504, in <module>
    from .modules import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\nn\modules\__init__.py", line 2, in <module>
    from . import masked
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\masked\__init__.py", line 3, in <module>
    from ._ops import (
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\masked\_ops.py", line 11, in <module>
    from .linear import Identity, Linear, Bilinear, LazyLinear
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\nn\modules\linear.py", line 7, in <module>
    from torch._prims_common import corresponding_real_dtype
    from .. import functional as F
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\torch\_prims_common\__init__.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode
MemoryError
    import sympy
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\__init__.py", line 74, in <module>
    from .polys import (Poly, PurePoly, poly_from_expr, parallel_poly_from_expr,
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\polys\__init__.py", line 78, in <module>
    from .polyfuncs import (symmetrize, horner, interpolate,
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\polys\polyfuncs.py", line 10, in <module>
    from sympy.polys.specialpolys import (
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\polys\specialpolys.py", line 298, in <module>
    from sympy.polys.rings import ring
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\polys\rings.py", line 30, in <module>
    from sympy.printing.defaults import DefaultPrinting
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\printing\__init__.py", line 3, in <module>
    from .pretty import pager_print, pretty, pretty_print, pprint, pprint_use_unicode, pprint_try_use_unicode
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\sympy\printing\pretty\__init__.py", line 3, in <module>
    from .pretty import (pretty, pretty_print, pprint, pprint_use_unicode,
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1032, in get_code
  File "<frozen importlib._bootstrap_external>", line 1131, in get_data
MemoryError
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "C:\Users\TNC\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\TNC\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\run\run_training.py", line 276, in <module>
    run_training_entry()
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\run\run_training.py", line 270, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\run\run_training.py", line 206, in run_training
    nnunet_trainer.run_training()
  File "C:\Users\TNC\Coderlife\nnUNet-master\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1249, in run_training
    val_outputs.append(self.validation_step(next(self.dataloader_val)))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-4 (results_loop):
Traceback (most recent call last):
  File "C:\Users\TNC\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\TNC\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception ignored in: <function NonDetMultiThreadedAugmenter.__del__ at 0x00000205A77DB380>
Traceback (most recent call last):
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 253, in __del__
    self._finish()
  File "C:\Users\TNC\Coderlife\nnUNet-master\venv\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 238, in _finish
    self.abort_event.set()
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\synchronize.py", line 338, in set
    self._cond.notify_all()
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\synchronize.py", line 297, in notify_all
    self.notify(n=sys.maxsize)
  File "C:\Users\TNC\anaconda3\Lib\multiprocessing\synchronize.py", line 272, in notify
    assert not self._wait_semaphore.acquire(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] 句柄无效。

**Comment by Kobalt93** [comment]
Hi tensorctn,
I think on 2 possible sources of errors:
- Please check whether your RAM was full during training
- nnU-Net multi-processing data loader is relying on batchgenerators where "windows support is very experimental": https://github.com/MIC-DKFZ/batchgenerators#windows-support-is-very-experimental
