### ISSUE TITLE
Question: Runtime Error

### ISSUE THREAD

**Issue by iffthomas** [MIC-DKFZ/nnUNet#1762]
Hi everyone,
Currently I'm trying to get the nn-Unet running sorry to bother as I'm rather new to the field. However I face a problem with runtime
in the plan_preprocess stage....what could be the reason for it?

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 86, in analyze_case
    images, properties_images = rw.read_images(image_files)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/imageio/simpleitk_reader_writer.py", line 74, in read_images
    raise RuntimeError()
RuntimeError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/monai/apps/nnunet/__main__.py", line 20, in <module>
    fire.Fire({"nnUNetV2Runner": nnUNetV2Runner})
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/monai/apps/nnunet/nnunetv2_runner.py", line 954, in run
    self.plan_and_process()
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/monai/apps/nnunet/nnunetv2_runner.py", line 481, in plan_and_process
    self.extract_fingerprints(fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/monai/apps/nnunet/nnunetv2_runner.py", line 325, in extract_fingerprints
    extract_fingerprints([int(self.dataset_name_or_id)], fpe, npfp, verify_dataset_integrity, clean, verbose)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 33, in extract_fingerprint_dataset
    return fpe.run(overwrite_existing=clean)
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 154, in run
    results = [i.get()[0] for i in r]
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/site-packages/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 154, in <listcomp>
    results = [i.get()[0] for i in r]
  File "/cluster/home/ifft/miniconda3/envs/venv-spine/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
RuntimeError

**Comment by Bihuaa** [comment]
I have the same error, has it been solved yet?
