### ISSUE TITLE
MemoryError in Inference

### ISSUE THREAD

**Issue by Fair95** [MIC-DKFZ/nnUNet#178]
Hi Fabian,
Firstly, thank your for this great work! Your plain U-net + excellent preprocess pipeline certainly outperformed many state-of-the-art U-net variants!
I was trying to use nnUnet for my own project, but when I was running the prediction, I encountered the following error, do you have any idea why this is happening?
```
Traceback (most recent call last):
  File "inference/predict_simple.py", line 131, in <module>
    overwrite_existing=overwrite)
  File "/data/liqianyi/kidney_cancer_project/nnUNet-master/nnunet/inference/predict.py", line 251, in predict_from_folder
    tta, overwrite_existing=overwrite_existing)
  File "/data/kidney_cancer_project/nnUNet-master/nnunet/inference/predict.py", line 175, in predict_cases
    True, True, 2, trainer.patch_size, True)[None])
  File "/data/kidney_cancer_project/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 479, in predict_preprocessed_data_return_softmax
    pad_kwargs=self.inference_pad_kwargs)[2]
  File "/data/kidney_cancer_project/nnUNet-master/nnunet/network_architecture/neural_network.py", line 96, in predict_3D
    all_in_gpu=all_in_gpu)
  File "/data/kidney_cancer_project/nnUNet-master/nnunet/network_architecture/neural_network.py", line 270, in _internal_predict_3D_3Dconv_tiled
    predicted_segmentation = softmax_pred.argmax(0)
MemoryError
```

Best,
Fair

**Comment by FabianIsensee** [comment]
Hi,
is seems like you were running out of RAM on your computer. Please check the RAM usage while this is running and see whether the entire RAM fills up.
Best,
Fabian
