### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by MM-DHM** [MIC-DKFZ/nnUNet#1784]
Dear Fabian,

I am training nnUNetv2 on my custom dataset, training it localy on a partiall dataset was not a problem and the training went smoothly. However, since my main data set is stored in a remote folder, I face some challenges. , could you look at the output?

nnUNetv2_train 2 3d_fullres 0 --npz
Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 47, 'patch_size': [48, 48, 48], 'median_image_size_in_voxels': [44.0, 44.0, 44.0], 'spacing': [1.0, 1.0, 1.0], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'UNet_class_name': 'PlainConvUNet', 'UNet_base_num_features': 32, 'n_conv_per_stage_encoder': [2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2], 'num_pool_per_axis': [3, 3, 3], 'pool_op_kernel_sizes': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'unet_max_num_features': 320, 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'batch_dice': False}

These are the global plan.json settings:
 {'dataset_name': 'Dataset002', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [1.0, 1.0, 1.0], 'original_median_shape_after_transp': [44, 44, 44], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [0, 1, 2], 'transpose_backward': [0, 1, 2], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 4095.0, 'mean': 1204.14892578125, 'median': 1165.0, 'min': 0.0, 'percentile_00_5': 871.0, 'percentile_99_5': 1806.0, 'std': 203.32098388671875}}}

2023-11-06 10:56:54.689925: unpacking dataset...
2023-11-06 11:01:30.132051: unpacking done...             
2023-11-06 11:01:30.156736: do_dummy_2d_data_aug: False
2023-11-06 11:01:31.489979: Using splits from existing split file: /media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/splits_final.json
2023-11-06 11:01:31.566437: The split file contains 5 splits.
2023-11-06 11:01:31.578821: Desired fold for training: 0
2023-11-06 11:01:31.591016: This split has 24409 training and 6103 validation cases.
/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/torch/onnx/symbolic_helper.py:1513: UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True.
  warnings.warn(
2023-11-06 11:01:33.766785: Unable to plot network architecture:
2023-11-06 11:01:33.779853: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
2023-11-06 11:01:33.816667:
2023-11-06 11:01:33.829267: Epoch 0
2023-11-06 11:01:33.843523: Current learning rate: 0.01
using pin_memory on device 0
Exception in background worker 0:
 No data left in file
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 86, in load_case
    data = np.load(entry['data_file'][:-4] + ".npy", 'r')
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/npyio.py", line 436, in load
    raise EOFError("No data left in file")
EOFError: No data left in file
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/nicvi/nnUNet/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/nicvi/nnUNet/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/nicvi/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1242, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by MM-DHM** [comment]
Update on this issue:
I reran the preprocessing using nnUNetv2_plan_and_preprocess -d 2 -c 3d_fullres --verify_dataset_integrity, and the training process went through, but it stopped again with the same error after 29 epochs.

Currently, running the training again with the -c option seems promising. I will provide further updates if I observe any unusual behavior.


2023-11-06 20:02:10.332139: Epoch 29
2023-11-06 20:02:10.353243: Current learning rate: 0.00974
2023-11-06 20:08:18.229651: train_loss -0.4083
2023-11-06 20:08:18.313545: val_loss -0.4203
2023-11-06 20:08:18.330387: Pseudo dice [0.7853, 0.6851]
2023-11-06 20:08:18.349251: Epoch time: 367.94 s
2023-11-06 20:08:18.412777: Yayy! New best EMA pseudo Dice: 0.7015
2023-11-06 20:08:20.002308:
2023-11-06 20:08:20.077517: Epoch 30
2023-11-06 20:08:20.123707: Current learning rate: 0.00973
Exception in background worker 6:
Exception in background worker 4:
Exception in background worker 5:
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/L0550_RCA_sagital.pkl'
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/FA2766_RCA_2_axial.pkl'
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/D0195_RCA_axial.pkl'
Exception in background worker 3:
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/C1050_LAD_3_sagital.npy'
Exception in background worker 1:
Exception in background worker 0:
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/L1093_RCA_2_axial_seg.npy'
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/S0226_LAD_sagital_seg.npy'
Exception in background worker 2:
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/C0107_LAD_sagital.npy'
Exception in background worker 7:
 [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/FA1791_LAD_axial.pkl'
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 81, in load_case
    entry = self[key]
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 81, in load_case
    entry = self[key]
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 62, in __getitem__
    ret['properties'] = load_pickle(ret['properties_file'])
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 62, in __getitem__
    ret['properties'] = load_pickle(ret['properties_file'])
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 81, in load_case
    entry = self[key]
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 81, in load_case
    entry = self[key]
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 62, in __getitem__
    ret['properties'] = load_pickle(ret['properties_file'])
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 62, in __getitem__
    ret['properties'] = load_pickle(ret['properties_file'])
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 57, in load_pickle
    with open(file, mode) as f:
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/L0550_RCA_sagital.pkl'
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/FA1791_LAD_axial.pkl'
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/FA2766_RCA_2_axial.pkl'
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/D0195_RCA_axial.pkl'
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 86, in load_case
    data = np.load(entry['data_file'][:-4] + ".npy", 'r')
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/C1050_LAD_3_sagital.npy'
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/format.py", line 924, in open_memmap
    with open(os_fspath(filename), 'rb') as fp:
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/L1093_RCA_2_axial_seg.npy'
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/format.py", line 924, in open_memmap
    with open(os_fspath(filename), 'rb') as fp:
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002_CCTA_3D/nnUNetPlans_3d_fullres/S0226_LAD_sagital_seg.npy'
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
  File "/home/nicvi/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 86, in load_case
    data = np.load(entry['data_file'][:-4] + ".npy", 'r')
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/numpy/core/memmap.py", line 229, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
OSError: [Errno 5] Input/output error: '/media/project/nnUNet/nnUNet_preprocessed/Dataset002/nnUNetPlans_3d_fullres/C0107_LAD_sagital.npy'
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/nicvi/nnUNet/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/nicvi/nnUNet/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/nicvi/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1242, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-5 (results_loop):
Traceback (most recent call last):
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/nicvi/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Aborted (core dumped)

**Comment by norajitr** [comment]
Hi MM-DHM,

you mentioned that you are training on your preprocessed training data which is stored on a remote location, is that right? It seems like the dataloading is (therefore) not working smoothly. Do you have the means to store your training data locally and train from there? Also, in your update, you mentioned after re-running the preprocessing, it had worked better? But the preprocessing was apprently done in the same default fashion as before, wasn't it? 

Best,
Tobias

**Comment by MM-DHM** [comment]
Hi Tobias,

thanks for your reply. Exactly, I ran the training again using the --c command and it went smoothly. I can run the training on remote folder without any problem now, I don't know what caused the RuntimeError.

Best,
Mahdi

**Comment by norajitr** [comment]
Hi Mahdi,

ok perfect :-) thanks for the clarification.

Best,
Tobias
