### ISSUE TITLE
Running `nnUNetv2_predict` inside docker container: RuntimeError: Background workers died

### ISSUE THREAD

**Issue by rahul99** [MIC-DKFZ/nnUNet#1789]
Hello,

I have created a docker container with nnUNetv2 and mounted the trained model weights.

My Dockerfile is as follows:

```
FROM --platform=linux/amd64 pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime AS builder
ENV nnUNet_results="/app/model_weights/nnunetv2"

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
```

Contents of requirements.txt
```
nnunetv2==2.2.1
pynrrd==1.0.0
```

I start a container in interactive mode and mount the necessary input-dir (containing nifti files for inference), output-dir (to collect segmented output) and the model weights (the `nnUNet_results` folder)

```
nnUNetv2_predict -d [MY_DATASET_ID] -i MY_INPUT_DIR -o MY_OUTPUT_DIR -c 3d_fullres 
```

I am getting the following error:
```
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/opt/conda/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 838, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/opt/conda/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 249, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/opt/conda/lib/python3.10/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 342, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/opt/conda/lib/python3.10/site-packages/nnunetv2/inference/data_iterators.py", line 109, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!
```

The error msg seems misleading because I am running the inference in a server with very high CPU and GPU config.

I tried to tone down `nnUNetv2_predict` to run a single process and a single fold as follows but the error remains the same
```
nnUNetv2_predict -d [MY_DATASET_ID] -i MY_INPUT_DIR -o MY_OUTPUT_DIR -c 3d_fullres --verbose -nps 1 -npp 1 -device cpu -f 0
```

Note: `nnUNetv2_predict` works all right in the local environment / server. The issue appears only when an inference is run in the container environment.

Please suggest a way forward, thank you!

**Comment by rahul99** [comment]
`Update`:

Looking at one of the msg in error log:
```
perform_everything_on_gpu=True is only supported for cuda devices! Setting this to False
```

It appears as if `nnUNetv2` is not able to resolve some of the cuda driver functions. In the container image above, I have verified that the cuda drivers are installed properly and that we are able to perform torch tensor operations in cuda

In the interactive mode inside container, the following works:
```
$ nvidia-smi
# prints the available GPUs

$ python
import torch
x = torch.randn((3,4), device='cuda')
y = x**2 # works
```

**Comment by rahul99** [comment]
@FabianIsensee , @saikat-roy , just checking in if you guys got a chance to look into this.

**Comment by rahul99** [comment]
Btw, I changed the base image to the following so all cuda / torch related functions work as expected.
```
nvcr.io/nvidia/pytorch:23.05-py3
```

However, running nnunet-v2 continues to throw error inside container. For your reference, here is the update Dockerfile:

```
FROM nvcr.io/nvidia/pytorch:23.05-py3

ENV DOCKER_BUILDKIT=0
ENV COMPOSE_DOCKER_CLI_BUILD=0
ENV nnUNet_results="/app/model_weights/nnunetv2"

RUN apt-get update
# Needed for fury vtk. ffmpeg also needed
RUN apt-get install -y ffmpeg libsm6 libxext6 xvfb

RUN pip install --upgrade pip
RUN pip install TotalSegmentator==2.0.5 pynrrd==1.0.0

# Copy model weights
COPY model_weights/nnUNet_results $nnUNet_results

WORKDIR /app
COPY ./src /app
COPY ./tests /tests
ENTRYPOINT ["python", "/app/run.py"]
```

**Comment by ancestor-mithril** [comment]
What is your docker container shared memory size? 
Check this: https://github.com/pytorch/pytorch#using-pre-built-images.

**Comment by rahul99** [comment]
Thanks a lot. Attaching shared memory did solve the problem. Appreciate your help!
