### ISSUE TITLE
Error occurs during the training procedure...

### ISSUE THREAD

**Issue by wjcheon** [MIC-DKFZ/nnUNet#1797]
I faced up the blow error during the training procedure...

(env)>> nnUNetv2_train.exe 001 2d 0 --npz

Please give me adivse.

Best regards 
Wonjoong Cheon

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda_env\nnunet_liver\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "D:\anaconda_env\nnunet_liver\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\training\dataloading\utils.py", line 15, in _convert_to_npy
    np.save(npz_file[:-3] + "npy", a['data'])
  File "D:\anaconda_env\nnunet_liver\lib\site-packages\numpy\lib\npyio.py", line 249, in __getitem__
    magic = bytes.read(len(format.MAGIC_PREFIX))
  File "D:\anaconda_env\nnunet_liver\lib\zipfile.py", line 924, in read
    data = self._read1(n)
  File "D:\anaconda_env\nnunet_liver\lib\zipfile.py", line 1000, in _read1
    data = self._decompressor.decompress(data, n)
zlib.error: Error -3 while decompressing data: invalid stored block lengths
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\anaconda_env\nnunet_liver\Scripts\nnUNetv2_train-script.py", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\run\run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\run\run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1221, in run_training
    self.on_train_start()
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 799, in on_train_start
    unpack_dataset(self.preprocessed_dataset_folder, unpack_segmentation=True, overwrite_existing=False,
  File "c:\users\user\dropbox\research\개인연구\903_nnunet_gui\code\nnunet-wjcheon\nnunetv2\training\dataloading\utils.py", line 33, in unpack_dataset
    p.starmap(_convert_to_npy, zip(npz_files,
  File "D:\anaconda_env\nnunet_liver\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "D:\anaconda_env\nnunet_liver\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
zlib.error: Error -3 while decompressing data: invalid stored block lengths

**Comment by ykirchhoff** [comment]
Hi @wjcheon,

it seems like the issue is with the preprocessed .npz files. Could you try running the preprocessing again, to check if that solves the issue?

Best,
Yannick

**Comment by wjcheon** [comment]
Hi @ykirchhoff 

Yes, there was issue in the pre-processed data.

Thus, I solved the problem using below procedure:

1) create new env for conda environment 
2) install the new version of nnunetv2 

Thanks alots 

Best regards 
Wonjoong Cheon
