### ISSUE TITLE
Issue with nnUNetv2_find_best_configuration

### ISSUE THREAD

**Issue by vlgonz** [MIC-DKFZ/nnUNet#1819]
I have run this for the 5 folds: F [0,1,2,3,4]

**!nnUNet_n_proc_DA=0 nnUNetv2_train 1 3d_fullres F -tr nnUNetTrainer_10epochs --npz**

However, I do not have any validation_raw folder ( where the softmax outputs during the final validation should be) and therefore when I try to execute **!nnUNetv2_find_best_configuration 1 -c 3d_fullres -tr nnUNetTrainer_10epochs** an error arises saying:  _Traceback (most recent call last):
  File "/data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/.conda/bin/nnUNetv2_find_best_configuration", line 8, in <module>
    sys.exit(find_best_configuration_entry_point())
  File "/data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/.conda/lib/python3.9/site-packages/nnunetv2/evaluation/find_best_configuration.py", line 295, in find_best_configuration_entry_point
    find_best_configuration(dataset_name, model_dict, allow_ensembling=not args.disable_ensembling,
  File "/data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/.conda/lib/python3.9/site-packages/nnunetv2/evaluation/find_best_configuration.py", line 100, in find_best_configuration
    accumulate_cv_results(output_folder, merged_output_folder, folds, num_processes, overwrite)
  File "/data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/.conda/lib/python3.9/site-packages/nnunetv2/evaluation/accumulate_cv_results.py", line 36, in accumulate_cv_results
    raise RuntimeError(f"fold {f} of model {trained_model_folder} is missing. Please train it!")
RuntimeError: fold 0 of model /data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/dataset/nnUNet_results/Dataset001_HaN/nnUNetTrainer_10epochs__nnUNetPlans__3d_fullres is missing. Please train it!_

**Question 1: WHAT should I execute to save softmax outputs during the final validation at first????**

----------------------------------------------------------------------------------------
I know that If I run now **!nnUNet_n_proc_DA=0 nnUNetv2_train 1 3d_fullres F -tr nnUNetTrainer_10epochs --val --npz**, softmax outputs would be saved but I GOT THIS "BUS ERROR": _Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2023-11-24 11:48:57.828794: Using splits from existing split file: /data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/dataset/nnUNet_preprocessed/Dataset001_HaN/splits_final.json
2023-11-24 11:48:57.829354: The split file contains 5 splits.
2023-11-24 11:48:57.829394: Desired fold for training: 0
2023-11-24 11:48:57.829677: This split has 25 training and 7 validation cases.
2023-11-24 11:48:57.829802: predicting case_01
/data/10001/nextmed-devEnv/Codigo/Python/Laboratorio/ai/nnUNet-2.2/.conda/lib/python3.9/site-packages/torch/nn/modules/conv.py:605: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1699542476443/work/aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv3d(
2023-11-24 12:49:08.775106: predicting case_04
Bus error._ 

**Question 2: Why do I get this BUS error? How can I solve it?**

**Comment by mrokuss** [comment]
Hey @vlgonz 

It is very hard to judge from this point what is going on but it does not appear to be related to nnUNet itself. It seems to me that you probably have some issue with you CUDA/cuDNN installation. I would suggest to reinstall CUDA/cuDNN or use another version as discussed [here](https://stackoverflow.com/questions/76216778/userwarning-applied-workaround-for-cudnn-issue-install-nvrtc-so). Hope this helps and let me know if this could fix it.

Max
