### ISSUE TITLE
Assertion Error: assert 1 < output_dimension < 4

### ISSUE THREAD

**Issue by pykehuang** [MIC-DKFZ/nnUNet#1820]
The errors are as follows:
Traceback (most recent call last):
  File "/opt/miniconda3/envs/nnunet/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/miniconda3/envs/nnunet/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/syx/segmentation/nnUNet/nnunetv2/inference/export_prediction.py", line 105, in export_prediction_from_logits
    rw.write_seg(segmentation_final, output_file_truncated + dataset_json_dict_or_file['file_ending'],
  File "/home/syx/segmentation/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 120, in write_seg
    assert 1 < output_dimension < 4
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/nnunet/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/home/syx/segmentation/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 838, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/home/syx/segmentation/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 249, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/home/syx/segmentation/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 400, in predict_from_data_iterator
    ret = [i.get()[0] for i in r]
  File "/home/syx/segmentation/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 400, in <listcomp>
    ret = [i.get()[0] for i in r]
  File "/opt/miniconda3/envs/nnunet/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AssertionError

Can you guys give me some tips? Thanks.

**Comment by Kobalt93** [comment]
Hi pykehuang,
Have you already checked your input/output data properties in the write_seg? I would check the dimensions whether they are correct

**Comment by Kobalt93** [comment]
Feel free to reopen this issue if it still persists
