### ISSUE TITLE
nnUNetv2_train  IndexError: list index out of range

### ISSUE THREAD

**Issue by neu-null** [MIC-DKFZ/nnUNet#1824]
Traceback (most recent call last):
  File "/root/anaconda3/envs/nnunet/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/home/nnUNet-v2/nnunetv2/run/run_training.py", line 253, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/nnUNet-v2/nnunetv2/run/run_training.py", line 196, in run_training
    nnunet_trainer.run_training()
  File "/home/nnUNet-v2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1227, in run_training
    self.on_train_start()
  File "/home/nnUNet-v2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 813, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
  File "/home/nnUNet-v2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 612, in get_dataloaders
    dl_tr, dl_val = self.get_plain_dataloaders(initial_patch_size, dim)
  File "/home/nnUNet-v2/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 632, in get_plain_dataloaders
    dl_tr = nnUNetDataLoader2D(dataset_tr, self.batch_size,
  File "/home/nnUNet-v2/nnunetv2/training/dataloading/base_data_loader.py", line 38, in __init__
    self.data_shape, self.seg_shape = self.determine_shapes()
  File "/home/nnUNet-v2/nnunetv2/training/dataloading/base_data_loader.py", line 57, in determine_shapes
    data, seg, properties = self._data.load_case(self.indices[0])
IndexError: list index out of range

**Comment by Kobalt93** [comment]
Hi neu-null,
Could you please provide us more details regarding your data and settings? I see that you train with 2D data, is it possible that they have an extra dimension/cannel with the size of 1? [1, y, x] instead of [y, x]
