### ISSUE TITLE
RuntimeError: Could not find a dataset with the ID 2.

### ISSUE THREAD

**Issue by neu-null** [MIC-DKFZ/nnUNet#1890]
Fingerprint extraction...
Traceback (most recent call last):
  File "/root/anaconda3/envs/umamba/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2==2.1.1', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
  File "/root/anaconda3/envs/umamba/lib/python3.10/site-packages/nnunetv2-2.1.1-py3.10.egg/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 2. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/data1/dataset/nnUNet_preprocessed
nnUNet_results=/data1/dataset/nnUNet_results
nnUNet_raw=/data1/dataset/nnUNet_raw

![Uploading 屏幕截图 2024-01-12 103726.png…]()

Best Regards

**Comment by SiruLiu645** [comment]
hi，have you solved this problem？I meet the same problem now.

**Comment by dojoh** [comment]
did you make sure that the corresponding files exist?

**Comment by SiruLiu645** [comment]
I solved this problem，thank you！

----- 原始邮件 -----
发件人: "dojoh" ***@***.***>
收件人: "MIC-DKFZ/nnUNet" ***@***.***>
抄送: "SiruLiu645" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期一, 2024年 5 月 06日 下午 7:04:23
主题: Re: [MIC-DKFZ/nnUNet] RuntimeError: Could not find a dataset with the ID 2. (Issue #1890)

did you make sure that the corresponding files exist?

**Comment by Jchanel-1** [comment]
Hi! I met the problem too. How to solve this problem? I use the private RGB dataset! 
nnUNetv2_plan_and_preprocess -d 501  --verify_dataset_integrityFingerprint extraction...
Traceback (most recent call last):
  File "/home/jjj/miniconda3/envs/lu2/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/data/jjj/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 184, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/data/jjj/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/data/jjj/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
  File "/data/jjj/nnUNet/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 501. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:

**Comment by whatwhyhow1** [comment]
hello ,have you solved this problem?I met same one....

**Comment by SiruLiu645** [comment]
you can try to name the id larger than 500, maybe

----- 原始邮件 -----
发件人: "whatwhyhow1" ***@***.***>
收件人: "MIC-DKFZ/nnUNet" ***@***.***>
抄送: "SiruLiu645" ***@***.***>, "Comment" ***@***.***>
发送时间: 星期三, 2024年 9 月 25日 下午 8:00:51
主题: Re: [MIC-DKFZ/nnUNet] RuntimeError: Could not find a dataset with the ID 2. (Issue #1890)

hello ,have you solved this problem?I met same one....
