### ISSUE TITLE
 RuntimeError: Pretrained weights are not compatible with the current network architecture

### ISSUE THREAD

**Issue by Yuejingkun** [MIC-DKFZ/nnUNet#1891]
I trained 40 epochs on task 600 and got the pre-training weights, I want to use this pre-training weights to train on task 602, the command I used is
CUDA_VISIBLE_DEVICES=6 nnUNet_train 2d nnUNetTrainerV2 602 0 --npz -pretrained_weights "/data/yjk22/nnUNet/nnUNetFrame/DATASET/nnUNet_trained_models/nnUNet/2d/Task600_MRIBrainEdemaBraTS2020T2/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_best.model"

the error is：
Traceback (most recent call last):
  File "/home/yjk22/anaconda3/envs/nnunet/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/yjk22/nnUNet/nnunet/run/run_training.py", line 177, in main
    load_pretrained_weights(trainer.network, args.pretrained_weights)
  File "/home/yjk22/nnUNet/nnunet/run/load_pretrained_weights.py", line 61, in load_pretrained_weights
    raise RuntimeError("Pretrained weights are not compatible with the current network architecture")
RuntimeError: Pretrained weights are not compatible with the current network architecture

**Comment by Yuejingkun** [comment]
I use nnUNet v1
