### ISSUE TITLE
Preprocessing bug

### ISSUE THREAD

**Issue by iamsalvatore** [MIC-DKFZ/nnUNet#1900]
I'm trying to run: nnUNetv2_plan_and_preprocess -d 155.

I've followed every step of the documentation, but I get this error when executing that line:

Dataset155_SEGA
Dataset keys: ['patient_00', 'patient_01', 'patient_02', 'patient_03', 'patient_04', 'patient_05', 'patient_06', 'patient_07', 'patient_08', 'patient_09', 'patient_10', 'patient_11', 'patient_12', 'patient_13', 'patient_14', 'patient_15', 'patient_16', 'patient_17', 'patient_18', 'patient_19', 'patient_20', 'patient_21', 'patient_22', 'patient_23', 'patient_24', 'patient_25', 'patient_26', 'patient_27', 'patient_28', 'patient_29', 'patient_30', 'patient_31', 'patient_32', 'patient_33', 'patient_34', 'patient_35', 'patient_36', 'patient_37', 'patient_38', 'patient_39', 'patient_40']
First dataset key: patient_00
Images for first dataset key: []
Traceback (most recent call last):
  File "/home/salvatore/miniconda3/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salvatore/Documents/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/salvatore/Documents/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/salvatore/Documents/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 32, in extract_fingerprint_dataset
    return fpe.run(overwrite_existing=clean)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salvatore/Documents/nnUNet/nnunetv2/experiment_planning/dataset_fingerprint/fingerprint_extractor.py", line 123, in run
    self.dataset[self.dataset.keys().__iter__().__next__()]['images'][0])
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range


My dataset.json is:

{
    "channel_names": {
        "0": "CT"
    },
    "labels": {
        "background": 0,
        "Liver": 1,
        "Vessel": 2
    },
    "numTraining": 270,
    "file_ending": ".nii.gz"
}

**Comment by eyafg** [comment]
Hi @iamsalvatore , can you please explain how u solved the error? 
Thanks a lot!
