### ISSUE TITLE
nnUNetv2_predict can not make .nii.gz file

### ISSUE THREAD

**Issue by avBuffer** [MIC-DKFZ/nnUNet#1909]
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.11/multiprocessing/resource_sharer.py", line 138, in _serve
    with self._listener.accept() as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/multiprocessing/connection.py", line 464, in accept
    deliver_challenge(c, self._authkey)
  File "/home/anaconda3/lib/python3.11/multiprocessing/connection.py", line 739, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/multiprocessing/connection.py", line 215, in recv_bytes
    buf = self._recv_bytes(maxlength)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/multiprocessing/connection.py", line 413, in _recv_bytes
    buf = self._recv(4)
          ^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/multiprocessing/connection.py", line 378, in _recv
    chunk = read(handle, remaining)
            ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/lib/python3.11/site-packages/nnunetv2-2.2.1-py3.11.egg/nnunetv2/inference/export_prediction.py", line 86, in export_prediction_from_logits
    rw.write_seg(segmentation_final, output_file_truncated + dataset_json_dict_or_file['file_ending'], properties_dict)
  File "/home/anaconda3/lib/python3.11/site-packages/nnunetv2-2.2.1-py3.11.egg/nnunetv2/imageio/simpleitk_reader_writer.py", line 127, in write_seg
    itk_image.SetDirection(properties['sitk_stuff']['direction'])
  File "/home/anaconda3/lib/python3.11/site-packages/SimpleITK/SimpleITK.py", line 3255, in SetDirection
    return _SimpleITK.Image_SetDirection(self, direction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception thrown in SimpleITK Image_SetDirection: /tmp/SimpleITK/Code/Common/include/sitkTemplateFunctions.h:191:
sitk::ERROR: Length of input (16) does not match matrix dimensions (3, 3).

**Comment by constantinulrich** [comment]
Hi, i would need some more information. Did you train a default nnU-Net without manual changes? And on which dataset?

**Comment by avBuffer** [comment]
> Hi, i would need some more information. Did you train a default nnU-Net without manual changes? And on which dataset?

Thanks! Training Dataset001_BrainTumour by using default nnUNet.

**Comment by constantinulrich** [comment]
Mh this dataset is already tested plenty of times. So I guess the error must be on your side. Did you used the provided scripts for dataset conversion?
