### ISSUE TITLE
nnUNet_train error, unable to write to file

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#1910]
###############################################
2024-01-22 15:42:43.972844: Using dummy2d data augmentation
loading dataset
loading all case properties
unpacking dataset
done
2024-01-22 15:44:57.731584: lr: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_2020_3561407020>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_2016_3737862368>

**Comment by Kobalt93** [comment]
Hi goodsave,
Could you please provide more details regarding your settings? It is hard to tell the problem without additional details. Could you please check whether
- you set your paths correctly (writing permissions?),
- your RAM has enough space, and
- The SingleThreadedAugmenter works?
