### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by Sharanya0690** [MIC-DKFZ/nnUNet#1929]
I trained the network and it saved all the necessary files for folds 0, 1, 2, 3 and 4. During inference, I am getting this error.

Traceback (most recent call last):
  File "/scratch/sharanya/nnUNet/nnUNet/env/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/inference/predict_simple.py", line 219, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/inference/predict.py", line 668, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/inference/predict.py", line 191, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision,
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/training/model_restore.py", line 140, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "%s.model.pkl" % checkpoint_name), fp16=mixed_precision)
IndexError: list index out of range

**Comment by seziegler** [comment]
Hi @Sharanya0690 ,

what was the command you used for inference?

Best,
Sebastian

**Comment by Sharanya0690** [comment]
Hi seziegler,

I used nnUNet_predict -i $FOLDER_WITH_TEST_CASES -o $OUTPUT_FOLDER -t Task_ID -m 3d_fullres -tr nnUNetTrainerV2 --save_npz

**Comment by Sharanya0690** [comment]
Before running the inference, I tried to run the best configuration. It says some folds are missing. But, I could see all the necessary files in all 5 folders.

Traceback (most recent call last):
  File "/scratch/sharanya/nnUNet/nnUNet/env/bin/nnUNet_find_best_configuration", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')())
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 144, in main
    consolidate_folds(output_folder, folds=folds)
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 61, in consolidate_folds
    collect_cv_niftis(output_folder_base, output_folder_raw, validation_folder_name,
  File "/scratch/sharanya/nnUNet/nnUNet/nnunet/postprocessing/consolidate_postprocessing.py", line 31, in collect_cv_niftis
    raise RuntimeError("some folds are missing. Please run the full 5-fold cross-validation. "
RuntimeError: some folds are missing. Please run the full 5-fold cross-validation. The following folds seem to be missing: [0, 1, 2, 3, 4]

**Comment by seziegler** [comment]
It seems like nnunet cannot find your trained folds at all, since in the last error you've shown all folds are missing. Are you sure that the environment variable `RESULTS_FOLDER` (for nnunet v1) points to the directory where your folds are saved?

**Comment by Sharanya0690** [comment]
Yes, it points to the directory where my all trained folds are saved.

**Comment by Sharanya0690** [comment]
export RESULTS_FOLDER=/scratch/$USER/nnUNet/nnUNet/trained_models/
![Picture1](https://github.com/MIC-DKFZ/nnUNet/assets/99428512/dce7effd-8d95-47f6-a018-30510fdcbc1f)

**Comment by Sharanya0690** [comment]
It works now!!

Thank you!!
