### ISSUE TITLE
When executing nnUNetv2_extract_fingerprint, issues arise.

### ISSUE THREAD

**Issue by x0204** [MIC-DKFZ/nnUNet#1939]
Dear contributors,

Thanks for this great work of your team
Upon attempting to execute nnUNetv2_extract_fingerprint, I encountered an issue. Below is the command I used along with the corresponding error code:
chang@chang-System-Product-Name:~/nnUNet/nnunetv2/dataset_conversion$ nnUNetv2_extract_fingerprint -d 159 --verify_dataset_integrity
Traceback (most recent call last):
  File "/home/chang/anaconda3/envs/GBM_env/bin/nnUNetv2_extract_fingerprint", line 8, in <module>
    sys.exit(extract_fingerprint_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chang/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 27, in extract_fingerprint_entry
    extract_fingerprints(args.d, args.fpe, args.np, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/chang/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/chang/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chang/nnUNet/nnunetv2/utilities/dataset_name_id_conversion.py", line 45, in convert_id_to_dataset_name,
    raise RuntimeError("More than one dataset name found for dataset id %d. Please correct that. (I looked in the "
RuntimeError: More than one dataset name found for dataset id 159. Please correct that. (I looked in the following folders:
/home/chang/nnUNet/nnUNetFrame/DATASET/nnUNet_raw/nnUNet_raw_data
/home/chang/nnUNet/nnUNetFrame/DATASET/nnUNet_preprocessed
/home/chang/nnUNet/nnUNetFrame/DATASET/nnUNet_results
-------------------------------------------------------------------------------------------------------------------------------------------------
Upon investigation, it was found that the Dataset159 folder exists in each of the aforementioned directories. This is due to Dataset159 being a pre-trained nnUNet model.

I kindly request assistance in resolving this issue.

Thank you for your attention to this matter.

**Comment by ykirchhoff** [comment]
Hi @x0204,

the error means, that nnUNet was not able to unambiguously find the correct dataset. The names of the datasets probably differ in the different directories. If you have a pretrained model in Dataset159 it would be best to change the dataset number for the finetuning task, otherwise this will interfere.

Best,
Yannick

**Comment by x0204** [comment]
Thanks for the explanation!
After I change my data number and try again.
There is no more error message.
Thanks!

**Comment by ykirchhoff** [comment]
Great, then I will close the issue now.
Feel free to open another issue if you run into any other problems in the future :)

Best,
Yannick
