### ISSUE TITLE
2D RGB png dataset bechmarking

### ISSUE THREAD

**Issue by HamzaFarooq013** [MIC-DKFZ/nnUNet#1948]
Hi,
I am trying to bechmark nnUnet on my own 2D ( RGB  .png) dataset but got errors in  (verify_dataset_integrity). Can you please share some configuration setting for normal .png datset for binary class  for benchmarking on nnUnet. (Thanks in advance)

my settings  for Json:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
overwrite_json_file = True #make it True if you want to overwrite the dataset.json file in Dataset_folder
json_file_exist = False

if os.path.exists(os.path.join(task_folder_name,'dataset.json')):
    print('dataset.json already exist!')
    json_file_exist = True

if json_file_exist==False or overwrite_json_file:

    json_dict = OrderedDict()
    json_dict['name'] = dataset_name
    json_dict['description'] = "multi_lables_uniclass"
    json_dict['tensorImageSize'] = "3D"
    json_dict['reference'] = "ABC"
    json_dict['licence'] = "ABC"
    json_dict['release'] = "0.1"

    #you may mention more than one modality
    json_dict['channel_names'] = {
       "0": "R",
       "1": "G",
       "3": "B"
    }

    # set expected file ending
    json_dict["file_ending"] = ".png"

    #label names should be mentioned for all the labels in the dataset
    json_dict['labels'] = {
        "background": 0,
        "white matter": 1
    }

    train_ids = os.listdir(train_label_dir)
    test_ids = os.listdir(test_dir)
    json_dict['numTraining'] = len(train_ids)
    json_dict['numTest'] = len(test_ids)

    with open(os.path.join(task_folder_name,"dataset.json"), 'w') as f:
        json.dump(json_dict, f, indent=4, sort_keys=True)

    if os.path.exists(os.path.join(task_folder_name,'dataset.json')):
        if json_file_exist==False:
            print('dataset.json created!')
        else:
            print('dataset.json overwritten!')
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

!nnUNetv2_plan_and_preprocess -d 876  -c 2d_fullres --verify_dataset_integrity

Error: Unexpected number of modalities. 
Expected: 3. 
Got: 1.

**Comment by HamzaFarooq013** [comment]
I have kind of solved that issue but why this shape error is happend?

As data is verified but still dim error 


#########################################################################

Exception in background worker 0:
 could not broadcast input array from shape (3,301,301) into shape (1,301,301)
using pin_memory on device 0
Output is truncated. View as a scrollable element or open in a text editor. Adjust cell output settings...
Traceback (most recent call last):
  File "d:\Hamza Farooq\.venv\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "d:\Hamza Farooq\.venv\lib\site-packages\batchgenerators\dataloading\data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "d:\Hamza Farooq\.venv\lib\site-packages\nnunetv2\training\dataloading\data_loader_2d.py", line 92, in generate_train_batch
    seg_all[j] = np.pad(seg, ((0, 0), *padding), 'constant', constant_values=-1)
ValueError: could not broadcast input array from shape (3,301,301) into shape (1,301,301)

**Comment by Ismatse** [comment]
Hi, @HamzaFarooq013 
Have you been able to solve that problem? I have kind of the same shape issue while training and I have no idea why.

**Comment by HamzaFarooq013** [comment]
Hello,
I am not able to solve this issue. but Greyscale channel will help to solve
this problem for data verification but In training that cause problem of
model input dim.

**Comment by Karol-G** [comment]
Hey,

Is this issue still relevant? Otherwise, I will close it in 14 days.

Best,
Karol

**Comment by HamzaFarooq013** [comment]
Yes, please!

**Comment by Karol-G** [comment]
@claude lets get some feedback from you

**Comment by Karol-G** [comment]
@HamzaFarooq013 Is claude right? From the log it also seems to me that your segmentations/labels have 3 channels. They should only have one however. If this is the case then this is an easy fix :)

**Comment by Karol-G** [comment]
I assume this is fixed. Will close the issue now due to inactivity. Feel free to open it again if the issue still persists.
