### ISSUE TITLE
"No candidate for Task id XXX in folder YYY"

### ISSUE THREAD

**Issue by tjhendrickson** [MIC-DKFZ/nnUNet#1978]
I've completed training of each of the 5 folds for a task and am attempting to run `nnUNet_find_best_configuration`. 

However, when I attempt to run it I receive the following error:
```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/home/support/public/pytorch_1.11.0_agate/bin/nnUNet_find_best_configuration", line 8, in <module>
    sys.exit(main())
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 100, in main
    task_name = find_task_name(get_output_folder_name(m), t)
  File "/home/support/public/pytorch_1.11.0_agate/lib/python3.10/site-packages/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 31, in find_task_name
    assert len(candidates) > 0, "no candidate for Task id %d found in folder %s" % (task_id, folder)
AssertionError: no candidate for Task id 709 found in folder /home/feczk001/shared/data/nnUNet/nnUNet_raw_data_base/nnUNet_trained_models/nnUNet/3d_fullres
```
Full command: `nnUNet_find_best_configuration -m 3d_fullres -t 709`
Environment variables:
```
- export nnUNet_raw_data_base="/scratch.global/hendr522-BIBSNet-T2only"
- export nnUNet_preprocessed="/scratch.global/hendr522-BIBSNet-T2only/nnUNet_preprocessed/"
- export RESULTS_FOLDER="/home/feczk001/shared/data/nnUNet/nnUNet_raw_data_base/nnUNet_trained_models

When I list the contents of $RESULTS_FOLDER/nnUNet/3d_fullres this is what I see:
```
Task526				       Task703	Task710  Task717  Task724
Task540				       Task704	Task711  Task718  Task725
Task552_uniform_distribution_synthseg  Task705	Task712  Task719  Task726
Task553_uniform_distribution_synthseg  Task706	Task713  Task720  Task727
Task700				       Task707	Task714  Task721  Task728
Task701				       Task708	Task715  Task722
Task702				       Task709	Task716  Task723
```

Any ideas?

**Comment by FabianIsensee** [comment]
Hey, Saikat recently left DKFZ and I am taking over some of his old issues. Can you please ping me if this question is still relevant? If I don't receive a response within a week I will close this :-)
