### ISSUE TITLE
Problem with networkarchitectures

### ISSUE THREAD

**Issue by Tkidnjxi** [MIC-DKFZ/nnUNet#2010]
I am a rookie in nnUNet, when i try to change the PlainConvEncoder to ResidualEncoderUNet ,there is an error showing:
Traceback (most recent call last):
  File "/HOME/.conda/envs/zheng_nnunet_new/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1317, in run_training
    self.on_train_start()
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 860, in on_train_start
    self.initialize()
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 213, in initialize
    self.network = self.build_network_architecture(
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 302, in build_network_architecture
    return get_network_from_plans(
  File "/data/run01/nnUNet_new/nnUNet/nnunetv2/utilities/get_network_from_plans.py", line 34, in get_network_from_plans
    network = nw_class(
TypeError: __init__() got an unexpected keyword argument 'n_conv_per_stage'
how can i fix this problem?I need some suggestions. The configuration in nnUNet is default expect changing the network architecture.
best wishes

**Comment by Tkidnjxi** [comment]
I have found the way to solve it, thanks a lot!
