### ISSUE TITLE
RuntimeError when started to run multi-GPU distributed training

### ISSUE THREAD

**Issue by shanruiyu** [MIC-DKFZ/nnUNet#202]
Hi, thank you very much for your amazing work! When I train with a single GPU, the code performs well. However, when I try to train with multiple GPUs, I used "CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port=4321 --nproc_per_node=4 /home/shanruiyu/nnunet/nnunet/run/run_training_DDP.py 3d_fullres nnUNetTrainerV2_DDP Task004_POOLING4_patchsize128 4“ to start the distributed training, but the following problems arise:

> Traceback (most recent call last):
>   File "/home/shanruiyu/nnunet/nnunet/run/run_training_DDP.py", line 163, in <module>
>     main()
>   File "/home/shanruiyu/nnunet/nnunet/run/run_training_DDP.py", line 137, in main
>     trainer.initialize(not validation_only)
>   File "/home/shanruiyu/nnunet/nnunet/training/network_training/nnUNetTrainerV2_DDP.py", line 243, in initialize
>     self._maybe_init_amp()
>   File "/home/shanruiyu/nnunet/nnunet/training/network_training/network_trainer.py", line 387, in _maybe_init_amp
>     self.network, self.optimizer = amp.initialize(self.network, self.optimizer, opt_level="O1")
>   File "/home/shanruiyu/pythonenv/nnunet/lib/python3.7/site-packages/apex/amp/frontend.py", line 358, in initialize
>     return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
>   File "/home/shanruiyu/pythonenv/nnunet/lib/python3.7/site-packages/apex/amp/_initialize.py", line 171, in _initialize
>     check_params_fp32(models)
>   File "/home/shanruiyu/pythonenv/nnunet/lib/python3.7/site-packages/apex/amp/_initialize.py", line 93, in check_params_fp32
>     name, param.type()))
>   File "/home/shanruiyu/pythonenv/nnunet/lib/python3.7/site-packages/apex/amp/_amp_state.py", line 32, in warn_or_err
>     raise RuntimeError(msg)
> RuntimeError: Found param conv_blocks_localization.0.0.blocks.0.conv.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
> When using amp.initialize, you need to provide a model with parameters
> located on a CUDA device before passing it no matter what optimization level
> you chose. Use model.to('cuda') to use the default device.

Looking forward your reply!

**Comment by shanruiyu** [comment]
Sorry, I just reinstalled the pytorch that adapts to my CUDA version. The problem has been solved....
