### ISSUE TITLE
Why do I get an error when processing?  The directory structure of labelsTr should only have labels, why is there also img?

### ISSUE THREAD

**Issue by laodeyip** [MIC-DKFZ/nnUNet#2050]
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/usr/local/lib/python3.8/dist-packages/nnunet/preprocessing/sanity_checks.py", line 129, in verify_dataset_integrity
    assert isfile(expected_label_file), "could not find label file for case %s. Expected file: \n%s" % (
AssertionError: could not find label file for case img0001. Expected file: 
/hy-tmp/DATASET/nnUNet_raw_data_base/nnUNet_raw_data/Task501_Synapse/labelsTr/img0001.nii.gz

**Comment by FabianIsensee** [comment]
Does the expected label file exist?

**Comment by FabianIsensee** [comment]
Any update on this?
