### ISSUE TITLE
Some error on mutil-gpu training

### ISSUE THREAD

**Issue by Overflowu7** [MIC-DKFZ/nnUNet#2070]
When I changed from one 3090 to two 3090s connected with nvlink and added the parameter - num_gpus 2 correctly, the following error appeared. I tried several things including torch.nn.parallel.DistributedDataParallel but none of them work.

Hopefully someone can give me some suggestions for changes!

Epoch 0
Current learning rate: 0.01
using pin_memory on device 1
/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/onnx/symbolic_helper.py:1513: UserWarning: ONNX export mode is set to TrainingMode.EVAL, but operator 'instance_norm' is set to train=True. Exporting with train=True.
  warnings.warn(
2024-04-08 14:18:26.172545: Unable to plot network architecture:
2024-04-08 14:18:26.173235: failed to execute PosixPath('dot'), make sure the Graphviz executables are on your systems' PATH
2024-04-08 14:18:26.408904: 
2024-04-08 14:18:26.409347: Epoch 0
2024-04-08 14:18:26.409994: Current learning rate: 0.01
using pin_memory on device 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Traceback (most recent call last):
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 287, in <module>
    run_training_entry()
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 281, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 171, in run_training
    mp.spawn(run_ddp,
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 246, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 202, in start_processes
    while not context.join():
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 163, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 130, in run_ddp
    nnunet_trainer.run_training()
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1463, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1105, in train_step
    output = self.network(data)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1515, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1409, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 98 99
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

**Comment by FabianIsensee** [comment]
I think I have seen this before. I believe there was an update to pytorch which made DDP more picky with unused parameters. We do have them in nnU-Net because not all deep supervision heads are used in the loss computation 
Please install the most recent master and try again. You can do that with
`pip install git+https://github.com/MIC-DKFZ/nnUNet.git`

Also see here https://github.com/MIC-DKFZ/nnUNet/blob/5f363b35411ff27589ce84507e4890b2f366ec96/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L379

Best,
Fabian

**Comment by Overflowu7** [comment]
Thank you Fabian!  I am using the latest version of nnUNet, and I think I figured out what the problem is.
When I run nnUNet from the command line and use the -tr command to select my own trainer file, it gives me an error that
`RuntimeError: Could not find requested nnunet trainer nnUNetTrainer2 in nnunetv2.training.nnUNetTrainer (/home/wu/.conda/envs/nnUNet/lib/python3.9/site-packages/nnunetv2/training/nnUNetTrainer). If it is located somewhere else, please move it there.`
```

So i change the run_training.py like:
  parser.add_argument('-network_trainer', default='nnUNetv2_train')
    parser.add_argument('-dataset_name_or_id', type=str,default='32',
                        help='0, 1,3,4,, 5 or \'all\'')
    parser.add_argument('-configuration', type=str,default='3d_lowres',
                        help="Configuration that should be trained")
    parser.add_argument('-fold', type=str,default='66',
                        help='0, 1, ..., 5 or \'all\'')
    parser.add_argument('--cuda_devices', type=str, default='0,1', help='Set CUDA_VISIBLE_DEVICES (e.g., "0,1")')
    parser.add_argument('-num_gpus', type=int, required=False, default=2,
                        help='Specify the number of GPUs to use for training')
```
and add one parameter cuda_devices try to control the 'CUDA_VISIBLE_DEVICES'.
`    if args.cuda_devices:
        os.environ['CUDA_VISIBLE_DEVICES'] = args.cuda_devices` 

But unfortunately, these changes were fine when I was using only one gpu. But once I use more than two gpu's, the altered code still uses only one gpu during training and shows the previous reported error. 

So I'd like to ask you for some suggestions on how I can use two gpus in pycharm.
All the best to you!!!

**Comment by GregorKoehler** [comment]
Hi @Overflowu7 ,

did you, as suggested in the help of that --cuda_devices option, set "CUDA_VISIBLE_DEVICES" correctly in your setup?

**Comment by Overflowu7** [comment]
> Hi @Overflowu7 ,
> 
> did you, as suggested in the help of that --cuda_devices option, set "CUDA_VISIBLE_DEVICES" correctly in your setup?

I think I have it set up correctly. I added the following code to run_training to control the custom parameters --cuda_devices.

```
    if args.cuda_devices:
        os.environ['CUDA_VISIBLE_DEVICES'] = args.cuda_devices

    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
                 args.num_gpus, args.use_compressed, args.npz, args.c, args.val, args.disable_checkpointing,
                 args.val_best,
                 device=device)
```
When I use single gpu i.e., --cuda_devices with default='1', the project works fine. But once I set default='0,1' the project reports an error as described above. I'm confused as to what could cause this.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 108, in results_loop
    item = in_queue.get()
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 495, in rebuild_storage_fd
    fd = df.detach()
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/multiprocessing/resource_sharer.py", line 86, in get_connection
Traceback (most recent call last):
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 291, in <module>
    run_training_entry()
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 284, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 172, in run_training
    mp.spawn(run_ddp,
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/home/wu/wyc/nnUNet/nnunetv2/run/run_training.py", line 130, in run_ddp
    nnunet_trainer.run_training()
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1258, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/wu/wyc/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 900, in train_step
    output = self.network(data)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    inputs, kwargs = self._pre_forward(*inputs, **kwargs)
  File "/home/wu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1413, in _pre_forward
    if torch.is_grad_enabled() and self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`, and by 
making sure all `forward` function outputs participate in calculating loss. 
If you already have done the above, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
Parameter indices which did not receive grad for rank 1: 208 209
 In addition, you can set the environment variable TORCH_DISTRIBUTED_DEBUG to either INFO or DETAIL to print out information about which particular parameters did not receive gradient on this rank as part of this error

```

**Comment by GregorKoehler** [comment]
Hi @Overflowu7 ,

you could try to set `find_unused_parameters=True` in your DistributedDataParallel constructor `self.network = DDP(self.network, device_ids=[self.local_rank], find_unused_parameters=True)` (see, e.g. here in the original trainer: https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py#L224 )
Apparently, this setting makes DDP check for unused parameters and handle them correctly.

If this doesn't help, maybe the suggested env variable `TORCH_DISTRIBUTED_DEBUG` set to DETAIL might give you more information?

**Comment by GregorKoehler** [comment]
Hi @Overflowu7,

I'm closing this issue for the time being due to it being stale for over a week. Feel free to re-open if the info above didn't help resolving the issue!
