### ISSUE TITLE
RuntimeError: No data left in file

### ISSUE THREAD

**Issue by MM-DHM** [MIC-DKFZ/nnUNet#2086]
Hello Fabian,

first of all, thanks for you solid work. I am trying to train a 3D dataset on an A6000 ada, linux system. I have problem with data_loader and I can't figure it out, do you have any idea what could cause the runtime error?

Thank in advance

Log:
2024-04-12 14:36:11.375571: unpacking dataset...
2024-04-12 14:36:16.986147: unpacking done...
2024-04-12 14:36:16.989555: do_dummy_2d_data_aug: False
2024-04-12 14:36:17.007486: Using splits from existing split file: /media/project/nnUNet/Processed_Data/nnUNet_preprocessed/Dataset009_ImageCAS/splits_final.json
2024-04-12 14:36:17.009683: The split file contains 5 splits.
2024-04-12 14:36:17.011479: Desired fold for training: 0
2024-04-12 14:36:17.012179: This split has 640 training and 160 validation cases.
2024-04-12 14:36:17.071842: Unable to plot network architecture:
2024-04-12 14:36:17.072695: No module named 'hiddenlayer'
2024-04-12 14:36:17.085284: 
2024-04-12 14:36:17.085947: Epoch 0
2024-04-12 14:36:17.086544: Current learning rate: 0.01
using pin_memory on device 0
Exception in background worker 11:
 No data left in file
Traceback (most recent call last):
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
           ^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/nnunetv2/training/dataloading/data_loader_3d.py", line 19, in generate_train_batch
    data, seg, properties = self._data.load_case(i)
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/numpy/lib/npyio.py", line 436, in load
    raise EOFError("No data left in file")
EOFError: No data left in file
Traceback (most recent call last):
  File "/home/nicvi/.conda/envs/nnUNet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/nnunetv2/run/run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/nnunetv2/run/run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1291, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nicvi/.conda/envs/nnUNet/lib/python3.11/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by constantinulrich** [comment]
Hi, the problem appears when np.load is called. Can it be that one of your files is corrupted?

**Comment by MM-DHM** [comment]
Thanks a lot, that was it, I deleted the npy files in preprocessed folder and ran the training again

**Comment by APLaS-Plus** [comment]
I met this bug today, and the npy files and cache files even were in the datasets used to train. It is in another datasets under the same lib of the datasets used to train. And they caused the fail😭

**Comment by APLaS-Plus** [comment]
I met this bug today, and the npy files and cache files even were in the datasets used to train. It is in another datasets under the same lib of the datasets used to train. And they caused the fail😭
