### ISSUE TITLE
Saving one of the models as a torchscript file

### ISSUE THREAD

**Issue by ckolluru** [MIC-DKFZ/nnUNet#2088]
Is it possible to save the trained nnUNet model (one of them, say 3d_fullres for example) in the `torchscript` format (in a .pt file)?

I used the `network` class variable in `nnUNetPredictor` as the model. Next, I used the `load_state_dict` function to load in the `network_weights` from the checkpoint file in the results folder.

I followed the instructions [here](https://pytorch.org/tutorials/beginner/saving_loading_models.html) (Export/Load Model in TorchScript Format). I get the following error.

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_script.py", line 1324, in script
    return torch.jit._recursive.create_script_module(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_recursive.py", line 559, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_recursive.py", line 632, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_script.py", line 639, in _construct
    init_fn(script_module)
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_recursive.py", line 608, in init_fn
    scripted = create_script_module_impl(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_recursive.py", line 636, in create_script_module_impl
    create_methods_and_properties_from_stubs(
  File "/home/chaitanya.kolluru/miniconda3/envs/rsip-env/lib/python3.11/site-packages/torch/jit/_recursive.py", line 469, in create_methods_and_properties_from_stubs
    concrete_type._create_methods_and_properties(
RuntimeError: Can't redefine method: forward on class: __torch__.dynamic_network_architectures.building_blocks.plain_conv_encoder.PlainConvEncoder (of Python compilation unit at: 0x676bc80)

**Comment by Body123** [comment]
did you reach anything?

**Comment by ckolluru** [comment]
You can try the following. As I mentioned above, I'm using the `network` class variable in nnUNetPredictor as the model.

```
device = torch.device('cuda:0')
input_example = torch.randn(1, channel_size, patch_size_x, patch_size_y, patch_size_z).to(device)
model.eval()

traced_model = torch.jit.trace(model, input_example)
torch.jit.save(trace_model, 'model.pt')
```

I believe torch.jit.trace does not handle if-else conditionals in the model definition, but it seems to be OK in this case since the architectures used in nnUNet are fully defined beforehand.

**Comment by machur** [comment]
@ckolluru were you able to make it work? did you successfully migrate your nnUNet model to TorchScript?

**Comment by ckolluru** [comment]
Yes, I'm able to do it by adding the following code at this line. You might want to fork the repo and commit these changes.

https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/inference/predict_from_raw_data.py#L618

You need to set up a model_saved variable in the `nnUNetPredictor` class and initialize it to False in the __init__ function. The code below will then save the model during inference on the first dataset of your `nnUNetv2_predict` call.

```
if self.model_saved == False:
    print('Tracing model')
    torch.manual_seed(0)

    # Change the input size of the random tensor below according to your model
    traced_model = torch.jit.trace(self.network, torch.randn(1, 1, 224, 224, 224).to(self.device))

    torch.jit.save(traced_model, './traced_model.pt')

    print('Finished tracing model')
    self.model_saved = True
```

**Comment by qxyqxyqxy642** [comment]
Hello, may I ask if you could share the complete code for exporting the torchscript model

**Comment by chaitanya-kolluru-elucid** [comment]
Did you try adding the code I posted above? Where are you stuck?

**Comment by ckolluru** [comment]
@qxyqxyqxy642 Did you try adding the code I posted in the comment above? Where are you stuck?

**Comment by qxyqxyqxy642** [comment]
Thank you for your reply. I tried adding the code at line 618, and during training, the .pth model file is generated. However, the Tracing model is not created afterward.

**Comment by ckolluru** [comment]
This portion of the code is executed at inference. Once you have a trained model, run `nnUNetv2_predict` with the appropriate parameters and it should execute this code and save the traced model in a `.pt` file.

**Comment by qxyqxyqxy642** [comment]
Thank you! My understanding is that after the training is completed, the code will run and generate the .pt file when performing inference using the trained .pth file.I will try it now.

**Comment by qxyqxyqxy642** [comment]
Is a single 24GB graphics card not enough to run the tracking? How to use dual cards for prediction?

**Comment by qxyqxyqxy642** [comment]
hi I meet some question.Your code consistently consumes GPU memory during inference. Even after upgrading from 24GB to 48GB, it is still not enough.
`Traceback (most recent call last):
  File "/root/miniconda3/envs/nnUNet/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 964, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 260, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 377, in predict_from_data_iterator
    prediction = self.predict_logits_from_preprocessed_data(data).cpu()
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 494, in predict_logits_from_preprocessed_data
    prediction = self.predict_sliding_window_return_logits(data).to('cpu')
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 663, in predict_sliding_window_return_logits
    predicted_logits = self._internal_predict_sliding_window_return_logits(data, slicers, False)
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 611, in _internal_predict_sliding_window_return_logits
    raise e
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 594, in _internal_predict_sliding_window_return_logits
    prediction = self._internal_maybe_mirror_and_predict(workon)[0].to(results_device)
  File "/root/autodl-tmp/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 553, in _internal_maybe_mirror_and_predict
    prediction += torch.flip(self.network(torch.flip(x, axes)), axes)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/dynamic_network_architectures/architectures/unet.py", line 62, in forward
    return self.decoder(skips)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/dynamic_network_architectures/building_blocks/unet_decoder.py", line 111, in forward
    x = self.stages[s](x)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/dynamic_network_architectures/building_blocks/simple_conv_blocks.py", line 137, in forward
    return self.convs(x)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/dynamic_network_architectures/building_blocks/simple_conv_blocks.py", line 71, in forward
    return self.all_modules(x)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/container.py", line 250, in forward
    input = module(input)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 725, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/nnUNet/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 720, in _conv_forward
    return F.conv3d(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 106.00 MiB. GPU 0 has a total capacity of 47.50 GiB of which 80.56 MiB is free. Process 71279 has 47.42 GiB memory in use. Of the allocated memory 46.80 GiB is allocated by PyTorch, and 288.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)`
