### ISSUE TITLE
IndexError in Experiment planning stage

### ISSUE THREAD

**Issue by asanudeep** [MIC-DKFZ/nnUNet#2092]
Hello everyone, 

I have used nn-UNet for couple of projects before but I have never faced any issue, untill this time. I wanted to train on simple [White Blood Cells](https://www.nature.com/articles/s41598-021-04426-x) Segmentation dataset. The dataset consists of .bmp images for WBCs and segmentation masks for nucleus and cytoplasm, both of shape 575x575. I created the proper format and stored it in nnUNet_raw directory. 

After this step, I had run 
```
nnUNetv2_plan_and_preprocess -d 14 --verify_dataset_integrity
```

Fingerprint extraction and dataset integrity was completed without any error. But I got the following error in Experiment planning

```
Fingerprint extraction...
Dataset014_RaabinWBC
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> reader/writer

####################
verify_dataset_integrity Done. 
If you didn't see any error messages then your dataset is most likely OK!
####################

Experiment planning...
Traceback (most recent call last):
  File "/home/anudeep/miniconda3/envs/nnUNet/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/anudeep/snap/DeepClustering4OSR/nnUNet/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 186, in plan_and_preprocess_entry
    plans_identifier = plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "/home/anudeep/snap/DeepClustering4OSR/nnUNet/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 86, in plan_experiments
    _, plans_identifier = plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb,
  File "/home/anudeep/snap/DeepClustering4OSR/nnUNet/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 70, in plan_experiment_dataset
    ret = planner.plan_experiment()
  File "/home/anudeep/snap/DeepClustering4OSR/nnUNet/nnUNet/nnunetv2/experiment_planning/experiment_planners/default_experiment_planner.py", line 424, in plan_experiment
    fullres_spacing_transposed = fullres_spacing[transpose_forward]
IndexError: index 2 is out of bounds for axis 0 with size 2

```

I would be grateful if someone could help me out!

Also if I should attach anything else please let me know.

**Comment by Lars-Kraemer** [comment]
Hey @asanudeep ,

difficult to find the error using only the error message. Can you share your dataset.json?

Best,
Lars

**Comment by mhmodgad** [comment]
Hi @asanudeep, Did you solve it? if so, can you share the solution please?
