### ISSUE TITLE
I found a bug on nnUNetv2_convert_MSD_dataset.

### ISSUE THREAD

**Issue by deepsea920415** [MIC-DKFZ/nnUNet#2097]
I installed nnunet v2 with "pip install nnunetv2".
And downloaded MSD task_4 and task_5 datasets.
And then, I tried to convert them with nnUNetv2_convert_MSD_dataset command.

This is what I used.
"nnUNetv2_convert_MSD_dataset -i 'D:/Projects/dental/proj/NNUNet/RawData/Task04_Hippocampus'"

And the result error was:

Traceback (most recent call last):
  File "C:\Users\TY\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\TY\.pyenv\pyenv-win\versions\3.10.11\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\TY\.pyenv\pyenv-win\versions\3.10.11\Scripts\nnUNetv2_convert_MSD_dataset.exe\__main__.py", line 7, in <module>
  File "D:\Projects\dental\proj\NNUNet\nnUNet\nnunetv2\dataset_conversion\convert_MSD_dataset.py", line 128, in entry_point
    convert_msd_dataset(args.i, args.overwrite_id, args.np)
  File "D:\Projects\dental\proj\NNUNet\nnUNet\nnunetv2\dataset_conversion\convert_MSD_dataset.py", line 49, in convert_msd_dataset
    assert isdir(labelsTr), f"labelsTr subfolder missing in source folder"
AssertionError: labelsTr subfolder missing in source folder

Also, I uninstalled nnunetv2 and used second way(git clone).
But in that case, that command still didn't working.
Finally, I went into the convert_MSD_dataset.py file and manually changed __main__() part.
It was worked.
Please fix this bug.

**Comment by constantinulrich** [comment]
Hi, i tried to reproduce the bug, but for me it was working. What did change to make it work for you?

**Comment by deepsea920415** [comment]
I used convert_MSD_dataset.py manually.
There, __main__ part is like "convert_msd_dataset('/home/fabian/Downloads/Task05_Prostate', overwrite_target_id=201)".
So, I changed path and used that script.

**Comment by constantinulrich** [comment]
Okay, thank you. The expected way to use is:  nnUNetv2_convert_MSD_dataset -i Path
Directly calling main is just for internal development/debugging.

**Comment by deepsea920415** [comment]
I'll try it.
Thank you.
