### ISSUE TITLE
How to evaluate test data

### ISSUE THREAD

**Issue by w378441719** [MIC-DKFZ/nnUNet#213]
Thank you for your great job. After prediction, I want to evaluate the result, such as the dice score. How can I do it. Thank you.

**Comment by FabianIsensee** [comment]
You can use this: https://github.com/MIC-DKFZ/nnUNet/blob/b38c69b345b2f60cd0d053039669e8f988b0c0af/nnunet/evaluation/evaluator.py#L446

**Comment by FabianIsensee** [comment]
please explain in detail what you did. nnU-Net v1 or v2?

**Comment by i-moes** [comment]
Sorry. I am still working with nnUNet v1. 

The error occurs when using the advanced computation metrics. 

I now run in on a different device after re-installing v1.
When using the advanced metrics it results in:

Traceback (most recent call last):
  File "/Users/irismoes/opt/anaconda3/envs/diep/bin/nnUNet_evaluate_folder", line 8, in <module>
    sys.exit(nnunet_evaluate_folder())
  File "/Users/irismoes/opt/anaconda3/envs/diep/lib/python3.9/site-packages/nnunet/evaluation/evaluator.py", line 484, in nnunet_evaluate_folder
    return evaluate_folder(args.ref, args.pred, args.l)
  File "/Users/irismoes/opt/anaconda3/envs/diep/lib/python3.9/site-packages/nnunet/evaluation/evaluator.py", line 460, in evaluate_folder
    res = aggregate_scores(test_ref_pairs, json_output_file=join(folder_with_predictions, "summary.json"),
  File "/Users/irismoes/opt/anaconda3/envs/diep/lib/python3.9/site-packages/nnunet/evaluation/evaluator.py", line 361, in aggregate_scores
    all_res = p.map(run_evaluation, zip(test, ref, [evaluator]*len(ref), [metric_kwargs]*len(ref)))
  File "/Users/irismoes/opt/anaconda3/envs/diep/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/irismoes/opt/anaconda3/envs/diep/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by FabianIsensee** [comment]
Hey, the current v1 branch doesn't have any more np.bool in it. You can thus just reinstall/pull that. `pip install --upgrade nnunet` should do the trick as well in case you have not installed it from source
