### ISSUE TITLE
Multiprocessing Error

### ISSUE THREAD

**Issue by serg-bg** [MIC-DKFZ/nnUNet#2134]
Hi, 

I am trying to use the updated nnU-Net ResEncL. I am running the code on Windows 10 with a RTX4090 GPU. I continue to get the error below but am having trouble identifying a solution. Any help would be appreciated! 

Exception ignored in: <function NonDetMultiThreadedAugmenter.__del__ at 0x00000210127A3920>
Traceback (most recent call last):
  File "C:\Users\Windows\anaconda3\envs\spinepipe\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 253, in __del__
    self._finish()
  File "C:\Users\Windows\anaconda3\envs\spinepipe\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 238, in _finish
    self.abort_event.set()
  File "C:\Users\Windows\anaconda3\envs\spinepipe\Lib\multiprocessing\synchronize.py", line 345, in set
    self._cond.notify_all()
  File "C:\Users\Windows\anaconda3\envs\spinepipe\Lib\multiprocessing\synchronize.py", line 304, in notify_all
    self.notify(n=sys.maxsize)
  File "C:\Users\Windows\anaconda3\envs\spinepipe\Lib\multiprocessing\synchronize.py", line 279, in notify
    assert not self._wait_semaphore.acquire(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 6] The handle is invalid

**Comment by Kobalt93** [comment]
Hi serg-bg,
This is a Batchgenerators issue. nnUNet uses Batchgenerators' multithreaded augmenter, which is currently experimental on Windows. You can find
more details here: https://github.com/MIC-DKFZ/batchgenerators?tab=readme-ov-file#windows-support-is-very-experimental,
an example of the modification here: https://github.com/MIC-DKFZ/batchgenerators/issues/23
and try to modify your code accordingly.
Feel free to reopen this issue if you need further assistance.

**Comment by serg-bg** [comment]
Hi Balint, 

Thank you so much for messaging me about this issue! It now makes sense. I will try to adapt the code as you suggest below and re-try a training round with the new nnU-Net ResEnc. Will definitely reach back out if I get stuck again. 

Best, 

Sergio
