### ISSUE TITLE
RuntimeError: Background label not declared (remember that this should be label 0!)

### ISSUE THREAD

**Issue by lu711003** [MIC-DKFZ/nnUNet#2156]
Traceback (most recent call last):
  File "/home/lyh/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/lyh/anaconda3/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 146, in run_case_save
    data, seg, properties = self.run_case(image_files, seg_file, plans_manager, configuration_manager, dataset_json)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 139, in run_case
    data, seg = self.run_case_npy(data, seg, data_properties, plans_manager, configuration_manager,
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 95, in run_case_npy
    label_manager = plans_manager.get_label_manager(dataset_json)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/utilities/plans_handling/plans_handler.py", line 314, in get_label_manager
    return self.label_manager_class(label_dict=dataset_json['labels'],
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/utilities/label_handling/label_handling.py", line 24, in __init__
    self._sanity_check(label_dict)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/utilities/label_handling/label_handling.py", line 53, in _sanity_check
    raise RuntimeError('Background label not declared (remember that this should be label 0!)')
RuntimeError: Background label not declared (remember that this should be label 0!)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lyh/nnUNet-master/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 204, in <module>
    plan_and_preprocess_entry()
  File "/home/lyh/nnUNet-master/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 200, in plan_and_preprocess_entry
    preprocess(args.d, plans_identifier, args.c, np, args.verbose)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 153, in preprocess
    preprocess_dataset(d, plans_identifier, configurations, num_processes, verbose)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 131, in preprocess_dataset
    preprocessor.run(dataset_id, c, plans_identifier, num_processes=n)
  File "/home/lyh/anaconda3/lib/python3.9/site-packages/nnunetv2/preprocessing/preprocessors/default_preprocessor.py", line 255, in run
    r[_].get()  # allows triggering errors
  File "/home/lyh/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
RuntimeError: Background label not declared (remember that this should be label 0!)

Where do I need to make the modifications?

**Comment by lu711003** [comment]
I have declared the value of “background” as 0 in dataset.json.
But it doesn't work.

**Comment by mehnaz1985** [comment]
I am facing the same problem
![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/cf21cea9-e1f7-4a4f-9ee8-a067771d0a8c)
and i have declared the value of background as 0 in dataset.json
![image](https://github.com/MIC-DKFZ/nnUNet/assets/66414863/71671679-20f8-4e4d-80d9-99b27667b6c2)

**Comment by mehnaz1985** [comment]
@lu711003 any updates?

**Comment by lu711003** [comment]
> @lu711003 any updates?

maybe you should turn  "0":"background"  into  "background": 0

**Comment by mehnaz1985** [comment]
@lu711003: Is your problem solved by this strategy?

**Comment by lu711003** [comment]
> @lu711003: Is your problem solved by this strategy?

yes

**Comment by mehnaz1985** [comment]
@lu711003 Thanks, it works!

**Comment by FabianIsensee** [comment]
Thanks @lu711003 !

**Comment by chuxinZ** [comment]
Unexpected and successful solution!
