### ISSUE TITLE
ValueError: Integers to negative integer powers are not allowed.

### ISSUE THREAD

**Issue by seg123456** [MIC-DKFZ/nnUNet#216]
Hi Fabian! Thanks for your nnUNet!
I got a trouble when I Experiment Planning and Preprocessing.  
RuntimeWarning: divide by zero encountered in log
  network_numpool_per_axis = np.floor([np.log(i / min_feature_map_size) / np.log(2) for i in patch_size]).astype(int)
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 228, in <module>
    plan_and_preprocess(t, processes, no_preprocessing)
  File "experiment_planning/plan_and_preprocess_task.py", line 134, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "/home/Desktop/nnUNnt/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 251, in plan_experiment
    num_modalities, len(all_classes) + 1))
  File "/home/Desktop/nnUNnt/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 190, in get_properties_for_stage
    CSSE_UNet.MAX_NUMPOOL_3D, current_spacing)
  File "/home/Desktop/nnUNnt/nnunet/experiment_planning/common_utils.py", line 83, in get_pool_and_conv_props_poolLateV2
    must_be_divisible_by = get_shape_must_be_divisible_by(num_pool_per_axis)
  File "/home/Desktop/nnUNnt/nnunet/experiment_planning/common_utils.py", line 195, in get_shape_must_be_divisible_by
    return 2 ** np.array(net_numpool_per_axis)
ValueError: Integers to negative integer powers are not allowed.

I want to know how to solve the problem.
Thanks a lot!

**Comment by FabianIsensee** [comment]
Is there some whay I can reproduce this error? Maybe you can provide all the inputs to the `get_properties_for_stage` function? Otherwise there is not much I can do

**Comment by seg123456** [comment]
Hi fabian,

     Thank you for your letter.
     I reprocessed my data, and there was a new problem.
I'm using DATA in MRI format.
There was a problem when I preprocessed my data：
Traceback (most recent call last):
  File "experiment_planning/plan_and_preprocess_task.py", line 236, in <module>
    plan_and_preprocess(task, processes, no_preprocessing)
  File "experiment_planning/plan_and_preprocess_task.py", line 134, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "/home/zhengsc/Desktop/mri-colon-nnuent/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 223, in plan_experiment
    use_nonzero_mask_for_normalization = self.determine_whether_to_use_mask_for_norm()
  File "/home/zhengsc/Desktop/mri-colon-nnuent/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 337, in determine_whether_to_use_mask_for_norm
    if "CT" in modalities[i]:
KeyError: 0

**Comment by seg123456** [comment]
Hi Fabian!
I don't have this problem with the new nnunet preprocessing.But when i use the older version , get
“ File "/raid/zhengsc/Desktop/ok-nnunet/nnunet/experiment_planning/common_utils.py", line 195, in get_shape_must_be_divisible_by
    return 2 ** np.array(net_numpool_per_axis)
ValueError: Integers to negative integer powers are not allowed.
” 
and I used MRI Colon data.
Can I pre-process it with the new Version of Nnunet, training with the old version of nnunet?
Best wish!

**Comment by FabianIsensee** [comment]
It makes sense to use the newest version. If that works, then there is no problem ;-)
