### ISSUE TITLE
Only 1 modality, but nnUNET reads it as 3

### ISSUE THREAD

**Issue by Alice715324** [MIC-DKFZ/nnUNet#2177]
For the life of me I cannot figure this one out. nnUnet reads my nii.gz file as 3 modalities when it should read it as 1. Anyone encounter this?

**Comment by felixkrones** [comment]
Could this be related to issue #2017 ?

**Comment by seziegler** [comment]
Hi @Alice715324 ,

can you please share your `dataset.json` and the commands you used for preprocessing and training? 
What is the error you're seeing?

Best,
Sebastian

**Comment by casami3** [comment]
I'm having the same problem but with .png format. My .json file looks is:

{"channel_names": {"0": "XAG"}, "labels": {"background": 0, "stenosis": 1}, "numTraining": 1300, "file_ending": ".png"}

And the error that I get on the Prompt is: 

Error: Unexpected number of modalities.
Expected: 1.
Got: 3.
Images: ['C:/Users/joanc/OneDrive/Escritorio/UPF/curs2trim3/AABI/proy/nnUNet_raw\\Dataset004_Stenosis\\imagesTr\\Stenosis_1022_0000.png']

Error: Unexpected number of modalities.
Expected: 1.
Got: 3.
Images: ['C:/Users/joanc/OneDrive/Escritorio/UPF/curs2trim3/AABI/proy/nnUNet_raw\\Dataset004_Stenosis\\imagesTr\\Stenosis_1229_0000.png']

Error: Unexpected number of modalities.
Expected: 1.
Got: 3.
Images: ['C:/Users/joanc/OneDrive/Escritorio/UPF/curs2trim3/AABI/proy/nnUNet_raw\\Dataset004_Stenosis\\imagesTr\\Stenosis_1025_0000.png']

Error: Unexpected number of modalities.
Expected: 1.
Got: 3.
Images: ['C:/Users/joanc/OneDrive/Escritorio/UPF/curs2trim3/AABI/proy/nnUNet_raw\\Dataset004_Stenosis\\imagesTr\\Stenosis_1230_0000.png']

Traceback (most recent call last):
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\joanc\anaconda3\envs\aaib\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 184, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "C:\Users\joanc\anaconda3\envs\aaib\lib\site-packages\nnunetv2\experiment_planning\verify_dataset_integrity.py", line 220, in verify_dataset_integrity
    raise RuntimeError(
RuntimeError: Some images have errors. Please check text output above to see which one(s) and what's going on.

**Comment by seziegler** [comment]
Hi @casami3 ,

for rgb images you need to specify `"channel_names": {0: 'R', 1: 'G', 2: 'B'}` in your dataset.json. 
You can see an example [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/dataset_conversion/Dataset120_RoadSegmentation.py).
There is also a side note in the documentation [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md#what-do-training-cases-look-like).

Best,
Sebastian
