### ISSUE TITLE
Error occurred when following pretraining_and_finetuning tutorial

### ISSUE THREAD

**Issue by yy042** [MIC-DKFZ/nnUNet#2195]
Hello. Thank you for your amazing work.
I got a problem when I try to fine tune a pretrained model on my personal dataset(Dataset020). Following the steps in documentation/pretraining_and_finetuning.md, I have finished pretraining on Dataset040_KiTS19 successfully. But when I try to run the last order `nnUNetv2_train TARGET_DATASET CONFIG FOLD -pretrained_weights PATH_TO_CHECKPOINT`, as I run `nnUNetv2_train 20 3d_fullres 0 -pretrained_weights D:\nnUNet\nnUNetFrame\nnUNet_results\Dataset040_KiTS19\nnUNetTrainer__custom_plan1__3d_fullres\fold_all\checkpoint_best.pth`, an error occured:

>  File "D:\nnUNet\nnunetv2\run\run_training.py", line 46, in get_trainer_from_args
    assert issubclass(nnunet_trainer, nnUNetTrainer), 'The requested nnunet trainer class must inherit from ' \
AssertionError: The requested nnunet trainer class must inherit from nnUNetTrainer

It's odd because I've been strictly follow the instructions in documentation/pretraining_and_finetuning.md, and I have never changed the structure of my nnU-Net. 
I would appreciate it if you could point out what I have done is wrong. Thank you for your support!

**Comment by seziegler** [comment]
Hi @yy042 ,
can you please share all the commands you used when following the pretraining steps?

One thing you could try is setting your checkpoint path in quotation marks like this:
`nnUNetv2_train TARGET_DATASET CONFIG FOLD -pretrained_weights PATH_TO_CHECKPOINT, as I run nnUNetv2_train 20 3d_fullres 0 -pretrained_weights "D:\nnUNet\nnUNetFrame\nnUNet_results\Dataset040_KiTS19\nnUNetTrainer__custom_plan1__3d_fullres\fold_all\checkpoint_best.pth"`

Best,
Sebastian

**Comment by yy042** [comment]
Thank you for your reply! I've tried setting checkpoint path in quotation marks, but the same error occurred again.
Here are the commands I used when following the pretraining tutorial:

`source dataset`-Dataset040_KiTS19
`target dataset`-Dataset020_KidneyTumor

1. `nnUNetv2_plan_and_preprocess -d 20`
2. `nnUNetv2_extract_fingerprint -d 40`
3. `nnUNetv2_move_plans_between_datasets -s 20 -t 40 -sp nnUNetPlans -tp custom_plan1`
4. `nnUNetv2_preprocess -d 40 -plans_name custom_plan1`
5. `nnUNetv2_train 40 3d_fullres all -p custom_plan1`
6. `nnUNetv2_train 20 3d_fullres 0 -pretrained_weights "D:\nnUNet\nnUNetFrame\nnUNet_results\Dataset040_KiTS19\nnUNetTrainer__custom_plan1__3d_fullres\fold_all\checkpoint_best.pth"` -AssertionError: The requested nnunet trainer class must inherit from nnUNetTrainer

**Comment by yy042** [comment]
Hi, I've changed to another device and run the exactly same orders, now there's no more `AssertionError: The requested nnunet trainer class must inherit from nnUNetTrainer`, the process was smooth until the Epoch 0 training began: new errors occurred as follows↓

> 2024-05-20 01:47:02.738993: Epoch 0
2024-05-20 01:47:02.745988: Current learning rate: 0.01
using pin_memory on device 0
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [70,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [71,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [72,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [73,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [74,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [75,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [36,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [37,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [38,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [39,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [40,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [41,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [42,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\cuda\ScatterGatherKernel.cu:367: block: [3981,0,0], thread: [43,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\nnunet39\Scripts\nnUNetv2_train.exe\__main__.py", line 7, in <module>
  File "G:\nnUNet\nnunetv2\run\run_training.py", line 268, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "G:\nnUNet\nnunetv2\run\run_training.py", line 204, in run_training
    nnunet_trainer.run_training()
  File "G:\nnUNet\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1302, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "G:\nnUNet\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 917, in train_step
    l = self.loss(output, target)
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\nnUNet\nnunetv2\training\loss\deep_supervision.py", line 30, in forward
    return sum([weights[i] * self.loss(*inputs) for i, inputs in enumerate(zip(*args)) if weights[i] != 0.0])
  File "G:\nnUNet\nnunetv2\training\loss\deep_supervision.py", line 30, in <listcomp>
    return sum([weights[i] * self.loss(*inputs) for i, inputs in enumerate(zip(*args)) if weights[i] != 0.0])
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\nnUNet\nnunetv2\training\loss\compound_losses.py", line 50, in forward
    dc_loss = self.dc(net_output, target_dice, loss_mask=mask) \
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\nnUNet\nnunetv2\training\loss\dice.py", line 93, in forward
    sum_gt = y_onehot.sum(axes) if loss_mask is None else (y_onehot * loss_mask).sum(axes)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "C:\ProgramData\Anaconda3\envs\nnUNet39\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

could you give me some suggestions on solving this problem? Thank you for reading this.

**Comment by seziegler** [comment]
Hi @yy042 ,

can you try running the train command when adding `-tr nnUNetTrainer`?

**Comment by U-ma-s** [comment]
I had the same error problem. The cause was that the nnUNetTrainer class was loaded from a different module. (In my case, it was due to the custom nnUNetTrainer class being created in a separate file).

This can be confirmed by describing `
print(f'nnunet_trainer: {nnunet_trainer.__module__}’)
print(f'nnUNetTrainer: {nnunetTrainer.__module__}')
`
before the  `assert issubclass(nnunet_trainer, nnUNetTrainer), The requested nnunet trainer class must inherit from ' \ ' nnUNetTrainer'` in run_training.py
