### ISSUE TITLE
 error happened, when running nnUNet_plan_and_preprocess using my own data

### ISSUE THREAD

**Issue by rongrongxiangxin** [MIC-DKFZ/nnUNet#221]
1. My own data, chest CT, lung region segmentation labeled by 3D slicer.
2. Like MSD dataset, set my own data as Task069_Lung.
3. The step "nnUNet_convert_decathlon_task" is OK, but running "nnUNet_plan_and_preprocess", the error as follows:

$ nnUNet_plan_and_preprocess -t 069 --verify_dataset_integrity

Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Verifying training set
checking case 1515031574
checking case 1515031574
Traceback (most recent call last):
  File "/dev/disk1/environments/nnunet_env/bin/nnUNet_plan_and_preprocess", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()
  File "/dev/disk1/environments/nnunet_env/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 77, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/dev/disk1/environments/nnunet_env/nnUNet/nnunet/preprocessing/sanity_checks.py", line 128, in verify_dataset_integrity
    nii_files_in_imagesTr.remove(os.path.basename(i))
ValueError: list.remove(x): x not in list

**Comment by rongrongxiangxin** [comment]
solved
