### ISSUE TITLE
Inference with pretrained data 

### ISSUE THREAD

**Issue by selayav** [MIC-DKFZ/nnUNet#2215]
I'm trying to use pretrained data (using version 1, since I saw version 2 does not infer using pretrained models yet). I'm able to set the environment variables, but when running `nnUNet_download_pretrained_model Task001_BrainTumour`, I run into the following error: 
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

######################################################
!!!!!!!!!!!!!!!!!!!!!!!!WARNING!!!!!!!!!!!!!!!!!!!!!!!
######################################################
Using the pretrained model weights is subject to the license of the dataset they were trained on. Some allow commercial use, others don't. It is your responsibility to make sure you use them appropriately! Use nnUNet_print_pretrained_model_info(task_name) to see a summary of the dataset and where to find its license!
######################################################

Downloading pretrained model from url: https://zenodo.org/record/4003545/files/Task001_BrainTumour.zip?download=1
Traceback (most recent call last):
  File "/opt/anaconda3/bin/nnUNet_download_pretrained_model", line 8, in <module>
    sys.exit(download_by_name())
             ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.11/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 344, in download_by_name
    download_and_install_pretrained_model_by_name(taskname)
  File "/opt/anaconda3/lib/python3.11/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 260, in download_and_install_pretrained_model_by_name
    download_and_install_from_url(url)
  File "/opt/anaconda3/lib/python3.11/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 288, in download_and_install_from_url
    raise e
  File "/opt/anaconda3/lib/python3.11/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 283, in download_and_install_from_url
    download_file(url=url, local_filename=tempfile, chunk_size=8192 * 16)
  File "/opt/anaconda3/lib/python3.11/site-packages/nnunet/inference/pretrained_models/download_pretrained_model.py", line 299, in download_file
    r.raise_for_status()
  File "/opt/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.**HTTPError: 404 Client Error: Not Found for url: https://zenodo.org/record/4003545/files/Task001_BrainTumour.zip?download=1**

How would I fix this?

**Comment by seziegler** [comment]
Hi @selayav ,
the link seems to work fine, you could download it manually or try to run the automatic download with another device.
