### ISSUE TITLE
Inability to train nnUNet with CPU and Windows

### ISSUE THREAD

**Issue by amspsingh04** [MIC-DKFZ/nnUNet#2219]
Hi, I am trying to train nnUNet using the Colon Cancer dataset used in MSD, I have completed the preprocessing tasks and have configured the dataset into the format recommended by nnUNet v2 documentation and conversion guide

when I execute this command:
`nnUNetv2_train 10 2d 3 -device 'cpu'`
i run into the following error

Error generated:
```
2024-05-24 14:13:27.332666: Using torch.compile...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\spsin\anaconda3\Scripts\nnUNetv2_train.exe\__main__.py", line 7, in <module>
  File "E:\CoCaDe\nnUNet\nnunetv2\run\run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "E:\CoCaDe\nnUNet\nnunetv2\run\run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "E:\CoCaDe\nnUNet\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1338, in run_training
    self.on_train_start()
  File "E:\CoCaDe\nnUNet\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 885, in on_train_start
    self.initialize()
  File "E:\CoCaDe\nnUNet\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 221, in initialize
    self.network = torch.compile(self.network)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spsin\anaconda3\Lib\site-packages\torch\__init__.py", line 1820, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\spsin\anaconda3\Lib\site-packages\torch\_dynamo\eval_frame.py", line 753, in optimize
    check_if_dynamo_supported()
  File "C:\Users\spsin\anaconda3\Lib\site-packages\torch\_dynamo\eval_frame.py", line 702, in check_if_dynamo_supported
    raise RuntimeError("Windows not yet supported for torch.compile")
RuntimeError: Windows not yet supported for torch.compile
Exception ignored in: <function NonDetMultiThreadedAugmenter.__del__ at 0x0000014F1A10B240>
Traceback (most recent call last):
  File "C:\Users\spsin\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 253, in __del__
    self._finish()
  File "C:\Users\spsin\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 238, in _finish
    self.abort_event.set()
  File "C:\Users\spsin\anaconda3\Lib\multiprocessing\synchronize.py", line 343, in set
    self._flag.acquire(False)
OSError: [WinError 6] The handle is invalid
Exception ignored in: <function NonDetMultiThreadedAugmenter.__del__ at 0x0000014F1A10B240>
Traceback (most recent call last):
  File "C:\Users\spsin\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 253, in __del__
    self._finish()
  File "C:\Users\spsin\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 238, in _finish
    self.abort_event.set()
  File "C:\Users\spsin\anaconda3\Lib\multiprocessing\synchronize.py", line 343, in set
    self._flag.acquire(False)
OSError: [WinError 6] The handle is invalid
```

Training log file:
> 2024-05-24 14:12:55.947247: do_dummy_2d_data_aug: False 
> 2024-05-24 14:12:55.951257: Using splits from existing split file: E:\CoCaDe\nnUNet\nnUnet_preprocessed\Dataset010_Colon\splits_final.json 
> 2024-05-24 14:12:55.964268: The split file contains 5 splits. 
> 2024-05-24 14:12:55.971258: Desired fold for training: 3 
> 2024-05-24 14:12:55.976279: This split has 101 training and 25 validation cases. 
> 2024-05-24 14:13:27.332666: Using torch.compile... 

im using pytorch installation as one based on cpu (no cuda, no gpu) on windows
i installed pytorch using this statement: pip3 install torch torchvision torchaudio

kindly do help me resolve this issue

**Comment by FabianIsensee** [comment]
Seems like we didn't test this thoroughly enough. Should be fixed now in the current master. We disable torch.compile if the device is CPU.
Please note that we do not recommend training on CPU as this is frustratingly slow!

**Comment by amspsingh04** [comment]
sounds good, @FabianIsensee can i work with the current master because it says checks have failed, do let me know if there would be any problem. cheers

**Comment by Lai-shixuan** [comment]
hi, i met the same problem in windows11 and using cuda on 3060 GPU. I installed nnuNet using pip, and the version is nnunetv2 2.4.2. I believe that torch.compile may not suit for windows at all, not just windows and training on cpu.

You can see the website here: [Investigate torch.compile Windows support. · Issue #122094 · pytorch/pytorch](https://github.com/pytorch/pytorch/issues/122094). It seems that torch.compile need a module called triton, and it do not support windows.

**Comment by amspsingh04** [comment]
That is weird, and to navigate the same i have since shifted from windows to linux. but ig it is very limiting for torch as a whole.
Thank you for letting me know
