### ISSUE TITLE
nnUNetv2_plan_and_preprocess_TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ABMRI** [MIC-DKFZ/nnUNet#2222]
Dear nnUNet Developer,

Thank you for your outstanding work on this project.

I am currently encountering an issue while attempting to configure the Residual Encoder. Below is the command I executed and the corresponding error message:

nnUNetv2_plan_and_preprocess -d 199 -pl L
Fingerprint extraction...
Dataset199_pre_with_T2
Using <class 'nnunetv2.imageio.simpleitk_reader_writer.SimpleITKIO'> as reader/writer
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3422/3422 [02:37<00:00, 21.74it/s]
Experiment planning...
Traceback (most recent call last):
  File "/home/chang/anaconda3/envs/GBM/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chang/anaconda3/envs/GBM/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 188, in plan_and_preprocess_entry
    plans_identifier = plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chang/anaconda3/envs/GBM/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 94, in plan_experiments
    _, plans_identifier = plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/chang/anaconda3/envs/GBM/lib/python3.11/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 65, in plan_experiment_dataset
    planner = experiment_planner_class(dataset_id,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

Could you please provide any insights or suggestions to resolve this issue?

Thank you in advance for your assistance.
-Edward

**Comment by mtoan65** [comment]
I also have the same error:

Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 188, in plan_and_preprocess_entry
    plans_identifier = plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 98, in plan_experiments
    _, plans_identifier = plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 68, in plan_experiment_dataset
    planner = experiment_planner_class(dataset_id,
TypeError: 'NoneType' object is not callable

**Comment by GregorKoehler** [comment]
Hi @ABMRI and @mtoan65,
looking at [this link](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunetv2/experiment_planning/experiment_planners/resencUNet_planner.py), it seems that the correct name for the planner should be ` ResEncUNetPlanner`. Can you confirm you still encounter this error when you're using the correct planner name?

**Comment by mtoan65** [comment]
I've also been able to run this command successfully, thank you for your support.

**Comment by GregorKoehler** [comment]
I'm glad we could resolve your issue!

Concerning the training command, please check the documentation here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md#scaling-resenc-nnu-net-beyond-the-presets

If you use the `-overwrite_plans_name` flag to rename the plans name, make sure to use the name you chose for the plans when starting your training.

As the original issue has been resolved, I'm closing this issue.
