### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer Killed

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#225]
Hi Fabian
When I was training my data recently, I had the following problem:
Traceback (most recent call last):
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/connection.py", line 455, in accept
    deliver_challenge(c, self._authkey)
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/connection.py", line 729, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/zhengsc/anaconda3/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Killed

How can I solve it?Type -c after the training command to continue.Did this error affect the training results?
nnUNet_train 2d nnUNetTrainerV2 Taskxxx_xxx4  -c

**Comment by FabianIsensee** [comment]
You are running out of memory. This is (unfortunately) a known issue with mixed precision training on the 2d network. Please train with --fp32

You can continue with -c. This will not have adverse effects on performance :-)

**Comment by AManHasNoName12138** [comment]
> You are running out of memory. This is (unfortunately) a known issue with mixed precision training on the 2d network. Please train with --fp32
> 
> You can continue with -c. This will not have adverse effects on performance :-)

Hi Fabian, why does this issue occur only trainning on 2d network?
