### ISSUE TITLE
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

### ISSUE THREAD

**Issue by Malitha123** [MIC-DKFZ/nnUNet#2265]
Hi,
When I try following command I get this issue. I googled and some suggested to downgrade  Simple ITK. but it did not work

`CUDA_VISIBLE_DEVICES=0 nnUNetv2_plan_and_preprocess -d 128 --verify_dataset_integrity`

"""
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 34, in verify_labels
    seg, properties = rw.read_seg(label_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 115, in read_seg
    return self.read_images((seg_fname, ))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/imageio/simpleitk_reader_writer.py", line 37, in read_images
    itk_image = sitk.ReadImage(f)
                ^^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/Virtual_ENV/hpc/lib64/python3.11/site-packages/SimpleITK/extra.py", line 375, in ReadImage
    return reader.Execute()
           ^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/Virtual_ENV/hpc/lib64/python3.11/site-packages/SimpleITK/SimpleITK.py", line 8430, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:2016:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hpc/mgun939/Virtual_ENV/hpc/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/hpc/mgun939/newNNU/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 204, in verify_dataset_integrity
    result = p.starmap(
             ^^^^^^^^^^
  File "/usr/lib64/python3.11/multiprocessing/pool.py", line 375, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/multiprocessing/pool.py", line 774, in get
    raise self._value
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /tmp/SimpleITK-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:2016:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by seziegler** [comment]
Hi @Malitha123 ,
what version of SimpleITK do you have?

**Comment by Malitha123** [comment]
I am using SimpleITK 2.3.1 currently and that is where I face the issue.

**Comment by seziegler** [comment]
Hi, I see that you're using python 3.11, could you try it with python 3.10?
