### ISSUE TITLE
[Errno 13] Permission denied: '.../nnUnet_datasets/nnUNet_preprocessed/Task099_Covid19/nnUNetData_plans_v2.1_stage1/covid19_006.npy'

### ISSUE THREAD

**Issue by Karol-G** [MIC-DKFZ/nnUNet#227]
Hi,

I tried training the model on my own dataset. However at epoch 68 I get the following error:
````python
2020-06-10 20:27:05.730335:
epoch:  68
2020-06-10 20:34:08.297657: train loss : -0.2923
Exception in background worker 4:
 [Errno 13] Permission denied: '/gris/gris-f/homelv/me/datasets/covid19/nnUnet_datasets/nnUNet_preprocessed/Task099_Covid19/nnUNetData_plans_v2.1_stage1/covid19_006.npy'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/threading.py", line 870, in run
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 102, in results_loop
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/queues.py", line 116, in get
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 502, in Client
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/multiprocessing/connection.py", line 629, in SocketClient
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/bin/nnUNet_train", line 11, in <module>
  File "/gris/gris-f/homelv/me/remote_projects/nnUNet/nnunet/run/run_training.py", line 142, in main
  File "/gris/gris-f/homelv/me/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 387, in run_training
  File "/gris/gris-f/homelv/me/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
  File "/gris/gris-f/homelv/me/remote_projects/nnUNet/nnunet/training/network_training/network_trainer.py", line 456, in run_training
  File "/gris/gris-f/homelv/me/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 228, in run_iteration
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 203, in __next__
  File "/gris/gris-f/homelv/me/anaconda3/envs/pytorch/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed
````
I believe the  ` [Errno 13] Permission denied: '/gris/gris-f/homelv/me/datasets/covid19/nnUnet_datasets/nnUNet_preprocessed/Task099_Covid19/nnUNetData_plans_v2.1_stage1/covid19_006.npy'` part is the real error. However the file does exists and the error happened at epoch 68, so the file got probably accessed quite a lot already. So in the end I have no idea why it suddenly throws this error.

Best
Karol

**Comment by FabianIsensee** [comment]
Hi,
strange. Please try to delete all npy files in that folder and try to continue the training with the `-c` option.
Also please don't use anaconda, we had issues with that in the past (not this one, though)
Best,
Fabian

**Comment by Karol-G** [comment]
Hi again,

ok I did what you said but to no avail. To be sure that the error does not originate from the dataset I used the medical decathlon lung dataset 006 with the exact same result. I looked into the logs and noticed that nnUNet crashed each time after about 10 hours (I tested it 3 times now in total).
Any ideas why this could be?

Best
Karol

**Comment by jk-blacker** [comment]
Hi ,
I try to do this: nnUNet_plan_and_preprocess -t Task001_Lung --verify_dataset_integrity, but I got the following error:

> Traceback (most recent call last):
  File "/home/jk/anaconda3/envs/dl/bin/nnUNet_plan_and_preprocess", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')()
  File "/home/jk/anaconda3/envs/dl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jk/anaconda3/envs/dl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/home/jk/anaconda3/envs/dl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2453, in load
    return self.resolve()
  File "/home/jk/anaconda3/envs/dl/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2459, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jk/python/nnUNet-master/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 18, in <module>
    from nnunet.experiment_planning.DatasetAnalyzer import DatasetAnalyzer
  File "/home/jk/python/nnUNet-master/nnunet/experiment_planning/DatasetAnalyzer.py", line 19, in <module>
    from nnunet.paths import nnUNet_raw_data, nnUNet_cropped_data
  File "/home/jk/python/nnUNet-master/nnunet/paths.py", line 36, in <module>
    maybe_mkdir_p(nnUNet_raw_data)
  File "/home/jk/anaconda3/envs/dl/lib/python3.7/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 41, in maybe_mkdir_p
    os.mkdir(os.path.join("/", *splits[:i+1]))
PermissionError: [Errno 13] Permission denied: '/media/fabian'

Could you tell me how to solve this?

**Comment by FabianIsensee** [comment]
Hi,
please read the documentation:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md

You need to set your own paths for nnU-Net, not copy mine...
Best,
Fabian

**Comment by FabianIsensee** [comment]
> Hi again,
> 
> ok I did what you said but to no avail. To be sure that the error does not originate from the dataset I used the medical decathlon lung dataset 006 with the exact same result. I looked into the logs and noticed that nnUNet crashed each time after about 10 hours (I tested it 3 times now in total).
> Any ideas why this could be?
> 
> Best
> Karol

I don't know what can cause this, this seems to be an issue with your system. Is that maybe a network drive or something?

**Comment by Karol-G** [comment]
Hi,

yeah, it's most likely not the nnUNet. I asked my supervisor today about the problem and as it turns out it is propably a time restriction active on the server I used. 
Thank you for your quick help though!

Best
Karol

**Comment by jk-blacker** [comment]
> Hi,
> please read the documentation:
> https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md
> 
> You need to set your own paths for nnU-Net, not copy mine...
> Best,
> Fabian

Hi 
 I know where the error is，Thank you for your help！

Best 
JK

**Comment by FabianIsensee** [comment]
> Hi,
> 
> yeah, it's most likely not the nnUNet. I asked my supervisor today about the problem and as it turns out it is propably a time restriction active on the server I used.
> Thank you for your quick help though!
> 
> Best
> Karol

I strongly recommend you use a local SSD for training, not a network drive. Network drives (unless it's a really high performance one) have high access latency and may cause bad epoch times.
Best,
Fabian

**Comment by Karol-G** [comment]
I believe the drive is an SSD. I am connected via ssh to the server, so the nnUNet is running locally on the server (with the SSD). But as the server has to be shared between multiple people the administrators seem to have introduced a time limitation on executed jobs (similar to the 12 hour limitation on google colab). 
Best
Karol
