### ISSUE TITLE
Using ResEnc

### ISSUE THREAD

**Issue by Beemd** [MIC-DKFZ/nnUNet#2279]
I wanted to try using the new presets using the following commands, but it gives me an error. Can you please guide me on where I went wrong and what is this error about?
nnUNetv2_plan_and_preprocess -d 503 -pl nnUNetPlannerResEncL
nnUNetv2_plan_and_preprocess -d 503 -pl nnUNetPlannerResEncL -gpu_memory_target 32

Error:
Fingerprint extraction...
Dataset503_NatGeSM_
Experiment planning...
Traceback (most recent call last):
  File "/home/80024222/miniconda3/envs/nnUNet/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/80024222/projects/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 186, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "/home/80024222/projects/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 82, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "/home/80024222/projects/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 61, in plan_experiment_dataset
    return experiment_planner_class(dataset_id,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by toufiqmusah** [comment]
using `ResEncUNetPlanner` inplace of `nnUNetPlannerResEncL` worked for me. 

And to run training, `!nnUNetv2_train ID 2d/3d all -p nnUNetPlannerResEnc`

Not sure how to set number of epochs though.

**Comment by constantinulrich** [comment]
did this already solved the problem?

**Comment by constantinulrich** [comment]
should be already [there](https://github.com/MIC-DKFZ/nnUNet/blob/2eaa371317c55e22bf5166428315076a1ba9b7af/nnunetv2/experiment_planning/experiment_planners/residual_unets/residual_encoder_unet_planners.py#L247)
