### ISSUE TITLE
RuntimeError: Some background workers are no longer alive

### ISSUE THREAD

**Issue by mtoan65** [MIC-DKFZ/nnUNet#2281]
Dear @FabianIsensee and team: I encountered into this (or at least a related) issue with "RuntimeError: Some background workers are no longer alive" (including the whole error log below just for reference). To clarify, I'm running the validation code on Google colab (GPU L4 and nnUNetv2 version 2.4.2):

```
!nnUNetv2_train 001 2d 0 --npz --val
```

# Full error log below:

############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-06-11 14:24:56.063429: Using torch.compile...
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
2024-06-11 14:25:25.826511: Creating new 5-fold cross-validation split...
2024-06-11 14:25:25.836390: Desired fold for training: 0
2024-06-11 14:25:25.840555: This split has 64 training and 16 validation cases.
2024-06-11 14:25:25.846818: predicting 003
2024-06-11 14:25:28.630884: 003, shape torch.Size([1, 285, 363, 488]), rank 0
2024-06-11 14:26:07.882504: predicting 005
2024-06-11 14:26:12.618663: 005, shape torch.Size([1, 312, 575, 575]), rank 0
2024-06-11 14:27:07.648258: predicting 007
2024-06-11 14:27:12.135971: 007, shape torch.Size([1, 317, 536, 536]), rank 0
Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 214, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1190, in perform_actual_validation
    proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
    raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive

# When I try to run this command again:
2024-06-11 14:33:06.579502: Using torch.compile...
/usr/local/lib/python3.10/dist-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "
2024-06-11 14:33:10.179716: Using splits from existing split file: /content/nnUNet_Dataset/nnUNet_preprocessed/Dataset001_PengwinTask01/splits_final.json
2024-06-11 14:33:10.190123: The split file contains 5 splits.
2024-06-11 14:33:10.194519: Desired fold for training: 0
2024-06-11 14:33:10.199502: This split has 64 training and 16 validation cases.
2024-06-11 14:33:10.204264: predicting 003
2024-06-11 14:33:12.647058: 003, shape torch.Size([1, 285, 363, 488]), rank 0
2024-06-11 14:33:40.411766: predicting 005
2024-06-11 14:33:44.344859: 005, shape torch.Size([1, 312, 575, 575]), rank 0
2024-06-11 14:34:36.240836: predicting 007
2024-06-11 14:34:39.508949: 007, shape torch.Size([1, 317, 536, 536]), rank 0
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 138, in _serve
    with self._listener.accept() as conn:
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 466, in accept
    answer_challenge(c, self._authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/run/run_training.py", line 214, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1190, in perform_actual_validation
    proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
    raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive

**Comment by aymuos15** [comment]
This looks like a colab timeout.

**Comment by mtoan65** [comment]
Hi @ykirchhoff and @aymuos15, 

As I found, nnUNet has some steps that require multiprocessing or something like that, and it seems this error occured in during one of those steps. I trained successfully nnUNet 2d, 3dlowres and 3d fullress on colab but when I tried to execute validation commandline for all three models, I encountered the same error. Additionally, the colab session at that time was not timeout or had any unusual signs.

**Comment by mtoan65** [comment]
Hello, I just encountered this error again while performing validation on a vast.ai instance (GPU RTX 3090 and nnUNetv2 version 2.4.2)

# Full error log below:
File "/opt/conda/bin/nnUNetv2_train", line 8, in
sys.exit(run_training_entry())
File "/opt/conda/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 274, in run_training_entry
run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
File "/opt/conda/lib/python3.10/site-packages/nnunetv2/run/run_training.py", line 214, in run_training
nnunet_trainer.perform_actual_validation(export_validation_probabilities)
File "/opt/conda/lib/python3.10/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1190, in perform_actual_validation
proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
File "/opt/conda/lib/python3.10/site-packages/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive

# When I try to run validation again:
Bus error (core dumped)
root@C.11195783:~$ Process SpawnPoolWorker-38:
Traceback (most recent call last):
File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 131, in worker
put((job, i, result))
File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 377, in put
self._writer.send_bytes(obj)
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
self._send_bytes(m[offset:offset + size])
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
self._send(header + buf)
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
self.run()
File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.10/multiprocessing/pool.py", line 136, in worker
put((job, i, (False, wrapped)))
File "/opt/conda/lib/python3.10/multiprocessing/queues.py", line 377, in put
self._writer.send_bytes(obj)
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 200, in send_bytes
self._send_bytes(m[offset:offset + size])
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 411, in _send_bytes
self._send(header + buf)
File "/opt/conda/lib/python3.10/multiprocessing/connection.py", line 368, in _send
n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by ykirchhoff** [comment]
Hi @mtoan65,

yes that is correct nnUNet uses multiprocessing quite frequently, especially for dataloading and prediction. In the actual validation nnUNet predicts the validation cases, which are then exported by background processes. I assume that colab and vast.ai both kill one of these background workers either due to CPU or OOM problems. You can try to change the `default_num_processes` parameter, which should help with these kind of issues. This can be done by either setting `os.environ["nnUNet_def_n_proc"] = x` if you call it in a Notebook, or using `nnUNet_def_n_proc=x nnUNet_train ...` in the command itself. The default value is 8 so choose something smaller than 8 for x (maybe start with 4 and see if that works).
Hope that already fixes the issue.

Best,
Yannick

**Comment by mtoan65** [comment]
I noticed that this error occurs only during the 2D nnUNet evaluation process. When I ran the evaluation for 3dfullres and 3dlowres models, they worked fine. Here are all the commands I ran:

## For preparing dataset:
```
nnUNetv2_plan_and_preprocess -d 001 --verify_dataset_integrity
```

## For training nnUNet 2d:
```
nnUNetv2_train 001 2d 0 --npz
```

## For training nnUNet 3dfullres:
```
nnUNetv2_train 001 3d_fullres 0 --npz
```

## For training nnUNet 3dlowres:
```
nnUNetv2_train 001 3d_lowres 0 --npz
```

**Comment by ykirchhoff** [comment]
Prediction with the 2d network is significantly faster than for the 3d networks, therefore the load for the workers is a lot higher, which then likely leads to colab/vast.ai killing the workers due to resource limitations. The only way around this is reducing the number of workers.

Best,
Yannick

**Comment by mtoan65** [comment]
I've just completed a segmentation challenge competition and confirmed that your solution works for me, , thanks so much for supporting @ykirchhoff ❤

**Comment by ykirchhoff** [comment]
Great to hear that!
