### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by guanjinquan** [MIC-DKFZ/nnUNet#2295]
I executed the following command, but found an Import Error:
```
git clone git@github.com:MIC-DKFZ/nnUNet.git
conda create -n HNC python=3.10
conda activate HNC  # activate my environment
pip install -e .
nnUNetv2_plan_and_preprocess -d 18--verify_dataset_integrity
nnUNetv2_train 18 3d_fullres 0
```
Error was found:
```
Traceback (most recent call last):  File "/home/Guanjq/miniconda3/envs/HNC/bin/nnUNetv2_train", line 5, in <module>
    from nnunetv2.run.run_training import run_training_entry
  File "/home/Guanjq/Work/HNC_SEG/nnUNet/nnunetv2/run/run_training.py", line 13, in <module>
    from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer
  File "/home/Guanjq/Work/HNC_SEG/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 25, in <module>
    from batchgeneratorsv2.transforms.nnunet.remove_connected_components import \
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/batchgeneratorsv2/transforms/nnunet/remove_connected_components.py", line 5, in <module>
    from acvl_utils.morphology.morphology_helper import label_with_component_sizes
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/acvl_utils/morphology/morphology_helper.py", line 7, in <module>
    import cc3d
Traceback (most recent call last):
  File "/home/Guanjq/miniconda3/envs/HNC/bin/nnUNetv2_train", line 5, in <module>
    from nnunetv2.run.run_training import run_training_entry
  File "/home/Guanjq/Work/HNC_SEG/nnUNet/nnunetv2/run/run_training.py", line 13, in <module>
    from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer
  File "/home/Guanjq/Work/HNC_SEG/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 25, in <module>
    from batchgeneratorsv2.transforms.nnunet.remove_connected_components import \
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/batchgeneratorsv2/transforms/nnunet/remove_connected_components.py", line 5, in <module>
    from acvl_utils.morphology.morphology_helper import label_with_component_sizes
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/acvl_utils/morphology/morphology_helper.py", line 7, in <module>
    import cc3d
  File "cc3d.pyx", line 1, in init cc3d
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```
 How can I solve this problem? Please help!

**Comment by guanjinquan** [comment]
Here is my conda list: 
```
 conda list
# packages in environment at /home/Guanjq/miniconda3/envs/HNC:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
acvl-utils                0.2                      pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
batchgenerators           0.25                     pypi_0    pypi
batchgeneratorsv2         0.1.1                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bzip2                     1.0.8                h5eee18b_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2024.3.11            h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
certifi                   2024.6.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
connected-components-3d   3.16.0                   pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dicom2nifti               2.4.11                   pypi_0    pypi
dynamic-network-architectures 0.3.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
fft-conv-pytorch          1.2.0                    pypi_0    pypi
filelock                  3.15.1                   pypi_0    pypi
fonttools                 4.53.0                   pypi_0    pypi
fsspec                    2024.6.0                 pypi_0    pypi
future                    1.0.0                    pypi_0    pypi
idna                      3.7                      pypi_0    pypi
imagecodecs               2024.6.1                 pypi_0    pypi
imageio                   2.34.1                   pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jinja2                    3.1.4                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.4.4                h6a678d5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgomp                   11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libuuid                   1.41.5               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
linecache2                1.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.9.0                    pypi_0    pypi
mkl                       2023.1.0         h213fc3f_46344    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               2.4.0           py310h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.3.8           py310h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.2.4           py310hdb19cb5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
networkx                  3.3                      pypi_0    pypi
nibabel                   5.2.1                    pypi_0    pypi
nnunetv2                  2.5                      pypi_0    pypi
numpy                     2.0.0                    pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.5.40                  pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
openssl                   3.0.14               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0            py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pydicom                   2.4.4                    pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
python                    3.10.14              h955ad1f_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.9.0.post0              pypi_0    pypi
python-gdcm               3.0.24.1                 pypi_0    pypi
python-graphviz           0.20.3                   pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
readline                  8.2                  h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.32.3                   pypi_0    pypi
scikit-image              0.23.2                   pypi_0    pypi
scikit-learn              1.5.0                    pypi_0    pypi
scipy                     1.13.1                   pypi_0    pypi
seaborn                   0.13.2                   pypi_0    pypi
setuptools                69.5.1          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
simpleitk                 2.3.1                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
sympy                     1.12.1                   pypi_0    pypi
tbb                       2021.8.0             hdb19cb5_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
theano                    1.0.5                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.5.22                pypi_0    pypi
tk                        8.6.14               h39e8969_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
torch                     2.3.1                    pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
traceback2                1.4.0                    pypi_0    pypi
triton                    2.3.1                    pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
unittest2                 1.1.0                    pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
wheel                     0.43.0          py310h06a4308_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xz                        5.4.6                h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yacs                      0.1.8                    pypi_0    pypi
zlib                      1.2.13               h5eee18b_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```

**Comment by guanjinquan** [comment]
I have searched this error online, but no one can work. 
I try to install `numpy` by using `conda install numpy`, but I encountered another error: 
```
Traceback (most recent call last):
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/numpy/_core/arrayprint.py", line 34, in <module>
    from . import numerictypes as _nt
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/numpy/_core/numerictypes.py", line 102, in <module>
    from ._type_aliases import (
  File "/home/Guanjq/miniconda3/envs/HNC/lib/python3.10/site-packages/numpy/_core/_type_aliases.py", line 38, in <module>
    allTypes[_abstract_type_name] = getattr(ma, _abstract_type_name)
AttributeError: module 'numpy.core.multiarray' has no attribute 'generic'
```

**Comment by guanjinquan** [comment]
I have solved this problem by changing the numpy version to 1.26 since I got warn from `import cc3d`
![image](https://github.com/MIC-DKFZ/nnUNet/assets/75822481/099e3cf6-2d79-48ce-aeb3-7befcfa13016)
So after I install `numpy=1.26`, this problem doesn't appear.

**Comment by geon6** [comment]
搜issue搜到老同学😄

**Comment by guanjinquan** [comment]
您好，我是关锦权，已收到您发送的邮件，谢谢！

**Comment by FabianIsensee** [comment]
Please don't force install numpy 1.X! Pytorch is no longer ocmpatible with it. Sole exception is if you are on an Intel Mac (https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/getting-started/installation-and-setup.md#3-install-nnu-net)

**Comment by guanjinquan** [comment]
您好，我是关锦权，已收到您发送的邮件，谢谢！
