### ISSUE TITLE
The latest version of nnUNetv2 encounters an error when setting deep supervision to False.

### ISSUE THREAD

**Issue by xingfengqwq** [MIC-DKFZ/nnUNet#2300]
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
             ^^^^^^^^^^^^^^^^^^^^
  File "/data/hd/code/nnUNet/nnunetv2/run/run_training.py", line 278, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/data/hd/code/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/data/hd/code/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1374, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hd/code/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1000, in train_step
    l = self.loss(output, target)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hd/code/nnUNet/nnunetv2/training/loss/compound_losses.py", line 50, in forward
    dc_loss = self.dc(net_output, target_dice, loss_mask=mask) \
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.conda/envs/nnunet/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/hd/code/nnUNet/nnunetv2/training/loss/dice.py", line 84, in forward
    if x.ndim != y.ndim:
                 ^^^^^^
AttributeError: 'list' object has no attribute 'ndim'

**Comment by xingfengqwq** [comment]
Using trainner  '-tr nnUNetTrainerNoDeepSupervision'.

**Comment by seziegler** [comment]
Hi @xingfengqwq ,
thanks for pointing this out! I could reproduce the error and we will fix it as soon as possible!

**Comment by FabianIsensee** [comment]
Fixed in master now. Thanks for bringing this to our attention!
