### ISSUE TITLE
background workers died, unable to find solution from other similar issues

### ISSUE THREAD

**Issue by Rahul-Narasimhan** [MIC-DKFZ/nnUNet#2310]
Hi Team, 

I see that others have faced this issue as well. I was unable to find a solution.
The 2d model was trained for 1000 epochs for just fold 0. It ran successfully.
I was able to run the best configuration and got the inference instructions.txt as well. 

When I tried to use the model to predict on unseen data, i use this command
nnUNetv2_predict -d Dataset777_TestData -i /folder1/nnUNet/nnUNet_raw/Dataset777_TestData/imagesTs -o /folder1/nnUNet/nnUNet_raw/Dataset777_TestData/imagesTs_predlowres -f 0 -tr nnUNetTrainer -c 2d -p nnUNetPlans

This is the error I get. Unfortunately, I was not able to figure out what could be the solution from the similar issues that was raised

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 47 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 47 cases that I would like to predict
Traceback (most recent call last):
  File "/my-conda-envs/nnunet/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 866, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 258, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 351, in predict_from_data_iterator
    for preprocessed in data_iterator:
  File "/nnUNet/nnunetv2/inference/data_iterators.py", line 111, in preprocessing_iterator_fromfiles
    raise RuntimeError('Background workers died. Look for the error message further up! If there is '
RuntimeError: Background workers died. Look for the error message further up! If there is none then your RAM was full and the worker was killed by the OS. Use fewer workers or get more RAM in that case!

**Comment by Rahul-Narasimhan** [comment]
@saikat-roy to give more context. The inference for the validation cases were all predicted during training and stored as well. But when I try to use the trained model to run inference on an unseen dataset, I get the background workers error. Could you please help ?

**Comment by lvbartow** [comment]
Hi @Rahul-Narasimhan , i keep getting this error too; did you find any solution ?
It runs well on my mac m1 pro in command line with -device cpu but when it comes to use it with Docker / linux-amd64 on a 32gb ram VM I can't get rid of this message !
Thanks

**Comment by zhaohb** [comment]
> Hi [@Rahul-Narasimhan](https://github.com/Rahul-Narasimhan) [@lvbartow](https://github.com/lvbartow) Just want to bud in and say that I am also having this issue when trying to run the` predict_from_modelfolder` function from a docker container. I tried the solutions proposed in [#2769](https://github.com/MIC-DKFZ/nnUNet/issues/2769) [#2297](https://github.com/MIC-DKFZ/nnUNet/issues/2297) [#2595](https://github.com/MIC-DKFZ/nnUNet/issues/2595) and [#2749](https://github.com/MIC-DKFZ/nnUNet/issues/2749) In the end I got it to work by using `--ipc=host` when starting up the Docker container.
> 
> Hopefully it will help someone!

thank you very much.
I also got it to work by using `--ipc=host` when starting up the Docker container.

**Comment by ruffsl** [comment]
Thanks for the heads up y'all; it seems that docker's `default-shm-size` is only `64MiB`, per the manual:

https://github.com/moby/moby/blob/f7ccfed3f3b91112950437fdd054930b2d4e39f1/man/dockerd.8.md?plain=1#L193-L194

This can be increased via the run arg `--shm-size=`, although `--ipc=host` is an approximate workaround.

https://docs.docker.com/engine/containers/run/

```
--shm-size=""	Size of /dev/shm. The format is <number><unit>. number must be greater than 0. Unit is optional and can be b (bytes), k (kilobytes), m (megabytes), or g (gigabytes). If you omit the unit, the system uses bytes. If you omit the size entirely, the system uses 64m.
```

**Comment by FabianIsensee** [comment]
Thanks for pointing to the documentation. This should help future users running into this issue!
Seems like this is resolved. I will close this for now. Feel free to post a new issue if something still doesn't work as it should
