### ISSUE TITLE
Unable to use ResEnc presets

### ISSUE THREAD

**Issue by ajojosephthomas** [MIC-DKFZ/nnUNet#2314]
I'm trying to use the preset resenc, however running into following error with the following command:
nnUNetv2_plan_and_preprocess -d 458  -pl nnUNetPlannerResEncL       
Fingerprint extraction...
Dataset458_Kidneys
Experiment planning...
Traceback (most recent call last):
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mdq23at\AppData\Local\Programs\Python\Python38\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>  
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 177, in plan_and_preprocess_entry
    plan_experiments(args.d, args.pl, args.gpu_memory_target, args.preprocessor_name, args.overwrite_target_spacing, args.overwrite_plans_name)
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", 
line 82, in plan_experiments
    plan_experiment_dataset(d, experiment_planner, gpu_memory_target_in_gb, preprocess_class_name,
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", 
line 61, in plan_experiment_dataset
    return experiment_planner_class(dataset_id,
TypeError: 'NoneType' object is not callable

I thought maybe because the data was already preprocessed, i could just command in 'plan experiment' but run into the following error where it requires a json file:

nnUNetv2_plan_experiment -d 458  -pl nnUNetPlannerResEncL   
  
Preprocessing dataset Dataset458_Kidneys
Traceback (most recent call last):
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\mdq23at\AppData\Local\Programs\Python\Python38\Scripts\nnUNetv2_plan_experiment.exe\__main__.py", line 7, in <module>      
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 97, in preprocess_entry
    preprocess(args.d, args.plans_name, configurations=args.c, num_processes=args.np, verbose=args.verbose)
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", 
line 127, in preprocess
    preprocess_dataset(d, plans_identifier, configurations, num_processes, verbose)
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\experiment_planning\plan_and_preprocess_api.py", 
line 105, in preprocess_dataset
    plans_manager = PlansManager(plans_file)
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\nnunetv2\utilities\plans_handling\plans_handler.py", line 
190, in __init__
    self.plans = plans_file_or_dict if isinstance(plans_file_or_dict, dict) else load_json(plans_file_or_dict)
  File "c:\users\mdq23at\appdata\local\programs\python\python38\lib\site-packages\batchgenerators\utilities\file_and_folder_operations.py", 
line 68, in load_json
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mdq23at\\nnUNet\\nnUNet_preprocessed\\Dataset458_Kidneys\\nnUNetPlannerResEncL.json'

**Comment by dengzhuohao** [comment]
i have the same question

**Comment by rooskraaijveld** [comment]
I have the same issue!

**Comment by GXcells** [comment]
How did you solve?
