### ISSUE TITLE
Problems encountered after training to 999 rounds：    RuntimeError: Some background workers are no longer alive

### ISSUE THREAD

**Issue by yuanlve** [MIC-DKFZ/nnUNet#2324]
2024-06-27 02:42:28.120952: Epoch 999
2024-06-27 02:42:28.121082: Current learning rate: 2e-05
2024-06-27 02:43:10.529340: train_loss -0.786
2024-06-27 02:43:10.529615: val_loss -0.6647
2024-06-27 02:43:10.530026: Pseudo dice [0.977, 0.9205, 0.8069, 0.6351, 0.5142, 0.4206, 0.9599, 0.411, 0.4653, 0.5818, 0.7952, 0.7334, 0.7709, 0.7579, 0.803, 0.8296, 0.8739, 0.8713, nan, nan, 0.7657, 0.7301, 0.7638, 0.7582, 0.7869, 0.782, 0.8446, 0.3474, nan, nan, 0.9256, 0.8984, 0.9334, 0.9227, 0.8638, 0.875, 0.8561, 0.8209, nan, nan, 0.9111, 0.9299, 0.9346, 0.9304, 0.924, 0.9021, 0.8781, 0.9027]
2024-06-27 02:43:10.530342: Epoch time: 42.41 s
2024-06-27 02:43:13.226687: Training done.
2024-06-27 02:43:13.493962: Using splits from existing split file: /home/yons/nnUNet/nnUNet_preprocessed/Dataset500_ToothFairy/splits_final.json
2024-06-27 02:43:13.496136: The split file contains 5 splits.
2024-06-27 02:43:13.496217: Desired fold for training: 1
2024-06-27 02:43:13.496272: This split has 384 training and 96 validation cases.
2024-06-27 02:43:13.497348: predicting ToothFairy2F_004
2024-06-27 02:43:13.508561: ToothFairy2F_004, shape torch.Size([1, 273, 410, 410]), rank 0
2024-06-27 02:43:56.989293: predicting ToothFairy2F_005
2024-06-27 02:43:57.010993: ToothFairy2F_005, shape torch.Size([1, 274, 410, 410]), rank 0
2024-06-27 02:44:23.460134: predicting ToothFairy2F_018
2024-06-27 02:44:23.500890: ToothFairy2F_018, shape torch.Size([1, 264, 410, 410]), rank 0
2024-06-27 02:44:48.855264: predicting ToothFairy2F_021
2024-06-27 02:44:48.886912: ToothFairy2F_021, shape torch.Size([1, 267, 410, 410]), rank 0
2024-06-27 02:45:14.571691: predicting ToothFairy2F_023
2024-06-27 02:45:14.610901: ToothFairy2F_023, shape torch.Size([1, 274, 410, 410]), rank 0
2024-06-27 02:45:40.251756: predicting ToothFairy2F_025
2024-06-27 02:45:40.292123: ToothFairy2F_025, shape torch.Size([1, 274, 410, 410]), rank 0
2024-06-27 02:46:07.460865: predicting ToothFairy2F_033
2024-06-27 02:46:07.503754: ToothFairy2F_033, shape torch.Size([1, 274, 410, 410]), rank 0
2024-06-27 02:46:33.653109: predicting ToothFairy2F_034
2024-06-27 02:46:33.690509: ToothFairy2F_034, shape torch.Size([1, 274, 410, 410]), rank 0
2024-06-27 02:47:00.338096: predicting ToothFairy2F_039
2024-06-27 02:47:00.371563: ToothFairy2F_039, shape torch.Size([1, 298, 512, 512]), rank 0
2024-06-27 02:47:31.092578: predicting ToothFairy2F_043
2024-06-27 02:47:31.122455: ToothFairy2F_043, shape torch.Size([1, 270, 410, 410]), rank 0
Traceback (most recent call last):
  File "/home/yons/anaconda3/envs/nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/yons/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/yons/nnUNet/nnunetv2/run/run_training.py", line 215, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/home/yons/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1265, in perform_actual_validation
    proceed = not check_workers_alive_and_busy(segmentation_export_pool, worker_list, results,
  File "/home/yons/nnUNet/nnunetv2/utilities/file_path_utilities.py", line 103, in check_workers_alive_and_busy
    raise RuntimeError('Some background workers are no longer alive')
RuntimeError: Some background workers are no longer alive

**Comment by ykirchhoff** [comment]
Hi @yuanlve,

sorry for the late reply. The error indicates that the training crashed in the final validation step. The rather generic error indicates that this is likely due to problems with your RAM. ToothFairy has rather large scans, which can be problematic during segmentation export and resampling, especially due to the large number of classes in the v2 dataset.
Could you run your training command with the `--val` flag and monitor your RAM usage? This will only run the validation step and should only take a few minutes until it crashes. I RAM is actually the issue you would need to reduce the number of workers in that step but let's first check that this is indeed the issue.

Best,
Yannick
