### ISSUE TITLE
SyntaxError: (unicode error) 'unicodeescape' codec When Training Model

### ISSUE THREAD

**Issue by sjanko2-vt** [MIC-DKFZ/nnUNet#2330]
Hello all,

Thank you for your hard work on this excellent tool for AI researchers and scientists alike. I'm attempting to train my first model on a Windows machine with a CPU and am running into the following error as training begins. I have bolded the error to make it more visible.

I have done some research on this issue over the last few days and had no luck finding a solution. According to Google and other forums, a SyntaxError associated with the unicode in the temporary file indicates an issue with the backslash character. I'm not sure how to resolve this as that temporary file is automatically generated.

$ **nnUNetv2_train 321 3d_fullres 2 -device 'cpu'**

############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cpu

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-06-28 11:57:43.469689: do_dummy_2d_data_aug: False
2024-06-28 11:57:43.473688: Using splits from existing split file: C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\nnUNetFrame\dataset\nnUNet_preprocessed\Dataset321_PigBrainsSA\splits_final.json
2024-06-28 11:57:43.480647: The split file contains 5 splits.
2024-06-28 11:57:43.488570: Desired fold for training: 2
2024-06-28 11:57:43.496581: This split has 5 training and 1 validation cases.
2024-06-28 11:58:04.440445: Using torch.compile...
C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\optim\lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

This is the configuration used by this training:
Configuration name: 3d_fullres
 {'data_identifier': 'nnUNetPlans_3d_fullres', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 2, 'patch_size': [160, 96, 160], 'median_image_size_in_voxels': [210.
0, 120.0, 210.0], 'spacing': [0.3333333432674408, 0.33000001311302185, 0.3333333432674408], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [False], 'r
esampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z
': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_da
ta_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dyna
mic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 6, 'features_per_stage': [32, 64, 128, 256, 320, 320], 'conv_op': 'torch.nn.modules.c
onv.Conv3d', 'kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]], 'strides': [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 1, 2]]
, 'n_conv_per_stage': [2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm3d', 'norm_op_
kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}, 'deep_supervision': True}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': False}

These are the global plan.json settings:
 {'dataset_name': 'Dataset321_PigBrainsSA', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [0.3333333432674408, 0.33000001311302185, 0.3333333432674408]
, 'original_median_shape_after_transp': [210, 120, 210], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [1, 0, 2], 'transpose_backward': [1, 0, 2], 'experiment_pl
anner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 53095.93359375, 'mean': 15091.646484375, 'median': 13681.625, 'min': 98.28585815429688, 'percentile_00_5': 5191.55419921875, 'percentile_99_5': 32341.51171875, 'std': 6200.67626953125}}}

2024-06-28 11:58:04.990923: unpacking dataset...
2024-06-28 11:58:05.635889: unpacking done...
2024-06-28 11:58:05.652578: Unable to plot network architecture: nnUNet_compile is enabled!
2024-06-28 11:58:05.710472: 
2024-06-28 11:58:05.719432: Epoch 0
2024-06-28 11:58:05.731467: Current learning rate: 0.01
Traceback (most recent call last):
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\Scripts\nnUNetv2_train.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\nnunetv2\run\run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\nnunetv2\run\run_training.py", line 210, in run_training
    nnunet_trainer.run_training()
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1295, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 922, in train_step
    output = self.network(data)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\eval_frame.py", line 451, in _fn
    return fn(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 921, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 786, in _convert_frame
    result = inner_convert(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 400, in _convert_frame_assert
    return _compile(
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 676, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 535, in compile_inner
    out_code = transform_code_object(code, transform)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1036, in transform_code_object
    transformations(instructions, code_options)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 165, in _fn
    return fn(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\convert_frame.py", line 500, in transform
    tracer.run()
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2149, in run
    super().run()
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 810, in run
    and self.step()
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 773, in step
    getattr(self, inst.opname)(inst)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2268, in RETURN_VALUE
    self.output.compile_subgraph(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1001, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1178, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1251, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\output_graph.py", line 1232, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\__init__.py", line 1731, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1330, in compile_fx
    return aot_autograd(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\backends\common.py", line 58, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 903, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_functorch\aot_autograd.py", line 628, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 443, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_functorch\_aot_autograd\runtime_wrappers.py", line 648, in aot_wrapper_synthetic_base    
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 352, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 1257, in fw_compiler_base
    return inner_compile(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\repro\after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 438, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\compile_fx.py", line 714, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\graph.py", line 1307, in compile_to_fn
    return self.compile_to_module().call
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_dynamo\utils.py", line 262, in time_wrapper
    r = func(*args, **kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\graph.py", line 1254, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\torch\_inductor\codecache.py", line 2154, in load_by_key_path
    **raise RuntimeError(
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Failed to import C:\Users\Sammy\AppData\Local\Temp\torchinductor_Sammy\g6\cg6uxe7tn4ynicp7ildzqpxvo25jhl3r7x5jtutxxdglxe2wy36p.py
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 13-14: truncated \UXXXXXXXX escape (cg6uxe7tn4ynicp7ildzqpxvo25jhl3r7x5jtutxxdglxe2wy36p.py, line 123)**

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop      
    raise e
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop      
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\Sammy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop      
    raise e
  File "C:\Users\Sammy\PycharmProjects\nnUNet_Sandbox3\venv\lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop      
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by amspsingh04** [comment]
I faced the issue of background workers no longer alive as well
you could do well by using GPU instead of a CPU and if possible, have atleast 16GB of free RAM in the memory to work it out 
additionally you could try killing any other invasive process running in the background
take a look at this 
https://gitlab.inria.fr/amasson/nnunet/-/blob/d39337eabc3263dc40c5bf3251eb2c44c73113b2/documentation/common_problems_and_solutions.md
the second subheading in here

**Comment by Karol-G** [comment]
Hey, training on a CPU is theoretically possible. In practice, however, you can expect training time of multiple months or years for a single training fold. I highly recommend to use a GPU.

**Comment by sjanko2-vt** [comment]
Hello folks,

Thank you for your response regarding this issue. As an update for anyone that might have similar problems in the future, I went ahead and moved all of my files to my desktop PC where I had a 1080TI. After running into some problems with compatibility (the 1080TI has a CUDA Compute Capability compatibility rating of 6.1 and Torch said I need something with > 6.5), I installed a 3080 into my PC. However, now I'm running into an issue with Triton at the same point in the training execution: 

```
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
RuntimeError: Cannot find a working triton installation. More information on installing Triton can be found at https://github.com/openai/triton

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
```

After doing a bit of research and investigating the [README.md file](https://github.com/triton-lang/triton/blob/main/README.md) for Triton, it is only compatible with Linux. However, [in installation instructions for nnUNet it says that it should work out of the box on Windows PCs](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md). 

Do I need to run nnUNet on Linux?

**Comment by FabianIsensee** [comment]
Triton does not ship with the windows installation of pytorch. This is why torch.compile (which requires it to be present) is disabled on windows be default now. Please install the most recent version of nnU-Net from the master: `pip install git+https://github.com/MIC-DKFZ/nnUNet.git`. Then everything should work.
Like @Karol-G said, training on CPU is a bad idea because it takes forever. Any GPU will do better! 1080ti is a bit old (no tensorcore acceleration) but 3080 should be fine
Best,
Fabian

**Comment by sjanko2-vt** [comment]
Thanks so much everyone! It is working now!
