### ISSUE TITLE
docker run

### ISSUE THREAD

**Issue by HuiLin0220** [MIC-DKFZ/nnUNet#2331]
When I docker run testing, I get this issue: No space left on device (28); but when I do Python run testing, it is fine. Are there any people who can kindly help me? Thank you! (num_processes_preprocessing=1, num_processes_segmentation_export=1)
------------------------error-----------------------------
There are 5 cases in the source folder

Predicting amos_0507:
done with amos_0507
Process SpawnProcess-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/nnunetv2/inference/data_iterators.py", line 58, in preprocess_fromfiles_save_to_queue
    raise e
  File "/workspace/nnunetv2/inference/data_iterators.py", line 50, in preprocess_fromfiles_save_to_queue
    target_queue.put(item, timeout=0.01)
  File "<string>", line 2, in put
  File "/usr/local/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/local/lib/python3.9/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/local/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/user/.local/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 568, in reduce_storage
    fd, size = storage._share_fd_cpu_()
  File "/home/user/.local/lib/python3.9/site-packages/torch/storage.py", line 304, in wrapper
    return fn(self, *args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/torch/storage.py", line 374, in _share_fd_cpu_
    return super()._share_fd_cpu_(*args, **kwargs)
RuntimeError: unable to write to file </torch_199_1620553159_0>: No space left on device (28)

**Comment by HuiLin0220** [comment]
Thanks! https://github.com/MIC-DKFZ/nnUNet/issues/2206
It was solved by docker run --shm-size XXgb(larger value)
