### ISSUE TITLE
nnUNetv1 TypeError issue

### ISSUE THREAD

**Issue by amspsingh04** [MIC-DKFZ/nnUNet#2341]
hello

i was running preprocessing of Task010_Colon raw data when I encountered this error, as it was cropping the files (ig?)

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/undergraduate/shourya/anaconda3/envs/cocade_hrnet/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/undergraduate/shourya/anaconda3/envs/cocade_hrnet/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/preprocessing/preprocessing.py", line 322, in _run_internal
    data, seg, properties = self.resample_and_normalize(data, target_spacing,
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/preprocessing/preprocessing.py", line 249, in resample_and_normalize
    data, seg = resample_patient(data, seg, np.array(original_spacing_transposed), target_spacing, 3, 1,
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/preprocessing/preprocessing.py", line 102, in resample_patient
    seg_reshaped = resample_data_or_seg(seg, new_shape, True, axis, order_seg, do_separate_z, cval=cval_seg,
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/preprocessing/preprocessing.py", line 150, in resample_data_or_seg
    reshaped_data.append(resize_fn(data[c, slice_id], new_shape_2d, order, cval=cval, **kwargs))
TypeError: resize_segmentation() got an unexpected keyword argument 'cval'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/undergraduate/shourya/anaconda3/envs/cocade_hrnet/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 128, in main
    exp_planner.run_preprocessing(threads)
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 441, in run_preprocessing
    preprocessor.run(target_spacings, self.folder_with_cropped_data, self.preprocessed_output_folder,
  File "/home/undergraduate/shourya/TransHRNet/nnUNet/nnunet/preprocessing/preprocessing.py", line 389, in run
    p.starmap(self._run_internal, all_args)
  File "/home/undergraduate/shourya/anaconda3/envs/cocade_hrnet/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/undergraduate/shourya/anaconda3/envs/cocade_hrnet/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: resize_segmentation() got an unexpected keyword argument 'cval'

```

before this i ran the command nnUNet_plan_and_preprocess -t 10

my variables are set properly and are as follows:

nnUNet_raw_data_base=/home/undergraduate/shourya/colon/nnUNet_raw_data_base
nnUNet_preprocessed=/home/undergraduate/shourya/colon/nnUNet_preprocessed
RESULTS_FOLDER=/home/undergraduate/shourya/colon/nnUNet_trained_models

nnUNet_raw_data_base has nnUNet_raw_data which has Task010_Colon which includes imagesTr, imagesTs, labelsTr, dataset.json

how can i complete the preprocessing? am i going wrong somewhere?

**Comment by Karol-G** [comment]
Are you using nnunetv1 or v2? I recommend using nnunetv2.

**Comment by amspsingh04** [comment]
This was on nnunetv1, i wanted to use Trans HR Net which extends the nnunetv1 preprocessing techniques and then proceeds to provide the requisite training pathway
I will see if i can use nnunetv2 with the same, ill try it out but i think it is not made for nnunetv2

**Comment by FabianIsensee** [comment]
Please install nnU-Net v1 from the current nnU-Net v1 branch: https://github.com/MIC-DKFZ/nnUNet/tree/nnunetv1
I just tested it and it works for me

**Comment by FabianIsensee** [comment]
`pip install git+https://github.com/MIC-DKFZ/nnUNet.git@nnunetv1`

**Comment by FabianIsensee** [comment]
Did that work for you?

**Comment by amspsingh04** [comment]
Yes it did, the preprocessing is still going on but it has started saving the npz and normalised files in the required nnUNet_preprocessed path with the following subdirectoried

![image](https://github.com/MIC-DKFZ/nnUNet/assets/93045361/2aa2e3f9-7ae9-4ef5-8c6c-4d383983205b)

**Comment by FabianIsensee** [comment]
Perfect :-)
