### ISSUE TITLE
IndexError: ‘index 26 is out of bounds for axis 0 with size 26’ after training on MPS device, model not saved

### ISSUE THREAD

**Issue by sahikabetul** [MIC-DKFZ/nnUNet#2383]
Hello, 

After training, and after predicting the dataset images, I got IndexError. My dataset including 12 training and 3 test images and labels. The error message has been produced after 12nd image. Because of that problem, despite the training has been finished,  the model is not saved.

My raw dataset structure same as suggested structure. Converted to nnUNet structure. I also runned dataset verification via this command, and corrected the mistakes. So, I don't think it caused from my dataset:

`nnUNetv2_plan_and_preprocess -d 666 --verify_dataset_integrity`

 The code that I am using for training process:

`nnUNetv2_train 666 2d all -p nnUNetPlansSpine -device mps -tr nnUNetTrainer_10epochs `

The error message:
```

2024-07-20 23:18:25.235026: unpacking done...
2024-07-20 23:18:25.244699: Unable to plot network architecture:
2024-07-20 23:18:25.246547: No module named 'hiddenlayer'
2024-07-20 23:18:25.277605: 
2024-07-20 23:18:25.279938: Epoch 0
2024-07-20 23:18:25.282348: Current learning rate: 0.01
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py:1044: RuntimeWarning: invalid value encountered in scalar divide
  global_dc_per_class = [i for i in [2 * i / (2 * i + j + k) for i, j, k in zip(tp, fp, fn)]]
2024-07-20 23:28:10.494386: train_loss 0.4936
2024-07-20 23:28:10.498129: val_loss 0.2855
2024-07-20 23:28:10.499977: Pseudo dice [np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-20 23:28:10.501816: Epoch time: 585.22 s
2024-07-20 23:28:10.503826: Yayy! New best EMA pseudo Dice: 0.0
2024-07-20 23:28:11.961117: 
2024-07-20 23:28:11.963388: Epoch 1
2024-07-20 23:28:11.965194: Current learning rate: 0.0091
2024-07-20 23:37:53.176200: train_loss 0.2361
2024-07-20 23:37:53.187152: val_loss 0.165
2024-07-20 23:37:53.195680: Pseudo dice [np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-20 23:37:53.251974: Epoch time: 581.22 s
2024-07-20 23:37:54.172962: 
2024-07-20 23:37:54.175742: Epoch 2
2024-07-20 23:37:54.177841: Current learning rate: 0.00818
2024-07-20 23:47:38.024999: train_loss 0.142
2024-07-20 23:47:38.026308: val_loss 0.0908
2024-07-20 23:47:38.029089: Pseudo dice [np.float32(0.0), np.float32(0.0175), np.float32(0.2913), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.6258), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-20 23:47:38.031622: Epoch time: 583.85 s
2024-07-20 23:47:38.033793: Yayy! New best EMA pseudo Dice: 0.005499999970197678
2024-07-20 23:47:39.316096: 
2024-07-20 23:47:39.316566: Epoch 3
2024-07-20 23:47:39.318655: Current learning rate: 0.00725
2024-07-20 23:57:21.485537: train_loss 0.0842
2024-07-20 23:57:21.487911: val_loss 0.0554
2024-07-20 23:57:21.497697: Pseudo dice [np.float32(0.0006), np.float32(0.0423), np.float32(0.3128), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.8645), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-20 23:57:21.506062: Epoch time: 582.17 s
2024-07-20 23:57:21.512560: Yayy! New best EMA pseudo Dice: 0.01209999993443489
2024-07-20 23:57:22.835561: 
2024-07-20 23:57:22.835871: Epoch 4
2024-07-20 23:57:22.838091: Current learning rate: 0.00631
2024-07-21 00:06:59.036105: train_loss 0.0536
2024-07-21 00:06:59.037666: val_loss 0.0135
2024-07-21 00:06:59.048433: Pseudo dice [np.float32(0.1339), np.float32(0.1727), np.float32(0.3657), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.8807), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:06:59.052185: Epoch time: 576.2 s
2024-07-21 00:06:59.060036: Yayy! New best EMA pseudo Dice: 0.019999999552965164
2024-07-21 00:07:00.333239: 
2024-07-21 00:07:00.335638: Epoch 5
2024-07-21 00:07:00.337388: Current learning rate: 0.00536
2024-07-21 00:16:36.923052: train_loss -0.0007
2024-07-21 00:16:36.934732: val_loss -0.0591
2024-07-21 00:16:36.942990: Pseudo dice [np.float32(0.1958), np.float32(0.0345), np.float32(0.4511), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.8998), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:16:36.947974: Epoch time: 576.59 s
2024-07-21 00:16:36.955770: Yayy! New best EMA pseudo Dice: 0.027300000190734863
2024-07-21 00:16:38.211440: 
2024-07-21 00:16:38.213857: Epoch 6
2024-07-21 00:16:38.215755: Current learning rate: 0.00438
2024-07-21 00:26:14.436854: train_loss -0.08
2024-07-21 00:26:14.448916: val_loss -0.1325
2024-07-21 00:26:14.455781: Pseudo dice [np.float32(0.3656), np.float32(0.3317), np.float32(0.4989), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.883), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:26:14.461033: Epoch time: 576.23 s
2024-07-21 00:26:14.467067: Yayy! New best EMA pseudo Dice: 0.03680000081658363
2024-07-21 00:26:15.763127: 
2024-07-21 00:26:15.765329: Epoch 7
2024-07-21 00:26:15.767034: Current learning rate: 0.00338
2024-07-21 00:35:52.626220: train_loss -0.1356
2024-07-21 00:35:52.630180: val_loss -0.189
2024-07-21 00:35:52.632497: Pseudo dice [np.float32(0.529), np.float32(0.6236), np.float32(0.3977), np.float32(0.0), np.float32(0.0872), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.898), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:35:52.634646: Epoch time: 576.86 s
2024-07-21 00:35:52.636826: Yayy! New best EMA pseudo Dice: 0.04809999838471413
2024-07-21 00:35:53.920485: 
2024-07-21 00:35:53.923115: Epoch 8
2024-07-21 00:35:53.924836: Current learning rate: 0.00235
2024-07-21 00:45:30.268207: train_loss -0.186
2024-07-21 00:45:30.279616: val_loss -0.2283
2024-07-21 00:45:30.287670: Pseudo dice [np.float32(0.7281), np.float32(0.7562), np.float32(0.4545), np.float32(0.0082), np.float32(0.5023), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.9145), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:45:30.296341: Epoch time: 576.35 s
2024-07-21 00:45:30.303141: Yayy! New best EMA pseudo Dice: 0.06310000270605087
2024-07-21 00:45:31.745094: 
2024-07-21 00:45:31.747323: Epoch 9
2024-07-21 00:45:31.748963: Current learning rate: 0.00126
2024-07-21 00:55:08.095404: train_loss -0.2213
2024-07-21 00:55:08.107355: val_loss -0.2494
2024-07-21 00:55:08.113922: Pseudo dice [np.float32(0.8652), np.float32(0.8642), np.float32(0.5754), np.float32(0.0067), np.float32(0.5891), np.float32(1e-04), np.float32(0.0), np.float32(0.0), np.float32(nan), np.float32(0.914), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(0.0), np.float32(nan)]
2024-07-21 00:55:08.119577: Epoch time: 576.35 s
2024-07-21 00:55:08.126232: Yayy! New best EMA pseudo Dice: 0.07919999957084656
2024-07-21 00:55:10.458365: Training done.
perform_everything_on_device=True is only supported for cuda devices! Setting this to False
2024-07-21 00:55:10.604099: predicting 112
2024-07-21 00:55:10.611278: 112, shape torch.Size([1, 24, 448, 448]), rank 0
2024-07-21 00:55:15.567606: predicting 113
2024-07-21 00:55:15.590546: 113, shape torch.Size([1, 26, 449, 450]), rank 0
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2024-07-21 00:55:24.675225: predicting 118
2024-07-21 00:55:24.692907: 118, shape torch.Size([1, 20, 482, 480]), rank 0
2024-07-21 00:55:31.133328: predicting 165
2024-07-21 00:55:31.147656: 165, shape torch.Size([1, 15, 448, 448]), rank 0
2024-07-21 00:55:33.602367: predicting 181
2024-07-21 00:55:33.616183: 181, shape torch.Size([1, 19, 422, 416]), rank 0
2024-07-21 00:55:36.701741: predicting 38
2024-07-21 00:55:36.716890: 38, shape torch.Size([1, 30, 456, 448]), rank 0
2024-07-21 00:55:41.589948: predicting 39
2024-07-21 00:55:41.605067: 39, shape torch.Size([1, 26, 451, 448]), rank 0
2024-07-21 00:55:45.838206: predicting 44
2024-07-21 00:55:45.855270: 44, shape torch.Size([1, 24, 448, 448]), rank 0
2024-07-21 00:55:49.741971: predicting 45
2024-07-21 00:55:49.757362: 45, shape torch.Size([1, 17, 480, 480]), rank 0
2024-07-21 00:55:55.279124: predicting 71
2024-07-21 00:55:55.304966: 71, shape torch.Size([1, 15, 448, 448]), rank 0
2024-07-21 00:55:57.754477: predicting 94
2024-07-21 00:55:57.771436: 94, shape torch.Size([1, 26, 450, 448]), rank 0
2024-07-21 00:56:01.993409: predicting 95
2024-07-21 00:56:02.007638: 95, shape torch.Size([1, 24, 448, 448]), rank 0
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/inference/export_prediction.py", line 88, in export_prediction_from_logits
    ret = convert_predicted_logits_to_segmentation_with_correct_shape(
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/inference/export_prediction.py", line 30, in convert_predicted_logits_to_segmentation_with_correct_shape
    predicted_logits = configuration_manager.resampling_fn_probabilities(predicted_logits,
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/preprocessing/resampling/default_resampling.py", line 121, in resample_data_or_seg_to_shape
    data_reshaped = resample_data_or_seg(data, new_shape, is_seg, axis, order, do_separate_z, order_z=order_z)
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/preprocessing/resampling/default_resampling.py", line 174, in resample_data_or_seg
    reshaped_here[slice_id] = resize_fn(data[c, :, :, slice_id], new_shape_2d, order, **kwargs)
IndexError: index 26 is out of bounds for axis 0 with size 26
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 274, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/run/run_training.py", line 214, in run_training
    nnunet_trainer.perform_actual_validation(export_validation_probabilities)
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1263, in perform_actual_validation
    _ = [r.get() for r in results]
  File "/Users/yayli.sahikabetul/Desktop/vestibularSchwannoma/spineSegm/.venv/lib/python3.9/site-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1263, in <listcomp>
    _ = [r.get() for r in results]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: index 26 is out of bounds for axis 0 with size 26
```

**Comment by sahikabetul** [comment]
I got this error when 2D trainings. I can complete training with 3D_highres images.

**Comment by TaWald** [comment]
Sorry for the late reply.
Is the issue still persisting or did you fix the issue already?
If you found the issue it would be great if you could share it and post your solution.

**Comment by TaWald** [comment]
Closing due to inactivity, feel free to reopen whenever
