### ISSUE TITLE
Error during nnUNet preprocessing with Brats2023 Dataset

### ISSUE THREAD

**Issue by mariem-m11** [MIC-DKFZ/nnUNet#2385]
**Environment:**
- OS: Windows

**Issue Description:**
While preprocessing the Brats2023 dataset using nnU-Net with the command `nnUNet_plan_and_preprocess -t 180 --verify_dataset_integrity`, the process successfully validates the training and test sets and labels. However after showing cropping logs I get this error

**Error Message:**
 Task180_BraTS2023
number of threads:  (8, 8)

C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
Are we using the nonzero mask for normalization? OrderedDict([(0, False), (1, False), (2, False), (3, False)])
Traceback (most recent call last):
  File "C:\Users\makni\anaconda3\envs\PFA\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\makni\anaconda3\envs\PFA\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\makni\anaconda3\envs\PFA\Scripts\nnUNet_plan_and_preprocess.exe\__main__.py", line 7, in <module>     
  File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
    exp_planner.plan_experiment()
  File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
    target_spacing = self.get_target_spacing()
  File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
    target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
  File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core\shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate

**Comment by constantinulrich** [comment]
Hi, it looks like you are using v1? 
Windows is only somewhat stable supported in v2.

Best 
Constantin
