### ISSUE TITLE
UnboundLocalError: local variable 'region_labels' referenced before assignment in "Region-based training"

### ISSUE THREAD

**Issue by Nastii22** [MIC-DKFZ/nnUNet#2397]
Hello,

I encountered the following error when running the command: 
```
TORCHDYNAMO_DISABLE=1 OMP_NUM_THREADS=1 CUDA_VISIBLE_DEVICES=0 nnUNetv2_train 200 3d_fullres 0 -tr nnUNetTrainer_250epochs
```
I get the error despite having installed batchgeneratorsv2, as suggested in the [#2181(comment)](https://github.com/MIC-DKFZ/nnUNet/issues/2181#issuecomment-2134541092).

**Error Message:**

############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-07-26 10:35:36.140049: do_dummy_2d_data_aug: True
2024-07-26 10:35:36.140597: Creating new 5-fold cross-validation split...
2024-07-26 10:35:36.143059: Desired fold for training: 0
2024-07-26 10:35:36.143115: This split has 39 training and 10 validation cases.
using pin_memory on device 0
Exception in background worker 0:
 local variable 'region_labels' referenced before assignment
Traceback (most recent call last):
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/training/dataloading/data_loader_3d.py", line 63, in generate_train_batch
    tmp = self.transforms(**{'image': data_all[b], 'segmentation': seg_all[b]})
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgeneratorsv2/transforms/base/basic_transform.py", line 18, in __call__
    return self.apply(data_dict, **params)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgeneratorsv2/transforms/utils/compose.py", line 13, in apply
    data_dict = t(**data_dict)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgeneratorsv2/transforms/base/basic_transform.py", line 18, in __call__
    return self.apply(data_dict, **params)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgeneratorsv2/transforms/base/basic_transform.py", line 67, in apply
    data_dict['segmentation'] = self._apply_to_segmentation(data_dict['segmentation'], **params)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgeneratorsv2/transforms/utils/seg_to_regions.py", line 17, in _apply_to_segmentation
    if isinstance(region_labels, int) or len(region_labels) == 1:
UnboundLocalError: local variable 'region_labels' referenced before assignment
Traceback (most recent call last):
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/bin/nnUNetv2_train", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_train')())
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1362, in run_training
    self.on_train_start()
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 903, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
  File "/mnt/nvme0n1p1/scratch/nnUNetFrame/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 696, in get_dataloaders
    _ = next(mt_gen_train)
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/mnt/nvme0n1p1/scratch/env_nnunetv2/lib64/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by Nastii22** [comment]
Hi @FabianIsensee  , @dojoh 
I wanted to follow up on my previous question. Could you kindly provide an update on my query? 
Thank you in advance.

**Comment by niubihonghong12345** [comment]
I’m experiencing the same issue. Have you fixed it?

**Comment by Nastii22** [comment]
> I’m experiencing the same issue. Have you fixed it?

Unfortunately, no!

**Comment by Nastii22** [comment]
upgrading batchgeneratorsv2 to 0.2, solved the issue.

**Comment by Nastii22** [comment]
upgrading batchgeneratorsv2 to 0.2, solved the issue.
