### ISSUE TITLE
MultiThreadedAugmenter crashes

### ISSUE THREAD

**Issue by mehrtash** [MIC-DKFZ/nnUNet#24]
Hi, I am trying to run the following experiment, but it crashes:
```
python -u run/run_training.py 3d_lowres nnUNetTrainer Task17_challenge2019 0 --ndet
```
I added export OMP_NUM_THREADS=1 to my .bashrc and also change numpy version to 1.14.5 but it is still unresolved.
```
stage:  1
{'batch_size': 2, 'num_pool_per_axis': [3, 5, 5], 'patch_size': array([ 48, 192, 192]), 'median_patient_size_in_voxels': array([137, 512, 512]), 'current_spacing': array([3.     , 0.78125, 0.78125]), 'original_spacing': array([3.     , 0.78125, 0.78125]), 'do_dummy_2D_data_aug': True, 'pool_op_kernel_sizes': [[1, 2, 2], [1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/mehrtash/nn_unet_data/preprocessing/nnUNet/Task17_challenge2019/nnUNet
###############################################
2019-06-30 09:52:52.244086: unpacking dataset
2019-06-30 09:52:52.374044: done
2019-06-30 09:52:54.762235:
epoch:  0
gpu 0
Exception in worker 1
Traceback (most recent call last):
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 46, in producer
    item = next(data_loader)
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/mehrtash/projects/nnUNet/nnunet/training/dataloading/dataset_loading.py", line 217, in generate_train_batch
    case_all_data = np.load(self._data[i]['data_file'][:-4] + ".npy", self.memmap_mode)
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/numpy/lib/npyio.py", line 418, in load
    return format.open_memmap(file, mode=mmap_mode)
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/numpy/lib/format.py", line 802, in open_memmap
    mode=mode, offset=offset)
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
Traceback (most recent call last):
  File "run/run_training.py", line 105, in <module>
    trainer.run_training()
  File "/home/mehrtash/projects/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 263, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/mehrtash/projects/nnUNet/nnunet/training/network_training/network_trainer.py", line 342, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/mehrtash/projects/nnUNet/nnunet/training/network_training/network_trainer.py", line 509, in run_iteration
    data_dict = next(data_generator)
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __next__
    item = self.__get_next_item()
  File "/home/mehrtash/anaconda3/envs/torch/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 172, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed
```

**Comment by FabianIsensee** [comment]
This happens when the unpacking of the data failed. Delete all the npy
files (not npz!) in the preprocessed data folder and try again. Make sure
you have enough disk space available.
Best,
Fabian

**Comment by mehrtash** [comment]
Thank you @FabianIsensee. Deleting the npys resolved the issue.

**Comment by FabianIsensee** [comment]
No worries! Glad I could help!
