### ISSUE TITLE
Error during inference

### ISSUE THREAD

**Issue by HaoLi12345** [MIC-DKFZ/nnUNet#2408]
Hi, 

I use this command for inference:
```
 nnUNetv2_predict -i /nnUNet_raw/Dataset001_Pathology/imagesTs -o /nnUNet/nnUNet_segmentations/ -c 2d -d 001 -f 0
```

However, I encountered this bug only with GPU mode; CPU works fine. Would you mind helping me figure out what's going on?

Please see below

```
#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

There are 1643 cases in the source folder
I am process 0 out of 1 (max process ID is 0, we start counting with 0!)
There are 1643 cases that I would like to predict

Predicting subject1:
perform_everything_on_device: True
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  4.77it/s]
sending off prediction to background worker for resampling and export
done with subject1

Predicting subject2:
perform_everything_on_device: True
Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/nnunet/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 883, in predict_entry_point
    predictor.predict_from_files(args.i, args.o, save_probabilities=args.save_probabilities,
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 258, in predict_from_files
    return self.predict_from_data_iterator(data_iterator, save_probabilities, num_processes_segmentation_export)
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 375, in predict_from_data_iterator
    prediction = self.predict_logits_from_preprocessed_data(data).cpu()
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/predict_from_raw_data.py", line 501, in predict_logits_from_preprocessed_data
    self.network.load_state_dict(params)
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PlainConvUNet:
        While copying the parameter named "encoder.stages.0.0.convs.0.norm.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([32]), an exception occurred : ('Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.',).
.
.
.
.
.
.
Many repeated 
.
.
.
.
.
.
 While copying the parameter named "decoder.stages.7.convs.1.all_modules.1.num_batches_tracked", whose dimensions in the model are torch.Size([]) and whose dimensions in the checkpoint are torch.Size([]), an exception occurred : ('Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.',).
Process SpawnProcess-22:
Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/data_iterators.py", line 59, in preprocess_fromfiles_save_to_queue
    raise e
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/data_iterators.py", line 50, in preprocess_fromfiles_save_to_queue
    target_queue.put(item, timeout=0.01)
  File "<string>", line 2, in put
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
Process SpawnProcess-20:
Traceback (most recent call last):
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/data_iterators.py", line 59, in preprocess_fromfiles_save_to_queue
    raise e
  File "/media/hao/mydrive/nnUNet/nnunetv2/inference/data_iterators.py", line 50, in preprocess_fromfiles_save_to_queue
    target_queue.put(item, timeout=0.01)
  File "<string>", line 2, in put
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/managers.py", line 810, in _callmethod
    kind, result = conn.recv()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/hao/anaconda3/envs/nnunet/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
     
```
I have checked #2364 or other similar Issues, but I didn't figure it out.
Thank you for helping!
Hao

**Comment by HaoLi12345** [comment]
Hi,

I found this issue is related to @torch.inference_mode(). However, I just found the predict_from_raw_data.py was updated 4days ago and removed this line. No bug with the newest version. Leave this here in case others meet this problem.
