### ISSUE TITLE
Overflow Error while downloading pretrained model

### ISSUE THREAD

**Issue by toashiqur** [MIC-DKFZ/nnUNet#242]
Hi Fabian,

I was trying to download a pretrained nnUNet model (`nnUNet_download_pretrained_model Task005_Prostate`) but got the `OverflowError: signed integer is greater than maximum.` How can I solve it? Please see below for detail.

System Configuration:
Geforce RTX 2080 Ti
Intel® Core™ i7-9700K CPU
Ubuntu 20.04 LTS
Python 3.8
Cuda 10.1

```
Downloading pretrained model https://zenodo.org/record/3734294/files/Task005_Prostate.zip?download=1
Traceback (most recent call last):
  File "/home/ashiqur/workstation/nnUNet_venv/bin/nnUNet_download_pretrained_model", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_download_pretrained_model')()
  File "/home/ashiqur/workstation/nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py", line 246, in download_by_name
    download_and_install_pretrained_model_by_name(taskname)
  File "/home/ashiqur/workstation/nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py", line 177, in download_and_install_pretrained_model_by_name
    download_and_install_from_url(av_models[taskname]['url'])
  File "/home/ashiqur/workstation/nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py", line 191, in download_and_install_from_url
    data = urlopen(url).read()
  File "/usr/lib/python3.8/http/client.py", line 467, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python3.8/http/client.py", line 608, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
OverflowError: signed integer is greater than maximum
```

Thanks in advance for your help.

**Comment by FabianIsensee** [comment]
Hi,
interesting. I had this error, too and thought I fixed it. This is because the file is very large.
For now, please download the model directly from Zenodo: https://zenodo.org/record/3734294
Then use `nnUNet_install_pretrained_model_from_zip` to install it.
Best,
Fabian

**Comment by toashiqur** [comment]
Thanks Fabian! Download from Zenodo worked.

**Comment by toashiqur** [comment]
Thanks Fabian! Download from Zenodo worked.
