### ISSUE TITLE
not using nonzero mask for normalization

### ISSUE THREAD

**Issue by mariem-m11** [MIC-DKFZ/nnUNet#2421]
Environment:
OS: Windows

Issue Description:
While preprocessing the Brats2023 dataset using nnU-Net with the command nnUNet_plan_and_preprocess -t 180 --verify_dataset_integrity, the process successfully validates the training and test sets and labels. However after showing cropping logs I get this error

Error Message:
Task180_BraTS2023
number of threads: (8, 8)

C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
ret = ret.dtype.type(ret / rcount)
not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
not using nonzero mask for normalization
Are we using the nonzero mask for normalization? OrderedDict([(0, False), (1, False), (2, False), (3, False)])
Traceback (most recent call last):
File "C:\Users\makni\anaconda3\envs\PFA\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\makni\anaconda3\envs\PFA\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\makni\anaconda3\envs\PFA\Scripts\nnUNet_plan_and_preprocess.exe_main.py", line 7, in
File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\nnUNet_plan_and_preprocess.py", line 159, in main
exp_planner.plan_experiment()
File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\experiment_planner_baseline_3DUNet.py", line 257, in plan_experiment
target_spacing = self.get_target_spacing()
File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\nnunet\experiment_planning\experiment_planner_baseline_3DUNet_v21.py", line 51, in get_target_spacing
target = np.percentile(np.vstack(spacings), self.target_spacing_percentile, 0)
File "C:\Users\makni\anaconda3\envs\PFA\lib\site-packages\numpy\core\shape_base.py", line 289, in vstack
return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate

**Comment by fgracia93** [comment]
Do you know what the issue ended up being? I am having the same thing happen, but with the hippocampus decathlon dataset.

**Comment by LOL1234LOL** [comment]
Excuse me how is this issue resolved, this is closed without furtherr reference
