### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by maggie-may-22** [MIC-DKFZ/nnUNet#2434]
Hi,
I have previously completed preprocessing, training and prediction and everything was working fine.

I have now created a new folder structure and restarted using different data. For some reason I am getting an error code that says the command is not found - i am doing the preprocessing and have tried both nnUNetv2_plan_and_preprocess and nnUNetv2_extract_fingerprint. I have also tried cloning the nnUNet repository as well as using as a standardised baseline.

Looking at the file paths in my image below, the folder named '001' contains 'data' folder, 'nnUNet' folder and the script I submitted.

For context, I have to run bash files through a HPC as my computer isn't powerful enough. I have attached a screenshot of my script and the error message.
<img width="632" alt="Bash file" src="https://github.com/user-attachments/assets/cf97b3ca-6b8b-4407-87d0-0f8a1a0ea4a4">
<img width="854" alt="Error" src="https://github.com/user-attachments/assets/5530cd05-f84f-4ef4-91bd-c8dd6c94e1dc">

**Comment by JackRio** [comment]
Try upgrading your pip and setuptools library and then install.

Read the whole error logs the issue is with old pip and setuptools versions most likely.

**Comment by maggie-may-22** [comment]
I am running through a HPC using the PuTTY SSH so I can't run any commands or upgrade directly from the terminal. I haven't been able to get the issue to go away and this is the only error file I get after running my script:

Collecting nnunetv2
  Using cached https://files.pythonhosted.org/packages/e9/76/b07d94295b8680333c267420cb8fe68780c1f0330b01f83de221e14398f8/nnunetv2-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data1/pbs.9829022.pbs/pip-build-MXkLvm/nnunetv2/setup.py", line 1, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name find_namespace_packages
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data1/pbs.9829022.pbs/pip-build-MXkLvm/nnunetv2/
You are using pip version 9.0.1, however version 24.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/var/spool/PBS/mom_priv/jobs/9829022.pbs.SC: line 18: nnUNetv2_plan_and_preprocess: command not found

Any ideas??

**Comment by saikat-roy** [comment]
Hi @maggie-may-22 , sorry for the very late reply. Are you still having this issue?
