### ISSUE TITLE
Not sure where this warning is coming from or what it means?

### ISSUE THREAD

**Issue by aymuos15** [MIC-DKFZ/nnUNet#2439]
```
############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0
/home/localssk23/backup/soumya/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py:163: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.grad_scaler = GradScaler() if self.device.type == 'cuda' else None
2024-08-10 12:06:25.018213: do_dummy_2d_data_aug: False
2024-08-10 12:06:25.018385: Using splits from existing split file: /home/localssk23/backup/soumya/nnUNet_Data/nnUNet_preprocessed/Dataset999_Dummy/splits_final.json
2024-08-10 12:06:25.018435: The split file contains 5 splits.
2024-08-10 12:06:25.018451: Desired fold for training: 0
2024-08-10 12:06:25.018464: This split has 8 training and 2 validation cases.
using pin_memory on device 0
using pin_memory on device 0
2024-08-10 12:06:25.828037: Using torch.compile...
/home/localssk23/backup/soumya/env/nnunet/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(

2024-08-10 12:06:26.518468: unpacking dataset...
2024-08-10 12:06:29.179959: unpacking done...
2024-08-10 12:06:29.180958: Unable to plot network architecture: nnUNet_compile is enabled!
2024-08-10 12:06:29.184165:
2024-08-10 12:06:29.184221: Epoch 0
2024-08-10 12:06:29.184302: Current learning rate: 0.01
W0810 12:06:31.980000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0810 12:06:32.021000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0810 12:06:32.062000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0810 12:06:33.870000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:34.218000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:34.565000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:34.592000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:35.022000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:35.070000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:35.332000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:35.554000 140120994833984 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0810 12:06:40.436000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0810 12:06:40.472000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
W0810 12:06:40.508000 140124163403776 torch/fx/experimental/symbolic_shapes.py:4449] [0/1] xindex is not in var_ranges, defaulting to unknown range.
```

Everything else is working fine.

**Comment by ykirchhoff** [comment]
Hi @aymuos15,

could you please set `nnUNet_compile` to false and see if that works? I had a similar issue recently, which was related to torch.compile (which `nnUNet_compile` uses). If disabling `nnUNet_compile` works, the issue might be resolved by updating all packages, including pytorch, but I am not sure about that.

Best,
Yannick

**Comment by Merom99** [comment]
I am facing the same issue :). Could you please show me how did you that? where can I find nnUnet_compile?

**Comment by aymuos15** [comment]
` nnUNet_compile=f `

This should be set as your environment variable or front of your commands.

**Comment by Merom99** [comment]
Hi @aymuos15 , I am still getting the same error :( , please see below:

Traceback (most recent call last):
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1377, in run_training
    val_outputs.append(self.validation_step(next(self.dataloader_val)))
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1042, in validation_step
    l = self.loss(output, target)
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/training/loss/deep_supervision.py", line 30, in forward
    return sum([weights[i] * self.loss(*inputs) for i, inputs in enumerate(zip(*args)) if weights[i] != 0.0])
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/training/loss/deep_supervision.py", line 30, in <listcomp>
    return sum([weights[i] * self.loss(*inputs) for i, inputs in enumerate(zip(*args)) if weights[i] != 0.0])
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/nnUNet/nnunetv2/training/loss/compound_losses.py", line 52, in forward
    ce_loss = self.ce(net_output, target[:, 0]) \
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7fe467f85f86 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7fe467f34d10 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7fe468060f08 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x102b38c (0x7fe4690e538c in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #4: <unknown function> + 0x1033f3d (0x7fe4690edf3d in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x5dbbc0 (0x7fe4b5accbc0 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #6: <unknown function> + 0x6abdf (0x7fe467f69bdf in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x21b (0x7fe467f62c3b in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x9 (0x7fe467f62de9 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x892438 (0x7fe4b5d83438 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #10: THPVariable_subclass_dealloc(_object*) + 0x2c6 (0x7fe4b5d83786 in /home/maa19/pythonProject1/pythonProject/Maram/venv/lib/python3.9/site-packages/torch/lib/libtorch_python.so)
frame #11: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x6051f3]
frame #12: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x60609c]
frame #13: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x624300]
frame #14: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x56d848]
frame #15: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x56d8a6]
frame #16: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x56d8a6]
frame #17: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x56d8a6]
frame #18: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x56d8a6]
frame #19: PyDict_SetItemString + 0x531 (0x6039a1 in /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python)
frame #20: /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python() [0x6c0e2e]
frame #21: Py_FinalizeEx + 0x183 (0x6bab43 in /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python)
frame #22: Py_RunMain + 0x16e (0x6f4c3e in /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python)
frame #23: Py_BytesMain + 0x2d (0x6f506d in /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python)
frame #24: __libc_start_main + 0xf3 (0x7fe4b801a083 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: _start + 0x2e (0x630f0e in /home/maa19/pythonProject1/pythonProject/Maram/venv/bin/python)

Aborted

**Comment by ykirchhoff** [comment]
Hi @Merom99,

it seems like that is a separate issue, could you please open a new issue and tag me there so I can assign myself to it?

Best,
Yannick
