### ISSUE TITLE
My error in train 3dfullres

### ISSUE THREAD

**Issue by alarmtran** [MIC-DKFZ/nnUNet#2447]
**I HAVE AN ERROR AS **

**############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0
C:\Users\AlarmTran\anaconda3\Lib\site-packages\torch\cuda\amp\grad_scaler.py:125: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn(

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-08-15 18:33:58.161332: do_dummy_2d_data_aug: False
2024-08-15 18:33:58.162330: Using splits from existing split file: C:/Users/AlarmTran/anaconda3/Lib/site-packages/nnunetv2/nnUNet_preprocessed\Dataset002_Heart\splits_final.json
2024-08-15 18:33:58.164329: The split file contains 5 splits.
2024-08-15 18:33:58.165329: Desired fold for training: 0
2024-08-15 18:33:58.166328: This split has 16 training and 4 validation cases.
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 373, in _load_modules
    self._find_modules_with_enum_process_module_ex()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Process Process-2:
Traceback (most recent call last):
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 373, in _load_modules
    self._find_modules_with_enum_process_module_ex()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\AlarmTran\anaconda3\Lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 41, in producer
    with threadpool_limits(1, None):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 171, in __init__
    self._original_info = self._set_threadpool_limits()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 268, in _set_threadpool_limits
    modules = _ThreadpoolInfo(prefixes=self._prefixes,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 340, in __init__
    self._load_modules()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 373, in _load_modules
    self._find_modules_with_enum_process_module_ex()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 485, in _find_modules_with_enum_process_module_ex
    self._make_module_from_path(filepath)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\threadpoolctl.py", line 646, in get_version
    config = get_config().split()
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
Exception in thread Thread-1 (results_loop):
Traceback (most recent call last):
  File "C:\Users\AlarmTran\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\AlarmTran\anaconda3\Scripts\nnUNetv2_train.exe\__main__.py", line 7, in <module>
    self.run()
  File "C:\Users\AlarmTran\anaconda3\Lib\threading.py", line 975, in run
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\nnunetv2\run\run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\nnunetv2\run\run_training.py", line 211, in run_training
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 103, in results_loop
    nnunet_trainer.run_training()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 1362, in run_training
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
    self.on_train_start()
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 903, in on_train_start
    self.dataloader_train, self.dataloader_val = self.get_dataloaders()
                                                 ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\nnunetv2\training\nnUNetTrainer\nnUNetTrainer.py", line 696, in get_dataloaders
    _ = next(mt_gen_train)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AlarmTran\anaconda3\Lib\site-packages\batchgenerators\dataloading\nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message**

**Thank you for suporting**

**Comment by Lars-Kraemer** [comment]
Hey @alarmtran,

This typically happens when you run out of RAM. 
1. Ensure your hardware is sufficient
2. Ensure you are training using your GPU and not on your CPU
3. Decrease patch_size and batch_size 

Best,
Lars

**Comment by alarmtran** [comment]
My computer has 32gb ram but when I train my model, my laptop uses about 10gb ram for Internet Explorer etc . I think it can't be full of RAM
