### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by Gingerwtw** [MIC-DKFZ/nnUNet#2457]
Traceback (most recent call last):
  File "/home/gingerwen/miniforge3/envs/nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/data/home/gingerwen/nnUNet/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/data/home/gingerwen/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/data/home/gingerwen/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1362, in run_training
    self.on_train_start()
  File "/data/home/gingerwen/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 906, in on_train_start
    self.initialize()
  File "/data/home/gingerwen/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 221, in initialize
    self.network = torch.compile(self.network)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/__init__.py", line 1893, in compile
    return torch._dynamo.optimize(backend=backend, nopython=fullgraph, dynamic=dynamic, disable=disable)(model)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 681, in optimize
    compiler_config=backend.get_compiler_config()
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/__init__.py", line 1734, in get_compiler_config
    from torch._inductor.compile_fx import get_patched_config_dict
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/compile_fx.py", line 57, in <module>
    from .fx_passes.joint_graph import joint_graph_passes
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/fx_passes/joint_graph.py", line 12, in <module>
    from ..pattern_matcher import (
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/pattern_matcher.py", line 46, in <module>
    from .lowering import fallback_node_due_to_unsupported_type
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/lowering.py", line 6002, in <module>
    import_submodule(kernel)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1866, in import_submodule
    importlib.import_module(f"{mod.__name__}.{filename[:-3]}")
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/kernel/flex_attention.py", line 155, in <module>
    flex_attention_template = TritonTemplate(
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/select_algorithm.py", line 453, in __init__
    self.template = self._template_from_string(source)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/torch/_inductor/codegen/common.py", line 1720, in _template_from_string
    return env.from_string(source)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/jinja2/environment.py", line 1091, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/jinja2/environment.py", line 756, in compile
    self.handle_exception(source=source_hint)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 104, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'indent_except_first'.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    raise e
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    self.run()
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/threading.py", line 917, in run
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
    self._target(*self._args, **self._kwargs)
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/gingerwen/miniforge3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by Gingerwtw** [comment]
jinja2.exceptions.TemplateAssertionError: No filter named 'indent_except_first'.

**Comment by Gingerwtw** [comment]
the version of jinja2 of mine is 3.0.0

**Comment by ykirchhoff** [comment]
Hi @Gingerwtw,

it seems like your issue is with torch.compile. Could you please set nnUNet_compile to False and check if that solves the issue (you can easily do this by `nnUNet_compile=f nnUNetv2_train ...`). If that solves the issue it is indeed related to torch.complie. Independent of that, could you please give me a list of your installed packages with versions?

Best,
Yannick

**Comment by Gingerwtw** [comment]
Sovled. Thank you very much!

**Comment by ykirchhoff** [comment]
Great, no problem!
