### ISSUE TITLE
Error when using ResEncUNet with nnUNetTrainer_DASegOrd0_NoMirroring

### ISSUE THREAD

**Issue by wasserth** [MIC-DKFZ/nnUNet#2486]
When trying to train a model with plan `nnUNetResEncUNetMPlans` and trainer `nnUNetTrainer_DASegOrd0_NoMirroring` I get the following error:
```
Traceback (most recent call last):
  File "/mnt/nor/miniconda3/envs/nnunet_latest/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 55, in producer
    item = transform(**item)
  File "/mnt/nor/miniconda3/envs/nnunet_latest/lib/python3.10/site-packages/batchgeneratorsv2/transforms/base/basic_transform.py", line 18, in __call__
    return self.apply(data_dict, **params)
  File "/mnt/nor/miniconda3/envs/nnunet_latest/lib/python3.10/site-packages/batchgeneratorsv2/transforms/utils/compose.py", line 13, in apply
    data_dict = t(**data_dict)
  File "/mnt/nor/miniconda3/envs/nnunet_latest/lib/python3.10/site-packages/batchgeneratorsv2/transforms/base/basic_transform.py", line 17, in __call__
    params = self.get_parameters(**data_dict)
  File "/mnt/nor/miniconda3/envs/nnunet_latest/lib/python3.10/site-packages/batchgeneratorsv2/transforms/spatial/spatial.py", line 58, in get_parameters
    dim = data_dict['image'].ndim - 1
KeyError: 'image'
```

It does not happend with trainer `nnUNetTrainerNoMirroring` or `nnUNetTrainer_DASegOrd0`.

**Comment by kndahl** [comment]
https://github.com/MIC-DKFZ/nnUNet/issues/2480
Same issue

**Comment by FabianIsensee** [comment]
Hey, sorry for not taking care if this for so long! Is this issue still relevant?
