### ISSUE TITLE
Preprocessing and Installation - setuptools, cannot import name find_namespace_packages

### ISSUE THREAD

**Issue by maggie-may-22** [MIC-DKFZ/nnUNet#2503]
Hi,

I have used the nnUNet successfully before but I moved my folders around and broke everything - I have learnt my lesson not to do that again. 

for some reason now when I try again from scratch, I am getting persistent errors. I am using an SSH to run everything on a HPC - due to my computer being bad. I did this last time too and it worked well.

I have cloned the nnUNet repo following the steps outlined and tried to submit a script to run the plan_and_preprocess command. However, I keep getting the following error. PLEASE HELP!! I have wasted nearly 5/6 weeks trying to fix this.

`Collecting nnunetv2
  Using cached https://files.pythonhosted.org/packages/e9/76/b07d94295b8680333c267420cb8fe68780c1f0330b01f83de221e14398f8/nnunetv2-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data1/pbs.10356798.pbs/pip-build-FrOqoG/nnunetv2/setup.py", line 1, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name find_namespace_packages
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data1/pbs.10356798.pbs/pip-build-FrOqoG/nnunetv2/
You are using pip version 9.0.1, however version 24.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/var/spool/PBS/mom_priv/jobs/10356798.pbs.SC: line 17: nnUNetv2_plan_and_preprocess: command not found
PBS Job 10356798.pbs
CPU time  : 00:00:00
Wall time : 00:00:01
Mem usage : 0b
`

BTW: This is the script I submit through the SSH

`#!/bin/bash -l

#PBS -N plan_and_preprocess_701
#PBS -l walltime=12:00:00
#PBS -l ncpus=12
#PBS -l mem=200G
#PBS -l ngpus=0
#PBS -j oe
#PBS -m abe

pip install nnunetv2

export nnUNet_raw="\\hpc-fs\home\data\nnUNet_raw"
export nnUNet_results="\\hpc-fs\home\data\nnUNet_results"
export nnUNet_preprocessed="\\hpc-fs\home\data\nnUNet_preprocessed"

nnUNetv2_plan_and_preprocess -d 701 --verify_dataset_integrity`

**Comment by TaWald** [comment]
It seems like your installation is quite clearly not working.

`/var/spool/PBS/mom_priv/jobs/10356798.pbs.SC: line 17: nnUNetv2_plan_and_preprocess: command not found`
When trying to run plan and preprocess your command is not found indicating that the installation failed.

This is also stated by the stacktrace above

```
Traceback (most recent call last):
File "", line 1, in
File "/data1/pbs.10356798.pbs/pip-build-FrOqoG/nnunetv2/setup.py", line 1, in
from setuptools import setup, find_namespace_packages
ImportError: cannot import name find_namespace_packages
```
I would recommend debugging this in bash script.
Some commands that can help you figure out what's wrong are:

1. Check which interpreter you are actually calling
`which pip` 
`which python`
2. Check you are using python 3 -- As far as I see you are not using a conda environment (you should) 
`python --version` <-- Check which 
3. Ask some colleagues. If you are working on a HPC system there have to be people near you that can help you out. This seems like basic knowledge most colleagues will be able to solve much quicker. They can also walk you through conda environment set-ups

**Comment by TaWald** [comment]
Closing due to inactivity
