### ISSUE TITLE
Error training on docker container with python 3.7

### ISSUE THREAD

**Issue by satara** [MIC-DKFZ/nnUNet#2505]
I am trying to train in a docker container, is this error related to python3.7?
I am setting up the paths  just before running the training command:

```export nnUNet_raw="/ml_codes/ml_codes/nnunet/nnUNet_raw"```
```export nnUNet_preprocessed="/ml_codes/ml_codes/nnunet/nnUNet_preprocessed"```
```export nnUNet_results="/ml_codes/ml_codes/nnunet/nnUNet_results"```
```nnUNetv2_train 20 2d 0 ```

```Traceback (most recent call last):```
```  File "/usr/local/bin/nnUNetv2_train", line 5, in <module>```
```    from nnunetv2.run.run_training import run_training_entry```
```  File "/usr/local/lib/python3.7/dist-packages/nnunetv2/run/run_training.py", line 12, in <module>```
```    from nnunetv2.training.nnUNetTrainer.nnUNetTrainer import nnUNetTrainer```
```  File "/usr/local/lib/python3.7/dist-packages/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 50, in <module>```
```    from nnunetv2.utilities.file_path_utilities import should_i_save_to_file, check_workers_busy```
```  File "/usr/local/lib/python3.7/dist-packages/nnunetv2/utilities/file_path_utilities.py", line 45```
```    return folders[idx - 2], *splitted```
```                             ^```

**Comment by satara** [comment]
Sorry, we are trying to update the container so I will not be able to reproduce this error
