### ISSUE TITLE
RuntimeError: One or more background workers are no longer alive.

### ISSUE THREAD

**Issue by Guoxt** [MIC-DKFZ/nnUNet#2516]
File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

Traceback (most recent call last):
  File "/opt/conda/bin/nnUNetv2_predict", line 8, in <module>
    sys.exit(predict_entry_point())
  File "/opt/conda/lib/python3.8/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 525, in predict_entry_point
    predict_from_raw_data(args.i,
  File "/opt/conda/lib/python3.8/site-packages/nnunetv2/inference/predict_from_raw_data.py", line 236, in predict_from_raw_data
    for preprocessed in mta:
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 204, in __next__
    item = self.__get_next_item()
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by Guoxt** [comment]
How can this issue be resolved?

**Comment by e-FunJs** [comment]
I rent a new serve..And the problem had been resolved.

**Comment by e-FunJs** [comment]
I solved this problem by changing a server. I encountered this issue with 3090 x 4, but later I rented V100 x 2 on AutoDL and solved this problem.



---- Replied Message ----
| From | Jiahao ***@***.***> |
| Date | 07/15/2025 00:08 |
| To | ***@***.***> |
| Cc | Yifan ***@***.***>***@***.***> |
| Subject | Re: [MIC-DKFZ/nnUNet] RuntimeError: One or more background workers are no longer alive. (Issue #2516) |
JiahaoHuang99 left a comment (MIC-DKFZ/nnUNet#2516)

I have the same problem. Have you solved it? Thanks a lot

**Comment by Lars-Kraemer** [comment]
These problems are often related to out of RAM issues.
For `nnUNetv2_predictuse `these flags to reduce the RAM consumption:
```
    parser.add_argument('-npp', type=int, required=False, default=_getDefaultValue('nnUNet_npp', int, 3),
                        help='Number of processes used for preprocessing. More is not always better. Beware of '
                             'out-of-RAM issues. Default: 3')
    parser.add_argument('-nps', type=int, required=False, default=_getDefaultValue('nnUNet_nps', int, 3),
                        help='Number of processes used for segmentation export. More is not always better. Beware of '
                             'out-of-RAM issues. Default: 3')
```
if this does not help try to get access for better Hardware or subdivide you image into smaller chunks and predict them individually. This is of course not the best solution but a work around to make it run.

Best,
Lars
