### ISSUE TITLE
when i training... use my dataset ->free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by gittzb** [MIC-DKFZ/nnUNet#2523]
2024-09-27 03:28:32.231575: unpacking dataset...
2024-09-27 03:28:47.705576: unpacking done...
2024-09-27 03:28:47.745351: Unable to plot network architecture: nnUNet_compile is enabled!
2024-09-27 03:28:48.406594: 
2024-09-27 03:28:48.406942: Epoch 0
2024-09-27 03:28:48.407847: Current learning rate: 0.01
W0927 03:29:42.844659 140527333500096 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0927 03:29:43.388365 140527333500096 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0927 03:29:44.021123 140527333500096 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0927 03:29:44.343075 140527333500096 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0927 03:29:44.527453 140527333500096 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] xindex is not in var_ranges, defaulting to unknown range.
W0927 03:30:32.569092 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:34.037217 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:35.325292 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:36.129835 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:41.825655 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] d0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:47.389648 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:47.732059 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:49.458221 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:49.668665 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:51.330883 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:51.697602 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:52.530189 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:52.707627 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:59.252643 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] q0 is not in var_ranges, defaulting to unknown range.
W0927 03:30:59.626246 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] z0 is not in var_ranges, defaulting to unknown range.
W0927 03:31:03.509407 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x1 is not in var_ranges, defaulting to unknown range.
W0927 03:31:04.719871 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0927 03:31:05.694612 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0927 03:31:06.482680 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x0 is not in var_ranges, defaulting to unknown range.
W0927 03:31:10.602096 140519741843200 torch/fx/experimental/symbolic_shapes.py:4449] [0/0] x1 is not in var_ranges, defaulting to unknown range.
free(): corrupted unsorted chunks
free(): corrupted unsorted chunks
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnUNet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/home/ubuntu/PB-group/ZS/nnUNet/nnunetv2/run/run_training.py", line 277, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/home/ubuntu/PB-group/ZS/nnUNet/nnunetv2/run/run_training.py", line 211, in run_training
    raise e
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
    nnunet_trainer.run_training()
  File "/home/ubuntu/PB-group/ZS/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1371, in run_training
    train_outputs.append(self.train_step(next(self.dataloader_train)))
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/ubuntu/anaconda3/envs/nnUNet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
what is the issue and how can it be solved?

**Comment by gaojh135** [comment]
Is PyTorch using a relatively new version? Have you tried downgrading to a few earlier versions?
torch是不是用的比较新的版本，试试回退几个版本？

**Comment by Kaihua1203** [comment]
Yea, I face same error. I guess it's version mismatching, my nnunet verion is 2.5.1.

**Comment by Karol-G** [comment]
Hey,

Is this issue still relevant? Otherwise, I will close it in 14 days.

Best,
Karol

**Comment by Karol-G** [comment]
Closing this issue due to inactivity.
