### ISSUE TITLE
Training. Torch Error?

### ISSUE THREAD

**Issue by maggie-may-22** [MIC-DKFZ/nnUNet#2533]
Hi, I am hoping to get some assistance. I have finished the preprocessing of my dataset which seemed to go well. I am having some issues with the training - I am just training the 2d configuration for now and was only running for Fold 0 to check if it was working. I am running through a SSH connected to HPC.

However, it gives me an error after about 5 minutes. I have put the output below if someone could please help me understand the issue and how to fix it.

`/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py:164: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.grad_scaler = GradScaler() if self.device.type == 'cuda' else None

############################
INFO: You are using the old nnU-Net default plans. We have updated our recommendations. Please consider using those instead! Read more here: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/resenc_presets.md
############################

Using device: cuda:0

#######################################################################
Please cite the following paper when using nnU-Net:
Isensee, F., Jaeger, P. F., Kohl, S. A., Petersen, J., & Maier-Hein, K. H. (2021). nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation. Nature methods, 18(2), 203-211.
#######################################################################

2024-10-08 20:37:48.713970: do_dummy_2d_data_aug: False
2024-10-08 20:37:48.717379: Creating new 5-fold cross-validation split...
2024-10-08 20:37:48.742585: Desired fold for training: 0
2024-10-08 20:37:48.743828: This split has 7 training and 2 validation cases.
using pin_memory on device 0
/home/hornigmm/.local/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:60: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn(
using pin_memory on device 0
2024-10-08 20:40:08.757191: Using torch.compile...

This is the configuration used by this training:
Configuration name: 2d
 {'data_identifier': 'nnUNetPlans_2d', 'preprocessor_name': 'DefaultPreprocessor', 'batch_size': 4, 'patch_size': [1152, 768], 'median_image_size_in_voxels': [1111.0, 713.0], 'spacing': [0.40350183844566356, 0.404444009065628], 'normalization_schemes': ['ZScoreNormalization'], 'use_mask_for_norm': [True], 'resampling_fn_data': 'resample_data_or_seg_to_shape', 'resampling_fn_seg': 'resample_data_or_seg_to_shape', 'resampling_fn_data_kwargs': {'is_seg': False, 'order': 3, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_seg_kwargs': {'is_seg': True, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'resampling_fn_probabilities': 'resample_data_or_seg_to_shape', 'resampling_fn_probabilities_kwargs': {'is_seg': False, 'order': 1, 'order_z': 0, 'force_separate_z': None}, 'architecture': {'network_class_name': 'dynamic_network_architectures.architectures.unet.PlainConvUNet', 'arch_kwargs': {'n_stages': 8, 'features_per_stage': [32, 64, 128, 256, 512, 512, 512, 512], 'conv_op': 'torch.nn.modules.conv.Conv2d', 'kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'strides': [[1, 1], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'n_conv_per_stage': [2, 2, 2, 2, 2, 2, 2, 2], 'n_conv_per_stage_decoder': [2, 2, 2, 2, 2, 2, 2], 'conv_bias': True, 'norm_op': 'torch.nn.modules.instancenorm.InstanceNorm2d', 'norm_op_kwargs': {'eps': 1e-05, 'affine': True}, 'dropout_op': None, 'dropout_op_kwargs': None, 'nonlin': 'torch.nn.LeakyReLU', 'nonlin_kwargs': {'inplace': True}}, '_kw_requires_import': ['conv_op', 'norm_op', 'dropout_op', 'nonlin']}, 'batch_dice': True} 

These are the global plan.json settings:
 {'dataset_name': 'Dataset701_SHOULDER', 'plans_name': 'nnUNetPlans', 'original_median_spacing_after_transp': [0.40444400906562805, 0.40350183844566356, 0.404444009065628], 'original_median_shape_after_transp': [1059, 1114, 656], 'image_reader_writer': 'SimpleITKIO', 'transpose_forward': [2, 0, 1], 'transpose_backward': [1, 2, 0], 'experiment_planner_used': 'ExperimentPlanner', 'label_manager': 'LabelManager', 'foreground_intensity_properties_per_channel': {'0': {'max': 284.0, 'mean': 61.74697494506836, 'median': 60.0, 'min': 0.0, 'percentile_00_5': 6.0, 'percentile_99_5': 132.0, 'std': 24.240419387817383}}} 

2024-10-08 20:40:15.290197: unpacking dataset...
Traceback (most recent call last):
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/data_loader_2d.py", line 21, in generate_train_batch
    data, seg, properties = self._data.load_case(current_key)
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 86, in load_case
    data = np.load(entry['data_file'][:-4] + ".npy", 'r')
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
Exception in background worker 4:
 mmap length is greater than file size
Traceback (most recent call last):
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/data_loader_2d.py", line 21, in generate_train_batch
    data, seg, properties = self._data.load_case(current_key)
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
Exception in background worker 5:
 mmap length is greater than file size
Traceback (most recent call last):
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/data_loader_2d.py", line 21, in generate_train_batch
    data, seg, properties = self._data.load_case(current_key)
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
Exception in background worker 3:
 mmap length is greater than file size
Traceback (most recent call last):
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/hornigmm/.local/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/data_loader_2d.py", line 21, in generate_train_batch
    data, seg, properties = self._data.load_case(current_key)
  File "/mnt/hpccs01/home/hornigmm/nnUNet_Base_Folder/nnUNet/nnunetv2/training/dataloading/nnunet_dataset.py", line 97, in load_case
    seg = np.load(entry['data_file'][:-4] + "_seg.npy", 'r')
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/npyio.py", line 453, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/lib/format.py", line 945, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/hornigmm/.local/lib/python3.10/site-packages/numpy/core/memmap.py", line 268, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
Exception in background worker 2:
 mmap length is greater than file size
/data1/pbs.10494714.pbs/tmpwfjp1sgm/main.c:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
/data1/pbs.10494714.pbs/tmpjdkfhlyo/main.c:6:23: fatal error: stdatomic.h: No such file or directory
 #include <stdatomic.h>
                       ^
compilation terminated.
`

**Comment by Haneskixy** [comment]
Same problem, and also I tried to run CUDA_VISIBLE_DEVICES=2 nnUNetv2_train ..., it seems that the training process is still on CUDA device 0.

**Comment by FabianIsensee** [comment]
This should work now, sorry for not responding sooner. 
Are you still experiencing issues?
