### ISSUE TITLE
RuntimeError: Some images have errors. Please check text output above to see which one(s) and what's going on.

### ISSUE THREAD

**Issue by Guoxt** [MIC-DKFZ/nnUNet#2551]
Warning: Origin mismatch between segmentation and corresponding images. 
Origin images: (-123.0, 215.3117218017578, 271.3599853515625). 
Origin seg: (-124.51171875, 124.51171875, -74.25). 
Image files: ['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/imagesTr/0144_image_0000.nii.gz']. 
Seg file: /userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/labelsTr/0144_image.nii.gz

Warning: Origin mismatch between segmentation and corresponding images. 
Origin images: (-115.0, 184.83078002929688, 121.48999786376953). 
Origin seg: (-114.55078125, 114.55078125, -79.19998168945312). 
Image files: ['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/imagesTr/0185_image_0000.nii.gz']. 
Seg file: /userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/labelsTr/0185_image.nii.gz

Warning: Origin mismatch between segmentation and corresponding images. 
Origin images: (-115.0, 175.79078674316406, 92.26000213623047). 
Origin seg: (-114.55078125, 114.55078125, -79.20000457763672). 
Image files: ['/userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/imagesTr/0173_image_0000.nii.gz']. 
Seg file: /userhome/GUOXUTAO/DATA_ALL/DATASET/nnUNet_raw/Dataset700_skull/labelsTr/0173_image.nii.gz

Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunetv2', 'console_scripts', 'nnUNetv2_plan_and_preprocess')())
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 46, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 29, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/code/GUOXUTAO/2023_15/00/nnUNet/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 202, in verify_dataset_integrity
    raise RuntimeError(
RuntimeError: Some images have errors. Please check text output above to see which one(s) and what's going on.

**_### Could you please explain the reason for this error?_**

**Comment by seziegler** [comment]
Hi @Guoxt ,
the metadata of your images and the label files does not seem to align since they have different origins set. When viewing your images with labels overlayed are the labels displayed accurately or are they somehow shifted?

**Comment by fahad-git** [comment]
Hi, I am facing the same problem. Mine labels overlayed perfectly fine. 
<img width="736" alt="Screenshot 2024-12-15 at 3 51 41 PM" src="https://github.com/user-attachments/assets/2856ee75-b2bd-494c-8662-817c9efbcae9" />

```
Error: Spacing mismatch between segmentation and corresponding images.
Spacing images: [0.5, 0.7820000052452087, 0.7820000052452087].
Spacing seg: [0.25, 0.7820000052452087, 0.7820000052452087].
Image files: ['G:/CT_Data/CT/nnUNet_raw\\Dataset001_Temporary\\imagesTr\\Round_3_Stent_5_Non-Contrast_IM00010_0000.nii.gz'].
Seg file: G:/CT_Data/CT/nnUNet_raw\Dataset001_Temporary\labelsTr\Round_3_Stent_5_Non-Contrast_IM00010.nii.gz

Warning: Direction mismatch between segmentation and corresponding images.
Direction images: (1.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0).
Direction seg: (1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, -1.0).
Image files: ['G:/CT_Data/CT/nnUNet_raw\\Dataset001_Temporary\\imagesTr\\Round_3_Stent_5_Non-Contrast_IM00010_0000.nii.gz'].
Seg file: G:/CT_Data/CT/nnUNet_raw\Dataset001_Temporary\labelsTr\Round_3_Stent_5_Non-Contrast_IM00010.nii.gz

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User1\anaconda3\envs\nseg\Scripts\nnUNetv2_plan_and_preprocess.exe\__main__.py", line 7, in <module>
  File "C:\Users\User1\fahad\CT_Segmentation\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_entrypoints.py", line 180, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "C:\Users\User1\fahad\CT_Segmentation\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "C:\Users\User1\fahad\CT_Segmentation\nnUNet\nnunetv2\experiment_planning\plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "C:\Users\User1\fahad\CT_Segmentation\nnUNet\nnunetv2\experiment_planning\verify_dataset_integrity.py", line 219, in verify_dataset_integrity
    raise RuntimeError(
RuntimeError: Some images have errors. Please check text output above to see which one(s) and what's going on.

```

**Comment by seziegler** [comment]
Hi @fahad-git ,
from the warning message you can see that your image and masks have different spacings and orientations.

**Comment by denis-samatov** [comment]
Hi @Guoxt and @fahad-git — I'm following up on the image/label geometry mismatches documented here. A mask can look aligned in a viewer that displays both in physical space while still having a different voxel grid for voxelwise training; the spacing and direction values in the later example also differ. I would not change header numbers or increase a tolerance without verifying where the mask voxels land in the source image.

Did either of you identify the step that produced the mismatched origin/spacing/direction, and what safely fixed it? I'm researching whether a read-only preflight showing the two grids, their physical bounds, and a diagnostic overlay would have made the cause clearer before nnU-Net preprocessing. Which comparison was missing from the existing warning, if any, and how much debugging time did this take? A description or synthetic example is enough; please don't share patient images or identifying logs.
