### ISSUE TITLE
Ignore Labels for 2D images

### ISSUE THREAD

**Issue by FabianHoerst** [MIC-DKFZ/nnUNet#2567]
Hi,

i try to work with 2D rgb images with sparse augmentations. If I use the following dataset.json file (without ignore), everything works fine:
```json
{ 
 "channel_names": {
   "0": "R",
   "1": "G",
   "2": "B"
 }, 
 "labels": { 
    "background": 0,
    "tumor": 1,
    "tumor-stroma": 2,
    "necrotic-debris": 3,
    "mucin": 4,
    "benign-lung": 5,
    "benign-connective-tissue": 6,
    "bleeding/blood": 7,
    "bronchial-mucosa": 8,
    "cartilage": 9,
    "peribronchial-glands": 10,
    "inflammatory-infiltrate": 11,
    "check": 12
 }, 
 "numTraining": 1600, 
 "file_ending": ".png",
 "overwrite_image_reader_writer": "NaturalImage2DIO"
 }
```
However, If i change the last label to ignore like this
```json
...
 "labels": { 
   ...
    "check": 12
 }, 
...
```
I get the following error:
```bash
2024-10-24 14:34:03.093880: Epoch 0
2024-10-24 14:34:03.105457: Current learning rate: 0.01
Exception in background worker 7:
 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/jovyan/nsclc-code/environments/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/jovyan/nsclc-code/environments/nnunet/lib/python3.10/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/home/jovyan/nsclc-code/environments/nnunet/lib/python3.10/site-packages/nnunetv2/training/dataloading/data_loader_2d.py", line 63, in generate_train_batch
    bbox_lbs, bbox_ubs = self.get_bbox(shape, force_fg if selected_class_or_region is not None else None,
  File "/home/jovyan/nsclc-code/environments/nnunet/lib/python3.10/site-packages/nnunetv2/training/dataloading/base_data_loader.py", line 89, in get_bbox
    if len(class_locations[selected_class]) == 0:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by FabianHoerst** [comment]
Write your own loss and trainer for this solved the problem for me
