### ISSUE TITLE
multiple labels modalities 

### ISSUE THREAD

**Issue by Ouzuo1** [MIC-DKFZ/nnUNet#2580]
Hello, first thank you for this awesome model and im sorry to open such an issue but i tried a lot to solve this but with no luck. 

i came across this issue when i was trying to run the nnunet plan and preprocess

""""""
Fingerprint extraction...
Dataset101_MRISEG
Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 180, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 30, in extract_fingerprint_dataset
    verify_dataset_integrity(join(nnUNet_raw, dataset_name), num_processes)
  File "/usr/local/lib/python3.10/dist-packages/nnunetv2/experiment_planning/verify_dataset_integrity.py", line 155, in verify_dataset_integrity
    assert len(dataset) == expected_num_training, 'Did not find the expected number of training cases ' \
AssertionError: Did not find the expected number of training cases (357). Found 35 instead.
Examples: ['', '1', '107_t2_', '110_t2_', '118_t2_']
""""

the issue occurs as i have multiple labels modalities, i tried to do a script to copy and rename but every time i did so the labels with different for the same case but different modalities treated like duplicates and only one came to be copied, as the nnunet structure requires that the labels naming to only have the case numebr with no modalities attached i think this is what im facing 
an example of labels i have, 107_t1, 107_t2, 107_t2_SPACE
so for the case 107 i have three labels with different modalities.

**Comment by TaWald** [comment]
nnU-Net can't read your mind how the data is organized, so you need to change your dataset format.
The nnU-Net dataset convention is explained here:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_format.md

Please check through the existing readmes first, as most basic information should be accessible there.
