### ISSUE TITLE
mmap length is greater than file size

### ISSUE THREAD

**Issue by skz0602** [MIC-DKFZ/nnUNet#2581]
it seems that the issue with mmap had resulted in the dead of background worker, which leads to runtime error. 
I've tried to delete all the .npy documents in the preprocessed file and rerun the plan_and_preprocess. but the same problem occured again when i run the training part..... anyone can help?

Followings are the detailed information after i started to run the training part. 
2024-11-04 09:03:10.057891: unpacking dataset...
Exception in background worker 3:
 mmap length is greater than file size
Traceback (most recent call last):
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 53, in producer
    item = next(data_loader)
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/mnt/cjy/nnUNet-master/nnunetv2/training/dataloading/data_loader_2d.py", line 21, in generate_train_batch
    data, seg, properties = self._data.load_case(current_key)
  File "/mnt/cjy/nnUNet-master/nnunetv2/training/dataloading/nnunet_dataset.py", line 86, in load_case
    data = np.load(entry['data_file'][:-4] + ".npy", 'r')
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/numpy/lib/_npyio_impl.py", line 481, in load
    return format.open_memmap(file, mode=mmap_mode,
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/numpy/lib/format.py", line 970, in open_memmap
    marray = numpy.memmap(filename, dtype=dtype, shape=shape, order=order,
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/numpy/_core/memmap.py", line 279, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
2024-11-04 09:18:13.220467: unpacking done...
2024-11-04 09:18:13.445262: Unable to plot network architecture: nnUNet_compile is enabled!
2024-11-04 09:18:13.650955: 
2024-11-04 09:18:13.651367: Epoch 0
2024-11-04 09:18:13.652348: Current learning rate: 0.01
Traceback (most recent call last):
  File "/home/cjy/miniconda3/envs/nnunet/bin/nnUNetv2_train", line 8, in <module>
    sys.exit(run_training_entry())
  File "/mnt/cjy/nnUNet-master/nnunetv2/run/run_training.py", line 275, in run_training_entry
    run_training(args.dataset_name_or_id, args.configuration, args.fold, args.tr, args.p, args.pretrained_weights,
  File "/mnt/cjy/nnUNet-master/nnunetv2/run/run_training.py", line 211, in run_training
    nnunet_trainer.run_training()
  File "/mnt/cjy/nnUNet-master/nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py", line 1377, in run_training
    val_outputs.append(self.validation_step(next(self.dataloader_val)))
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 196, in __next__
    item = self.__get_next_item()
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 181, in __get_next_item
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/cjy/miniconda3/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

**Comment by MenghanLiu212** [comment]
Hi,

I ran into the same issue and this link may be helpful: https://github.com/MIC-DKFZ/nnUNet/issues/291
I tried the deleting method (not working) but the changing r to r+ method works!

**Comment by skz0602** [comment]
That works! Thanks a lot!
