### ISSUE TITLE
RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID ".

### ISSUE THREAD

**Issue by feng-ye00** [MIC-DKFZ/nnUNet#2594]
I am using U-mamba to segment brain regions, I am doing this in linux. I have also prepared the dataset in nnUNet format and set the correct directories for nnUNet_raw, nnUNet_preprocessed and nnUNet_results.
Here is the structure: 
Inside nnUNet_raw, I have a folder named Dataset701_AbdomenCT .
Within Dataset701_AbdomenCT , there are imagesTr, imagesTs, labelsTr, and dataset.json.
I followed the nnUNet formatting guidelines when preparing the data and the dataset.json file.
{
    "channel_names": {
        "0": "CT"
    },
    "labels": {
        "background": 0,
        "liver": 1,
        "right kidney": 2,
        "spleen": 3,
        "pancreas": 4,
        "aorta": 5,
        "inferior vena cava": 6,
        "right adrenal gland": 7,
        "left adrenal gland": 8,
        "gallbladder": 9,
        "esophagus": 10,
        "stomach": 11,
        "duodenum": 12,
        "left kidney": 13
    },
    "numTraining": 50,
    "file_ending": ".nii.gz",
    "name": "Dataset701_AbdomenCT",
    "description": "This dataset was from MICCAI FLARE 2022 Challenge. The training set contained 50 CT scans that were from the MSD Pancreas dataset and the annotations were from AbdomenCT-1K. Another 50 validation cases were from TCIA and the annotations were provided by the challenge organizers."
}

I got the error when running the following command.
Fingerprint extraction...
Traceback (most recent call last):
  File "/home/zrh/ENTER/envs/mamba-env/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/home/zrh/ENTER/envs/mamba-env/lib/python3.10/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/home/zrh/ENTER/envs/mamba-env/lib/python3.10/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/home/zrh/ENTER/envs/mamba-env/lib/python3.10/site-packages/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
  File "/home/zrh/ENTER/envs/mamba-env/lib/python3.10/site-packages/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 701. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/home/zrh/PycharmProjects/pythonProject/U-Mamba/data/nnUNet_preprocessed
nnUNet_results=/home/zrh/PycharmProjects/pythonProject/U-Mamba/data/nnUNet_trained_models
nnUNet_raw=/home/zrh/PycharmProjects/pythonProject/U-Mamba/data/nnUNet_raw
If something is not right, adapt your environment variables.

Thank you very much

**Comment by seziegler** [comment]
HI @feng-ye00 ,
can other datasets in your nnUNet_raw directory be found?

**Comment by renlyly** [comment]
I encountered a similar problem when testing using UU-mamba to segment brain regions.This dataset was from HECKOR  Challenge 2025. The version for nnunetv2 is 2.3.2.
I set the path as:
export nnUNet_raw="/UU-Mamba/data/nnUNet_raw" 
export nnUNet_preprocessed"/UU-Mamba/data/nnUNet_preprocessed"
export nnUNet_results="/UU-Mamba/data/nnUNet_results"
 
The dataset is under /UU-Mamba/data/nnUNet_raw/Dataset001_restructured
 The dataset.json file is: {
    "dataset_name": "Dataset001_restructured",
    "labels": {
        "background": 0,
        "GTVp": 1,
        "GTVn": 2
    },
    "channel_names": {
        "0": "CT",
        "1": "PET"
    },
    "file_ending": ".nii.gz",
    "numTraining": 1,
    "training": [
        {
            "image": [
                "./imagesTr/CHUM-001_0000.nii.gz",
                "./imagesTr/CHUM-001_0001.nii.gz"
            ],
            "label": "./labelsTr/CHUM-001.nii.gz"
        }
    ]
}

Below is my error message: (/work/users/s/h/shiliny/Hongtu/.conda/uumamba_clean2) [shiliny@longleaf-login4 UU-Mamba]$ nnUNetv2_plan_and_preprocess -d 1 --verify_dataset_integrity
Fingerprint extraction...
Traceback (most recent call last):
  File "/work/users/s/h/shiliny/Hongtu/.conda/uumamba_clean2/bin/nnUNetv2_plan_and_preprocess", line 8, in <module>
    sys.exit(plan_and_preprocess_entry())
  File "/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/uumamba/nnunetv2/experiment_planning/plan_and_preprocess_entrypoints.py", line 182, in plan_and_preprocess_entry
    extract_fingerprints(args.d, args.fpe, args.npfp, args.verify_dataset_integrity, args.clean, args.verbose)
  File "/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/uumamba/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 47, in extract_fingerprints
    extract_fingerprint_dataset(d, fingerprint_extractor_class, num_processes, check_dataset_integrity, clean,
  File "/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/uumamba/nnunetv2/experiment_planning/plan_and_preprocess_api.py", line 26, in extract_fingerprint_dataset
    dataset_name = convert_id_to_dataset_name(dataset_id)
  File "/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/uumamba/nnunetv2/utilities/dataset_name_id_conversion.py", line 48, in convert_id_to_dataset_name
    raise RuntimeError(f"Could not find a dataset with the ID {dataset_id}. Make sure the requested dataset ID "
RuntimeError: Could not find a dataset with the ID 1. Make sure the requested dataset ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/data/nnUNet_preprocessed
nnUNet_results=/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/data/nnUNet_results
nnUNet_raw=/work/users/s/h/shiliny/Hongtu/HECKTOR_2025/UU-Mamba/data/nnUNet_raw
If something is not right, adapt your environment variables.
