### ISSUE TITLE
ValueError: Integers to negative integer powers are not allowed.

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#261]
Hi Fabian,
    My data preprocessing problem has not been solved, I hope you can help me. I used an older version of the 'XXX' code.
I used an older version of the 'python experiment_planning/plan_and_preprocess_task.py -t Task10_Colon' code

Traceback (most recent call last):
  File "/home/zhengsc/Desktop/ok-nnunet/nnunet/experiment_planning/plan_and_preprocess_task.py", line 237, in <module>
    plan_and_preprocess(task, processes, no_preprocessing)
  File "/home/zhengsc/Desktop/ok-nnunet/nnunet/experiment_planning/plan_and_preprocess_task.py", line 135, in plan_and_preprocess
    exp_planner.plan_experiment()
  File "/home/Desktop/nnunet/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 251, in plan_experiment
    num_modalities, len(all_classes) + 1))
  File "/home/Desktop/nnunet/nnunet/experiment_planning/experiment_planner_baseline_3DUNet.py", line 190, in get_properties_for_stage
    CSSE_UNet.MAX_NUMPOOL_3D, current_spacing)
  File "/home/Desktop/nnunet/nnunet/experiment_planning/common_utils.py", line 83, in get_pool_and_conv_props_poolLateV2
    must_be_divisible_by = get_shape_must_be_divisible_by(num_pool_per_axis)
  File "/home/Desktop/nnunet/nnunet/experiment_planning/common_utils.py", line 197, in get_shape_must_be_divisible_by
    return 2 ** np.array(net_numpool_per_axis)
ValueError: Integers to negative integer powers are not allowed.

I  print(net_numpool_per_axis)
![image](https://user-images.githubusercontent.com/53425125/87271998-8a107a00-c507-11ea-8adc-fdc2f59e2195.png)
 
The results are as follows
![image](https://user-images.githubusercontent.com/53425125/87271973-72d18c80-c507-11ea-9bc7-43e0e1bcd2f5.png)

I think it might be my data. How do you know which data is wrong?Or is there some other cause of the problem?
How can I solve this problem? It has been bothering me for a long time. I hope you can help me.

Best wish!

**Comment by FabianIsensee** [comment]
To solve this I need to be able to reproduce this error. Please provide some code to reproduce it. Something like this will do:

```python
    median_shape = [24, 504, 512]
    spacing = [5.9999094, 0.50781202, 0.50781202]
    num_pool_per_axis, net_num_pool_op_kernel_sizes, net_conv_kernel_sizes, patch_size, must_be_divisible_by = get_pool_and_conv_props_poolLateV2(median_shape, min_feature_map_size=4, max_numpool=999, spacing=spacing)

```

Also please use nnU-Net V2 and the corresponding default experiment planner! You are still using the old stuff

**Comment by wxr521314** [comment]
I can share my data and code with you. How can I share it with you?
Can you provide an email address?

**Comment by FabianIsensee** [comment]
Just give me some python script that will reproduce this error:
```get_pool_and_conv_props_poolLateV2(median_shape, min_feature_map_size=4, max_numpool=999, spacing=spacing)```

Just manually set what all these inputs are
