### ISSUE TITLE
nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity KeyError: 'training'

### ISSUE THREAD

**Issue by ClaraLlorens** [MIC-DKFZ/nnUNet#2631]
I am working with a custom dataset in Google Colab. 

The dataset is located in (nnUNet_raw_data_base/nnUNet_raw_data/Task100_CON) which has the imagesTr, imagesTs, labelsTr folders with the .bmp images, and dataset.json. All the training images have been named VESSELS_001_0000.bmp, VESSELS_002_0000.bmp, VESSELS_003_0000.bmp,... and so on.

I have specified the paths for the different folders as

_os.environ['nnUNet_raw_data_base'] = "/content/drive/MyDrive/cvessels_segmentation/my_nnunet/nnUNet/nnunet/nnUNet_raw_data_base"
os.environ['nnUNet_preprocessed'] = "/content/drive/MyDrive/cvessels_segmentation/my_nnunet/nnUNet/nnunet/nnUNet_preprocessed"
os.environ['RESULTS_FOLDER'] = "/content/drive/MyDrive/cvessels_segmentation/my_nnunet/nnUNet/nnunet/nnUNet_results"_

When I run _!nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity_     I get the following error:

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 105, in main
    verify_dataset_integrity(join(nnUNet_raw_data, task_name))
  File "/usr/local/lib/python3.10/dist-packages/nnunet/preprocessing/sanity_checks.py", line 105, in verify_dataset_integrity
    training_cases = dataset['training']
KeyError: 'training'

This is the first time I am using nnUnet so I don't know what I am doing wrong.

Thank you!

**Comment by ClaraLlorens** [comment]
I have just realized that I was using a version that does not support .bmp :)
