### ISSUE TITLE
RuntimeError: unable to write to file </torch_15769_1517813162>

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#294]
Hi Fabian,
     I had the following problem when I was training 2d network. How can I solve it ?

epoch:  342
Traceback (most recent call last):
  File "/raid/zhengsc/anaconda3/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/raid/zhengsc/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/raid/zhengsc/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_15769_1517813162>

 Best Wish !

**Comment by fconstance** [comment]
Hello !
I also get the same problem but before epoch 0 and with the 3d_fullres version of the network. Do you have any idea of how to solve this issue?

###############################################
unpacking dataset
done
2020-08-18 10:41:14.055091: lr: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/constance/sources/environments/venv_nnunet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_714_3048706062>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/constance/sources/environments/venv_nnunet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_718_1473779337>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/constance/sources/environments/venv_nnunet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_717_2883701098>
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/constance/sources/environments/venv_nnunet/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_716_4025004697>

Thank you very much !

**Comment by FabianIsensee** [comment]
Hi there,
this issue is not related to nnU-Net (see error trace) and googling it helps:
https://discuss.pytorch.org/t/unable-to-write-to-file-torch-18692-1954506624/9990/5
Best,
Fabian

**Comment by moaddeli** [comment]
Hi, I had the same problem in ubuntu. finally, I found that the size of shared memory /dev/shm was low (only 64 M) . Changing size  /dev/shm to 10 GB solved this issue.

**Comment by wxr521314** [comment]
> Hi, I had the same problem in ubuntu. finally, I found that the size of shared memory /dev/shm was low (only 64 M) . Changing size /dev/shm to 10 GB solved this issue.
  
Where can I find /dev/shm

**Comment by fconstance** [comment]
Thank you ! 
@moaddeli your solution seems to work so far (at least the network is training)

**Comment by FabianIsensee** [comment]
Great to hear it works now. Can I close this issue?
