### ISSUE TITLE
TypeError: consolidate_folds() got an unexpected keyword argument 'folds'

### ISSUE THREAD

**Issue by wxr521314** [MIC-DKFZ/nnUNet#296]
Hi Fabian,
I had the following problem when I was Identifying the best U-Net configuration. How can I solve it ?
   Traceback (most recent call last):
  File "/raid/zhengsc/anaconda3/bin/nnUNet_find_best_configuration", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')()
  File "/raid/zhengsc/apex/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 121, in main
    raise e
  File "/raid/zhengsc/apex/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 108, in main
    consolidate_folds(output_folder, folds=folds)
TypeError: consolidate_folds() got an unexpected keyword argument 'folds'

**Comment by Joevaen** [comment]
Hi wxr,
Could you please show your command line?

**Comment by wxr521314** [comment]
Delete the folds, and the program can run normally

**Comment by FabianIsensee** [comment]
Hi,
which version of nnU-Net do you have? Did you install via pip or by cloning the github repo? Please use the latest version form master and try again. If the problem persists please let me know and I will fix it.
Best,
Fabian

**Comment by FabianIsensee** [comment]
hey there, is the problem fixed?

**Comment by Karol-G** [comment]
Hi Fabian,

I got the same error today. When running the command `nnUNet_find_best_configuration -m 3d_fullres -t 089 --strict`:

```
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

running missing postprocessing for Task089_MMRF and model 3d_fullres
Traceback (most recent call last):
  File "/gris/gris-f/homelv/kgotkows/anaconda3/envs/pytorch/bin/nnUNet_find_best_configuration", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')()
  File "/gris/gris-f/homelv/kgotkows/remote_projects/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 121, in main
    raise e
  File "/gris/gris-f/homelv/kgotkows/remote_projects/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 108, in main
    consolidate_folds(output_folder, folds=folds)
TypeError: consolidate_folds() got an unexpected keyword argument 'folds'
```

and when running without `strict`:
```

Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

running missing postprocessing for Task089_MMRF and model 3d_fullres
WARNING!
consolidate_folds() got an unexpected keyword argument 'folds'

Found the following valid models:
 []
Traceback (most recent call last):
  File "/gris/gris-f/homelv/kgotkows/anaconda3/envs/pytorch/bin/nnUNet_find_best_configuration", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')()
  File "/gris/gris-f/homelv/kgotkows/remote_projects/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 153, in main
    best = np.max(foreground_dices)
  File "<__array_function__ internals>", line 5, in amax
  File "/gris/gris-f/homelv/kgotkows/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2667, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "/gris/gris-f/homelv/kgotkows/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

All five folds do exists and their training is finished. My nnUNet version is from about a month ago (cloned).
I only trained 3d_fullres. Does it even make sense to use the nnUNet_find_best_configuration command then?

Best
Karol

**Comment by FabianIsensee** [comment]
Hi Karol,
I just verified that it is working for me. Please update to the most recent master and it will work. 
Running this with only 3d_fullres still makes sense because this will trigger `nnUNet_determine_postprocessing`.
Best,
Fabian

**Comment by Karol-G** [comment]
Thanks for the quick answer!
I don't know if you can answer this question: I still have a couple nnUNet trainings running with other datasets. If I clone & reinstall the nnUNet version, could the running training cases crash?

Best
Karol

**Comment by FabianIsensee** [comment]
No you should be able to just update.
Best,
Fabian

**Comment by Karol-G** [comment]
Thanks again. Yeah it is working now 👍
