### ISSUE TITLE
Non-consecutive labels within ground truth

### ISSUE THREAD

**Issue by hyt35** [MIC-DKFZ/nnUNet#309]
Hi Fabian,

I'm getting this following error when trying to apply nnUNet to a TCGA brain tumour dataset formatted like BraTS, with some manual correction. I have run the python script to convert the dataset into an nnUNet-compatible format as suggested. Running `nnUNet_plan_and_preprocess -t 100 --verify_dataset-integrity` returns no errors.

```
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'T1', 1: 'T1ce', 2: 'T2', 3: 'FLAIR'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')])
stages...

stage:  0
{'batch_size': 107, 'num_pool_per_axis': [5, 5], 'patch_size': array([192, 160]), 'median_patient_size_in_voxels': array([138, 169, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/hyt35/nnunet-data/nnUNet_preprocessed/Task100_BraTS/nnUNetData_plans_v2.1_2D
###############################################
unpacking dataset
done
2020-09-03 05:15:09.128544: lr: 0.01
using pin_memory on device 0
using pin_memory on device 0
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")
2020-09-03 05:22:55.289280: Unable to plot network architecture:
2020-09-03 05:23:00.025529: No module named 'IPython'
2020-09-03 05:23:01.358612: 
printing the network instead:

2020-09-03 05:23:04.365905: 

2020-09-03 05:23:04.869593: 
epoch:  0
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [1,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:208: operator(): block: [5616,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/hyt35/nnunet-venv/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 387, in run_training
    ret = super().run_training()
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 318, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/network_training/network_trainer.py", line 445, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 244, in run_iteration
    loss = self.loss(output, target)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/loss_functions/deep_supervision.py", line 42, in forward
    l += weights[i] * self.loss(x[i], y[i])
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/loss_functions/dice_loss.py", line 326, in forward
    dc_loss = self.dc(net_output, target) if self.weight_dice != 0 else 0
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/training/loss_functions/dice_loss.py", line 178, in forward
    x = self.apply_nonlin(x)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/nnunet/utilities/nd_softmax.py", line 23, in softmax_helper
    return e_x / e_x.sum(1, keepdim=True).repeat(*rpt)
  File "/home/hyt35/nnunet-venv/lib/python3.7/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA error: device-side assert triggered
```

I've used the BraTS2019 python script to generate the dataset.json file, which looks like this
```
{
    "description": "nothing",
    "labels": {
        "0": "background",
        "1": "edema",
        "2": "non-enhancing",
        "3": "enhancing"
    },
    "licence": "see BraTS2019 license",
    "modality": {
        "0": "T1",
        "1": "T1ce",
        "2": "T2",
        "3": "FLAIR"
    },
    "name": "BraTS2019",
    "numTest": 0,
    "numTraining": 231,
    "reference": "see BraTS2019",
    "release": "0.0",
    "tensorImageSize": "4D",
    "test": [],
    "training": [
        {
            "image": "./imagesTr/HGG__TCGA-02-0003.nii.gz",
            "label": "./labelsTr/HGG__TCGA-02-0003.nii.gz"
        }, ...
}
```

I'm aware that this error is usually caused by labels not being consecutive in the ground truth segmentation files. However, I've used np.unique on each of my label files, and all of them are contained in [0, 1, 2, 3]. In fact all of them are either [0, 1, 2, 3], [0, 2], [0, 1, 2] or [0, 2, 3].

Any ideas? Many thanks!

Cheers, 
hyt35

**Comment by FabianIsensee** [comment]
Please look in the dataset_conversion folder. There should be an example for BraTS 2019 (https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/dataset_conversion/Task043_BraTS_2019.py). Just use that and it will work.
Best,
Fabian

**Comment by hyt35** [comment]
Thanks for your quick reply Fabian!

I've used that code to convert my own dataset to the nnUNet format already, and generate the dataset.json file. The data in the nnUNet_raw_data folder has these consecutive labels already. 

I first delete the Task100_BraTS folder under nnUNet_preprocessed. I then run `nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity` which returns no errors. Running it again however returns the same CUDA error. Any ideas? Cheers

**Comment by hyt35** [comment]
Fixed. Changed task id from 100 to 101, deleted nnUNet_cropped_data, nnUNet_preprocessed and nnUNet_trained_models, then reprocessed. Probably some residual data somewhere.

**Comment by FabianIsensee** [comment]
Ah indeed. Cropped data must be deleted manually sometimes. Sorry, i should have known that this was it
