### ISSUE TITLE
MultiThreadedAugmenter.abort_event was set, something went wrong. 

### ISSUE THREAD

**Issue by hanwinbi** [MIC-DKFZ/nnUNet#313]
Hi Febian,

Thanks for your awesome program.

When I run `nnUNet_train` on my device, I came across the `MultiThread` error below and do not know how to solve it
```
2020-09-07 08:59:38.414363: lr: 0.01
using pin_memory on device 0
Exception in background worker 2:
 'class_locations'
Traceback (most recent call last):
  File "/datasets/users/bihanwen/env/nnunet/bin/nnUNet_train", line 10, in <module>
    sys.exit(main())
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 416, in run_training
    ret = super().run_training()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 320, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 405, in run_training
    _ = self.tr_gen.next()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 203, in __next__
    item = self.__get_next_item()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x7f52c34c0f70>
Traceback (most recent call last):
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 287, in __del__
    self._finish()
  File "/datasets/users/bihanwen/env/nnunet/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 262, in _finish
    while self.pin_memory_thread.is_alive() and start + timeout > time():
AttributeError: 'NoneType' object has no attribute 'is_alive'
```
OS: Ubuntu 18.04
GPU: RTX 2070 8GB
CUDA Version: 11.0

**Comment by FabianIsensee** [comment]
Hi,
thanks for the bug report. This is a known issue that I fixed yesterday. Please try `pip install --upgrade nnunet` and it should be fixed.
Best,
Fabian
