### ISSUE TITLE
Training errors in docker  nvcr.io/nvidia/pytorch:20.09-py3

### ISSUE THREAD

**Issue by ruifenggong** [MIC-DKFZ/nnUNet#346]
Hi Fabian,

Thank you for your great work!

When I directly use pytorch1.6 to train on RTX2080TI, it takes nearly 400 seconds to train an epoch.

 In one of the issues you mentioned, you suggest that one can use a Pytorch with cuda11 and cudnn8.0.2 to speed up the training.

 I used `docker pull nvcr.io/nvidia/pytorch:20.09-py3` to get the image and deployed it on my machine. However, an error message occurred during training. Could you give me some suggestions?

By the way ,I can use the same dataset and seting to train in my real machine.

Thanks

```
root@eaec98078ce3:/workspace/nnUNet_preprocessed# nnUNet_train 3d_fullres nnUNetTrainerV2 66 4 

Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  4
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 64, 192, 192]), 'median_patient_size_in_voxels': array([117, 285, 285]), 'current_spacing': array([1.7987096 , 1.17513352, 1.17513352]), 'original_spacing': array([1.        , 0.65332031, 0.65332031]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

stage:  1
{'batch_size': 2, 'num_pool_per_axis': [4, 5, 5], 'patch_size': array([ 64, 192, 192]), 'median_patient_size_in_voxels': array([210, 512, 512]), 'current_spacing': array([1.        , 0.65332031, 0.65332031]), 'original_spacing': array([1.        , 0.65332031, 0.65332031]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 1 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /workspace/nnUNet_preprocessed/Task066_hepaticduct/nnUNetData_plans_v2.1
###############################################
loading dataset
loading all case properties
unpacking dataset
done
2020-10-16 13:07:13.017121: lr: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/conda/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_781_2606105346>
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/workspace/nnUNet-1.6.4/nnunet/run/run_training.py", line 142, in main
    trainer.run_training()
  File "/workspace/nnUNet-1.6.4/nnunet/training/network_training/nnUNetTrainerV2.py", line 420, in run_training
    ret = super().run_training()
  File "/workspace/nnUNet-1.6.4/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/workspace/nnUNet-1.6.4/nnunet/training/network_training/network_trainer.py", line 402, in run_training
    _ = self.tr_gen.next()
  File "/opt/conda/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/opt/conda/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/opt/conda/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
root@eaec98078ce3:/workspace/nnUNet_preprocessed# 
```

**Comment by FabianIsensee** [comment]
A quick google search reveals: start your docker with `--ipc=host`

**Comment by ruifenggong** [comment]
> A quick google search reveals: start your docker with `--ipc=host`

Thanks for pointing that out. 

It works!
