### ISSUE TITLE
Erorr run pretrained model  prostate example

### ISSUE THREAD

**Issue by agatadefr** [MIC-DKFZ/nnUNet#374]
Hi Guys,

I am trying to run example with pretrained model. I managed to  download, convert and install dataset from Decathlon and model. But now I am getting error when I am trying to run predict 
my cmd: 
**nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task005_Prostate/imagesTs/ -o /Agata/nnUNet/nnUNet_preprocessed/ -t 5 -m 3d_fullres --disable_tta -f 0** 

Traceback (most recent call last):
  File "/p/home/.local/bin/nnUNet_predict", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')()
  File "/p/home/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/p/home/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/p/home/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/p/home/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/p/data/Agata/nnUNet/nnUNet/nnunet/inference/predict_simple.py", line 19, in <module>
    from nnunet.inference.predict import predict_from_folder
  File "/p/data/Agata/nnUNet/nnUNet/nnunet/inference/predict.py", line 29, in <module>
    from nnunet.postprocessing.connected_components import load_remove_save, load_postprocessing
  File "/p/data/Agata/nnUNet/nnUNet/nnunet/postprocessing/connected_components.py", line 22, in <module>
    from nnunet.evaluation.evaluator import aggregate_scores
  File "/p/data/oncology_imaging/Agata/nnUNet/nnUNet/nnunet/evaluation/evaluator.py", line 23, in <module>
    import pandas as pd
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/series.py", line 3981, in <module>
    Series._add_series_or_dataframe_operations()
  File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/generic.py", line 8899, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  **File "/p/apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/core/window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: /pstore/apps/GCC/4.8.4/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /apps/Python/3.7.1-2018.12/lib/python3.7/site-packages/pandas/_libs/window.cpython-37m-x86_64-linux-gnu.so)**

Pandas seems to work fine ... 

Could anyone help me please ? 

Best,
Agata

**Comment by FabianIsensee** [comment]
This problem is not related to nnU-Net. Please try to google it.
My first attempt: https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error
