### ISSUE TITLE
What's the rapid way to stop data augmentation?

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/nnUNet#38]
Hi Fabian,

I want to **train a model without data augmentation**. What's the rapid way to stop data augmentation? 

comment these parameters or something else?
https://github.com/MIC-DKFZ/nnUNet/blob/cabe8fc4ded9fba26f462ccfe0113cd0cddfb2d0/nnunet/training/data_augmentation/default_data_augmentation.py#L28-L38

Looking forward to your reply.

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun Ma,
replace get_default_augmentation with the all new get_no_augmentation which I will push in 1 Minute.
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

Thank you so much for your help.
I replace get_default_augmentation with the new `get_no_augmentation` as following:

![image](https://user-images.githubusercontent.com/19947331/62787427-ae134200-ba92-11e9-81f9-03c3c93e4150.png)

However, following error occurred:
```python
I am using data from this folder:  path to/nnUNet
###############################################
2019-08-09 10:42:58.697883: Using dummy2d data augmentation
2019-08-09 10:42:58.727254: unpacking dataset
2019-08-09 10:42:58.879633: done
gpu 0
gpu 0
2019-08-09 10:43:07.812761:
epoch:  0
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/nnunet/training/network_training/nnUNetTrainer                  .py", line 260, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/nnunet/training/network_training/network_train                  er.py", line 339, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/nnunet/training/network_training/network_train                  er.py", line 520, in run_iteration
    output = self.network(data)
  File "/home/jma/anaconda3/envs/torch10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/nnunet/network_architecture/generic_UNet.py",                   line 374, in forward
    x = torch.cat((x, skips[-(u + 1)]), dim=1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 15 and 16 in dimension 3 at /opt/conda/conda-bl                  d/pytorch_1549628766161/work/aten/src/THC/generic/THCTensorMath.cu:83

```

If I go back to original augmentation function, everything is ok.
Could you share your insights on this error at your convenience?

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi Jun,
sorry I forgot to mention that you need to adapt the patch size of the basic generators.
Have a look at nnUNetTrainerNoDA. I just pushed it. This one should work.
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

Yes, it works now.
I really appreciate your help.

Best,
Jun

**Comment by FabianIsensee** [comment]
Happy to help :-)
Best,
Fabian

**Comment by JunMa11** [comment]
Hi @FabianIsensee ,

A quick question. We **can not delete** the `npz` files in preprocessing folder after unpacking finished, right?
I do that but get following error.

```
Exception in worker 0
Traceback (most recent call last):
  File "/home/jma/anaconda3/envs/torch10/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 46,
    item = next(data_loader)
  File "/home/jma/anaconda3/envs/torch10/lib/python3.6/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/nnunet/training/dataloading/dataset_loading.pynerate_train_batch
    selected_keys = np.random.choice(self.list_of_keys, self.batch_size, True, None)
  File "mtrand.pyx", line 1125, in mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
gpu 0
pin_memory_loop exiting...
Traceback (most recent call last):
  File "run/run_training.py", line 103, in <module>
    trainer.run_training()
  File "/nnunet/training/network_training/nnUNetTrainer run_training
    super(nnUNetTrainer, self).run_training()
  File "/nnunet/training/network_training/network_trainin run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/nnunet/training/network_training/network_trainin run_iteration
    data_dict = next(data_generator)
  File "/home/jma/anaconda3/envs/torch10/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190,
    item = self.__get_next_item()
  File "/home/jma/anaconda3/envs/torch10/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 172,m
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed

```

Best,
Jun

**Comment by FabianIsensee** [comment]
Hi,
this is one of many things I could have done better. You need the npz files, otherwise it won't wort :-/
Best,
Fabian

**Comment by JunMa11** [comment]
Hi Fabian,

Got it. Thank you very much.

Best,
Jun

**Comment by ArmanAvesta** [comment]
Hi Fabian,

I'm trying to run nnUNet training without data augmentation. I copied nnUNetTrainerV2_noDA.py to /home/arman_avesta/nnUNet/nnunet/training/network_training and ran this command:

nnUNet_train 3d_fullres nnUNetTrainerV2_noDA Task504_rhipp60 $FOLD

I'm receiving this error:


###############################################
I am running the following nnUNet: 3d_fullres
My trainer class is:  None
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'T1'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([137, 170, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/arman_avesta/nnUNet/data/nnUNet_preprocessed/Task504_rhipp60/nnUNetData_plans_v2.1
###############################################
Traceback (most recent call last):
  File "/home/arman_avesta/.local/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/arman_avesta/nnUNet/nnunet/run/run_training.py", line 140, in main
    raise RuntimeError("Could not find trainer class in nnunet.training.network_training")
RuntimeError: Could not find trainer class in nnunet.training.network_training

I would appreciate your help :) 

Arman
