### ISSUE TITLE
 MultiThreadedAugmenter error 

### ISSUE THREAD

**Issue by Wapity** [MIC-DKFZ/nnUNet#398]
Hello Fabian and all, 
I must say first it is an impressive pipeline,
I have a similar issue that was found before with  MultiThreadedAugmenter , 
I am running 3dfull_res training, the plan_and_preprocess went smooth, I tried the idea of deleting the .npy but it doesnt resolve,
do you think it it because of RAM? I see the free swap is null , there is place on the disk 
Is it possible to prevent multithreading? 
I am stuck 
Thank you very much for your help 

I ran 
`MKL_NUM_THREADS=1,NUMEXPR_NUM_THREADS=1,OMP_NUM_THREADS=1,CUDA_VISIBLE_DEVICES=2 nnUNet_train 3d_fullres nnUNetTrainerV2 4 0` 
<img width="1142" alt="error" src="https://user-images.githubusercontent.com/28689667/99971571-a2d64980-2d9d-11eb-8555-b501a4def29c.png">
<img width="225" alt="error_swap" src="https://user-images.githubusercontent.com/28689667/99971616-b8e40a00-2d9d-11eb-959a-dc217f1e7e06.PNG">

Actually when I reiterate the other errors appear : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: unable to write to file </torch_28907_4020605154>
```
or 
```
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/workspace/thera/server/thera/python/learning/projects/biogen/lesion_classifier/semantic_segmentation/nnUNet/nnunet/run/run_training.py", line 157, in main
    trainer.run_training()
  File "/workspace/thera/server/thera/python/learning/projects/biogen/lesion_classifier/semantic_segmentation/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 424, in run_training
    ret = super().run_training()
  File "/workspace/thera/server/thera/python/learning/projects/biogen/lesion_classifier/semantic_segmentation/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 323, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/workspace/thera/server/thera/python/learning/projects/biogen/lesion_classifier/semantic_segmentation/nnUNet/nnunet/training/network_training/network_trainer.py", line 403, in run_training
    _ = self.val_gen.next()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 203, in __next__
    self._start()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 239, in _start
    self._queues.append(Queue(self.num_cached_per_queue))
  File "/usr/lib/python3.8/multiprocessing/context.py", line 103, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/usr/lib/python3.8/multiprocessing/context.py", line 68, in Lock
    return Lock(ctx=self.get_context())
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 162, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/usr/lib/python3.8/multiprocessing/synchronize.py", line 57, in __init__
    sl = self._semlock = _multiprocessing.SemLock(
OSError: [Errno 28] No space left on device
```
while I have still 400Go free on the ssd, is it trying to write on a bad location ?

**Comment by FabianIsensee** [comment]
`RuntimeError: unable to write to file </torch_28907_4020605154>`

see here https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-training-in-docker-container-runtimeerror-unable-to-write-to-file-torch_781_2606105346

(in case you are running this in a docker)

swap is not automatically increased, you need to do that yourself. But i don't think this is the problem. A screenshot of htop while the training runs (shortly before it crashes) would be very helpful.
Best,
Fabian

**Comment by Wapity** [comment]
Thank you for your reply, yes I will reload the docker container soon when we will give me access, with your flag 
I took screenshots of htop as you said, the first one is baseline and the second one just before it crashes (took on the fly haha) 
<img width="1011" alt="htopbase" src="https://user-images.githubusercontent.com/28689667/100104766-e0eb7000-2e66-11eb-85d7-6bd96c8036d1.PNG">
<img width="1011" alt="htop2" src="https://user-images.githubusercontent.com/28689667/100104759-df21ac80-2e66-11eb-95ef-e53351891385.PNG">
I thought it could be a wrong 'no space left on disk' and tried solutions in https://www.maketecheasier.com/fix-linux-no-space-left-on-device-error/ but couldnt be useful
Is it possible to stop multithreading otherwise? export MKL_NUM_THREADS=1 doesnt help much more

**Comment by FabianIsensee** [comment]
Can you please sort htop by CPU utilization?
Your ram is not a problem - you only use 30GB out of 128GB

**Comment by Wapity** [comment]
Ah yes : 
<img width="1011" alt="htop_3" src="https://user-images.githubusercontent.com/28689667/100106697-2872fb80-2e69-11eb-82b2-8c9ef82ef258.PNG">
(I understand, you think the flag --ipc=host could increase the shared memory, which here is too limited and causes the crash?

**Comment by Wapity** [comment]
Hmm when I ran this again and again another training crashed with `ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).` so I stopped all other trainings and now it is showing the `RuntimeError: unable to write to file </torch_28907_4020605154>` so sounds like it is the flag that will solve this and that it needs a lot of shared memory? we have 48 cpus but I share them, I didnt think it would be that consuming ?

**Comment by FabianIsensee** [comment]
This shared memory thing has nothing to do with the number of CPUs. Just set the flag and the problem will go away :-)
Best,
Fabian

**Comment by Wapity** [comment]
I did that and it disappeared like you said, seems to be working like a charm,
Thank you !
Best regards
