### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by goodsave** [MIC-DKFZ/nnUNet#412]
When I finished executing the `nnUNet_find_best_configuration -m 3d_fullres -t 100` command, the following error occurred:
```
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

running missing postprocessing for Task100_HeadEyesTest_20201127 and model 3d_fullres
WARNING!
[Errno 2] No such file or directory: '/data/Data/nnUNet/RESULTS_FOLDER/nnUNet/3d_fullres/Task100_HeadEyesTest_20201127/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/validation_raw'

Found the following valid models:
 []
Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_find_best_configuration", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_find_best_configuration')())
  File "/home/allen/Project/nnUNet/nnunet/evaluation/model_selection/figure_out_what_to_submit.py", line 153, in main
    best = np.max(foreground_dices)
  File "<__array_function__ internals>", line 6, in amax
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2668, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
```

How to solve this problem？

**Comment by FabianIsensee** [comment]
It seems like you do not have trained this model yet. nnU-Net even tells where it thinks the model should be located. Maybe you used a different trainer class?
Best,
Fabian

**Comment by goodsave** [comment]
I just execute the following command according to the document:
```
nnUNet_plan_and_preprocess -t 100 --verify_dataset_integrity
nnUNet_train 3d_fullres nnUNetTrainerV2 100 0
nnUNet_train 3d_fullres nnUNetTrainerV2 100 1
nnUNet_train 3d_fullres nnUNetTrainerV2 100 2
nnUNet_train 3d_fullres nnUNetTrainerV2 100 3
nnUNet_train 3d_fullres nnUNetTrainerV2 100 4
[Here, all models iterate about 140 + times, and then manually terminate the command.]
nnUNet_find_best_configuration -m 3d_fullres -t 100
```
[And then there is this mistake.]

**Comment by FabianIsensee** [comment]
Your mistake is manually terminating the command. Let it finish...

**Comment by goodsave** [comment]
When training is on, does it stop automatically? If it will stop automatically, when will it stop automatically?

**Comment by FabianIsensee** [comment]
Training always runs for 1000 epochs.
Best,
Fabian

**Comment by goodsave** [comment]
OK,  thank you
