### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ProfessorHuang** [MIC-DKFZ/nnUNet#416]
Hi Fabian,
When I ran  
`nnUNet_train 3d_fullres nnUNetTrainerV2 2 0`
something went wrong
###############################################
loading dataset
loading all case properties
unpacking dataset
done
2020-12-03 20:01:59.975011: lr: 0.01
using pin_memory on device 0
using pin_memory on device 0
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/hzy/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/hzy/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/envs/hzy/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 102, in results_loop
    item = current_queue.get()
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/queues.py", line 116, in get
    return _ForkingPickler.loads(res)
  File "/root/anaconda3/envs/hzy/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 282, in rebuild_storage_fd
    fd = df.detach()
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/anaconda3/envs/hzy/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
2020-12-03 20:02:34.069242: 
epoch:  0
Traceback (most recent call last):
  File "/root/anaconda3/envs/hzy/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/data/hzy/nnUNet/nnUNet/nnunet/run/run_training.py", line 151, in main
    trainer.run_training()
  File "/data/hzy/nnUNet/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 431, in run_training
    ret = super().run_training()
  File "/data/hzy/nnUNet/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/data/hzy/nnUNet/nnUNet/nnunet/training/network_training/network_trainer.py", line 446, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/data/hzy/nnUNet/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 230, in run_iteration
    data_dict = next(data_generator)
  File "/root/anaconda3/envs/hzy/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/root/anaconda3/envs/hzy/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

Can you give me some advice? :-)

**Comment by FabianIsensee** [comment]
Are you using docker?

**Comment by ProfessorHuang** [comment]
Yes, I ran my code in the docker environment of Lab's server.

**Comment by FabianIsensee** [comment]
Maybe this: https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md#nnu-net-training-in-docker-container-runtimeerror-unable-to-write-to-file-torch_781_2606105346

**Comment by ProfessorHuang** [comment]
Thank you Fabian. Running docker with --ipc=host flag helps.
