### ISSUE TITLE
ModuleNotFoundError: No module named 'batchgenerators.dataloading.fast_multi_threaded_augmenter'

### ISSUE THREAD

**Issue by cgrain** [MIC-DKFZ/nnUNet#444]
Today, I installed nnUnet using `git clone`, because I might want to augment the system or at least understand it thoroughly. I encountered the problem described in the title while I ran `nnUNet_plan_and_preprocess` as was shown in the example. I found that this is a new feature that will be updated soon in the batchgenerators. The trick I used was to checkout tag `v1.6.5`. This solved the problem! My Issue is therefore mainly for other uses trying to install this and therefore a little bit different: Could you update the installation steps so that it includes this step? (`git checkout tags/v1.6.5 -b v1.6.5_master`)

Or well, make sure that the published version of batchgenerators also has the `fast_multi_threaded_augmenter`, that would be even more helpful :)

**Comment by MajesticBrownBear** [comment]
Hi All.
I was testing the nnUnet but had the same issue with 'batchgenerators.dataloading.fast_multi_threaded_augmenter'.
I installed v1.6.5 and it is working. 
Cheers!

**Comment by abergsneider** [comment]
Hi all, thanks for sharing this. I checked out v.1.6.5 and it worked for me as well.

Not sure if it helps but I'll attach my terminal output with the error for reference:

-------------------------------   Terminal Output   ------------------------------- 

**aberg@360074c714d5:/workspace/nnUNet$** nnUNet_train 3d_fullres nnUNetTrainerV2 121 0 -npz


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-jeauspiy because the default path (/home/aberg/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/opt/conda/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/nnUNet/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/workspace/nnUNet/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/workspace/nnUNet/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/workspace/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 34, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import default_3D_augmentation_params, \
  File "/workspace/nnUNet/nnunet/training/data_augmentation/default_data_augmentation.py", line 19, in <module>
    from batchgenerators.dataloading.fast_multi_threaded_augmenter import FasterMultiThreadedAugmenter
ModuleNotFoundError: No module named 'batchgenerators.dataloading.fast_multi_threaded_augmenter'

**Comment by FabianIsensee** [comment]
Hi,
sorry for that. This package exists in a different branch of batchgenerators and I have been experimenting with it. This is my bad - I will fix this problem :-)
Best,
Fabian

**Comment by FabianIsensee** [comment]
Should be fixed now :-)

**Comment by abergsneider** [comment]
Sweet thanks!
