### ISSUE TITLE
'TypeError: 'list' object cannot be interpreted as an integer' when training on 2d UNet network

### ISSUE THREAD

**Issue by DavidTu21** [MIC-DKFZ/nnUNet#445]
Hi there,

I am facing an issue when training with the 2d UNet network, and the error message is shown as follow:

-------------------------------------------------------------------------------------------------------------------------------------------
Please cite the following paper when using nnUNet:

Isensee, Fabian, et al. "nnU-Net: Breaking the Spell on Successful Medical Image Segmentation." arXiv preprint arXiv:1904.08128 (2019).

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet
###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainer.nnUNetTrainer'>
For that I will be using the following configuration:
num_classes:  26
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region OrderedDict([((21,), False), ((23,), False), ((9,), False), ((11,), False), ((13,), False), ((24,), False), ((15,), False), ((1,), False), ((28,), False), ((3,), False), ((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 28), False), ((5,), False), ((16,), False), ((7,), False), ((18,), False), ((20,), False), ((22,), False), ((8,), False), ((10,), False), ((12,), False), ((14,), False), ((25,), False), ((2,), False), ((4,), False), ((6,), False), ((17,), False), ((19,), False)])
min_region_size_per_class OrderedDict([(1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (28, 0.0)])
min_size_per_class OrderedDict([(1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (28, 0.0)])
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 20, 'num_pool_per_axis': [6, 6], 'patch_size': array([384, 384]), 'median_patient_size_in_voxels': array([484, 345, 333]), 'current_spacing': array([1.        , 0.92285156, 1.        ]), 'original_spacing': array([1.        , 0.92285156, 1.        ]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  nnUNet_preprocessed/Task56_Verse/nnUNet_2D
###############################################
2020-12-25 10:49:38.536654: unpacking dataset
2020-12-25 10:52:35.006111: done
2020-12-25 10:52:39.957045: Unable to plot network architecture:
2020-12-25 10:52:39.959715: No module named 'hiddenlayer'
2020-12-25 10:52:39.962580: 
epoch:  0
Traceback (most recent call last):
  File "run/run_training.py", line 109, in <module>
    trainer.run_training()
  File "/datasets/work/d61-singular-seg/reference/VerSe2020-Data/David/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 284, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/datasets/work/d61-singular-seg/reference/VerSe2020-Data/David/nnUNet-master/nnunet/training/network_training/network_trainer.py", line 357, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/datasets/work/d61-singular-seg/reference/VerSe2020-Data/David/nnUNet-master/nnunet/training/network_training/network_trainer.py", line 524, in run_iteration
    data_dict = next(data_generator)
  File "/home/tu012/.local/lib/python3.6/site-packages/batchgenerators/dataloading/single_threaded_augmenter.py", line 45, in __next__
    item = next(self.data_loader)
  File "/home/tu012/.local/lib/python3.6/site-packages/batchgenerators/dataloading/data_loader.py", line 126, in __next__
    return self.generate_train_batch()
  File "/datasets/work/d61-singular-seg/reference/VerSe2020-Data/David/nnUNet-master/nnunet/training/dataloading/dataset_loading.py", line 467, in generate_train_batch
    valid_slices = np.where(np.sum(case_all_data[-1] == selected_class, axis=[i for i in range(3) if i != leading_axis]))[0]
  File "<__array_function__ internals>", line 6, in sum
  File "/home/tu012/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2229, in sum
    initial=initial, where=where)
  File "/home/tu012/.local/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: 'list' object cannot be interpreted as an integer
-------------------------------------------------------------------------------------------------------------------------------------
It is fine when training with 3d fullres and 3d cascade UNet network and no errors would be shown. I suspect this error is because of the 'batchgenerators' package and I have upgrade the package the same issues still occur. I would really appreciate that if you could give me some insights on this. 

PS. I am using the SingleThreadAugumentor and set OMP_NUM_Threads = 1.

Thank you in advance for your time.

**Comment by FabianIsensee** [comment]
that is a strange one. Are you on the most recent version of nnU-Net?
