### ISSUE TITLE
Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by Karol-G** [MIC-DKFZ/nnUNet#447]
Hi,

I get the following error at epoch 0 when starting the training on my dataset:

```

Exception in background worker 7:
 Cannot load file containing pickled data when allow_pickle=False
Traceback (most recent call last):
  File "/gris/gris-f/homelv/user/anaconda3/envs/pytorch/bin/nnUNet_train", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/run/run_training.py", line 155, in main
    trainer.run_training()
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 432, in run_training
    ret = super().run_training()
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/training/network_training/network_trainer.py", line 446, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 231, in run_iteration
    data_dict = next(data_generator)
  File "/gris/gris-f/homelv/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/gris/gris-f/homelv/user/anaconda3/envs/pytorch/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
```

The real error should be:
`Cannot load file containing pickled data when allow_pickle=False`

I used the following command for training:
`nnUNet_train 3d_fullres nnUNetTrainerV2 Task101_MMRF 0`

Any ideas?

Best
Karol

**Comment by FabianIsensee** [comment]
Hi,
can you please delete the preprocessed data and rerun nnUNet_plan_and_preprocess? Does that fix it?
Best,
Fabian

**Comment by Karol-G** [comment]
Hi,

I have done that already, sadly I get the same error.

Best
Karol

**Comment by FabianIsensee** [comment]
What version of nnU-Net are you on? Can you upgrade to the latest version?

**Comment by Karol-G** [comment]
The newest now, I was just a couple commits behind before. But now, before I get to the error I get the following error:

```
Traceback (most recent call last):
  File "/gris/gris-f/homelv/user/anaconda3/envs/pytorch/bin/nnUNet_train", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')()
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/run/run_training.py", line 156, in main
    trainer.initialize(not validation_only)
  File "/gris/gris-f/homelv/user/remote_projects/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 105, in initialize
    self.tr_gen, self.val_gen = get_moreDA_augmentation(
TypeError: get_moreDA_augmentation() got an unexpected keyword argument 'use_FasterMultiThreadedAugmenter'
```

I believe you didn't update the default_data_augmentation_class.py.

Best
Karol

Happy new year btw ;)

**Comment by FabianIsensee** [comment]
Hi,
you are correct. Apologies. Fixed now.
Best,
Fabian

**Comment by Karol-G** [comment]
Thanks! It seems everything is working now. No idea what originally caused the error.

**Comment by annukkaa** [comment]
Hello, I'm also getting the same error!

`Cannot load file containing pickled data when allow_pickle=False`

I've just updated nnunet to 1.6.6

**Comment by FabianIsensee** [comment]
Strange. But glad to hear it works now. Maybe your drive is defective? 
Best,
Fabian
