### ISSUE TITLE
cannot import name 'SpatialTransform_2' from 'batchgenerators.transforms'

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#456]
After the Holidays I try to run a new prediction, however, I'm running into an error that I don't recall from before the Holidays.
Though I recall having issues with Pillow, since I need both a new version for 'batchgenerators', and an older version (6.2.2) for itkwidgets. So I am suspicious about the pip install requirements, but the error stack trace is also a bit strange:
What I noted is that it seems to require BraTS2020 stuff, even though I'm using a completely different task (Task114_heart_MNMs)

The error stack:

using model stored in  /home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 2 unique case ids, here are some examples: ['501_sbtfe_ka_ms_ED' '501_sbtfe_ka_ms_ED']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 2
number of cases that still need to be predicted: 0
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_0', '/home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_1', '/home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_2', '/home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_3', '/home/pieter/pretrained_models/nnUNet/2d/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_4']
Traceback (most recent call last):
  File "/home/pieter/.venv/bin/nnUNet_predict", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')()
  File "/home/pieter/unetcart/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/pieter/unetcart/nnUNet/nnunet/inference/predict.py", line 630, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/pieter/unetcart/nnUNet/nnunet/inference/predict.py", line 182, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision, checkpoint_name=checkpoint_name)
  File "/home/pieter/unetcart/nnUNet/nnunet/training/model_restore.py", line 140, in load_model_and_checkpoint_files
    trainer = restore_model(join(folds[0], "%s.model.pkl" % checkpoint_name), fp16=mixed_precision)
  File "/home/pieter/unetcart/nnUNet/nnunet/training/model_restore.py", line 60, in restore_model
    tr = recursive_find_python_class([search_in], name, current_module="nnunet.training.network_training")
  File "/home/pieter/unetcart/nnUNet/nnunet/training/model_restore.py", line 37, in recursive_find_python_class
    tr = recursive_find_python_class([join(folder[0], modname)], trainer_name, current_module=next_current_module)
  File "/home/pieter/unetcart/nnUNet/nnunet/training/model_restore.py", line 37, in recursive_find_python_class
    tr = recursive_find_python_class([join(folder[0], modname)], trainer_name, current_module=next_current_module)
  File "/home/pieter/unetcart/nnUNet/nnunet/training/model_restore.py", line 28, in recursive_find_python_class
    m = importlib.import_module(current_module + "." + modname)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pieter/unetcart/nnUNet/nnunet/training/network_training/competitions_with_custom_Trainers/BraTS2020/nnUNetTrainerV2BraTSRegions_moreDA.py", line 19, in <module>
    from nnunet.training.data_augmentation.data_augmentation_insaneDA2 import get_insaneDA_augmentation2
  File "/home/pieter/unetcart/nnUNet/nnunet/training/data_augmentation/data_augmentation_insaneDA2.py", line 16, in <module>
    from batchgenerators.transforms import DataChannelSelectionTransform, SegChannelSelectionTransform, SpatialTransform, \
ImportError: cannot import name 'SpatialTransform_2' from 'batchgenerators.transforms' (/home/pieter/.venv/lib/python3.8/site-packages/batchgenerators/transforms/__init__.py)

**Comment by FabianIsensee** [comment]
What version of batchgenerators do you have? You should have v0.21. Please try upgrading batchgenerators and let me know if that fixes the issue
Best,
Fabian

**Comment by FabianIsensee** [comment]
ah I think I found it :-)

**Comment by pkuppens** [comment]
> What version of batchgenerators do you have? You should have v0.21. Please try upgrading batchgenerators and let me know if that fixes the issue
> Best,
> Fabian

Indeed I hope you found it, because batchgenerators is at the latest version:

(.venv) pieter@LAPTOP-EQO8NIP3:~/unetcart$ pip show batchgenerators
Name: batchgenerators
Version: 0.21
Summary: Data augmentation toolkit
Home-page: https://github.com/MIC-DKFZ/batchgenerators
Author: Division of Medical Image Computing, German Cancer Research Center
Author-email: f.isensee@dkfz-heidelberg.de
License: Apache License Version 2.0, January 2004
Location: /home/pieter/unetcart/.venv/lib/python3.8/site-packages
Requires: future, scikit-learn, pillow, scikit-image, unittest2, scipy, threadpoolctl, numpy
Required-by: nnunet

**Comment by FabianIsensee** [comment]
I did. If you update to the most recent master it should be fixed

**Comment by FabianIsensee** [comment]
(master of nnU-Net that is)

**Comment by pkuppens** [comment]
Did a git pull and setup.py install, and it works again..
