### ISSUE TITLE
 ImportError: cannot import name find_namespace_packages

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#474]
I try to install nnUNet in the "source code" mode, which is done by cloning the Github repository into my local drive. But when I execute the pip install -e . command, the program prompt:
```
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///data/home/amaxcuda9/Mlis1403/zhangge/nnUNet
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/setup.py'"'"'; __file__='"'"'/data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-JigOy0
         cwd: /data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/setup.py", line 1, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name find_namespace_packages
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I use Python 3.8. Any help? Thanks a lot!

**Comment by FabianIsensee** [comment]
Please run
`pip install -U setuptools`
and try again

**Comment by squaresoft2015** [comment]
Problem solved, thanks!

**Comment by Vinograduss** [comment]
> pip install -U setuptools

мне это помогло только после pip install --upgrade pip

**Comment by abcxubu** [comment]
It helped me. Thanks.
