### ISSUE TITLE
The requested pretrained model ('Task05_Prostate') is not available.

### ISSUE THREAD

**Issue by squaresoft2015** [MIC-DKFZ/nnUNet#481]
I tried to download pre-trained models from zenodo with built-in nnUNet command, but the program prompt:

```
Traceback (most recent call last):
  File "/data/home/amaxcuda9/anaconda3/envs/nnUNet/bin/nnUNet_download_pretrained_model", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_download_pretrained_model')())
  File "/data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py", line 291, in download_by_name
    download_and_install_pretrained_model_by_name(taskname)
  File "/data/home/amaxcuda9/Mlis1403/zhangge/nnUNet/nnunet/inference/pretrained_models/download_pretrained_model.py", line 210, in download_and_install_pretrained_model_by_name
    raise RuntimeError("\nThe requested pretrained model ('%s') is not available." % taskname)
RuntimeError:
The requested pretrained model ('Task05_Prostate') is not available.
```

I also tried to download with a third-part tool, but the speed is extremely slow. Is it the reason ?

**Comment by FabianIsensee** [comment]
nnUNet_print_available_pretrained_models

> Task005_Prostate
> Prostate Segmentation. 
> Segmentation targets are peripheral and central zone, 
> input modalities are 0: T2, 1: ADC. 
> Also see Medical Segmentation Decathlon, http://medicaldecathlon.com/


It's Task005_Prostate, not 05 :-)
