### ISSUE TITLE
Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by estherpuyol** [MIC-DKFZ/nnUNet#509]
Hello

I was trying to train a 2D nnUnet network (nnUNet_train 2d nnUNetTrainerV2 Task 0) and I got the exception below. I am not sure what could cause the problem as I've correctly trained the network before with the same data and I had no errors and I've double-checked that the RAM is not full. Do you have any suggestion?

Thank you

Exception error:

epoch:  0
Exception in background worker 2:
 Cannot load file containing pickled data when allow_pickle=False
2021-02-09 18:02:54.214045: train loss : 0.0807
Traceback (most recent call last):
  File ".../anaconda3/envs/MR_US_project/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "..../nnUNet/nnunet/run/run_training.py", line 160, in main
    trainer.run_training()
  File "..../nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 442, in run_training
    ret = super().run_training()
  File "..../nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "..../nnUNet/nnunet/training/network_training/network_trainer.py", line 463, in run_training
    l = self.run_iteration(self.val_gen, False, True)
  File "..../nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration
    data_dict = next(data_generator)
  File ".../anaconda3/envs/MR_US_project/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File ".../anaconda3/envs/MR_US_project/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by FabianIsensee** [comment]
This is you error: 'Cannot load file containing pickled data when allow_pickle=False'

Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.
Best,
Fabian

**Comment by ShadowTwin41** [comment]
Hey! 
I found the same error, but it only happens after a few epochs. I'm also running the other 4 folds, and they have no problems. What could it be?

**Comment by kennyha85** [comment]
> Hey! I found the same error, but it only happens after a few epochs. I'm also running the other 4 folds, and they have no problems. What could it be? I am using multiple GPUs (2), and a shared machine.

I also got the same error on nnUnetv2 which happens after a few epochs. I trained with 1 fold only. Do you got it fixed?

**Comment by ShadowTwin41** [comment]
Hey @kennyha85. It was corrupted data. Double check that all data is correct.

**Comment by Myrrolinz** [comment]
> Hey @kennyha85. It was corrupted data. Double check that all data is correct.

Hi, I'm experiencing the same problem now. Did you mean the .npz files were corrupted? Or the whole dataset has problem?

**Comment by FabianIsensee** [comment]
Rerun the preprocessing to make sure ;-) THis fixes the problem 99.9% of the time
