### ISSUE TITLE
AssertionError: only one anisotropic axis supported  -- AFTER the segmentation

### ISSUE THREAD

**Issue by pkuppens** [MIC-DKFZ/nnUNet#538]
I get the following assertion error when I use a 3d_fullres prediction model for Task114: `AssertionError: only one anisotropic axis supported
`

Question 1: I would expect such an error if voxel sizes would be different in all three axes, but I don't see that in my data, x,y = 1.25. How should I interpret this assertion violation?
Question 2: Initially I had this while segmenting 30 phases of a heartbeat with CINE/MRI. The prediction took 16m30s, before reporting this assertion violation and producing no results. Could this be an input validation before prediction instead, which would shorten the feedback loop? On a single 3D-volume, the segmentation fails after 48 seconds.

Remarks:

- the NIfTI is created from DICOM using Python dicom2nifti, where I disabled various validations, the slice stack that was produced is in the reversed order, so it wouldn't surprise me if there are flaws in my DICOM and NIfTI files or its conversion.
- the `separate z, order in z is 0 order inplane is 1` is a bit suspect because of the previous statement
- earlier predictions on different NIfTI/DICOM files were OK, so I expect that the pipeline/command I use is adequate.

----

Logging - Jupyter lab notebook, with %time enabled

Command:

%time !nnUNet_predict -i $INPUT_PREDICT_CINE -o $TEMP_3D_CINE --save_npz -t 114 -m 3d_fullres -tr nnUNetTrainerV2_MMS

Output:

```
Please cite the following paper when using nnUNet:
Fabian Isensee, Paul F. Jäger, Simon A. A. Kohl, Jens Petersen, Klaus H. Maier-Hein "Automated Design of Deep Learning Methods for Biomedical Image Segmentation" arXiv preprint arXiv:1904.08128 (2020).
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

using model stored in  /home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 1 unique case ids, here are some examples: ['501_sbtfe_ka_ms_phase00']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 1
number of cases that still need to be predicted: 1
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_0', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_1', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_2', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_3', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_4']
2021-03-02 15:59:41.335655: Using dummy2d data augmentation
using the following model files:  ['/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_1/model_final_checkpoint.model', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_2/model_final_checkpoint.model', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_3/model_final_checkpoint.model', '/home/pieter/pretrained_models/nnUNet/3d_fullres/Task114_heart_MNMs/nnUNetTrainerV2_MMS__nnUNetPlansv2.1/fold_4/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
preprocessing /mnt/f/CART-Tech/automatic_segmentation/ADVISE03_UMCU_002/nifti/predict_temp_3d/cine/501_sbtfe_ka_ms_phase00.nii.gz
using preprocessor GenericPreprocessor
before crop: (1, 15, 256, 256) after crop: (1, 15, 256, 256) spacing: [0.24944322 1.25       1.25      ] 

WARNING: axis has len 2, axis: [1 2], spacing: [0.24944322 1.25       1.25      ], target_spacing: [5.   1.25 1.25]
no separate z, order 3
no separate z, order 1
before: {'spacing': array([0.24944322, 1.25      , 1.25      ]), 'spacing_transposed': array([0.24944322, 1.25      , 1.25      ]), 'data.shape (data is transposed)': (1, 15, 256, 256)} 
after:  {'spacing': array([5.  , 1.25, 1.25]), 'data.shape (data is resampled)': (1, 1, 256, 256)} 

(1, 1, 256, 256)
This worker has ended successfully, no errors to report
predicting /mnt/f/CART-Tech/automatic_segmentation/ADVISE03_UMCU_002/nifti/predict_temp_3d/cine/501_sbtfe_ka_ms_phase00.nii.gz
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 24, 288, 288)
patch size: [ 24 288 288]
steps (x, y, and z): [[0], [0], [0]]
number of tiles: 1
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 24, 288, 288)
patch size: [ 24 288 288]
steps (x, y, and z): [[0], [0], [0]]
number of tiles: 1
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 24, 288, 288)
patch size: [ 24 288 288]
steps (x, y, and z): [[0], [0], [0]]
number of tiles: 1
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 24, 288, 288)
patch size: [ 24 288 288]
steps (x, y, and z): [[0], [0], [0]]
number of tiles: 1
prediction done
debug: mirroring True mirror_axes (0, 1, 2)
step_size: 0.5
do mirror: True
data shape: (1, 24, 288, 288)
patch size: [ 24 288 288]
steps (x, y, and z): [[0], [0], [0]]
number of tiles: 1
prediction done
inference done. Now waiting for the segmentation export to finish...
force_separate_z: None interpolation order: 1
separate z: True lowres axis [1 2]
separate z, order in z is 0 order inplane is 1
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/pieter/nnUNet/nnunet/inference/segmentation_export.py", line 99, in save_segmentation_nifti_from_softmax
    seg_old_spacing = resample_data_or_seg(segmentation_softmax, shape_original_after_cropping, is_seg=False,
  File "/home/pieter/nnUNet/nnunet/preprocessing/preprocessing.py", line 136, in resample_data_or_seg
    assert len(axis) == 1, "only one anisotropic axis supported"
AssertionError: only one anisotropic axis supported
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_predict", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')()
  File "/home/pieter/nnUNet/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/pieter/nnUNet/nnunet/inference/predict.py", line 627, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/pieter/nnUNet/nnunet/inference/predict.py", line 260, in predict_cases
    _ = [i.get() for i in results]
  File "/home/pieter/nnUNet/nnunet/inference/predict.py", line 260, in <listcomp>
    _ = [i.get() for i in results]
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
AssertionError: only one anisotropic axis supported
CPU times: user 1.13 s, sys: 613 ms, total: 1.74 s
Wall time: 48 s
```

**Comment by FabianIsensee** [comment]
Hi,
I would like to reproduce this issue. Could you please provide a sample image that I can work with? You can pick one of your images that failed and, if necessary for privacy reasons, replace all the voxel intensities with random values.
Best,
Fabian

**Comment by pkuppens** [comment]
@FabianIsensee , I don't mind sharing the original file confidentially via mail. I think it has the personally identifiable stuff removed. Feel free to provide an email address to pieter.kuppens@cart-tech.com for me to send it to.

**Comment by FabianIsensee** [comment]
Please try again, it should be fixed now.
Your image data has the wrong spacing, so the 3d_fullres model only produces nonsense. There is nothing I can do about that - nnU-Net needs to be able to rely on the correct spacing information being given. At least it doesn't crash anymore ;-)
Best,
Fabian

**Comment by pkuppens** [comment]
@FabianIsensee , indeed, I got it to work here as well, with a little trouble. Mostly cleaing up my personal fork and older (sudo) pip installs of nnUNet, in- and outside of virtualenvs.

Making a fresh clone and 'python setup.py install' (without virtualenv) finally did the trick.,
