### ISSUE TITLE
Error on patch-based 2D networks

### ISSUE THREAD

**Issue by rohilG** [MIC-DKFZ/nnUNet#542]
When trying to run ```nnUNet_plan_and_preprocess -t 120 -pl3d None --verify_dataset_integrity``` with a Volta GPU ([link](https://docs.computecanada.ca/wiki/Graham#Volta_GPU_nodes_on_Graham)) on 16B of RAM, I encounter the following issue:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/nnUNet_plan_and_preprocess", line 10, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.7/site-packages/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 131, in main
    exp_planner.plan_experiment()
  File "/home/user/.local/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_2DUNet.py", line 130, in plan_experiment
    num_classes=len(all_classes) + 1),
  File "/home/user/.local/lib/python3.7/site-packages/nnunet/experiment_planning/experiment_planner_baseline_2DUNet_v21.py", line 57, in get_properties_for_stage
    raise RuntimeError("This framework is not made to process patches this large. We will add patch-based "
RuntimeError: This framework is not made to process patches this large. We will add patch-based 2D networks later. Sorry for the inconvenience
```

This is particularly weird since Task120 is an example within nnUNet

**Comment by FabianIsensee** [comment]
How did you install nnU-Net? If you install the current master branch it should work

**Comment by rohilG** [comment]
Thanks! The latest pull addresses this.
