### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'softmax'  at validation step

### ISSUE THREAD

**Issue by aprilaugust** [MIC-DKFZ/nnUNet#552]
Hi!
I modified the code to generate additional outputs, but still keep the original output as origin and train on my dataset. The training and online evaluation work perfectly, but i got this issue at validate function for full evaluation which did not use deep supervision. Especially, 2D and 3D both got this issue. 

Would you mind giving some suggestions?

Thank you for the great work!

===
outputs from deep supervision

epoch:  0
2021-03-11 08:13:59.286392: train loss : 0.5194
2021-03-11 08:14:28.048331: validation loss: 0.3127
2021-03-11 08:14:28.049443: Average global foreground Dice: [0.2353590095158386]
2021-03-11 08:14:28.049974: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-11 08:14:28.599265: lr: 0.0
2021-03-11 08:14:28.599925: This epoch took 219.169982 s

2021-03-11 08:14:28.635379: saving checkpoint...
2021-03-11 08:14:29.137591: done, saving took 0.54 seconds
1 (2, 136, 168, 137)

 self.fp16:  True

debug: mirroring True mirror_axes (0, 1)
Traceback (most recent call last):

 outputs from NO deep supervision

 File "/opt/conda/envs/nnunet/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
 
 File "/nnunet/run/run_training.py", line 178, in main
    run_postprocessing_on_folds=not disable_postprocessing_on_folds)
 
 File "/nnunet/training/network_training/nnUNetTrainerV2_SSL.py", line 201,in validate
    run_postprocessing_on_folds=run_postprocessing_on_folds)
 
 File "nnunet/training/network_training/nnUNetTrainer.py", line 601, in validate
    mixed_precision=self.fp16)[1]
  
File "nnunet/training/network_training/nnUNetTrainerV2_SSL.py", line 225,in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  
File "nnunet/training/network_training/nnUNetTrainer.py", line 521, in predict_preprocessed_data_return_seg_and_softmax
    mixed_precision=mixed_precision)
  
File "nnunet/network_architecture/neural_network.py", line 158, in predict_3D
    pad_kwargs, all_in_gpu, False)
  
File "nnunet/network_architecture/neural_network.py", line 800, in _internal_predict_3D_2Dconv_tiled
    pad_border_mode, pad_kwargs, all_in_gpu, verbose)
  
File "nnunet/network_architecture/neural_network.py", line 691, in _internal_predict_2D_2Dconv_tiled
    gaussian_importance_map)[0]
  
File "nnunet/network_architecture/neural_network.py", line 581, in _internal_maybe_mirror_and_pred_2D
    pred = self.inference_apply_nonlin(self(x))
  
File "nnunet/utilities/nd_softmax.py", line 20, in <lambda>
    softmax_helper = lambda x: F.softmax(x, 1)
  
File "/opt/conda/envs/nnunet/lib/python3.6/site-packages/torch/nn/functional.py", line 1512, in softmax
    ret = input.softmax(dim)
AttributeError: 'tuple' object has no attribute 'softmax'

**Comment by FabianIsensee** [comment]
Hi,
since you modified something I cannot tell you what exactly it is. You need to go into the code and debug it. You probably need to disable the additional outputs when model.eval() is called. 
Best,
Fabian

**Comment by aprilaugust** [comment]
Thanks for your suggestion.
luckily, the problem solved.

**Comment by zhuyajingSensetime** [comment]
> Thanks for your suggestion.
> luckily, the problem solved.

Hi, 

I met the same problem. How did you solve it?
