### ISSUE TITLE
RuntimeError: MultiThreadedAugmenter

### ISSUE THREAD

**Issue by SkyeC77** [MIC-DKFZ/nnUNet#555]
I met this error when I was training the 2D network on brats2019, with CUDA10.1&cudnn8.0.2, but when I tried the example task004 Hippocampus, it works well. How can I solve this problem?  The RAM is enough.
_______________________________________________________________________________________________________
If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

competitions_with_custom_Trainers True
network_trainer False
nnUNetTrainer False
nnUNetTrainerCascadeFullRes False
nnUNetTrainerV2 False
###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'T1', 1: 'T1ce', 2: 'T2', 3: 'FLAIR'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')])
stages...

stage:  0
{'batch_size': 106, 'num_pool_per_axis': [5, 5], 'patch_size': array([192, 160]), 'median_patient_size_in_voxels': array([139, 169, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/ubuntu/CQQ/nnUNet_data/nnUNet_preprocessed/Task043_BraTS2019/nnUNetData_plans_v2.1_2D
###############################################
loading dataset
loading all case properties
2021-03-14 21:27:48.594384: Using splits from existing split file: /home/ubuntu/CQQ/nnUNet_data/nnUNet_preprocessed/Task043_BraTS2019/splits_final.pkl
2021-03-14 21:27:48.594811: The split file contains 5 splits.
2021-03-14 21:27:48.594870: Desired fold for training: 0
2021-03-14 21:27:48.594905: This split has 268 training and 67 validation cases.
unpacking dataset
done
2021-03-14 21:27:50.566366: lr: 0.01
Exception in background worker 0:
 Cannot load file containing pickled data when allow_pickle=False
using pin_memory on device 0
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/cqq/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/home/ubuntu/CQQ/nnUNet/nnunet/run/run_training.py", line 160, in main
    trainer.run_training()
  File "/home/ubuntu/CQQ/nnUNet/nnunet/training/network_training/nnUNetTrainerV2.py", line 442, in run_training
    ret = super().run_training()
  File "/home/ubuntu/CQQ/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 319, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/ubuntu/CQQ/nnUNet/nnunet/training/network_training/network_trainer.py", line 417, in run_training
    _ = self.tr_gen.next()
  File "/home/ubuntu/miniconda3/envs/cqq/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/home/ubuntu/miniconda3/envs/cqq/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/home/ubuntu/miniconda3/envs/cqq/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by SkyeC77** [comment]
I find when I use the 2D model, this error will happen, but when the 3D_full model is used, it seems to work well now.

**Comment by FabianIsensee** [comment]
*Cannot load file containing pickled data when allow_pickle=False*

this is your actual error message. Delete all the *.npy files in the preprocessed folder, then run again.
Best,
Fabian
