### ISSUE TITLE
nnUNet 2d training crashed, broken pipe

### ISSUE THREAD

**Issue by RomStriker** [MIC-DKFZ/nnUNet#578]
Hi,

I am trying to train on nnUNet on a custom dataset. I ran the following command.
```
nnUNet_train 2d nnUNetTrainerV2 Task303_CoronaryRefinedSingle 0 --npz
```
The training seemed to run fine and after 999 epoch it started some process "debug: mirroring True mirror_axes (0, 1)"  which I am not sure what it means. The last part of stdout looks like this.
```
2021-03-29 14:57:15.468942: 
epoch:  997
2021-03-29 15:02:03.909899: train loss : -0.8131
2021-03-29 15:02:23.408071: validation loss: -0.7838
2021-03-29 15:02:23.408425: Average global foreground Dice: [0.7952603207195924]
2021-03-29 15:02:23.408489: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-29 15:02:23.952938: lr: 3.7e-05
2021-03-29 15:02:23.953074: This epoch took 308.484082 s

2021-03-29 15:02:23.953127: 
epoch:  998
2021-03-29 15:07:12.355980: train loss : -0.8090
2021-03-29 15:07:31.849160: validation loss: -0.7964
2021-03-29 15:07:31.849583: Average global foreground Dice: [0.8101597448937015]
2021-03-29 15:07:31.849667: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-29 15:07:32.396086: lr: 2e-05
2021-03-29 15:07:32.396218: This epoch took 308.443040 s

2021-03-29 15:07:32.396272: 
epoch:  999
2021-03-29 15:12:20.730891: train loss : -0.7998
2021-03-29 15:12:40.255859: validation loss: -0.7792
2021-03-29 15:12:40.256233: Average global foreground Dice: [0.7988967718636051]
2021-03-29 15:12:40.257680: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-29 15:12:40.871492: lr: 0.0
2021-03-29 15:12:40.871654: saving scheduled checkpoint file...
2021-03-29 15:12:40.894065: saving checkpoint...
2021-03-29 15:12:41.615306: done, saving took 0.74 seconds
2021-03-29 15:12:41.621570: done
2021-03-29 15:12:41.621655: This epoch took 309.225334 s

2021-03-29 15:12:41.639411: saving checkpoint...
2021-03-29 15:12:41.988508: done, saving took 0.37 seconds
902679_240 (2, 512, 406, 512)
debug: mirroring True mirror_axes (0, 1)
903450_079 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
905079_180 (2, 512, 362, 512)
debug: mirroring True mirror_axes (0, 1)
906220_238 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
906285_106 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
907288_181 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
907541_173 (2, 512, 344, 602)
debug: mirroring True mirror_axes (0, 1)
907584_054 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
907768_130 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
908014_211 (2, 512, 460, 512)
debug: mirroring True mirror_axes (0, 1)
910097_269 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
910284_146 (2, 512, 459, 563)
debug: mirroring True mirror_axes (0, 1)
912754_251 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
914695_085 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
915002_235 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
917594_191 (2, 512, 393, 512)
debug: mirroring True mirror_axes (0, 1)
917874_037 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
918413_036 (2, 512, 459, 602)
debug: mirroring True mirror_axes (0, 1)
919370_001 (2, 512, 459, 602)
debug: mirroring True mirror_axes (0, 1)
919504_183 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
920290_267 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
921239_021 (2, 512, 459, 512)
debug: mirroring True mirror_axes (0, 1)
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
no resampling necessary
force_separate_z: None interpolation order: 1
separate z: False lowres axis None
no separate z, order 1
Process ForkPoolWorker-34:
Traceback (most recent call last):
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/roman/anaconda3/envs/nnunet/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
```

The beginning of stdout looks like this.
```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

###############################################
I am running the following nnUNet: 2d
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  1
modalities:  {0: 'CT'}
use_mask_for_norm OrderedDict([(0, False)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'CT')])
stages...

stage:  0
{'batch_size': 12, 'num_pool_per_axis': [7, 7], 'patch_size': array([512, 512]), 'median_patient_size_in_voxels': array([512, 459, 512]), 'current_spacing': array([0.33203125, 0.30000001, 0.33203125]), 'original_spacing': array([0.33203125, 0.30000001, 0.33203125]), 'pool_op_kernel_sizes': [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]], 'conv_kernel_sizes': [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], 'do_dummy_2D_data_aug': False}

I am using stage 0 from these plans
I am using batch dice + CE loss

I am using data from this folder:  /home/roman/nnUNet_raw_data_base/nnUNet_preprocessed_data/Task303_CoronaryRefinedSingle/nnUNetData_plans_v2.1_2D
###############################################
loading dataset
loading all case properties
2021-03-26 00:26:10.522663: Creating new 5-fold cross-validation split...
2021-03-26 00:26:10.524058: Desired fold for training: 0
2021-03-26 00:26:10.524144: This split has 216 training and 55 validation cases.
unpacking dataset
done
2021-03-26 00:32:20.522866: lr: 0.01
using pin_memory on device 0
using pin_memory on device 0
2021-03-26 00:32:23.509237: Unable to plot network architecture:
2021-03-26 00:32:23.509398: No module named 'IPython'
2021-03-26 00:32:23.509459: 
printing the network instead:

2021-03-26 00:32:23.509512: Generic_UNet(
  (conv_blocks_localization): ModuleList(
    (0): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(960, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (1): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(960, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (2): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(960, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (3): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(512, 256, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(256, 256, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (4): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(256, 128, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(128, 128, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (5): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(128, 64, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(64, 64, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
    (6): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(64, 32, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
  )
  (conv_blocks_context): ModuleList(
    (0): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(1, 32, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(32, 32, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (1): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(32, 64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(64, 64, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (2): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(64, 128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(128, 128, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (3): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(128, 256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(256, 256, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (4): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(256, 480, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (5): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (6): StackedConvLayers(
      (blocks): Sequential(
        (0): ConvDropoutNormNonlin(
          (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
        (1): ConvDropoutNormNonlin(
          (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
          (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
          (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
        )
      )
    )
    (7): Sequential(
      (0): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
      (1): StackedConvLayers(
        (blocks): Sequential(
          (0): ConvDropoutNormNonlin(
            (conv): Conv2d(480, 480, kernel_size=[3, 3], stride=(1, 1), padding=[1, 1])
            (instnorm): InstanceNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=False)
            (lrelu): LeakyReLU(negative_slope=0.01, inplace=True)
          )
        )
      )
    )
  )
  (td): ModuleList()
  (tu): ModuleList(
    (0): ConvTranspose2d(480, 480, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (1): ConvTranspose2d(480, 480, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (2): ConvTranspose2d(480, 480, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (3): ConvTranspose2d(480, 256, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (4): ConvTranspose2d(256, 128, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (5): ConvTranspose2d(128, 64, kernel_size=[2, 2], stride=[2, 2], bias=False)
    (6): ConvTranspose2d(64, 32, kernel_size=[2, 2], stride=[2, 2], bias=False)
  )
  (seg_outputs): ModuleList(
    (0): Conv2d(480, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (1): Conv2d(480, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (2): Conv2d(480, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (3): Conv2d(256, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (4): Conv2d(128, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (5): Conv2d(64, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (6): Conv2d(32, 2, kernel_size=(1, 1), stride=(1, 1), bias=False)
  )
)
2021-03-26 00:32:23.513586: 

2021-03-26 00:32:23.513821: 
epoch:  0
2021-03-26 00:37:18.441895: train loss : -0.1634
2021-03-26 00:37:37.925865: validation loss: -0.4105
2021-03-26 00:37:37.926260: Average global foreground Dice: [0.5662984019337738]
2021-03-26 00:37:37.926326: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-26 00:37:38.388598: lr: 0.009991
2021-03-26 00:37:38.388740: This epoch took 314.874849 s

2021-03-26 00:37:38.388789: 
epoch:  1
2021-03-26 00:42:26.857861: train loss : -0.4919
2021-03-26 00:42:46.350202: validation loss: -0.5344
2021-03-26 00:42:46.350606: Average global foreground Dice: [0.6202977231321353]
2021-03-26 00:42:46.350667: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-26 00:42:46.836857: lr: 0.009982
2021-03-26 00:42:46.891032: saving checkpoint...
2021-03-26 00:42:47.220518: done, saving took 0.38 seconds
2021-03-26 00:42:47.226121: This epoch took 308.837290 s

2021-03-26 00:42:47.226178: 
epoch:  2
2021-03-26 00:47:35.586137: train loss : -0.5678
2021-03-26 00:47:55.070033: validation loss: -0.5931
2021-03-26 00:47:55.070379: Average global foreground Dice: [0.6495945525434277]
2021-03-26 00:47:55.070438: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2021-03-26 00:47:55.548711: lr: 0.009973
2021-03-26 00:47:55.602896: saving checkpoint...
2021-03-26 00:47:56.336090: done, saving took 0.79 seconds
2021-03-26 00:47:56.346525: This epoch took 309.120295 s
```

My hardware is,
CPU: Intel® Core™ i7-5930K CPU 6 Core, 12 Threads
GPU: TITAN X (Pascal)
RAM: 32 GB

Any idea what could be wrong?

**Comment by FabianIsensee** [comment]
Hi,
not entirely sure. Unfortunately python multiprocessing is not very good at communicating what is wrong with it :-D Your model is fully trained and no information has been lost, though. The crash was in the validation stage. You should be able to simply run the validation with

`nnUNet_train 2d nnUNetTrainerV2 Task303_CoronaryRefinedSingle 0 --npz -val`

While this runs, please monitor the RAM usage (not GPU Memory, but normal RAM) on your system. It could be that that was what caused it.

Best,
Fabian

**Comment by RomStriker** [comment]
That's a relief. Thank you.

**Comment by FabianIsensee** [comment]
did it work now?

**Comment by RomStriker** [comment]
Hi again,

I recently checked the validation logs and turns out the validation was still not complete, and it did fill the entire 32 GB RAM. To, solve it I set up a 64GB swap, and change the config to use it only when absolutely necessary, so as not to hinder performance.
 
I had a similar problem with the preprocessing step, which was filling the 64GB RAM of another system, and here also after setting the swap to 128GB, it worked fine.

**Comment by FabianIsensee** [comment]
Depending on the dataset resampling the segmentations back to the original image resolution can take up a lot of ram (and computation time) This is annoying - I know but there is not much you can do about it, unfortunately.
Best,
Fabian
