### ISSUE TITLE
MultiThreadedAugmenter.abort_event was set, something went wrong.

### ISSUE THREAD

**Issue by GuillaumeMougeot** [MIC-DKFZ/nnUNet#665]
After running the following command on my own dataset:
`nnUNet_train 3d_fullres nnUNetTrainerV2 Task500_Nucleus 0 --npz`

I got the following error:
```
###############################################
loading dataset
loading all case properties
unpacking dataset
done
2021-06-22 17:58:43.999276: lr: 0.01
using pin_memory on device 0
Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/nnunet/run/run_training.py", line 151, in main
    trainer.run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 431, in run_training
    ret = super().run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 316, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/opt/conda/lib/python3.8/site-packages/nnunet/training/network_training/network_trainer.py", line 408, in run_training
    _ = self.tr_gen.next()
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 181, in next
    return self.__next__()
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 205, in __next__
    item = self.__get_next_item()
  File "/opt/conda/lib/python3.8/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 189, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
```
Config:
OS: Ubuntu 18.04
GPU: RTX 3090
CUDA: 11.2
RAM: 32 Go

Note that I ran nnUNet from a Docker container (I don't know if it could cause the problem...)

Thanks for your help.

**Comment by Truring** [comment]
I got the same problem on Window 10. I don't know how to fix this bug.

**Comment by FabianIsensee** [comment]
Remember to set `--ipc=host` when running the Docker

**Comment by GuillaumeMougeot** [comment]
> Remember to set --ipc=host when running the Docker

@FabianIsensee Thank you very much! this solved my issue.
