### ISSUE TITLE
Running inference on cpu (on computer without available GPU)

### ISSUE THREAD

**Issue by estherpuyol** [MIC-DKFZ/nnUNet#667]
Good morning,

I saw that there is a new library that allows to do inference of the nnunet framework on a CPU: https://pypi.org/project/nnunet-inference-on-cpu-and-gpu/. However, when I try to run the code on a PC that doesn't have a GPU I have the error below, could you please advise on how to fix this error or which is the best way to do inference on a CPU. 
Thanks in advance,
E

_Error:_

using the following model files:  ['/nnUNetTrainerV2__nnUNetPlansv2.1/fold_0/model_final_checkpoint.model']
starting preprocessing generator
starting prediction...
Traceback (most recent call last)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/site-packages/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/site-packages/nnunet/inference/predict.py", line 630, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/site-packages/nnunet/inference/predict.py", line 203, in predict_cases
    for preprocessed in preprocessing:
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/site-packages/nnunet/inference/predict.py", line 109, in preprocess_multithreaded
    pr.start()
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/esther/opt/anaconda3/envs/test_CPU/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function <lambda> at 0x7fa3e9a60790>: attribute lookup <lambda> on nnunet.utilities.nd_softmax failed

**Comment by FabianIsensee** [comment]
Hi,
I am not the author of that package and cannot help you with it
Best,
Fabian
