### ISSUE TITLE
GLIBCXX_3.4.21 not found 

### ISSUE THREAD

**Issue by dhx000** [MIC-DKFZ/nnUNet#676]
error:
Traceback (most recent call last):
  File "./nnunet/inference/predict_simple.py", line 19, in <module>
    from nnunet.inference.predict import predict_from_folder
  File "/home/hxdong/nnUnet/nnUNet-master/nnunet/inference/predict.py", line 30, in <module>
    from nnunet.training.model_restore import load_model_and_checkpoint_files
  File "/home/hxdong/nnUnet/nnUNet-master/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/home/hxdong/nnUnet/nnUNet-master/nnunet/training/network_training/nnUNetTrainer.py", line 22, in <module>
    import matplotlib
  File "/home/hxdong/.conda/envs/myenv/lib/python3.8/site-packages/matplotlib/__init__.py", line 157, in <module>
    _check_versions()
  File "/home/hxdong/.conda/envs/myenv/lib/python3.8/site-packages/matplotlib/__init__.py", line 151, in _check_versions
    module = importlib.import_module(modname)
  File "/home/hxdong/.conda/envs/myenv/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/hxdong/.conda/envs/myenv/lib/python3.8/site-packages/kiwisolver.cpython-38-x86_64-linux-gnu.so)
it seems that error occured when import matplotlib,so I write a python file with only import matplotlib while it can work.

**Comment by FabianIsensee** [comment]
google helps: conda install libgcc

this is not a problem related to nnU-net

**Comment by GregorKoehler** [comment]
Hi @dhx000 ,
from the looks of it, this issue has been resolved back in 2021. If you don't have any further questions here, we'll close the issue in 2 weeks.
