### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'x'

### ISSUE THREAD

**Issue by jamesben6688** [MIC-DKFZ/nnUNet#677]
When I set `gpus=4` and run the command 

`nnUNet_train_DP 3d_fullres  nnUNetTrainerV2_DP Task001_Calf 0 -gpus 4 --dbs`, 

I got the following error:

`
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/bin/nnUNet_train_DP", line 11, in <module>
    load_entry_point('nnunet', 'console_scripts', 'nnUNet_train_DP')()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/run/run_training_DP.py", line 202, in main
    trainer.run_training()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/training/network_training/nnUNetTrainerV2_DP.py", line 167, in run_training
    ret = nnUNetTrainer.run_training(self)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/training/network_training/nnUNetTrainer.py", line 326, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/training/network_training/network_trainer.py", line 476, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/afs/crc.nd.edu/user/y/ypeng4/nnUnet/nnunet/training/network_training/nnUNetTrainerV2_DP.py", line 188, in run_iteration
    ret = self.network(data, target, return_hard_tp_fp_fn=run_online_evaluation)
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 177, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/afs/crc.nd.edu/user/y/ypeng4/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'x'
`

But when I change it to `gpus=2`, everything works ok. How could this happen?

**Comment by jamesben6688** [comment]
I figured out the problem, since I set the dbs and the batch size is less than the number of gpus, some gpus get a batch size of 0.

**Comment by jamesben6688** [comment]
I figured out the problem, since I set the dbs and the batch size is less than the number of gpus, some gpus get a batch size of 0.

**Comment by FabianIsensee** [comment]
makes sense :-) Glad you figured this out
