### ISSUE TITLE
About the MultiThreadedAugmenter &  SingleThreadedAugmenter

### ISSUE THREAD

**Issue by lsjAI** [MIC-DKFZ/nnUNet#696]
[https://github.com/MIC-DKFZ/batchgenerators/blob/master/batchgenerators/dataloading/multi_threaded_augmenter.py](url)
```python
def __get_next_item(self):
        item = None

        while item is None:
            if self.abort_event.is_set():
                self._finish()
                raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
                                   "your workers crashed. This is not the actual error message! Look further up your "
                                   "stdout to see what caused the error. Please also check whether your RAM was full")

            if not self.pin_memory_queue.empty():
                item = self.pin_memory_queue.get()
            else:
                sleep(self.wait_time)

        return item

```

When running on a cluster, multithreaded augmeter gets stuck, but singlethreaded augmeter has no problem. Will stcuck at sleep(self.wait_time).

Thanks~

**Comment by FabianIsensee** [comment]
Hi, what OS are you running on the cluster? We have never had this problem so far :-/
Best,
Fabian

**Comment by lsjAI** [comment]
> Hi, what OS are you running on the cluster? We have never had this problem so far :-/
> Best,
> Fabian
Hi, I am using the Debian9_cuda10.1_pytorch1.6 image. When the program runs to multithread augmenter, it will be stuck in the above code segment, sleep (self. wait_ time).  Please review the following code,  if i add the print, it will always executes this print(1).  That is to say the item always is None. 
```python
def __get_next_item(self):
        item = None

        while item is None:
            if self.abort_event.is_set():
                self._finish()
                raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
                                   "your workers crashed. This is not the actual error message! Look further up your "
                                   "stdout to see what caused the error. Please also check whether your RAM was full")

            if not self.pin_memory_queue.empty():
                item = self.pin_memory_queue.get()
            else:
                print(1) # if i add the print, it will always executes this print(1).  That is to say the item always is None. 
                sleep(self.wait_time)

        return item

```

**Comment by FabianIsensee** [comment]
Are you using Docker? If so you need the `--ipc=host` flag

**Comment by lsjAI** [comment]
> Are you using Docker? If so you need the `--ipc=host` flag

@FabianIsensee 
I am running this code on  a cluster, so I can not handle the process of container generation. But the SingleAugmenter runs well in this environment. Now, I can not locate the error. 
```python
    # if use_nondetMultiThreadedAugmenter:
    #     if NonDetMultiThreadedAugmenter is None:
    #         raise RuntimeError('NonDetMultiThreadedAugmenter is not yet available')
    #     batchgenerator_val = NonDetMultiThreadedAugmenter(dataloader_val, val_transforms,
    #                                                       max(params.get('num_threads') // 2, 1),
    #                                                       params.get("num_cached_per_thread"),
    #                                                       seeds=seeds_val, pin_memory=pin_memory)
    # else:
    #     batchgenerator_val = MultiThreadedAugmenter(dataloader_val, val_transforms,
    #                                                 max(params.get('num_threads') // 2, 1),
    #                                                 params.get("num_cached_per_thread"),
    #                                                 seeds=seeds_val, pin_memory=pin_memory)
    batchgenerator_val = SingleThreadedAugmenter(dataloader_val, val_transforms)
```

**Comment by lsjAI** [comment]
> Are you using Docker? If so you need the `--ipc=host` flag
@FabianIsensee 
Now, I locate the error, but it is difficult to solve. Maybe the two multiprocessing.Process operations cause the error.

**Comment by ArthurRyan0803** [comment]
I have the same problem too. I'm training nnUNet in a docker,  but I have no right to access the 'docker' command. How to solve this problem?

**Comment by lsjAI** [comment]
> I have the same problem too. I'm training nnUNet in a docker, but I have no right to access the 'docker' command. How to solve this problem?

If you run this code on GPU cluster and you can not handle the container generation, the --ipc=host  can not solve this error. I think you should locate the error.

**Comment by PfeifferMicha** [comment]
I believe I have a similar problem. I'm not using docker, but running the job through SLURM. The process hangs indefinitely at:

```
unpacking dataset
done
2021-09-28 15:39:13.094266: lr: 0.01
using pin_memory on device 0
```

Killing the process seems to indicate that it hangs within the MultiThreadedAugmenter:
In the backtrace, the error messages aren't really helpful (of course, because the actual "error" was receiving a SIGTERM), but maybe they can reveal where the program got stuck?

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run 
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/trace.py", line 735, in <module>
    main()
  File "/usr/lib/python3.6/trace.py", line 723, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.6/trace.py", line 462, in runctx
    exec(cmd, globals, locals)
  File "nnUNet/nnunet/run/run_training.py", line 199, in <module>
    main()
  File "nnUNet/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration
    data_dict = next(data_generator)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
```
I don't think RAM was full...

**Comment by lsjAI** [comment]
My problems was the dataloader, since I am using hadoop as backend storage, I am having problems loading the data. My problem should be different from yours, I think you can try single threaded to see if it works.&nbsp;Or maybe there's something wrong with your docker, you can reference the other issues.&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MIC-DKFZ/nnUNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 下午3:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MIC-DKFZ/nnUNet] About the MultiThreadedAugmenter &amp;  SingleThreadedAugmenter (#696)





 
I believe I have a similar problem. I'm not using docker, but running the job through SLURM. The process hangs indefinitely at:
 unpacking dataset done 2021-09-28 15:39:13.094266: lr: 0.01 using pin_memory on device 0  
Killing the process seems to indicate that it hangs within the MultiThreadedAugmenter:
 In the backtrace, the error messages aren't really helpful (of course, because the actual "error" was receiving a SIGTERM), but maybe they can reveal where the program got stuck?
 Exception in thread Thread-4: Traceback (most recent call last):   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner     self.run()   File "/usr/lib/python3.6/threading.py", line 864, in run      self._target(*self._args, **self._kwargs)   File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop     raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: " RuntimeError: Abort event was set. So someone died and we should end this madness.  IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full Traceback (most recent call last):   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main     "__main__", mod_spec)   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code     exec(code, run_globals)   File "/usr/lib/python3.6/trace.py", line 735, in <module&gt;     main()   File "/usr/lib/python3.6/trace.py", line 723, in main     t.runctx(code, globs, globs)   File "/usr/lib/python3.6/trace.py", line 462, in runctx     exec(cmd, globals, locals)   File "nnUNet/nnunet/run/run_training.py", line 199, in <module&gt;     main()   File "nnUNet/nnunet/run/run_training.py", line 179, in main     trainer.run_training()   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training     ret = super().run_training()   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training     super(nnUNetTrainer, self).run_training()   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training     l = self.run_iteration(self.tr_gen, True)   File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration     data_dict = next(data_generator)   File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__     item = self.__get_next_item()   File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item     raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of " RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full Exception in thread Thread-5: Traceback (most recent call last):   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner     self.run()   File "/usr/lib/python3.6/threading.py", line 864, in run     self._target(*self._args, **self._kwargs)   File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop     raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: " RuntimeError: Abort event was set. So someone died and we should end this madness. IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full  
I don't think RAM was full...
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YangQinzhu** [comment]
> 

I meet the same problem, and finally I find that it is problem of unsuitable version for pytorch and my RTXA6000 device. I use code "torch.tensor([10]).cuda()" to test it out. 
If you meet it again, may running with the command "conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch" will help you.

```
/------/miniconda3/envs/nnunet/lib/python3.7/site-packages/torch/cuda/__init__.py:143: UserWarning: 
NVIDIA RTX A6000 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA RTX A6000 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

**Comment by YangQinzhu** [comment]
>  Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run 
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/trace.py", line 735, in <module>
    main()
  File "/usr/lib/python3.6/trace.py", line 723, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.6/trace.py", line 462, in runctx
    exec(cmd, globals, locals)
  File "nnUNet/nnunet/run/run_training.py", line 199, in <module>
    main()
  File "nnUNet/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration
    data_dict = next(data_generator)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full


This is the problem that I comment about. I cite it again to make the comment more clear.

**Comment by YangQinzhu** [comment]
> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run 
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.6/trace.py", line 735, in <module>
    main()
  File "/usr/lib/python3.6/trace.py", line 723, in main
    t.runctx(code, globs, globs)
  File "/usr/lib/python3.6/trace.py", line 462, in runctx
    exec(cmd, globals, locals)
  File "nnUNet/nnunet/run/run_training.py", line 199, in <module>
    main()
  File "nnUNet/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration
    data_dict = next(data_generator)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full


This is the problem that I comment about. I cite it again to make the comment more clear.

**Comment by tiandaren** [comment]
I made the same mistake. Before that, I tested with a small sample and achieved success, but then I encountered such a mistake by putting in a large amount of data. I cleared the data other than the raw_data, and preprocessed the data again, and it was successful.Hope it helps.

**Comment by tuhinmallick** [comment]
@tiandaren which data did you remove? There is another issue #313 which asks us to remove preprocessed data and do it again. But its a never ending cycle. 
@FabianIsensee do you know the root cause and is there a permanent solution other than redoing preprocessing again and again

**Comment by rongzhao-zhang** [comment]
Hi I met the same problem, where my program stuck at the `sleep(self.wait_time)` line.
I'm on a GPU cluster, not on Docker, and SingleThreadAugmenter works for me but very slow. 
Change batch size to 1 also solves the problem, but if using batch_size > 1 and MultiThreadedAugmenter, it got stuck.
Any idea to solve it? Many thanks in advance.

**Comment by FabianIsensee** [comment]
Can you figure out what the wait time for you is? Just insert a print statement. The wait time should be really short, well below a second

**Comment by rongzhao-zhang** [comment]
It loops and prints "wait time is 0.02" infinitely

**Comment by rongzhao-zhang** [comment]
I just add a `print(f"wait time is {self.wait_time}") ` line before the `sleep` statement

**Comment by rongzhao-zhang** [comment]
Below is the output when I press ctrl + c
```
ERROR:root:MultiThreadedGenerator: caught exception: (<class 'KeyboardInterrupt'>, KeyboardInterrupt(), <traceback object at 0x7f064dd63000>)
Traceback (most recent call last):
  File "/nvme/zhangrongzhao/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 207, in __next__
    item = self.__get_next_item()
  File "/nvme/zhangrongzhao/anaconda3/envs/nnUNet/lib/python3.10/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 198, in __get_next_item
    sleep(self.wait_time)
KeyboardInterrupt
```
which also implies a infinite loop on the sleep statement.

**Comment by rongzhao-zhang** [comment]
I guess the `self.pin_memory_queue.empty()` statement is always true, but I cannot figure out why the queue cannot read any data. The loading process is fine when batch_size == 1 or using SingleThreadAugmenter or on my local PC
It is neither a full memory issue since I still have 800G+ memory free

**Comment by rongzhao-zhang** [comment]
And... in my case, I am using a customized network architecture, which is adapted from SwinUNETR in monai. When I change back to the original UNet model, the problem just disappears!  
So, does the network architecture has something to do with the dataloading process? Could you give me some hints on this?
Really appreciate your kind help!

**Comment by FabianIsensee** [comment]
Honestly I am at a loss here. I don't think this has something to do with your network architecture. I will take another look at the MTA but I am not sure I will find something. Do you have any other ideas?

**Comment by rongzhao-zhang** [comment]
Strangely... I track the program line by line, and find that the program actually hangs at `data_dict[key] = self.cast(torch.from_numpy(data_dict[key])).contiguous()` line.
When I remove the `.contiguous()` statement, it **works**! 
But why? It cannot allocate some contiguous memory in RAM?

The conclusion is, this is a bug of my own code, there is nothing wrong with MTA actually.

**Comment by rongzhao-zhang** [comment]
Thank you for the prompt reply anyway, it is still very helpful!

**Comment by 2vfbg** [comment]
> 我的问题是数据加载器，因为我使用 Hadoop 作为后端存储，所以我在加载数据时遇到问题。我的问题应该和你的不同，我想你可以试试单线程看看它是否有效。或者，也许您的 docker 有问题，您可以参考其他问题。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MIC-DKFZ/nnUNet" ***@***.***&gt;; 发送时间:&nbsp;2021年9月29日(星期三) 下午3:53 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MIC-DKFZ/nnUNet] About the MultiThreadedAugmenter &amp; SingleThreadedAugmenter (#696) I believe I have a similar problem. I'm not using docker, but running the job through SLURM. The process hangs indefinitely at: unpacking dataset done 2021-09-28 15:39:13.094266: lr: 0.01 using pin_memory on device 0 Killing the process seems to indicate that it hangs within the MultiThreadedAugmenter: In the backtrace, the error messages aren't really helpful (of course, because the actual "error" was receiving a SIGTERM), but maybe they can reveal where the program got stuck? Exception in thread Thread-4: Traceback (most recent call last): File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner self.run() File "/usr/lib/python3.6/threading.py", line 864, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: " RuntimeError: Abort event was set. So someone died and we should end this madness. IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full Traceback (most recent call last): File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/usr/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/usr/lib/python3.6/trace.py", line 735, in <module&gt; main() File "/usr/lib/python3.6/trace.py", line 723, in main t.runctx(code, globs, globs) File "/usr/lib/python3.6/trace.py", line 462, in runctx exec(cmd, globals, locals) File "nnUNet/nnunet/run/run_training.py", line 199, in <module&gt; main() File "nnUNet/nnunet/run/run_training.py", line 179, in main trainer.run_training() File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training ret = super().run_training() File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training super(nnUNetTrainer, self).run_training() File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/network_trainer.py", line 456, in run_training l = self.run_iteration(self.tr_gen, True) File "/usr/local/lib/python3.6/dist-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 232, in run_iteration data_dict = next(data_generator) File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__ item = self.__get_next_item() File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of " RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full Exception in thread Thread-5: Traceback (most recent call last): File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner self.run() File "/usr/lib/python3.6/threading.py", line 864, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.6/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: " RuntimeError: Abort event was set. So someone died and we should end this madness. IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full I don't think RAM was full... — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

I met the same question with you,please how to deal with it?

**Comment by 2vfbg** [comment]
> I met the same question with you,please how to deal with it?

I met the same question with you,please how to deal with it?

> > 您好，您在集群上运行的是什么操作系统？到目前为止，我们从未遇到过这个问题 ：-/ 最好，Fabian 嗨，我正在使用 Debian9_cuda10.1_pytorch1.6 映像。当程序运行到多线程 augmenter 时，会卡在上面的代码段 sleep （self. wait_ time）。请查看以下代码，如果我添加 print，它将始终执行此 print（1）。也就是说，该项目始终为 None。
> 
> ```python
> def __get_next_item(self):
>         item = None
> 
>         while item is None:
>             if self.abort_event.is_set():
>                 self._finish()
>                 raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
>                                    "your workers crashed. This is not the actual error message! Look further up your "
>                                    "stdout to see what caused the error. Please also check whether your RAM was full")
> 
>             if not self.pin_memory_queue.empty():
>                 item = self.pin_memory_queue.get()
>             else:
>                 print(1) # if i add the print, it will always executes this print(1).  That is to say the item always is None. 
>                 sleep(self.wait_time)
> 
>         return item
> ```

I met the same question with you,please how to deal with it?

**Comment by 2vfbg** [comment]
> Strangely... I track the program line by line, and find that the program actually hangs at line. When I remove the statement, it **works**! But why? It cannot allocate some contiguous memory in RAM?`data_dict[key] = self.cast(torch.from_numpy(data_dict[key])).contiguous()``.contiguous()`
> 
> The conclusion is, this is a bug of my own code, there is nothing wrong with MTA actually.
Excuse me, are you removing Cerf. Custer (Tocchi. Fromm_Nonppi). Contigus. Is Contigus working?

**Comment by YangForever** [comment]
Hi
I got the similar problem and I solved it by acquiring only 3 cpu cores (threads) on the cluster.

**Details:**
I was training nnUNet on a cluster with default cpu core as 1. While training, the epoch time is above 500s which is really long compared to the training locally of 150s per epoch. Then, I try to speed up the training on cluster by acquiring 12 cpu cores, but with the similar error:

> Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 917, in run
    self.run()
  File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    self._target(*self._args, **self._kwargs)
  File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
    raise e
  File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise e
  File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

I found that the error was thrown from thread-4 and the default number of processes in nnUNetv2_predict is 3, then I though it might apply to the training as well. Therefore, I change the cpu core as 3 and it works! The training time per epoch on cluster also reduced to 150s from 550s!

**Comment by 2vfbg** [comment]
> Hi I got the similar problem and I solved it by acquiring only 3 cpu cores (threads) on the cluster.
> 
> **Details:** I was training nnUNet on a cluster with default cpu core as 1. While training, the epoch time was above 500s which was really long compared to the training locally of 150s per epoch. Then, I tried to speed up the training on cluster by acquiring 12 cpu cores, but with the similar error:
> 
> > Exception in thread Thread-4:
> > Traceback (most recent call last):
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> > Exception in thread Thread-5:
> > Traceback (most recent call last):
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 980, in _bootstrap_inner
> > self.run()
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 917, in run
> > self.run()
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/threading.py", line 917, in run
> > self._target(*self._args, **self._kwargs)
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
> > self._target(*self._args, **self._kwargs)
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 125, in results_loop
> > raise e
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
> > raise e
> > File "/home/username/.conda/envs/nnunet/lib/python3.9/site-packages/batchgenerators/dataloading/nondet_multi_threaded_augmenter.py", line 103, in results_loop
> > raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
> > RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
> > raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
> > RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
> 
> I found that the error was thrown from thread-4 and the default number of processes in nnUNetv2_predict is 3, then I though it might apply to the training as well. Therefore, I change the cpu core as 3 and it works! The training time per epoch on cluster also reduced to 150s from 550s!

hello，May I ask which piece of code in which file you changed and how, can I see the code you modified?

**Comment by YangForever** [comment]
@2vfbg I didn't change any scripts from nnUNet repo. All you need to do is to modify your cluster submission bash file, which syntax depends on your cluster scheduler system.
