### ISSUE TITLE
Major Issue: .npy file automatically made and making its own error in nnunet_train following the documented example

### ISSUE THREAD

**Issue by tlsgusdn1107** [MIC-DKFZ/nnUNet#732]
Has there been a change in the code for some scripts? After doing every single procedure in the example for training, except with brain instead, when I ran `nnUNet_train 3d_fullres nnUNetTrainerV2 1 0`, this error popped up first and created npy files that I purposely deleted in the training set:

`loading dataset
loading all case properties
unpacking dataset
Exception ignored in: <function NpzFile.__del__ at 0x7f17648c7710>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 223, in __del__
    self.close()
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 214, in close
    if self.zip is not None:
AttributeError: 'NpzFile' object has no attribute 'zip'`

After this, the code then spit out this error, which I assume is from the npy file that the code itself created!

`"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.7/site-packages/nnunet/training/dataloading/dataset_loading.py", line 44, in convert_to_npy
    a = np.load(npz_file)[key]
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 432, in load
    pickle_kwargs=pickle_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 186, in __init__
    _zip = zipfile_factory(fid)
  File "/opt/conda/lib/python3.7/site-packages/numpy/lib/npyio.py", line 112, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/opt/conda/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/opt/conda/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/nnunet/run/run_training.py", line 143, in main
    trainer.initialize(not validation_only)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 98, in initialize
    unpack_dataset(self.folder_with_preprocessed_data)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/training/dataloading/dataset_loading.py", line 68, in unpack_dataset
    p.map(convert_to_npy, zip(npz_files, [key] * len(npz_files)))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
zipfile.BadZipFile: File is not a zip file`

This is getting extremely troublesome, because:

a) the code works fine in colab (which I cannot use for training due to its slow processing time and colab runtime limit), and 

b) i've already repeated downloading all files and running them for 5 times (took me hours), but the same error pops up.

I'm using GCP Cloud Notebook VM Instance with pytorch 1.9 and GPU enabled. The same methods were done in my previous VM instance, which worked fine, but now it's not working.

Thank you so much for reading this concern...

**Comment by FabianIsensee** [comment]
Hey, this looks to be a really specific problem related to your setup. I cannot help you with this because it is not a problem with nnU-Net (it works for everyone else)

**Comment by mehnaz1985** [comment]
@tlsgusdn1107 , hi though the issue is closed, i need to know how you solve this? I am facing the same problem. convert_to_numpy error. please help me in this regard
