### ISSUE TITLE
Convert 2D segmentation result to image.

### ISSUE THREAD

**Issue by qimingyudaowenti** [MIC-DKFZ/nnUNet#737]
I use nnU-net with 2D data. After run `nnUNet_predict`, I want to convert the prediction to normal 2D image. Code as follows:
```python
from pathlib import Path

from nnunet.utilities.file_conversions import convert_2d_segmentation_nifti_to_img

path_nifti = Path('/home/gy/ultrasound_dataset/nnUnet/pred_my/3_80.nii.gz')
out_dir = Path('/home/gy/ultrasound_dataset/nnUnet/pred_2d_converted')
path_out_img = out_dir.joinpath(path_nifti.stem).with_suffix('.png')

convert_2d_segmentation_nifti_to_img(path_nifti, path_out_img)
```
Something get wrong:
```
Traceback (most recent call last):
  File "/home/gy/pycharm_projects/UltraSound/nnUnet/data_prepare/pred_nifti_to_img.py", line 9, in <module>
    convert_2d_segmentation_nifti_to_img(path_nifti, path_out_img)
  File "/home/gy/anaconda3/envs/nnunet/lib/python3.8/site-packages/nnunet/utilities/file_conversions.py", line 93, in convert_2d_segmentation_nifti_to_img
    img = sitk.GetArrayFromImage(sitk.ReadImage(nifti_file))
  File "/home/gy/anaconda3/envs/nnunet/lib/python3.8/site-packages/SimpleITK/extra.py", line 342, in ReadImage
    reader.SetFileNames(fileName)
  File "/home/gy/anaconda3/envs/nnunet/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 7844, in SetFileNames
    return _SimpleITK.ImageSeriesReader_SetFileNames(self, fileNames)
TypeError: in method 'ImageSeriesReader_SetFileNames', argument 2 of type 'std::vector< std::string,std::allocator< std::string > > const &'
```
How can I fix it?

**Comment by FabianIsensee** [comment]
You need to convert the path to string. SimpleITK cannot handle paths as input argument

**Comment by qimingyudaowenti** [comment]
Solved. Thanks!
