### ISSUE TITLE
Error when 'deep_supervision=True'

### ISSUE THREAD

**Issue by yl255** [MIC-DKFZ/nnUNet#75]
Hi, Fabian
I want to try the 'deep_supervision' in nnunet, I set do_ds = True in 'generic_UNet.py' .
I got the error:

Traceback (most recent call last):
  File "run/run_training.py", line 108, in <module>
    trainer.run_training()
  File "D:\DeepLearning\nnUNet-master\nnunet\training\network_training\nnUNetTrainer.py", line 277, in run_training
    super(nnUNetTrainer, self).run_training()
  File "D:\DeepLearning\nnUNet-master\nnunet\training\network_training\network_trainer.py", line 359, in run_training
    l = self.run_iteration(self.tr_gen, True)
  File "D:\DeepLearning\nnUNet-master\nnunet\training\network_training\network_trainer.py", line 542, in run_iteration
    l = self.loss(output, target)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\DeepLearning\nnUNet-master\nnunet\training\loss_functions\dice_loss.py", line 124, in forward
    dc_loss = self.dc(net_output, target)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\DeepLearning\nnUNet-master\nnunet\training\loss_functions\dice_loss.py", line 92, in forward
    shp_x = x.shape
AttributeError: 'tuple' object has no attribute 'shape'

How to fix it?
best, 
Yaliang
PS：Hope you had a good trip in China :)

**Comment by FabianIsensee** [comment]
Hi,
that is because you will need a special loss function that can handle this. The unet will return several segmentations at different resolutions as a tuple.
My code for deep supervision is not released yet.
Best,
Fabian

**Comment by yl255** [comment]
Hi,Fabian
How much the dice of the prediction can be improved when using deep supervision in nnUnet?
I add a loss function to do the deep supervision, but the result is not better. 
Maybe you could give me some advise.
Best,
Yaliang
