### ISSUE TITLE
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' (/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/__init__.py)

### ISSUE THREAD

**Issue by perecanals** [MIC-DKFZ/nnUNet#752]
Hi,

I have been using nnunet in Colab for a while and all of a sudden I started to run into this import error with batchgenerators:

```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_train", line 5, in <module>
    from nnunet.run.run_training import main
  File "/usr/local/lib/python3.7/dist-packages/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/usr/local/lib/python3.7/dist-packages/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/usr/local/lib/python3.7/dist-packages/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/usr/local/lib/python3.7/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 34, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import default_3D_augmentation_params, \
  File "/usr/local/lib/python3.7/dist-packages/nnunet/training/data_augmentation/default_data_augmentation.py", line 18, in <module>
    from batchgenerators.dataloading import MultiThreadedAugmenter, SingleThreadedAugmenter
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' (/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/__init__.py)
```

I didn't change my code and overnight the error just popped... I have tried upgrading the batchgenerators package, uninstalling and installing again and nothing. Any idea on how to solve this? Did this happen top anybody else?

Thank you,

**Comment by AralRalud** [comment]
Hi,
I have the same issue when trying to run on a remote machine. I also tried to upgrade `batchgenerators`, with no success. Please let me know if you'll figure this out.

**Comment by AralRalud** [comment]
Okay, so it seems I managed to save the issue. In a couple of scripts, some of the paths had to be changed 
 including:
* `nnunet/training/data_augmentation/default_data_augmentation.py` :
```
# from batchgenerators.dataloading.nondet_multi_threaded_augmenter import MultiThreadedAugmenter, SingleThreadedAugmenter
from batchgenerators.dataloading.multi_threaded_augmenter import MultiThreadedAugmenter  
from batchgenerators.dataloading.single_threaded_augmenter import SingleThreadedAugmenter

# from batchgenerators.transforms import DataChannelSelectionTransform, SegChannelSelectionTransform, SpatialTransform, \
#     GammaTransform, MirrorTransform, Compose
from batchgenerators.transforms.channel_selection_transforms import DataChannelSelectionTransform, \
    SegChannelSelectionTransform
from batchgenerators.transforms.spatial_transforms import SpatialTransform
from batchgenerators.transforms.color_transforms import GammaTransform
from batchgenerators.transforms.spatial_transforms import MirrorTransform
from batchgenerators.transforms.abstract_transforms import Compose
```
and **ALL OTHER scripts** in `nnunet/training/data_augmentation` directory.

* in `training/dataloadingdataset_loading.py`:
```
 # from batchgenerators.dataloading import SlimDataLoaderBase
 from batchgenerators.dataloading.data_loader import SlimDataLoaderBase
```

Probably some others as well, but this is the general idea :) hope this helps.

**Comment by perecanals** [comment]
Yes, it worked! Thank you :)

**Comment by FabianIsensee** [comment]
Hi there,
this should be working with the newest version of nnU-Net from github. If you want to use the pip installer for nnU-Net you should use an older version of batchgenerators: `pip install batchgenerators==0.21`
Apologies - that problem is on me :-D
Best,
Fabian

**Comment by perecanals** [comment]
Hi Fabian,
No problem at all, I ran into a different error now using the 0.23 version and I did what you suggested (with version 0.20) using my old nnU-Net codes. Now it seems to be working as brilliantly as always :)
Thank you!
