### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by yingdiLee** [MIC-DKFZ/nnUNet#793]
When I run nnUNet_predict, an error occurs:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/inference/segmentation_export.py", line 106, in save_segmentation_nifti_from_softmax
    order_z=interpolation_order_z)
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/preprocessing/preprocessing.py", line 195, in resample_data_or_seg
    return reshaped_final_data.astype(dtype_data)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 5.18 GiB for an array with shape (26, 204, 512, 512) and data type float32
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zyd/anaconda3/envs/nnunet/bin/nnUNet_predict", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_predict')())
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/inference/predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/inference/predict.py", line 664, in predict_from_folder
    disable_postprocessing=disable_postprocessing)
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/inference/predict.py", line 269, in predict_cases
    _ = [i.get() for i in results]
  File "/home/zyd/beifen_xinsuoqu_/nnUNet/nnunet/inference/predict.py", line 269, in <listcomp>
    _ = [i.get() for i in results]
  File "/home/zyd/anaconda3/envs/nnunet/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numpy.core._exceptions.MemoryError: Unable to allocate 5.18 GiB for an array with shape (26, 204, 512, 512) and data type float32
I have no idea how is it happen, waiting for your reply

**Comment by Rickylht** [comment]
Hello, can you tell me how you solve this problem effectively?
I met the same problem when did a 32 multi-class segmentation task.

**Comment by FabianIsensee** [comment]
Hey, this means that you are out of RAM and cannot run the prediction :-/ Try `--num_threads_nifti_save 1`. If that still doesn't work you need to either get a better workstation or fiddle with the code and make the segmentation export use order=0
