### ISSUE TITLE
Hi, can you identify the issue. 

### ISSUE THREAD

**Issue by ahmadfaizan1990** [MIC-DKFZ/nnUNet#821]
DeprecationWarning)
Exception in background worker 0:
 a must be 1-dimensional or an integer
Traceback (most recent call last):
  File "mtrand.pyx", line 905, in numpy.random.mtrand.RandomState.choice
TypeError: 'dict_keys' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py37th/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 46, in producer
    item = next(data_loader)
  File "/home/ubuntu/anaconda3/envs/py37th/lib/python3.7/site-packages/batchgenerators/dataloading/data_loader.py", line 85, in __next__
    minibatch = self.generate_train_batch()
  File "/home/ubuntu/Downloads/Working/ACDC2017/BatchGenerator.py", line 71, in generate_train_batch
    patients = np.random.choice(self._data.keys(), self.BATCH_SIZE, True)
  File "mtrand.pyx", line 907, in numpy.random.mtrand.RandomState.choice
ValueError: a must be 1-dimensional or an integer
epoch:  0  learning rate:  0.0005
Traceback (most recent call last):
  File "run_training_2D.py", line 268, in <module>
    run(args.c, args.f)
  File "run_training_2D.py", line 191, in run
    for data_dict in data_gen_train:
  File "/home/ubuntu/anaconda3/envs/py37th/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/home/ubuntu/anaconda3/envs/py37th/lib/python3.7/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by FabianIsensee** [comment]
can you please tell me what command you ran?

**Comment by ahmadfaizan1990** [comment]
I am training a 2D network and receiving the above error.

python run_validation_2D.py -f 0 -c UNet2D_config.py
