### ISSUE TITLE
ImportError with MultiThreadedAugmenter from batchgenerators v0.23

### ISSUE THREAD

**Issue by jwc-rad** [MIC-DKFZ/nnUNet#823]
nnUNet_train produces ImportError with MultiThreadedAugmenter from batchgenerators v0.23 (currently the latest version) as follows:

Traceback (most recent call last):
  File "/opt/conda/envs/py38/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/opt/conda/envs/py38/bin/nnUNet_train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/envs/py38/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/opt/conda/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jupyter/workstation/nnUNet/nnunet/run/run_training.py", line 18, in <module>
    from nnunet.run.default_configuration import get_default_configuration
  File "/home/jupyter/workstation/nnUNet/nnunet/run/default_configuration.py", line 20, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/home/jupyter/workstation/nnUNet/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/home/jupyter/workstation/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 34, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import default_3D_augmentation_params, \
  File "/home/jupyter/workstation/nnUNet/nnunet/training/data_augmentation/default_data_augmentation.py", line 19, in <module>
    from batchgenerators.dataloading import MultiThreadedAugmenter
ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' (/opt/conda/envs/py38/lib/python3.8/site-packages/batchgenerators/dataloading/__init__.py)

In batchgenerators v0.23, __init__.py has become an empty file and that seems to be the problem.

Although I have solved this by downgrading batchgenerators to v0.21, I think nnUNet's import has to be also updated.

**Comment by jwc-rad** [comment]
My bad. The latest nnUNet is alright.

**Comment by Ouyuxuan623** [comment]
I still have this problem, the same error, could you help me with this?

Thanks a lot!

**Comment by jwc-rad** [comment]
@Ouyuxuan623 which versions of nnUNet and batchgenerators are you using? from nnUNet 1.7.0, batchgenerators>=0.23 is required. Before 1.7, you can downgrade batchgenerators to v0.21.
