### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'load_state_dict'

### ISSUE THREAD

**Issue by paul-reiners** [MIC-DKFZ/nnUNet#827]
Any idea what might cause this problem when running inference?

```
Traceback (most recent call last):
  File "/home/support/public/torch_cudnn8.2/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/home/support/public/torch_cudnn8.2/lib/python3.9/site-packages/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/home/support/public/torch_cudnn8.2/lib/python3.9/site-packages/nnunet/inference/predict.py", line 630, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/home/support/public/torch_cudnn8.2/lib/python3.9/site-packages/nnunet/inference/predict.py", line 214, in predict_cases
    trainer.load_checkpoint_ram(p, False)
  File "/home/support/public/torch_cudnn8.2/lib/python3.9/site-packages/nnunet/training/network_training/network_trainer.py", line 356, in load_checkpoint_ram
    self.amp_grad_scaler.load_state_dict(checkpoint['amp_grad_scaler'])
AttributeError: 'NoneType' object has no attribute 'load_state_dict'
```

**Comment by paul-reiners** [comment]
I'm trying to run inference.  How do you get the version number of nnU-Net?

**Comment by FabianIsensee** [comment]
please upade nnU-Net from the current master

`pip install git+https://github.com/MIC-DKFZ/nnUNet.git`
