### ISSUE TITLE
'NoneType' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by jasonyeong** [MIC-DKFZ/nnUNet#835]
Hi ,I'm training a 2D network with 
nnUNet_train 2d nnUNetTrainerV2 Task001_Caries 0  --npz,
but this happened to it. I have looked for a lot of solutions, but nothing seems to help the.
I would like to ask what is the reason?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "c:\python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
  File "C:\Python37\Scripts\nnUNet_train-script.py", line 33, in <module>
    exitcode = _main(fd)
      File "c:\python37\lib\multiprocessing\spawn.py", line 115, in _main
sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())    self = reduction.pickle.load(from_parent)

  File "c:\users\asus\nnunetframe\nnunet\nnunet\run\run_training.py", line 179, in main
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 29, in <module>
    import torch
  File "c:\python37\lib\site-packages\torch\__init__.py", line 124, in <module>
    raise err
OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "c:\python37\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.
    trainer.run_training()
  File "c:\users\asus\nnunetframe\nnunet\nnunet\training\network_training\nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "c:\users\asus\nnunetframe\nnunet\nnunet\training\network_training\nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "c:\users\asus\nnunetframe\nnunet\nnunet\training\network_training\network_trainer.py", line 418, in run_training
    _ = self.tr_gen.next()
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 182, in next
    return self.__next__()
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 203, in __next__
    self._start()
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 244, in _start
    self._processes[-1].start()
  File "c:\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function MultiThreadedAugmenter.__del__ at 0x00000224B3CD0828>
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 296, in __del__
    self._finish()
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 275, in _finish
    [i.terminate() for i in self._processes]
  File "c:\python37\lib\site-packages\batchgenerators\dataloading\multi_threaded_augmenter.py", line 275, in <listcomp>
    [i.terminate() for i in self._processes]
  File "c:\python37\lib\multiprocessing\process.py", line 124, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```

**Comment by FabianIsensee** [comment]
You are looking at the wrong error. The real error is 

> OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "c:\python37\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

nnU-Net is not build for windows and Windows is not supported, so I can't help you out here. Apologies. We don't have a single Windows system to test things on^^
There is a PR that is working on Windows support. Maybe look there

**Comment by xx1105362169** [comment]
解决了吗，我也是这个问题 ，help
