### ISSUE TITLE
Issue in loading model checkpoint file while running custom trained model for inference on different dataset

### ISSUE THREAD

**Issue by rohand24** [MIC-DKFZ/nnUNet#862]
Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

Hi,

Amazing Framework. Have been using it for the past year and have helped others in the lab to use it as well.

I have completed training a segmentation model on my own dataset and want to use it to segment a new dataset.

```
git_nnunet) [rnd27@gput054 rnd27]$ nnUNet_predict -i ../gxm320/UH_CT_Project_Files/CT_Project_UH/Dataset_CT/CAC_Nifty -o ./nnUNet_predictions/Liver_spleen/UH_CT_CAC -t 112 -tr nnUNetTrainerV2_ResencUNet -m 3d_fullres -p nnUNetPlans_FabiansResUNet_v2.1


Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

using model stored in  /mnt/rstor/CSE_BME_AXM788/home/rnd27/nnUNet_trained_models/nnUNet/3d_fullres/Task112_Liver_Spleen/nnUNetTrainerV2_ResencUNet__nnUNetPlans_FabiansResUNet_v2.1
This model expects 1 input modalities for each image
Found 102 unique case ids, here are some examples: ['00C3R1CSA_im_8_0.5' '00DGB01YL02_im_1' '00A2O8ZB0_im_5_0.5'
 '00C1GB61_im_2_0.5' '00DGB01YL02_im_5' '00DGB01YL02_im_5_tio'
 '00C3R1CSA_im_5_tio' '00DJ57Y783_im_4_tio' '00DGB01YL02_im_5'
 '00DGB01YL02_im_6_0.5']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 102
number of cases that still need to be predicted: 102
emptying cuda cache
loading parameters for folds, None
folds is None so we will automatically look for output folders (not using 'all'!)
found the following folds:  ['/mnt/rstor/CSE_BME_AXM788/home/rnd27/nnUNet_trained_models/nnUNet/3d_fullres/Task112_Liver_Spleen/nnUNetTrainerV2_ResencUNet__nnUNetPlans_FabiansResUNet_v2.1/fold_0']
2021-11-22 11:14:53.716161: Using dummy2d data augmentation
using the following model files:  ['/mnt/rstor/CSE_BME_AXM788/home/rnd27/nnUNet_trained_models/nnUNet/3d_fullres/Task112_Liver_Spleen/nnUNetTrainerV2_ResencUNet__nnUNetPlans_FabiansResUNet_v2.1/fold_0/model_final_checkpoint.model']
Traceback (most recent call last):
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 187, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'nitial_c'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 1095, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 1037, in frombuf
    chksum = nti(buf[148:156])
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 189, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/torch/serialization.py", line 556, in _load
    return legacy_load(f)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/torch/serialization.py", line 467, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/tarfile.py", line 2301, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/nnunet/inference/predict_simple.py", line 221, in main
    step_size=step_size, checkpoint_name=args.chk)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/nnunet/inference/predict.py", line 664, in predict_from_folder
    disable_postprocessing=disable_postprocessing)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/nnunet/inference/predict.py", line 185, in predict_cases
    checkpoint_name=checkpoint_name)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/nnunet/training/model_restore.py", line 147, in load_model_and_checkpoint_files
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/nnunet/training/model_restore.py", line 147, in <listcomp>
    all_params = [torch.load(i, map_location=torch.device('cpu')) for i in all_best_model_files]
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/mnt/rstor/CSE_BME_AXM788/home/rnd27/anaconda3/envs/git_nnunet/lib/python3.7/site-packages/torch/serialization.py", line 560, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /mnt/rstor/CSE_BME_AXM788/home/rnd27/nnUNet_trained_models/nnUNet/3d_fullres/Task112_Liver_Spleen/nnUNetTrainerV2_ResencUNet__nnUNetPlans_FabiansResUNet_v2.1/fold_0/model_final_checkpoint.model is a zip archive (did you mean to use torch.jit.load()?)
```

I have used this model for inference on different datasets before, but this is the first time facing this issue while running inference.
Kindly help.

Thank you,
Rohan Dhamdhere

**Comment by rohand24** [comment]
Issue was due to pytorch version. For some reason, my pytorch version was downgraded to 1.1.1.
Solved by Upgrading it to pytorch 1.7.1.
