### ISSUE TITLE
RuntimeError while training

### ISSUE THREAD

**Issue by sftyzxg** [MIC-DKFZ/nnUNet#876]
I am using RTX3060, 16GB RAM, 6GB VRam to train the model and received RuntimeError:

I am running the following nnUNet: 3d_fullres
My trainer class is:  <class 'nnunet.training.network_training.nnUNetTrainerV2.nnUNetTrainerV2'>
For that I will be using the following configuration:
num_classes:  3
modalities:  {0: 'FLAIR', 1: 'T1w', 2: 't1gd', 3: 'T2w'}
use_mask_for_norm OrderedDict([(0, True), (1, True), (2, True), (3, True)])
keep_only_largest_region None
min_region_size_per_class None
min_size_per_class None
normalization_schemes OrderedDict([(0, 'nonCT'), (1, 'nonCT'), (2, 'nonCT'), (3, 'nonCT')])
stages...

stage:  0
{'batch_size': 2, 'num_pool_per_axis': [5, 5, 5], 'patch_size': array([128, 128, 128]), 'median_patient_size_in_voxels': array([138, 169, 138]), 'current_spacing': array([1., 1., 1.]), 'original_spacing': array([1., 1., 1.]), 'do_dummy_2D_data_aug': False, 'pool_op_kernel_sizes': [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]], 'conv_kernel_sizes': [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]}

I am using stage 0 from these plans
I am using sample dice + CE loss

I am using data from this folder:  /home/sftyzxg/nnunet-master/nnUNet-master/nnunet/nnUNet_preprocessed/Task001_BrainTumour/nnUNetData_plans_v2.1
###############################################
loading dataset
loading all case properties
2021-12-04 11:42:24.523594: Using splits from existing split file: /home/sftyzxg/nnunet-master/nnUNet-master/nnunet/nnUNet_preprocessed/Task001_BrainTumour/splits_final.pkl
2021-12-04 11:42:24.524587: The split file contains 5 splits.
2021-12-04 11:42:24.524664: Desired fold for training: 4
2021-12-04 11:42:24.524707: This split has 388 training and 96 validation cases.
unpacking dataset
done
2021-12-04 11:42:29.193822: lr: 0.01
using pin_memory on device 0
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness.
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full

Traceback (most recent call last):
  File "/home/sftyzxg/.local/bin/nnUNet_train", line 8, in <module>
    sys.exit(main())
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/nnunet/run/run_training.py", line 179, in main
    trainer.run_training()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainerV2.py", line 440, in run_training
    ret = super().run_training()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/nnunet/training/network_training/network_trainer.py", line 418, in run_training
    _ = self.tr_gen.next()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 182, in next
    return self.__next__()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/home/sftyzxg/.local/lib/python3.6/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by sftyzxg** [comment]
Is there any method to reduce the workload of video memory while training?

**Comment by FabianIsensee** [comment]
You need to manually edit the experiment planner to use less VRAM. nnU-Net (as described in the readme...) needs at least 8GB, better 11. As soon as you deviate in terms of the amount of VRAM used you can no longer expect nnU-net to deliver the expected results. Maybe it will, maybe it won't.
So do this at your own risk:
https://github.com/MIC-DKFZ/nnUNet/blob/96d44c2fc1ce5e18da4cd54bf52882047c37982e/nnunet/experiment_planning/experiment_planner_baseline_3DUNet_v21.py#L120

Change that to 

```python
        ref = Generic_UNet.use_this_for_batch_size_computation_3D * self.unet_base_num_features / \
              Generic_UNet.BASE_NUM_FEATURES_3D * 6 / 8
```
For 6 GB. You may need to go lower than 6 if it still doesn't fit. Note that this change only applied for 3D confiugurations. Not 2D
Best.,
Fabian

**Comment by chaineypung** [comment]
Thank you! This is the effective way.
