### ISSUE TITLE
About plan and preprocessing

### ISSUE THREAD

**Issue by Ouyuxuan623** [MIC-DKFZ/nnUNet#915]
When I run the  "nnUNet_plan_and_preprocess -t 1" command, the error printed is "Traceback (most recent call last):
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_plan_and_preprocess')())
  File "/usr/local/bin/nnUNet_plan_and_preprocess", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/MyDrive/ADNITrans/CoTr/nnUNet/nnunet/experiment_planning/nnUNet_plan_and_preprocess.py", line 24, in <module>
    from nnunet.training.model_restore import recursive_find_python_class
  File "/content/drive/MyDrive/ADNITrans/CoTr/nnUNet/nnunet/training/model_restore.py", line 20, in <module>
    from nnunet.training.network_training.nnUNetTrainer import nnUNetTrainer
  File "/content/drive/MyDrive/ADNITrans/CoTr/nnUNet/nnunet/training/network_training/nnUNetTrainer.py", line 34, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import default_3D_augmentation_params, \
  File "/content/drive/MyDrive/ADNITrans/CoTr/nnUNet/nnunet/training/data_augmentation/default_data_augmentation.py", line 18, in <module>
    from batchgenerators.dataloading import MultiThreadedAugmenter, SingleThreadedAugmenter

ImportError: cannot import name 'MultiThreadedAugmenter' from 'batchgenerators.dataloading' (/usr/local/lib/python3.7/dist-packages/batchgenerators/dataloading/__init__.py)"

How can I fix this problem? Many Thanks for reading this issue!

**Comment by Ouyuxuan623** [comment]
Sorry, my bad.
