### ISSUE TITLE
Shape mismatch

### ISSUE THREAD

**Issue by lcerdaal** [MIC-DKFZ/nnUNet#920]
Hello! 
I am seeing an error in one of the 5 folds only, I am training a 3D model (currently using only one modality).
The original image and segmentation both have shapes (146, 539, 528). 
I am wondering what is happening as to why is trying to accomodate it to shape (120, 512, 512) and what I should do to fix it.

Thank you very much for your help!

Best regards

2022-01-20 11:27:13.581282: evaluation of raw predictions
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/evaluator.py", line 313, in run_evaluation
    current_scores = evaluator.evaluate(**metric_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/evaluator.py", line 303, in evaluate
    return super(NiftiEvaluator, self).evaluate(test, reference, **metric_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/evaluator.py", line 223, in evaluate
    **metric_kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/metrics.py", line 207, in accuracy
    tp, fp, tn, fn = confusion_matrix.get_matrix()
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/metrics.py", line 84, in get_matrix
    self.compute()
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/metrics.py", line 68, in compute
    assert_shape(self.test, self.reference)
  File "/opt/conda/lib/python3.7/site-packages/nnunet/evaluation/metrics.py", line 22, in assert_shape
    test.shape, reference.shape)
AssertionError: Shape mismatch: (120, 512, 512) and (146, 539, 528)

**Comment by FabianIsensee** [comment]
Hi Leo,
it is quite likely that something if off with your dataset. Have you changed the images located in imagesTr and labelsTr at some point? If you did - did you remember to delete the corresponding files in nnUNet_raw_cropped? I think that's what might have happened here.
Best,
Fabian

**Comment by lcerdaal** [comment]
Hi Fabian,
Ah, I see! I did change a few of them (as I had some things to correct that I discovered because of the preprocessing step). 
Do you think that if I delete now the nnUNet_raw_cropped files, and start again with this particular fold, I will need to re-run the other folds too? 
Thanks a lot!!
Best regards,
Leo

**Comment by lcerdaal** [comment]
Thanks for all the help :)

**Comment by FabianIsensee** [comment]
No problem :-)
