### ISSUE TITLE
Network initialization issue at inference time

### ISSUE THREAD

**Issue by mgendarme** [MIC-DKFZ/nnUNet#929]
First of all thanks for the fantastic work done with nnUNet!

I have trained a 2d model using my own data, training worked fine. The only modification implemented was decreasing the max_num_epochs parameter to 200.

When I try to run the predictions on the test set I get an error indicating the network couldn't be initialized. 
The command run:
```
nnUNet_predict -i $nnUNet_raw_data_base/nnUNet_raw_data/Task001_A549/imagesTs -o $RESULTS_FOLDER/nnUNet/2d/Task001_A549/nnUNetTrainerV2_200ep__nnUNetPlansv2.1/imagesTs_predicted -t 001 -m 2d -f 0 -tr nnUNetTrainerV2_200ep
```

The error message:
```
Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z


If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

using model stored in  /home/gendarme/Documents/nnUNet/nnUNet_trained_models/nnUNet/2d/Task001_A549/nnUNetTrainerV2_200ep__nnUNetPlansv2.1
This model expects 1 input modalities for each image
Found 48 unique case ids, here are some examples: ['A549_041' 'A549_030' 'A549_016' 'A549_011' 'A549_042' 'A549_035'
 'A549_044' 'A549_007' 'A549_034' 'A549_030']
If they don't look right, make sure to double check your filenames. They must end with _0000.nii.gz etc
number of cases: 48
number of cases that still need to be predicted: 48
emptying cuda cache
loading parameters for folds, [0]
Traceback (most recent call last):
  File "/me/anaconda3/bin/nnUNet_predict", line 8, in <module>
    sys.exit(main())
  File "/me/anaconda3/lib/python3.8/site-packages/nnunet/inference/predict_simple.py", line 217, in main
    predict_from_folder(model_folder_name, input_folder, output_folder, folds, save_npz, num_threads_preprocessing,
  File "/me/anaconda3/lib/python3.8/site-packages/nnunet/inference/predict.py", line 658, in predict_from_folder
    return predict_cases(model, list_of_lists[part_id::num_parts], output_files[part_id::num_parts], folds,
  File "/me/anaconda3/lib/python3.8/site-packages/nnunet/inference/predict.py", line 184, in predict_cases
    trainer, params = load_model_and_checkpoint_files(model, folds, mixed_precision=mixed_precision,
  File "/me/anaconda3/lib/python3.8/site-packages/nnunet/training/model_restore.py", line 144, in load_model_and_checkpoint_files
    trainer.initialize(False)
  File "/me/anaconda3/lib/python3.8/site-packages/nnunet/training/network_training/nnUNetTrainerV2_200ep.py", line 123, in initialize
    assert isinstance(self.network, (SegmentationNetwork, nn.DataParallel))

```
It looks like I am missing something but cannot pinpoint what it is.

Thanks for helping out.

**Comment by FabianIsensee** [comment]
Hi Mathieu,
the inference code needs some stuff from the SegmentationNetwork class to work properly. You need to identify what it is and then make sure your class offers this as well. Then you can remove that assert line and you're good to go.
Best,
Fabian

**Comment by mgendarme** [comment]
Hi Fabian,
Thanks for the quick answer. 
I will try to investigated that.
What I found strange is that I haven't changed anything from the original trainer `nnUNetTrainerV2` except decreasing the parameter `max_num_epochs`  from 1000 to 200 in the `nnUNetTrainerV2_200ep` trainer. Everything else is untouched from the source code, including `SegmentationNetwork`. The inference should works out of the box if one doesn't modify the source code right?

If this helps to figure out the issue the model was trained running (example for fold 0):
```
nnUNet_train 2d nnUNetTrainerV2_200ep Task001_A549 0
```

**Comment by FabianIsensee** [comment]
Honestly I don't know what else it could be. If all you did was change the number of epochs then the nnUNetTrainerV2 class will have the correct segmentation network to perform inference with

**Comment by mgendarme** [comment]
All fine, it was a mistake from my end in `nnUNetTrainer`.
Thanks for helping pinpointing where it could be coming from.
I am closing the issue.
