### ISSUE TITLE
Issuwith low_res training

### ISSUE THREAD

**Issue by midya2020** [MIC-DKFZ/nnUNet#953]
I tried to train a model with "3d_lowres". Training completed untill 500 epoch (i changed the max epoch via a new trainer), but then terminated with the following error. Can you please help me in fixing this

Error file looks like:
Traceback (most recent call last):
  File "/home/mid/miniconda3/envs/nnUNet_env/bin/nnUNet_train", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_train')())
  File "/lila/home/mid/nnUNet/nnunet/run/run_training.py", line 195, in main
    predict_next_stage(trainer, join(dataset_directory, trainer.plans['data_identifier'] + "_stage%d" % 1))
  File "/lila/home/mid/nnUNet/nnunet/training/cascade_stuff/predict_next_stage.py", line 67, in predict_next_stage
    predicted_probabilities = trainer.predict_preprocessed_data_return_seg_and_softmax(
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/mid/miniconda3/envs/nnUNet_env/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/mid/miniconda3/envs/nnUNet_env/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mid/miniconda3/envs/nnUNet_env/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/home/mid/miniconda3/envs/nnUNet_env/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    raise RuntimeError("Abort event was set. So someone died and we should end this madness. \nIMPORTANT: "
RuntimeError: Abort event was set. So someone died and we should end this madness. 
IMPORTANT: This is not the actual error message! Look further up to see what caused the error. Please also check whether your RAM was full
    self.run()
  File "/home/mid/miniconda3/envs/nnUNet_env/lib/python3.9/threading.py", line 910, in run

The I copied last few lines of output file here:

022-02-04 05:54:17.258258: 
epoch:  499
2022-02-04 06:02:52.794967: train loss : -0.7797
2022-02-04 06:03:28.211423: validation loss: -0.7202
2022-02-04 06:03:28.212010: Average global foreground Dice: [0.9473, 0.8952]
2022-02-04 06:03:28.212115: (interpret this as an estimate for the Dice of the different classes. This is not exact.)
2022-02-04 06:03:29.001639: lr: 0.0
2022-02-04 06:03:29.001857: saving scheduled checkpoint file...
2022-02-04 06:03:29.001968: done
2022-02-04 06:03:29.002068: This epoch took 551.743741 s

predicting segmentations for the next stage of the cascade
Liver_0011
PS:

Read file <4953603.stderr> for stderr output of this job.

**Comment by FabianIsensee** [comment]
Did you change somethine else with the trainer?

**Comment by midya2020** [comment]
I defined one training class to limit number of epoch to 500. That is the only change i made with trainer

**Comment by midya2020** [comment]
Sorry!! I got the error. I by mistake commented  some part of the script. I redownloaded and compared line by line and found the root cause. Sorry for bothering you with such a silly mistake
