### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/media/fabian'

### ISSUE THREAD

**Issue by mehnaz1985** [MIC-DKFZ/nnUNet#964]
I am facing the error above with the following comments
(nnUnet_ve) mehnaz@carlo-DGX-Station:~/environments/nnUNet/nnUNet$ nnUNet_convert_decathlon_task -i /home/mehnaz/environments/Task04_Hippocampus/Task04_Hippocampus

Please cite the following paper when using nnUNet:

Isensee, F., Jaeger, P.F., Kohl, S.A.A. et al. "nnU-Net: a self-configuring method for deep learning-based biomedical image segmentation." Nat Methods (2020). https://doi.org/10.1038/s41592-020-01008-z

If you have questions or suggestions, feel free to open an issue at https://github.com/MIC-DKFZ/nnUNet

Traceback (most recent call last):
  File "/home/mehnaz/environments/nnUnet_ve/bin/nnUNet_convert_decathlon_task", line 33, in <module>
    sys.exit(load_entry_point('nnunet', 'console_scripts', 'nnUNet_convert_decathlon_task')())
  File "/home/mehnaz/environments/nnUnet_ve/bin/nnUNet_convert_decathlon_task", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/mehnaz/environments/nnUnet_ve/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/nnUNet_convert_decathlon_task.py", line 16, in <module>
    from nnunet.experiment_planning.utils import split_4d
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/utils.py", line 25, in <module>
    from nnunet.experiment_planning.DatasetAnalyzer import DatasetAnalyzer
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/experiment_planning/DatasetAnalyzer.py", line 19, in <module>
    from nnunet.paths import nnUNet_raw_data, nnUNet_cropped_data
  File "/home/mehnaz/environments/nnUNet/nnUNet/nnunet/paths.py", line 36, in <module>
    maybe_mkdir_p(nnUNet_raw_data)
  File "/home/mehnaz/environments/nnUnet_ve/lib/python3.6/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 53, in maybe_mkdir_p
    os.makedirs(directory, exist_ok=True)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media/fabian'

Please read the following resources before posting issues:

Common questions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_questions.md

Common Problems and their solutions:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/common_problems_and_solutions.md

Expected epoch times and tips on how to identify bottlenecks:
https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/expected_epoch_times.md

**Comment by duytq99** [comment]
Hello Mehnaz.
Did you set up the environment dataset path as `https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md` ?
"""
export nnUNet_raw_data_base="/media/fabian/nnUNet_raw_data_base"
export nnUNet_preprocessed="/media/fabian/nnUNet_preprocessed"
export RESULTS_FOLDER="/media/fabian/nnUNet_trained_models
"""

`/media/fabian` is the default directory in some scripts so I guess that is your problem.

**Comment by mehnaz1985** [comment]
hi @duytq99, Yes, I have save them in the bash file.

**Comment by FabianIsensee** [comment]
Yeah it looks like you copied my paths instead of changing that to your own. You need to chance the paths to something that works on your system

**Comment by mehnaz1985** [comment]
I am facing version conflict now. 
pkg_resources.ContextualVersionConflict: (numpy 1.19.5 (/home/mehnaz/environments/nnUnet_ve/lib/python3.6/site-packages), Requirement.parse('numpy>=1.20.0'), {'imageio'})
I have tried to upgrade numpy but cant. it showing the following message:

imageio 2.16.0 requires numpy>=1.20.0, but you have numpy 1.19.5 which is incompatible.
Successfully installed numpy-1.19.5

**Comment by FabianIsensee** [comment]
see #974

**Comment by domadaaaa** [comment]
Traceback (most recent call last):
  File "/home/ivi/anaconda3/envs/lx310/bin/nnUNet_convert_decathlon_task", line 5, in <module>
    from nnunet.experiment_planning.nnUNet_convert_decathlon_task import main
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/site-packages/nnunet/experiment_planning/nnUNet_convert_decathlon_task.py", line 16, in <module>
    from nnunet.experiment_planning.utils import split_4d
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/site-packages/nnunet/experiment_planning/utils.py", line 25, in <module>
    from nnunet.experiment_planning.DatasetAnalyzer import DatasetAnalyzer
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/site-packages/nnunet/experiment_planning/DatasetAnalyzer.py", line 19, in <module>
    from nnunet.paths import nnUNet_raw_data, nnUNet_cropped_data
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/site-packages/nnunet/paths.py", line 36, in <module>
    maybe_mkdir_p(nnUNet_raw_data)
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/site-packages/batchgenerators/utilities/file_and_folder_operations.py", line 53, in maybe_mkdir_p
    os.makedirs(directory, exist_ok=True)
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ivi/anaconda3/envs/lx310/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/media/fabian'
